window.ConceptSymbols = function(){
  return [
  [_('Objet'), _('Paquet'), _('Carton')],
  [_('Famille'), _('Société'), _('Groupe')],
  [_('Femme'), _('Féminin'), _('Femelle')],
  [_('Homme'), _('Masculin'), _('Mâle')],
  [_('Travail'), _('Métier')],
  [_('Loisir'), _('Sport'), _('Activité')],
  [_('Faune'), _('Animal')],
  [_('Flore'), _('Plante'), _('Nature')],
  [_('Littérature'), _('Écriture'), _('Livre')],
  [_('Musique'), _('Chanson'), _('Note')],
  [_('Cinéma'), _('Film'), _('Caméra')],
  [_('Arts'), _('Sculpture'), _('Peinture'), _('Dessin'), _('Bande dessinée')],
  [_('Télévision'), _('Émission'), _('Série')],
  [_('Titre'), _('Marque'), _('Nom')],
  [_('Idée'), _('Pensée'), _('Concept')],
  [_('Expression'), _('Dialogue'), _('Citation'), _('Mot')],
  [_('Lieu'), _('Pays'), _('Drapeau')],
  [_('Bâtiment'), _('Construction'), _('Ville')],
  [_('Date'), _('Événement'), _('Jour')],
  [_('Fêtes'), _('Anniversaire')],
  [_('Véhicule marin'), _('Maritime'), _('Nager')],
  [_('Véhicule volant'), _('Aérien'), _('Voler')],
  [_('Véhicule routier'), _('Voiture'), _('Rouler')],
  [_('Outils')],
  [_('Jeux'), _('Jouet')],
  [_('Vêtements'), _('Accessoire'), _('Costume')],
  [_('Alimentaire'), _('Nourriture'), _('Comestible')],
  [_('Maison'), _('Intérieur'), _('Domestique')],
  [_('Réel'), _('Historique')],
  [_('Fictif'), _('Imaginaire')],
  [_('Enfant'), _('Bébé'), _('Jeune'), _('Nouveau')],
  [_('Vieux'), _('Adulte'), _('Ancien'), _('Passé')],
  [_('Lent'), _('Tortue')],
  [_('Rapide'), _('Vif'), _('Lièvre')],
  [_('Défense'), _('Protection'), _('Mur')],
  [_('Conflit'), _('Arme'), _('Combattre')],
  [_('Vie'), _('Coeur'), _('Amour')],
  [_('Mort'), _('Mal'), _('Maladie')],
  [_('Joyeux'), _('Positif')],
  [_('Triste'), _('Négatif')],
  [_('Électronique'), _('Informatique')],
  [_('Mécanique'), _('Industriel')],
  [_('Argent'), _('Riche'), _('Cher')],
  [_('Temps'), _('Durée')],
  [_('Religion'), _('Mythe'), _('Croyance')],
  [_('Pouvoir'), _('Politique')],
  [_('Sciences'), _('Mathématique'), _('Chimie')],
  [_('Médical'), _('Médicament'), _('Soigner')],
  [_('Tête'), _('Visage')],
  [_('Bras'), _('Main')],
  [_('Torse'), _('Ventre'), _('Corps')],
  [_('Jambe'), _('Pied')],
  [_('Oreille'), _('Son'), _('Entendre')],
  [_('Nez'), _('Odeur'), _('Sentir')],
  [_('Oeil'), _('Vue'), _('Voir')],
  [_('Bouche'), _('Goût'), _('Manger')],
  [_('Nuage'), _('Pluie'), _('Neige'), _('Froid')],
  [_('Éclair'), _('Électricité'), _('Tempête'), _('Colère')],
  [_('Nuit'), _('Soir'), _('Lune')],
  [_('Soleil'), _('Chaud'), _('Lumière'), _('Jour')],
  [_('Feu'), _('Brûler')],
  [_('Eau'), _('Liquide'), _('Aquatique')],
  [_('Air'), _('Vent'), _('Souffler')],
  [_('Terre')],
  [_('Roche'), _('Minéral'), _('Dur')],
  [_('Bois')],
  [_('Métal')],
  [_('Tissus')],
  [_('Plastique'), _('Caoutchouc')],
  [_('Papier'), _('Feuille')],
  [_('Opposé'), _('Contraire'), _('Inverse')],
  [_('Couper'), _('Séparer'), _('Moitié')],
  [_('Fragment'), _('Multitude'), _('Poudre')],
  [_('Partie de'), _('Morceau de'), _('Pièce de')],
  [_('Dedans'), _('Interne')],
  [_('Grille'), _('Réseau'), _('Prison')],
  [_('Zéro'), _('Néant'), _('Nul')],
  [_('Unité'), _('Un')],
  [_('Ligne'), _('droite'), _('Droit')],
  [_('Arc'), _('Courbe'), _('Bombé')],
  [_('Croix'), _('Croisement')],
  [_('Ligne'), _('brisée'), _('Pointu'), _('Accidenté')],
  [_('Spirale'), _('Ivresse'), _('-'), _('Folie'), _('Poil')],
  [_('Sinusoïdale'), _('Ondulation'), _('Cheveux'), _('Rivière')],
  [_('Anneau'), _('Cercle')],
  [_('Rond')],
  [_('Triangle')],
  [_('Étoile')],
  [_('Rectangle'), _('Carré')],
  [_('Plat')],
  [_('Cube'), _('Pavé')],
  [_('Sphère')],
  [_('Pyramide')],
  [_('Cylindre')],
  [_('Cône')],
  [_('Creux'), _('Trou'), _('Percé')],
  [_('Grand'), _('Plus grand'), _('Plus haut')],
  [_('Gros'), _('Large'), _('Plus large'), _('Plus long')],
  [_('Petit'), _('Plus petit'), _('Plus bas')],
  [_('Mince'), _('Fin'), _('Plus étroit'), _('Plus court')],
  [_('Haut'), _('Monter')],
  [_('Bas'), _('Descendre')],
  [_('Gauche'), _('Début'), _('Avant')],
  [_('Droite'), _('Fin'), _('Après')],
  [_('Tourner'), _('Entourer'), _('Cycle')],
  [_('Utiliser'), _('-'), _('Actionner'), _('Verbe')],
  [_('Rouge')],
  [_('Orange')],
  [_('Jaune')],
  [_('Vert')],
  [_('Bleu')],
  [_('Mauve')],
  [_('Rose')],
  [_('Brun')],
  [_('Noir')],
  [_('Gris')],
  [_('Blanc')],
  [_('Transparent'), _('Invisible'), _('Verre')],
];
};
