window.ConceptSymbols = function(){
  return [
    [_('Object'), _('Thing'), _('Package')],
    [_('Person'), _('Family'), _('Group')],
    [_('Female/Woman'), _('Wife'), _('Feminine')],
    [_('Male/Man'), _('Husband'), _('Masculine')],
    [_('Work'), _('Profession'), _('Craft')],
    [_('Recreation'), _('Sport'), _('Activity')],
    [_('Wildlife'), _('Animal')],
    [_('Flora'), _('Plant'), _('Nature')],
    [_('Literature'), _('Writing'), _('Book')],
    [_('Music'), _('Song'), _('Note')],
    [_('Theater'), _('Film'), _('Camera')],
    [_('Arts'), _('Sculpture/Painting'), _('Drawing/Comics')],
    [_('Television'), _('Brodcast'), _('Series')],
    [_('Title'), _('Brand'), _('Name')],
    [_('Idea'), _('Thought'), _('Concept')],
    [_('Expression/Quote'), _('Speak'), _('Word')],
    [_('Location'), _('Country'), _('Flag')],
    [_('Building'), _('Construction'), _('City')],
    [_('Date'), _('Event'), _('Daytime')],
    [_('Holidays'), _('Birthday'), _('Celebration')],
    [_('Watercraft'), _('Maritime'), _('Swim')],
    [_('Airborne vehicle'), _('Airline'), _('Fly')],
    [_('Land vehicle'), _('Car'), _('Ride')],
    [_('Tools'), _('Construction')],
    [_('Games'), _('Toys'), _('Youth')],
    [_('Clothing'), _('Accessories'), _('Costume')],
    [_('Food'), _('Nutrition'), _('Edible')],
    [_('Home'), _('Interior'), _('Domestic')],
    [_('Reality'), _('Historic')],
    [_('Fictional'), _('Imaginary'), _('Wish')],
    [_('Baby/Child'), _('Young'), _('New')],
    [_('Adult/Old'), _('Ancient'), _('Past')],
    [_('Slow'), _('Lengthy'), _('Turtle')],
    [_('Fast'), _('Lively'), _('Hare')],
    [_('Defense'), _('Protection'), _('Wall')],
    [_('Conflict'), _('Weapon'), _('Fight')],
    [_('Life'), _('Heart'), _('Love')],
    [_('Dead'), _('Evil'), _('Disease')],
    [_('Joyous'), _('Positive')],
    [_('Sad'), _('Negative')],
    [_('Electronics'), _('Computer')],
    [_('Mechanical'), _('Industrial')],
    [_('Money'), _('Rich'), _('Expensive')],
    [_('Time'), _('Duration')],
    [_('Religion'), _('Myth'), _('Belief')],
    [_('Power'), _('Politics')],
    [_('Science'), _('Mathematics'), _('Chemistry')],
    [_('Medical'), _('Drug'), _('Cure')],
    [_('Head'), _('Face')],
    [_('Arm'), _('Hand')],
    [_('Torso'), _('Stomach')],
    [_('Leg'), _('Foot')],
    [_('Ear'), _('Sound'), _('Hear')],
    [_('Nose'), _('Odor'), _('Smell')],
    [_('Eye'), _('View'), _('Watch')],
    [_('Mouth'), _('Flavor'), _('Eat')],
    [_('Cloud'), _('Rain'), _('Snow/cold')],
    [_('Lightning/electricity'), _('Storm'), _('Anger')],
    [_('Night'), _('Evening'), _('Moon')],
    [_('Sun/Heat'), _('Light'), _('Daytime')],
    [_('Fire'), _('Burn'), _('Heat')],
    [_('Water'), _('Liquid'), _('Aquatic')],
    [_('Air'), _('Wind'), _('Blow')],
    [_('Earth'), _('Dirt'), _('Grow')],
    [_('Rock'), _('Mineral'), _('Hard')],
    [_('Wood')],
    [_('Metal')],
    [_('Fabric')],
    [_('Plastic'), _('Rubber')],
    [_('Paper'), _('Sheet')],
    [_('Opposed'), _('Contrary'), _('Inverse')],
    [_('Break'), _('Separate'), _('Half')],
    [_('Fragment'), _('Multitude'), _('Powder')],
    [_('Part'), _('Bit'), _('Piece')],
    [_('Inside'), _('Internal')],
    [_('Grid'), _('Network'), _('Prison')],
    [_('Zero'), _('Nothing'), _('Null')],
    [_('Unity'), _('One')],
    [_('Straight line'), _('Smooth'), _('Rise')],
    [_('Curve'), _('Arc'), _('Rounded')],
    [_('Cross'), _('Intersection'), _('Addition')],
    [_('Broken line'), _('Sharp'), _('Uneven')],
    [_('Spiral'), _('Intoxication/Madnass'), _('Coll')],
    [_('Sinusoidal'), _('Ripple'), _('Hair')],
    [_('Ring'), _('Cycle')],
    [_('Circle'), _('Button')],
    [_('Triangle')],
    [_('Star')],
    [_('Rectangle'), _('Square')],
    [_('Flat')],
    [_('Cube'), _('Brick')],
    [_('Sphere')],
    [_('Pyramid')],
    [_('Cylinder')],
    [_('Cone')],
    [_('Hollow'), _('Hole'), _('Pierced')],
    [_('Tall'), _('Greater'), _('High')],
    [_('Small'), _('Lower'), _('Below')],
    [_('Huge'), _('Wider'), _('Longer')],
    [_('Skinny'), _('Closer'), _('Brief')],
    [_('Top'), _('Up'), _('Mount')],
    [_('Low'), _('Down'), _('Under')],
    [_('Left'), _('First'), _('Before')],
    [_('Right'), _('End'), _('After')],
    [_('Turn'), _('Surround'), _('Cycle')],
    [_('Use/Activate'), _('Verb')],
    [_('Red')],
    [_('Orange')],
    [_('Yellow')],
    [_('Green')],
    [_('Blue')],
    [_('Purple')],
    [_('Pink')],
    [_('Brown')],
    [_('Black')],
    [_('Gray')],
    [_('White')],
    [_('Clear'), _('Invisible')],
  ];
};
