<?php
class ConceptCardsHU {
  static $cards = [
    [ ["Kerék","Medence","Kenguru"], ["Teleshop","Szerencsekerék","Karaoke"],["Quimby","Lucky Luke","Brigitte Bardot"]],
    [ ["Villámhárító","Sör","Bor"], ["Mikrofon","Ételhordó","Austin Powers"],["Szegénylegények","Ödipusz","Robinson Crusoe"]],
    [ ["Tégla","Svájci bicska","Szótár"], ["A majmok bolygója","Dugó","Tépőzár"],["Nagyzási hóbort","Michelin baba","Lyukat beszél a hasába"]],
    [ ["Fürdőkád","Jegyzetfüzet","Számológép"], ["Balu","Beyoncé","Tüskevár"],["Smart kártya","Hab a tortán","Addig üti a vasat, amíg meleg"]],
    [ ["Traktor","Kagyló","Rubik kocka"], ["Infravörös távcső","Elem","Szilikon"],["Báránybőrbe bújt farkas","Tengeribetegség","Arany János"]],
    [ ["Tűzoltó repülőgép","Mókus","Angyal"], ["Termosz","Szarvas","Queen"],["Egy szalmaszálat sem tesz keresztbe","Sörnyitó","Kompromisszum"]],
    [ ["Bűvész","Sündisznó","Rendszámtábla"], ["Zsákos Bilbó","Teréz anya","Ludas Matyi"],["Újrakezdeni valamit","Fegyverszünet","Megtörni a csendet"]],
    [ ["Fúrógép","Iroda","Százszorszép"], ["A kis herceg","Indiana Jones","Pamela Anderson"],["Farkaséhes","Dragonball Z","Álomarcú lány"]],
    [ ["Nyugdíjasotthon","Vámpír","Létra"], ["Fogócska","Gát","A Gyűrűk Ura"],["Szegény embert az ág is húzza","Agymosás","Csak egy hajszállal mellé"]],
    [ ["Krokodil","Kanári","Zongora"], ["Beatles","Troll","Cyrano de Bergerac"],["Aki korpa közé keveredik, megeszik a disznók","Vesztésre játszani","Amélie csodálatos élete"]],
    [ ["Némó nyomában","Tetrisz","Bálna"], ["Céltábla","Billy, a Kölyök","Bajusz"],["Az ötödik elem","Fedezet nélküli csekk","Nyomozó"]],
    [ ["Pince","Oroszlán","Napóra"], ["Vonalkód","Stonehenge","Számszeríj"],["Hofi Géza","Lábáztató","Csak erős idegzetűeknek!"]],
    [ ["Siklórepülő","Műfogsor","Rák"], ["Melegvizes palack","Parittya","Gőzhajó"],["Gyónás","Bosszúállók","Porszívó"]],
    [ ["Skorpió","Kardhal","Parfüm"], ["Pálmafa","Könyvelő","Tölténytár"],["Világrekord","A kis gyufaárus lány","Bűntudata van"]],
    [ ["Teherautó","Egér","Parkolóóra"], ["Rögbi","Dinamit","Natalie Portman"],["Kutyából nem lesz szalonna","Sziluett","Balerina"]],
    [ ["Vadászrepülő","Kürt","Cápa"], ["Péntek 13","Vödör","Mike Tyson"],["Busójárás","A fellegekben jár","Tudatalatti üzenet"]],
    [ ["Tanár","Csokoládé","Gázspray"], ["Alien","Kill Bill","Feszty-körkép"],["Gerbeaud cukrászda","Beképzelt","Koldus"]],
    [ ["Pilóta","Gázálarc","Pinokkió"], ["Vörös és fekete","Grabowski","Bagira"],["Állig felfegyverkezve","Újra feléleszteni a tüzet","A jó, a rossz és a csúf"]],
    [ ["Zebra","Autószerelő","DVD"], ["Neil Armstrong","Paint It Black","Mechanikus narancs"],["Áthajt a piroson","A föld felett járni","Döntésképtelen"]],
    [ ["Tehén","Malac","Ablak"], ["Xilofon","Jeti","Biciklista"],["Vasárnapi újság","Zavarba hoz","Vak, mint a bányaló"]],
    [ ["Sátor","Ing","Rakéta"], ["Gyurta Dániel","Hód","Biztosítótű"],["Dr. John Watson","Beletörik a bicskája","Forróvérű"]],
    [ ["Konnektor","Vízvezeték-szerelő","Barbie baba"], ["Szusi","Sztetoszkóp","Sült krumpli"],["Nem a világ vége","Szórakozott","Tina Turner"]],
    [ ["Joghurt","Esernyő","Nindzsa"], ["Pattogatott kukorica","WC-papír","Alufólia"],["Tűnődni valamin","Harcosok Klubja","Popeye"]],
    [ ["Halász","Folyó","Tűzoltó készülék"], ["Mr. Bean","Radiátor","Elton John"],["Pandora szelencéje","Kicsi a bors, de erős","WC-pumpa"]],
    [ ["Szélkakas","Tornaterem","Kisvakond"], ["Háború és Béke","Fecske","Vakcina"],["Segíts magadon és Isten is megsegít!","Támad a Mars!","L’art pour l’art"]],
    [ ["Villa","Ágyú","Denevér"], ["Forrest Gump","Vadászgörény","Csótány"],["Egyik kopó, másik eb","Lassú, mint a csiga","Lascaux-i barlangok"]],
    [ ["Csiga","Zorro","Autórádió"], ["Dumbo","Gaia","Angry Birds"],["Eredet","Romantikus regény","Ismerd meg önmagad!"]],
    [ ["Fekete-erdő torta","Légy","Palacsinta"], ["Képregény","Kisasszonyok","Ösvény"],["Köddé válik","Szívszorító","Gyilkos elmék"]],
    [ ["Bika","Fenyőfa","Pac-Man"], ["Hercule Poirot","Görkorcsolya","Margaret Thatcher"],["Tyúkanyó","Amerikai szépség","Mint tű a szénakazalban"]],
    [ ["Pán Péter","Fűnyíró","Irányjelző"], ["Heti hetes","Tandembicikli","Képeslap"],["Tűri balsorsa minden nyűgét s nyilait","A háta mögött kibeszélni","Az istenek a fejükre estek"]],
    [ ["Túró Rudi","Szálloda","Iglu"], ["A katedrális","Jacuzzi","Jeanne D’Arc"],["Esik, mintha dézsából öntenék","A Megváltó Krisztus szobra","Összebújás"]],
    [ ["Kalóz","Bicikli","Malacpersely"], ["Szerv","Cunami","Ceruzahegyező"],["Bivalyerős","Kiönti a lelkét","A világ hét csodája"]],
    [ ["Vihar","Vitamin","Csengő"], ["Űrállomás","Nemo kapitány","Casino Royale"],["LGT","Marlon Brando","Monokli"]],
    [ ["Autómentő","Varrógép","Szigony"], ["Uborka","Hüvelyk Matyi","Hulahopp karika"],["Jobb félni, mint megijedni","Dugóhúzó","Made in Hungária"]],
    [ ["Keselyű","Farmernadrág","iPad"], ["Fekete lyuk","Zenegép","Monte Cristo grófja"],["V, mint vérbosszú","Makacs, mint egy öszvér","Dávid és Góliát"]],
    [ ["Nutella","Szánkó","Kard"], ["WC-ülőke","A rettenthetetlen","Barack Obama"],["Jurij Gagarin","Szépségpötty","Az vesse az első követ…"]],
    [ ["Barátok közt","Trolibusz","Vulkán"], ["Csingiling","Julia Roberts","Whiskey"],["Ablakon kidobott pénz","Művészetek Völgye","Lajka"]],
    [ ["Lakat","Kacsa","Nagyító"], ["A dalai láma","Biliárd","Lassie"],["Elássa a csatabárdot","Karácsonyi lidércnyomás","Liliomfi"]],
    [ ["Kémény","Avatar","Sombrero"], ["Kávéskanna","Afrodité","Villamosszék"],["Eladja a lelkét az ördögnek","Depresszió","Lámpaláz"]],
    [ ["Kút","Méh","Valentin nap"], ["Post-it","Robin Hood","2001: Űrodüsszeia"],["Bábel tornya","Hajkefe","Minden rosszban van valami jó"]],
    [ ["Hófehérke és a hét törpe","Zseni","Minecraft"], ["Asterix és Obelix","Gladiátor","Száz év magány"],["Nagy fába vágta a fejszéjét","Felültetni valakit","Nádas"]],
    [ ["Napfogyatkozás","Garázs","Padlás"], ["D’Artagnan","A Maszk","Napóleon"],["Ugyanazokat a köröket futja","Kiveri a veríték","Rushmore-hegy"]],
    [ ["Meteorit","Múzeum","Hűtőszekrény"], ["Kontaktlencse","The Sims","Power Rangers"],["80 nap alatt a Föld körül","Gyöngyöt szór a disznók elé","Rudolf Péter"]],
    [ ["Nyomtató","Vízipók-csodapók","Szőnyeg"], ["John Lennon","Kóla, puska, sültkrumpli","Snowboard"],["Csikóhal","A felvilágosodás kora","Izzad a tenyere"]],
    [ ["Elefánt","Öngyújtó","Manó"], ["Végső állomás","Bambi","Ördög"],["Esőember","Angela Merkel","Big Ben"]],
    [ ["Virágcserép","Sárkány","Úszás"], ["Olajfúró torony","Fogpiszkáló","Tini Nindzsa Teknőcök"],["Skyfall","Eminem","Tériszony"]],
    [ ["Aladdin","Űrhajós","Alma"], ["Földműves","Concord","Világítótorony"],["Tudja, mire számíthat","Minél többen, annál jobb","Demokrácia"]],
    [ ["Verdák","Yoda","Tengeralattjáró"], ["Postaláda","Woody Allen","József Attila"],["Büszkeség és balítélet","Az idegeimre mész","Dadogás"]],
    [ ["Mozi","Kígyó","Süsü"], ["Sherlock Holmes","Szent Grál","IMAX mozi"],["Kijön a sodrából","Szolárium","Szóljatok a köpcösnek!"]],
    [ ["Monopoly","Saláta","Iskola"], ["Mátyás király","Rocky","Johnny Cash"],["Mint két tojás","Kristálytiszta","A haját tépi"]],
    [ ["Lapát","Függöny","Álruha"], ["Muhammad Ali","Kviddics","Britney Spears"],["Muppet Show","Civilization","Befeszíti az izmait"]],
    [ ["Medúza","Ogre","Játékkonzol"], ["Kupidó","MacGyver","Hamupipőke"],["Alszik, mint egy csecsemő","Beleüti az orrát","Megforgatja benne a kést"]],
    [ ["Tenisz","Repülőtér","Kalap"], ["Kate Middleton","Szürkemarha","Iránytű"],["Péterfy Bori és a Love Band","A Sóhajok hídja","Jóbarátok"]],
    [ ["Bokszoló","Gabona","Kulacs"], ["Remeterák","Atlantisz","Bob Marley"],["Ördögi kör","Jankovics Marcell","Tíz kicsi indián"]],
    [ ["A kockás fülű nyúl","Aszpirin","Majom"], ["A szürke 50 árnyalata","Kontroll","Vaddisznó"],["Háborús sérülés","Emlékezetkiesés","Ínycsiklandó"]],
    [ ["Napszemüveg","Locsolókanna","Tündér"], ["A dzsungel könyve","Gandalf","Trágya"],["Bajonett","Szabadesés","Ali Baba"]],
    [ ["Farkas","Szabadítsátok ki Willyt!","Vasember"], ["Jelbeszéd","Rúzs","Júdás"],["Egyszer volt, hol nem volt…az élet","Elvisz egy körre","Al Capone"]],
    [ ["Rendőr","Banán","Fészek"], ["Mumus","Szivárvány","Luc Besson"],["Süket, mint az ágyú","Rosette-i kő","Szent Péter"]],
    [ ["Ló","Hitelkártya","Repülő csészealj"], ["Kaméleon","Atombomba","Cellux"],["Vakok közt a félszemű a király","Bedobja a törölközőt","Varró Dániel"]],
    [ ["Tea","Pokémon","Mesterszakács"], ["Toll","Jégkorcsolya","Szellemhajó"],["Napkeleti bölcsek","Pletyka","Egy birodalom bukása"]],
    [ ["Drón","A Múmia","Vár"], ["Mézga család","Ördögűző","Futóhomok"],["Visegrádi négyek","Truman show","Töri a nyelvet"]],
    [ ["Jégkocka","Strucc","Házasság"], ["Tell Vilmos","Tudakozó","Szfinx"],["Álommanó","Hegyeket mozgat meg","Stohl András"]],
    [ ["Étterem","Sisak","Anyajegy"], ["Protézis","Holt költők társasága","Petróleumlámpa"],["Kázmér és Huba","Mályvacukor","Padlógáz"]],
    [ ["Mikroszkóp","Őr","Anyahajó"], ["Micsoda nő!","Ötvös Csöpi","Mátrix"],["Keménykalap és krumpliorr","A miniszter félrelép","A trónok harca"]],
    [ ["Zenekar","Templom","Karácsonyi fények"], ["Gőzmozdony","Fogkrém","Helikopter-leszálló"],["Szabadságszobor","Forma 1","KFC"]],
    [ ["X-faktor","Plüssmaci","Szarka"], ["Cipzár","Smink","Szúnyogháló"],["Elpirul","Elment az esze","E.T."]],
    [ ["Ananász","Tojás","Postás"], ["Uszkár","McDonald’s","Empire State Building"],["Valami bűzlik","Sorbanállás","Madame Tussaud"]],
    [ ["Grillsütő","Orgyilkos","Darázs"], ["Paprikajancsi","Amy Winehouse","Harmonika"],["Kockázat nélkül nincs győzelem","Beleveti magát a munkába","Jockey Ewing"]],
    [ ["Hullócsillag","Sütemény","Pezsgő"], ["Ollókezű Edward","Szellemirtók","Bridget Jones"],["Gyors, mint a villám","Térdnadrág","Olaj a tűzre"]],
    [ ["Bányász","Börtön","Malom"], ["Tolvaj","Poszeidón","A piszkos 12"],["Hol van a kutya elásva?","Magányos farkas","Rágógumi"]],
    [ ["Eper","Petárda","Tűzoltó"], ["Bill Clinton","Borsszóró","Pecsét"],["A tudás hatalom","Holdfény királyság","Pertut inni"]],
    [ ["Patkány","Kerti slag","Gyalogkakukk"], ["Csontváz","Trambulin","Halálsoron"],["Kisujjból kirázza","Fidel Castro","Jim Carrey"]],
    [ ["Légzsák","Róka","Távcső"], ["Légpárnás hajó","Cseppkőbarlang","Jumanji"],["Drágán add az életed!","Rossz előérzet","Sportpálya"]],
    [ ["Bohóc","GPS","Fülbevaló"], ["Casper","Gitár","Honfoglalás"],["Schindler listája","Kétélű penge","Bosszantó"]],
    [ ["Kocsma","Béka","Vadász"], ["Transformers","Jelzőlámpa","Fogkefe"],["Felveszi a kesztyűt","Sátántangó","Éhezők viadala"]],
    [ ["Tigris","Hal","Napernyő"], ["Sudoku","Gyurma","Michael Jordan"],["Aki szerencsés a kártyában, szerencsétlen a szerelemben","Éleslátású","Elüti az időt"]],
    [ ["Metró","Karóra","Farkasember"], ["A hét szamuráj","Matrjoska baba","Lara Croft"],["Lélegzetvisszafojtva","A herceg fehér lovon","Fülébe suttog"]],
    [ ["Számítógép","Szélmalom","Lift"], ["Reszkessetek betörők!","Diablo","Majonéz"],["Martin Luther King","Achilles-ín","A kerekasztal lovagjai"]],
    [ ["Robot","Tengeri csillag","Foci"], ["Vasútvonal","Braille-írás","Patkó"],["Homokba dugja a fejét","Lottó","Ennio Morricone"]],
    [ ["Pénztárca","Alma együttes","Gyémánt"], ["Strand","Ügyvéd","Teasütemény"],["Ugróiskola","Rio de Janeiro","Fehér, mint a hó"]],
    [ ["Napellenző","Szobor","Kutyaház"], ["Öblítés","Shrek","Szitakötő"],["Bolond lyukból bolond szél fúj","Betintázik","Gyanakvó"]],
    [ ["Pingvin","Könyvtár","Orvos"], ["Dagobert bácsi","Édesítőszer","Croissant"],["Holdra szállás","Először üt, aztán kérdez","Rágja a körmét"]],
    [ ["Vadaspark","Melltartó","Párduc"], ["Pókember","Pincérnő","Mary Poppins"],["El Dorado","George W. Bush","Pengeélen táncol"]],
    [ ["Pék","A láthatatlan ember","Radar"], ["Macskanő","Koala","Puskapor"],["Belecsap a közepébe","Egy lyukas garast sem ér","Egri csillagok"]],
    [ ["Kiwi","Ablaktörlő","Titanic"], ["Bowling","Macskafogó","Tűsarok"],["Marco Polo","Baráti kör","Ki korán kel, aranyat lel"]],
    [ ["Papagáj","Szívószál","Eiffel-torony"], ["Keresztrejtvény","Marilyn Manson","Dexter"],["Majd ha piros hó esik","Justin Bieber","Buta, mint a tök"]],
    [ ["Dr. House","Toy Story","Cseresznye"], ["Harisnya","Jurassic Park","Guillotine"],["Piszkos Fred","Gollam","Feldobja a talpát"]],
    [ ["Sárkányrepülő","Gyümölcslé","Balaton"], ["A tanú","Reklám","Lance Armstrong"],["Húsvét-szigetek","Felmondás","Kerülgeti a forró kását"]],
    [ ["Tej","Orrszarvú","Unikornis"], ["Száll a kakukk fészkére","Kulcs","Milói Vénusz"],["Ben-Hur","Félbeszakítani valakit","Pénzfeldobás"]],
    [ ["Rózsaszín párduc","Dobókocka","A Simpson család"], ["Szépségkirálynő","A francia forradalom","Bőrönd"],["Hermione Granger","Lepereg róla a sértés","Vissza a jövőbe"]],
    [ ["Gyalogátkelőhely","Mikulás","Borász"], ["Bérbeadás","Szoborpark","Mozgólépcső"],["A pokolba vezető út jó szándékkal van kikövezve","Hallgatni arany","A római Colosseum"]],
    [ ["Csizma","Búvárfelszerelés","Ferrari"], ["Mágnes","Fénykard","Kuka"],["A vietnámi háború","Visszafogja magát","A Tiltott Város"]],
    [ ["Mentőautó","Fecskendő","Pizsama"], ["Micimackó","Állomás","Császármetszés"],["Olyan, akár egy nyitott könyv","Idényjellegű","Felhúzza magát"]],
    [ ["Ping-pong","Kesztyű","Szalvéta"], ["Hannibal Lecter","A rózsa neve","Kenyérpirító"],["Felpaprikázva","Szemfényvesztő","Maga alatt vágja a fát"]],
    [ ["Mobiltelefon","Pók","Zsiráf"], ["Animal Planet","Terminátor","Cirkusz"],["Alcatraz","Húzza az igát","Füstöl, mint egy gyárkémény"]],
    [ ["Sas","Napraforgó","Konyha"], ["Arkhimédész","Borat","Halálos iramban"],["Sixtus-kápolna","Volt egyszer egy vadnyugat","Felvágták a nyelvét"]],
    [ ["Bank","Hálószoba","Furulya"], ["Halász Judit","Síp","Született feleségek"],["Mákos bejgli","Elakad a lélegzete","Top Gun"]],
    [ ["Tricikli","Sült hús","Egyiptom"], ["Alkonyat","Batman","Brad Pitt"],["Klónozás","Szabad kezet kap","Billy Jane"]],
    [ ["Legyező","Kávé","Csörgő"], ["Krokodil Dundee","Szellemvasút","Sasszem"],["Heuréka!","Elharapja a szó végét","Sigmund Freud"]],
    [ ["Dinoszaurusz","Láncfűrész","Hupikék törpikék"], ["Dr. Jekyll","Mózes","Captain Jack Sparrow"],["Adam Sandler","Egy kép felér ezer szóval","Elszorul a torka"]],
    [ ["Spenót","Bárka","Örökség"], ["Yesterday","Halálos fegyver","Teflon edény"],["Jean-Claude Van Damme","Megkéri a kezét","Kábítószercsempész"]],
    [ ["Harry Potter","Tó","Coca-Cola"], ["Szauna","Rómeó és Júlia","A pisai ferde torony"],["Százéves háború","A tetovált lány","Luke, én vagyok az apád."]],
    [ ["Super Mario","Rúdugrás","Trombita"], ["Hősök tere","Szappan","Baguette"],["Az életemet tenném rá","Nincs itt keresnivalója","Rémálom"]],
    [ ["Jegesmedve","Boszorkány","Hóember"], ["Ejtőernyő","Katapult","Ruhacsipesz"],["Bal lábbal kel fel","Felkapja a vizet","Mindenki másképp csinálja"]],
    [ ["Madártoll","Kókuszdió","Kikötő"], ["Rozsomák","Az élet szép","Men in Black"],["Nászút","El van havazva","Nyomja a lelkét"]],
    [ ["Jojó","101 kiskutya","Pillangó"], ["Adéle","Blöff","Pillangókés"],["Bevásárlókocsi","Cenzúra","Ki mint vet, úgy arat"]],
    [ ["Kékestető","Szúnyog","Mikrohullámú sütő"], ["Az idő urai","Billentyűzet","Bruce Lee"],["A villám nem csap kétszer ugyanoda","Carpe Diem","Öregember nem vénember"]],
    [ ["Jégkorszak","Delfin","Víztorony"], ["Elfújta a szél","Ocean’s Eleven","Gabonakör"],["Két lábbal áll a földön","Veszedelmes viszonyok","Éhezés"]],
    [ ["Spongyabob","Fűszer","Tarzan"], ["Fűbe harapott","Richie Rich","Esmeralda"],["Kreml","Torkán akad a szó","Az elveszett cirkáló"]],
    [ ["Kolbász","LEGO","Mackó sajt"], ["Defibrillátor","Stílus","MP3-lejátszó"],["Nyitott szemmel néz a világra","Másnaposság","Snoopy"]],
  ];
}

?>
