<?php
class ConceptCardsSP {
  static $cards = [
    [ ["Rueda","Piscina","Canguro"], ["Rata","Ruleta de la fortuna","Karaoke"],["Robinson Crusoe","Delirios de grandeza","Ojo de águila"]],
    [ ["Pararrayos","Viernes 13","Reproductor mp3"], ["Micrófono","Tupperware","Austin Powers"],["Máscara","Buscarle tres pies al gato","Hora de Aventuras"]],
    [ ["Buscando a Nemo","Casco","Vino"], ["El planeta de los simios","Interruptor","Velcro"],["Puño de hierro en guante de terciopelo","La guinda del pastel","La ocasión la pintan calva"]],
    [ ["Ladrillo","Navaja suiza","Diccionario"], ["Balú","Beyoncé","Colmillo Blanco"],["Más vale pájaro en mano que ciento volando","Lope de Vega","Abrebotellas"]],
    [ ["Bañera","Cuaderno","Estetoscopio"], ["Araña","Batería","Silicona"],["Ni para ti, ni para mi","Estar mano sobre mano","Juego de Tronos"]],
    [ ["Tractor","Concha","Cubo de Rubik"], ["Termo","Ciervo","Reina"],["Hacer borrón y cuenta nueva","Alto el fuego","Romper el silencio"]],
    [ ["Avión de extinción de incendios","Ardilla","Ángel"], ["Bilbo Bolsón","David Guetta","Capitán Harlock"],["Hambre de lobo","Dragonball Z","Recuperar el tiempo perdido"]],
    [ ["Mago","Erizo","Matrícula"], ["El Principito","Indiana Jones","Pamela Anderson"],["No se puede hacer una tortilla sin romper algunos huevos","Lavado de cerebro","Las desgracias nunca vienen solas"]],
    [ ["Taladro","Oficina","Margarita"], ["Mr. Potato","Presa (embalse)","El Señor de los Anillos"],["Por los pelos","Tomarse un respiro","El club de los poetas muertos"]],
    [ ["Residencia de ancianos","Vampiro","Escalera"], ["Mediterráneo","Troll","Cyrano de Bergerac"],["El quinto elemento","Cheque sin fondos","Detective"]],
    [ ["Cocodrilo","Canario","Piano"], ["Objetivo","Billy el Niño","Bigote"],["Iñaki Gabilondo","Palangana","No apto para cardiacos"]],
    [ ["Desfibrilador","Tetris","Ballena"], ["Código de barras","Stonehenge","Ballesta"],["Confesar tus pecados","Los Vengadores","Aspiradora"]],
    [ ["Bodega","León","Reloj de sol"], ["Bolsa de agua caliente","Tirachinas","Barco de vapor"],["Batir un récord","La violetera","Tener cargo de conciencia"]],
    [ ["Planeador","Dentadura postiza","Cangrejo"], ["Palmera","Contable","Cargador de munición"],["De tal palo tal astilla","Silueta","Primera bailarina"]],
    [ ["Escorpión","Pez espada","Perfume"], ["Rugby","Dinamita","Martes y Trece"],["Fuera de contexto","Estar en el séptimo cielo","Mensaje subliminal"]],
    [ ["Camión","Ratón","Parquímetro"], ["Cerveza","Cubo","Mike Tyson"],["Atontado","Mirarse el ombligo","Mendigo"]],
    [ ["Caza (avión)","Cuerno","Tiburón"], ["Acuarelas","Kill Bill","Breaking Bad"],["Armado hasta los dientes","Kiwi","Reavivar la llama"]],
    [ ["Profesor","Chocolate","Spray de pimienta"], ["50 sombras de Grey","Pepa Pig","Bagheera"],["El bueno, el feo y el malo","Saltarse un semáforo en rojo","Estar en las nubes"]],
    [ ["Piloto","Máscara antigás","Pinocho"], ["Neil Armstrong","Enamorado de la moda juvenil","La naranja mecánica"],["Estar a dos bandos","Suplemento dominical","Saltarse las reglas"]],
    [ ["Cebra","Mecánico","DVD"], ["Xilófono","Yeti","Ciclista"],["Ciego como un topo","Estudio en escarlata","Malo como un dolor"]],
    [ ["Vaca","Cerdo","Ventana"], ["Trivial Pursuit","Castor","Imperdible"],["Estar cañón","No es el fin del mundo","Distraído"]],
    [ ["Tipi","Camisa","Cohete"], ["Sushi","Calculadora","Patatas fritas"],["Tina Turner","Preocuparse por alguien","La historia interminable"]],
    [ ["Enchufe","Fontanero","Barbie"], ["Palomitas de maíz","Papel higiénico","Ascensor"],["Popeye","Abrir la caja de Pandora","Ágil como un mono"]],
    [ ["Yogurt","Paraguas","Ninja"], ["Winnie the Pooh","Madre Teresa","Lucky Luke"],["Desatascador","Mars Attacks!","Rompetechos"]],
    [ ["Pescador","Río","Extintor"], ["Mister Bean","Radiador","Elton John"],["Sacarse las castañas del fuego","Socios y sabuesos","Lento como un caracol"]],
    [ ["Veleta","Gimnasio","Porche"], ["Guerra y paz","Golondrina","Vacuna"],["Las cuevas de Altamira","Inception","Novela rosa"]],
    [ ["Tenedor","Pistola","Murciélago"], ["Forrest Gump","Hurón","Cucaracha"],["Conocer tus límites","Val Kilmer","Rompecorazones"]],
    [ ["Caracol","Zorro","Radio de coche"], ["Dumbo","Zelda","Angry Birds"],["Mentes criminales","Mamá gallina","American Beauty"]],
    [ ["Mazapán","Volar","Bizcocho"], ["Cómic","Mujercitas","Camino"],["Buscar una aguja en un pajar","Pitar (que te piten) los oídos","La avaricia rompe el saco"]],
    [ ["Toro","Abeto","Pac -Man"], ["Tintín","Patines","Margaret Thatcher"],["La suerte está echada","La estatua del Cristo Redentor","Besucón"]],
    [ ["Peter Pan","Cortacésped","Intermitente"], ["Yellow Submarine","Asturias patria querida","Postal"],["Más chulo que un ocho","Llover a cántaros","Mi vecino Totoro"]],
    [ ["Montaña","Hotel","Iglú"], ["Los pilares de la Tierra","Jacuzzi","Juana de Arco"],["Las siete maravillas del mundo","Paco Martínez Soria","Marlon Brando"]],
    [ ["Pirata","Bicicleta","Hucha"], ["Órgano","Tsunami","Sacapuntas"],["Ojo morado","Hombre prevenido vale por dos","Sacacorchos"]],
    [ ["Tormenta","Vitamina","Campana"], ["Estación espacial","Veinte mil leguas de viaje submarino","Casino Royale"],["Gran Torino","V de vendetta","Cabezota"]],
    [ ["Grúa","Máquina de coser","Arpón"], ["Pepino","Pulgarcito","Hula hoop"],["David y Goliat","Macaulay Culkin","Yuri Gagarin"]],
    [ ["Buitre","Pantalón vaquero","Ipad"], ["Agujero negro","Tocadiscos","Platero y yo"],["Peca/Lunar","Tirar la primera piedra","Tirar el dinero por el desagüe"]],
    [ ["Nocilla","Trineo","Espada"], ["Taza de váter","Celda 211","Buenafuente"],["La noche del cazador","Laïka","Enterrar el hacha de guerra"]],
    [ ["La casa de la pradera","Día festivo","Volcán"], ["Campanilla","Julia Roberts","Whisky"],["Pesadilla antes de Navidad","Boys will be boys","Vender tu alma al diablo"]],
    [ ["Candado","Pato","Lupa"], ["Dalai Lama","Billar","Lassie"],["Hacerse una bola","Hacer la cobra","Torre de Babel"]],
    [ ["Chimenea","Avatar","Sombrero"], ["Cafetera","Afrodita","Salchicha"],["Cepillo para el pelo","Mimo","Las brujas de Zugarramurdi"]],
    [ ["Pozo","Día de San Valentín","Abeja"], ["Post-it","Robin Hood","2001: Una odisea del espacio"],["Dar el alto","Dar gato por liebre","Derrapar"]],
    [ ["Blancanieves y los siete enanitos","Genio","Minecraft"], ["Astérix y Obélix","Gladiator","El silencio de los corderos"],["Sudor frío","Hacerse el loco","La vuelta al mundo en 80 días"]],
    [ ["Eclipse","Garaje","Ático"], ["D’ Artagnan","El Gigante Verde","Santiago Calatrava"],["Dar margaritas a los cerdos","Paco León","Caballito de mar"]],
    [ ["Meteorito","Museo","Refrigerador"], ["Lentes de contacto","Los Sims","Power Rangers"],["El siglo de las luces","Tener las manos húmedas","Rain Man"]],
    [ ["Impresora","Chalet","Alfombra"], ["John Lennon","Bowling for Columbine","Snowboard"],["Una noche en la ópera","Big Ben","Skyfall"]],
    [ ["Elefante","Encendedor","Elfo"], ["Robocop","Bambi","Diablo"],["Eminem","Tener miedo a las alturas","Más solo que la una"]],
    [ ["Maceta","Dragón","Natación"], ["Torre de perforación petrolífera","Palillo","Pocoyó"],["Cuantos más, mejor","Democracia","Orgullo y Prejuicio"]],
    [ ["Aladino","Cometa","Manzana"], ["Agricultor","Panadero","Faro"],["Poner los nervios de punta","Tartamudo","Perder la calma"]],
    [ ["Cars","Yoda","Submarino"], ["Buzón","Woody Allen","Cervantes"],["Cabina de bronceado","Ladrón","Parecer dos gotas de agua"]],
    [ ["Cine","Serpiente","Mafalda"], ["Mortadelo y Filemón","Santo Grial","Los peces en el río"],["Más claro que el agua","Tirarse de los pelos","Barrio Sésamo"]],
    [ ["Monopoly","Ensalada","Colegio"], ["Los pájaros","Rocky","El Fary"],["Sin City","Sacar músculo","Dormir como un bebé"]],
    [ ["Pala","Cortinas","Disfraz"], ["Muhammad Ali","Quidditch","Amaral"],["Como un burro amarrado en la puerta del baile","Meter la pata","Echar sal en la herida"]],
    [ ["Medusa","Ogro","Videoconsola"], ["LEGO","MacGyver","Cenicienta"],["El puente de los Suspiros","Mario Casas","Círculo vicioso"]],
    [ ["Tenis","Aeropuerto","Sombrero"], ["Kate Middleton","Entre dos tierras","Brigitte Bardot"],["Epi y Blas","Estaba el señor Don Gato","Heridas de guerra"]],
    [ ["Boxeador","Trigo","Cantina"], ["Cangrejo Ermitaño","Atlantis","Bob Marley"],["Tener un lapsus","Boca de riego","Bayoneta"]],
    [ ["Moco","Aspirina","Mono"], ["La sombra del viento","Alf","Jabalí"],["Caída libre","Alí Babá","Tomar el pelo"]],
    [ ["Gafas de sol","Regadera","Hada"], ["El libro de la selva","Albus Dumbledore","Fertilizante"],["Superlópez","Al Capone","Sordo como una tapia"]],
    [ ["Lobo","Liberad a Willy","Iron man"], ["Lenguaje de signos","Pintalabios","Judas"],["La Piedra de Rosetta","San Pedro","Tirar la toalla"]],
    [ ["Policía","Plátano","Nido"], ["El Coco","Arco iris","Pedro Almodóvar"],["En el reino de los ciegos, el tuerto es el rey","Estirar la pata","Los Reyes Magos"]],
    [ ["Caballo","Tarjeta de crédito","Platillo volante"], ["Camaleón","Bomba atómica","Cinta adhesiva"],["La vaquilla","Construir un imperio","Ir vestido de punta en blanco"]],
    [ ["Té","Pokémon","Top Chef"], ["Bolígrafo","Patinar sobre hielo","Los Gremlins"],["El show de Truman","Amor a quemarropa","Sandman"]],
    [ ["Drone","La momia","Castillo"], ["Cúter","El Exorcista","Arenas movedizas"],["Mover montañas","David el Gnomo","Calvin y Hobbes"]],
    [ ["Cubito de hielo","Avestruz","Matrimonio"], ["Guillermo Tell","Guía telefónica","La Esfinge de Giza"],["Chupachups","Pisar el acelerador","Los Cinco"]],
    [ ["Restaurante","Estilo","Topo"], ["Prótesis","El club de la lucha","Penélope Cruz"],["Resident Evil","Canción de Hielo y Fuego","El Coloso de Rodas"]],
    [ ["Microscopio","Guardia","Portaaviones"], ["El Bola","Santiago Segura","Piratas del Caribe"],["Las 24 horas de Lemans","Carpanta","Ponerse rojo como un tomate"]],
    [ ["Orquesta","Iglesia","Luces de Navidad"], ["Máquina de vapor","Pasta de dientes","Helipuerto"],["Ojos que no ven , corazón que no siente","E. T. El extraterrestre","Oler a chamusquina"]],
    [ ["Telediario","Oso de peluche","Urraca"], ["Cremallera","Maquillaje","Mosquitera"],["Cortar de raíz","Duquesa de Alba","Lanzarse de cabeza"]],
    [ ["Piña","Huevo","Cartero"], ["Caniche","McDonald’s","Empire State Building"],["El toro de Osborne","Lewis Caroll","Rápido como un rayo"]],
    [ ["Barbacoa","Asesino","Avispa"], ["Arlequín","Amy Winehouse","Harmónica"],["Pantalones pirata","Echar leña al fuego","¿Dónde está el fuego?"]],
    [ ["Estrella fugaz","Pastel","Champán"], ["Eduardo Manostijeras","Cazafantasmas","El día de la bestia"],["Pipas de girasol","Chicle","El Gordo de Navidad"]],
    [ ["Minero","Prisión","Molino"], ["El Larguero","Poseidón","Las uvas de la ira"],["Contrabando","Brindar","Porción de pastel"]],
    [ ["Fresa","Petardo","Bombero"], ["Bill Clinton","Molinillo de pimienta","Sello"],["Fidel Castro","Remangarse","La jungla de cristal"]],
    [ ["Teletienda","Manguera","Correcaminos"], ["Esqueleto","Trampolín","La milla verde"],["Tentar a la suerte","Congreso de los Diputados","Muerte entre las flores"]],
    [ ["Airbag","Zorro","Prismáticos"], ["Hovercraft","Princesa","Jumanji"],["Espada de doble filo","Enredados","Jim Carrey"]],
    [ ["Payaso","GPS","Pendiente"], ["Casper","Guitarra","Columpio"],["Afortunado en el juego , desafortunado en amores","Molestar","Tener buena vista"]],
    [ ["Club","Rana","Cazador"], ["Transformers","Luz estroboscópica","Cepillo de dientes"],["Matar el tiempo","Los juegos del hambre","Contener la respiración"]],
    [ ["Tigre","Pescado","Sombrilla"], ["Sudoku","Plastilina","Michael Jordan"],["El Guerrero del Antifaz","Hablar en susurros","Martin Luther King"]],
    [ ["Metro","Reloj de pulsera","Hombre-lobo"], ["Mujeres al borde de un ataque de nervios","Los 7 samuráis","Lara Croft"],["Talón de Aquiles","Caballeros del Zodiaco","Esconder la cabeza"]],
    [ ["Ordenador","Molino de viento","Papel de aluminio"], ["Solo en casa","Mario Bros.","Mayonesa"],["Lotería","Ennio Morricone","Rayuela"]],
    [ ["Robot","Estrella de mar","Fútbol"], ["Vía de tren","Braille","Herradura"],["Rio de Janeiro","Blanco como la nieve","Ríos de tinta"]],
    [ ["Cartera","Lata","Diamante"], ["Playa","Abogado","Galleta"],["Sólo los tontos se enamoran","Oler a tigre","De la Tierra a la Luna"]],
    [ ["Protector solar","Estatua","Caseta de perro"], ["Rubor","Shrek","Libélula"],["Tropezar dos veces con la misma piedra","Estar de brazos cruzados","El gato Isidoro"]],
    [ ["Pingüino","Biblioteca","Médico"], ["Tío Gilito","Aspartamo","Croissant"],["George W. Bush","El hormiguero","Comienzo explosivo"]],
    [ ["Calabaza","Sujetador","Pantera"], ["Tamagochi","Camarero","Mary Poppins"],["Andar con pies de plomo","Echar un vistazo","Marco Polo"]],
    [ ["Concorde","El hombre invisible","Radar"], ["Catwoman","Koala","Pólvora"],["Círculo de amistades","El dinero no crece en los árboles","Cuando los cerdos vuelen"]],
    [ ["Silla eléctrica","Limpiaparabrisas","Titanic"], ["Bolos","Lejía","Tacón de aguja"],["Justin Bieber","Pagafantas","Desmayarse"]],
    [ ["Loro","Hierba","Torre Eiffel"], ["Crucigrama","Marilyn Manson","Dexter"],["Mi tesoro","Criar malvas","Isla de Pascua"]],
    [ ["Dr. House","Toy Story","Cereza"], ["Cupido","El gran dictador","Brújula"],["Dimitir","Andar con rodeos","Ben- Hur"]],
    [ ["Ala delta","Zumo de fruta","Timón"], ["Pantys","Parque Jurásico","Guillotina"],["Interrumpir a alguien","Lanzar una moneda","Hermione Granger"]],
    [ ["Leche","Rinoceronte","Unicornio"], ["En busca del fuego","Anuncio","Lance Armstrong"],["Bufy Cazavampiros","Regreso al futuro","El tiempo es oro"]],
    [ ["La Pantera Rosa","Dados","Los Simpson"], ["Guerra Mundial Z","Llave","Venus de Milo"],["Muela del juicio","El Coliseo de Roma","Guerra de Vietnam"]],
    [ ["Paso de peatones","Papá Noel","Enólogo"], ["Miss Universo","La Revolución francesa","Maleta"],["Ratoncito Pérez","La Ciudad Prohibida","Goku"]],
    [ ["Botas","Equipo de buceo","Ferrari"], ["Alquiler","Sopa de ganso","Escalera mecánica"],["El corazón en un puño","Las Cuatro Estaciones","Agarrar el toro por los cuernos"]],
    [ ["Ambulancia","Jeringuilla","Pijama"], ["Imán","Sable láser","Cubo de la basura"],["Es lo que es","Dispararse a uno mismo en el pie","Alcatraz"]],
    [ ["Tenis de mesa (ping-pong)","Guantes","Trituradora de papel"], ["Edipo","Estación","Cesárea"],["Demasiado cansado para pensar con claridad","Fumar como un carretero","La Capilla Sixtina"]],
    [ ["Telefono móvil","Telescopio infrarrojo","Jirafa"], ["Hannibal Lecter","El nombre de la rosa","Tostadora"],["Érase una vez en el Oeste","Lengua bífida","Monaguillo"]],
    [ ["Águila","Girasol","Cocina"], ["Velero","Terminator","Circo"],["Quedarse sin aliento","Top Gun","Clonación"]],
    [ ["Banco","Dormitorio","Flauta"], ["Arquímedes","Borat","Fast and Furious"],["Mi reino por un caballo","Billy Jean","¡Eureka!"]],
    [ ["Triciclo","Filete","Egipto"], ["El juego de Ender","Silbato","Mujeres Desesperadas"],["Morderse la lengua","Sigmund Freud","Adam Sandler"]],
    [ ["Ventilador","Café","Sonajero"], ["Crepúsculo","Batman","Chiquito de la Calzada"],["Una imagen vale más que mil palabras","Tener un nudo en la garganta","Jean -Claude van Damme"]],
    [ ["Dinosaurio","Sierra mecánica","Los pitufos"], ["Cocodrilo Dundee","El tren de la bruja","La vaca que ríe"],["Pedir la mano en matrimonio","Tráfico de drogas","La Guerra de los Cien Años"]],
    [ ["Espinacas","Barcaza","Patrimonio"], ["Dr. Jekyll","Moisés","Jack Sparrow"],["Los hombres que no amaban a las mujeres","Esmeralda","Luke, yo soy tu padre"]],
    [ ["Harry potter","Lago","Coca-cola"], ["La casa por el tejado","Loquillo y los trogloditas","Paella"],["Estar a dos velas","Tres son multitud","Pesadilla"]],
    [ ["Sonic el Erizo","Salto con pértiga","Trompeta"], ["Sauna","Romeo y Julieta","La torre de Pisa"],["Levantarse con el pie izquierdo","Como pez en el agua","Para gustos los colores"]],
    [ ["Oso polar","Bruja","Muñeco de nieve"], ["La Estatua de la Libertad","Jabón","Barra de pan"],["Luna de miel","Ir pisando huevos","Valer tu peso en oro"]],
    [ ["Pluma","Coco","Puerto"], ["Paracaídas","Catapulta","Pinza de ropa"],["Carro de la compra","Censura","Lágrimas de cocodrilo"]],
    [ ["Yoyó","101 Dálmatas","Mariposa"], ["Lobezno","La vida es bella","Men in Black"],["No tener abuela","Vivir la vida al máximo","Más viejo y más sabio"]],
    [ ["Leñador","Mosquito","Microondas"], ["Falete","Abierto hasta el amanecer","Cuchillo de mantequilla"],["Tener los pies en el suelo","Las amistades peligrosas","Hambre"]],
    [ ["Edad de hielo","Delfín","Depósito de agua"], ["Los Goonies","Teclado","Bruce Lee"],["Kremlin","Dejar a alguien sin palabras","Salir del armario"]],
    [ ["Bob Esponja","Especia","Tarzán"], ["Lo que el viento se llevó","Ocean’s Eleven","Círculo de la cosecha"],["Resaca","Dormir con un ojo abierto","Snoopy"]],
  ];
}

?>
