<?php
class ConceptCardsRO {
  static $cards = [
    [ ["Roată","Piscină","Cangur"], ["șoarece","roata norocului","karaoke"],["Prâslea cel voinic și merele de aur","Robinson Crusoe","ochi de vultur"]],
    [ ["paratrăznet","marți 13","MP3 player"], ["microfon","tigaie de teflon","Austin Powers"],["Decebal","ironic","Birt"]],
    [ ["În căutarea lui Nemo","cască","vin"], ["Planeta maimuțelor","Dop","Glob de brad"],["Cireașa de pe tort","Bate fierul cât e cald!","Colac peste pupăză!"]],
    [ ["Cărămidă","Briceag","Dicționar"], ["Ursul Baloo","Beyoncé","Amintiri din copilărie"],["A-ți veni mintea la cap","Mircea Vintilă","Desfăcător de sticle"]],
    [ ["Cadă","Laptop","Stetoscop"], ["Păianjen","Baterie","Mortar"],["A face treabă de mântuială","Compromis","A fi cu un picior în groapă"]],
    [ ["Tractor","Scoică","Cub Rubik"], ["Termos","Căprioară","Regină"],["A o lua de la început","Armistițiu","Arthur C. Clarke"]],
    [ ["Elicopter","Veveriță","înger"], ["Bilbo Baggins","Ion Creangă","I.L Caragiale"],["Tinerețe fără bătrânețe și viață fără de moarte","Mort de foame","Dragonball Z"]],
    [ ["Magician","Arici","Număr de înmatriculare"], ["Micul Prinț","Indiana Jones","Pamela Anderson"],["Nichifor Lipan","Spălat pe creier","A trage cu urechea"]],
    [ ["Burghiu","La birou","Margaretă"], ["Omulețul Gopo","Baraj","Stăpânul inelelor"],["Pe muchie de cuțit","Cară-te!","Cenaclul Flacăra"]],
    [ ["Azil de bătrâni","Vampir","Scară"], ["Iobag","Ciuleandra","Moromete"],["Al cincelea element","Ponosit","Detectiv"]],
    [ ["Crocodil","Peruș","Pian"], ["țintă","Frankenstein","Mustață"],["Smiley","Frecție la un picior de lemn","A fi dus cu pluta"]],
    [ ["Defibrilator","Tetris","Balenă"], ["Cod de bare","Stonehenge","Arbaletă"],["Spovedanie","The Avengers","Aspirator"]],
    [ ["Pivniță","leu","Cadran solar"], ["Bec economic","Praștie","Vas cu aburi"],["A doborâ un record","Fetița cu chibrituri","A avea conștiința încărcată"]],
    [ ["Planor","Smartphone","Crab"], ["Palmier","Contabil","Trusă de scule"],["A freca menta","Siluetă","Primă balerină"]],
    [ ["Scorpion","Păstrăv","Parfum"], ["Rugby","Dinamită","Maria Tănase"],["I-a picat fisa !","I-a sărit muștarul !","Mesaje subliminale"]],
    [ ["Basculantă","Mouse","Parcare cu plată"], ["șifonier","Găleată","Vincent van Gogh"],["Brain storming","Ada Milea","Cerșetor"]],
    [ ["Avion de vânătoare","Claxon","Rechin"], ["Acuarele","Kill Bill","Evadare"],["înarmat până în dinți","Kiwi","Ciorba reîncălzită îi acră!"]],
    [ ["Profesor","Ciocolată","Răufăcător"], ["Roșu și negru","Ursul păcălit de vulpe","Pantera Bagheera"],["Răbdări prăjite la tavă","A trece pe roșu","A fi cu capul în nori"]],
    [ ["Pilot","Mască de gaz","Pinocchio"], ["Neil Armstrong","Conversație telefonică","Portocala mecanică"],["Tufă de Veneția","Ziarul de duminică","A încurca borcanele"]],
    [ ["Zebră","Mecanic auto","DVD"], ["Xilofon","Muma pădurii","Ciclism"],["Orbul găinii","A avea o minte creață","La mama naibii"]],
    [ ["Vacă","Porc","Fereastră"], ["Activity","Castor","Voce electronică"],["A-ți băga coade unde nu-ți fierbe oala","Sfârșitul lumii","Visător"]],
    [ ["Cort","Tricou","Rachetă"], ["Sushi","Calculator","Cartofi prăjiți"],["Tina Turner","Pisicile aristocrate","Fight Club"]],
    [ ["ștecher","Instalator","Barbie"], ["Popcorn","Hârtie igienică","Lift"],["Popeye","A deschide cutia Pandorei","Azilant"]],
    [ ["Iaurt","Umbrelă","Ninja"], ["Ursulețul Winnie the Pooh","Maica Teresa","Nică a lui Ștefan a Petrei"],["A te îmbăta cu apă rece","Pădurea spânzuraților","Dem Rădulescu"]],
    [ ["Pescar","Râu","Hidrant"], ["Mister Bean","Calorifer","Elton John"],["Orson Scott Card","Monsters Inc.","Viteza melcului"]],
    [ ["Clanță","Gimnaziu","Verandă"], ["Război și pace","A înghiți","Vaccin"],["Peștera Muierii","Inception","Romane de dragoste"]],
    [ ["Furculiță","Pușcă","Liliac"], ["Forrest Gump","Dihor","Gândac"],["A dispărea ca măgarul în ceață","A-ți cunoaște limitele","îți frânge inima"]],
    [ ["Melc","Zorro","Aer condiționat"], ["Dumbo","Sarea în bucate","Angry Birds"],["Minți criminale","Cloșcă","American Beauty"]],
    [ ["Tăierea porcului","Muscă","Clătite"], ["Harap Alb continua","Parfum de femeie","Potecă"],["A căuta acul în carul cu fân","îmi bubuie urechile","Ați înnebunit cu toții!"]],
    [ ["Taur","Brad","Pac-Man"], ["Aventurile lui Tintin","Patine cu rotile","Margaret Thatcher"],["A avea noroc cu carul","Crucea de pe Caraiman","Mircea Albulescu"]],
    [ ["Peter Pan","Interfon","Semafor"], ["Punguța cu doi bani","Mașină de formula 1","Carte poștală"],["Privire tâmpă","A minți de îngheață apele","Când mi-oi vedea ceafa"]],
    [ ["Munte","Hotel","Iglo"], ["Baltagul","Jacuzi","Răspântie de drumuri"],["Cele 7 minuni ale lumii antice","Draga Olteanu Matei","Dragoș Bucur"]],
    [ ["Pirat","Bicicletă","Pușculiță"], ["Mineriadă","Tsunami","Ascuțitoare"],["Paza bună, trece primejdia rea!","Ochi învinețit","Tirbușon"]],
    [ ["Furtună","Vitamină","Clopot"], ["Stația Orbitală","20.000 de leghe sub mări","Casino Royale"],["A pune umărul la treabă","V de la Vendetă","Căpos"]],
    [ ["TIR","Mașină de cusut","Harpon"], ["Castravete","Tom Degețel","Dans din buric"],["David și Goliat","Putred de bogat","Yuri Gagarin"]],
    [ ["Vultur","Blugi","Tabletă"], ["Gaură neagră","Tonomat","Toma Caragiu"],["Semn de frumusețe","A-ți lua o piatră de pe inimă","A arunca banii pe fereastră"]],
    [ ["Cremă de ciocolată","Sanie","Sabie"], ["Colac WC","Miorița","Florin Piersic"],["Maia Morgenstern","Laika","A îngropa securea războiului"]],
    [ ["Casă de piatră","Sărbătoare națională","Vulcan"], ["Premiile Oscar","Julia Roberts","Whiskey"],["Frumoasa și Bestia","Șuie paparude","A-ți vinde sufletul diavolului"]],
    [ ["încuietoare","Rață","Lupă"], ["Dalai Lama","Biliard","Azorel"],["Iluzie optică","Sputnik","Turnul Babel"]],
    [ ["Coș de fum","Avatar","Sombrero"], ["2001: Odiseea spațială","Afrodita","IKEA"],["Post-it","Walt Disney","A-ți face curaj"]],
    [ ["Fântână","Albină","Dragobete"], ["Ibric de cafea","Robin Hood","Cârnat"],["Perie de păr","Dosar penal","Diasporaă"]],
    [ ["Albă ca Zăpada și cei 7 pitici","Genial","Minecraft"], ["Asterix și Obelix","Gladiatorul","Fălci"],["Ocolul pământului în 80 de zile","A te trece toate sudorile","Laura Cosoi"]],
    [ ["Eclipsă","Garaj","Podul casei"], ["D’Artagnan","Tarom","Marin Preda"],["A arunca orzul pe gâște","George Enescu","Căluț de mare"]],
    [ ["Meteorit","Muzeu","Congelator"], ["Lentilă de contact","Farmville","Hanul Ancuței"],["Opera din Sydney","Mâini transpirate","Hulk"]],
    [ ["Imprimantă","Conac","Covor"], ["John Lennon","Transfăgărășan","Snowboard"],["Florian Pitiș","Big Ben","Direcția 5"]],
    [ ["Elefant","Brichetă","Elf"], ["Trotinetă","Bambi","Diavol"],["Cu cât mai mult, cu atât mai bine!","Eminem","Frică de înălțime"]],
    [ ["Ghiveci","Dragon","înot"], ["Platformă petrolieră","Scobitoare","Țestoasele Ninja"],["A ști la ce să te aștepți","Democrație","Mândrie și prejudecată"]],
    [ ["Aladdin","Zmeu de vânt","Măr"], ["Fermier","Brutar","Farul de la Constanța"],["Mă calci pe nervi!","Bâlbâit","A-ți pierde cumpătul"]],
    [ ["Mașină","Cavaler Jedi","Submarin"], ["Cutie poștală","Woody Allen","Limax"],["A semăna ca două picături de apă!","Solar","Pungaș"]],
    [ ["Cinema","șarpe","Purcel"], ["BUG mafia","Liviu Rebreanu","Untold"],["A da târcoale","A-ți smulge părul din cap","Hologtaf"]],
    [ ["Monopoly","Salată","școală"], ["Taxi","A face din țânțar armăsar","Johnny Cash"],["Gramofon","A-ți încorda mușchii","A dormi neîntors"]],
    [ ["lopată","Perdele","Deghizare"], ["Islamism","Quidditch","Inginer constructor"],["A pune piciorul în prag","A întoarce cuțitul în rană","Filatelie"]],
    [ ["Meduză","Căpcăun","Consolă de jocuri"], ["LEGO","șofer de taxi","Cenușăreasă"],["Superman","Dan Bittman","Cerc vicios"]],
    [ ["Tenis","Aeroport","Pălărie"], ["Kate Middleton","Creștinism","Brigitte Bardot"],["Vița de Vie","Zece negri mititei","Caleidoscop"]],
    [ ["Boxeur","Grâu","Ploscă"], ["Parlamentul European","Atlantida","Bob Marley"],["A avea un lapsus","A-ți ploua în gură","The Jocker"]],
    [ ["Muci","Aspirină","Maimuță"], ["Documente contabile","Mihail Sadoveanu","Mistreț"],["Aferim","Ali Baba","A fi luat peste picior"]],
    [ ["Ochelari de soare","Stropitoare","Zână"], ["Cartea junglei","Albus Dumbledore","îngrășământ"],["Kung Fu Panda","Al Capone","Pomelo"]],
    [ ["lup","Capra cu trei iezi","Iron Man"], ["Limbajul semnelor","Ruj","Voltaj"],["Orb nu este cel ce nu vede, ci cel ce nu se uită!","Contabilitate primară","Sfântul Andrei"]],
    [ ["Polițist","Banană","Cuib"], ["Bau bau","Curcubeu","Corneliu Porumboiu"],["Greuceanu","Carie dentară","Liceenii rock ‘n’ roll"]],
    [ ["Cal","Carte de credit","OZN"], ["Cameleon","Bombă atomică","Bandă adezivă"],["Mica Sirenă","A construi un imperiu","îmbrăcat la patru ace"]],
    [ ["Ceai","Tom și Jery","Bucătar"], ["Pix","Patină de gheață","Corabie fantomă"],["The Truman Show","Accent moldovenesc","Moș Ene"]],
    [ ["Acvariu cu pești","Mumie","Castel"], ["Leonardo DiCaprio","Mitropolit","Nisipuri mișcătoare"],["Adam și Eva","Bere Gratis","încet ca un ardelean"]],
    [ ["Cub de gheată","Stridie","Căsătorie"], ["Mircea Eliade","Biserică Maramureșeană","Sfinxul din Giza"],["A da cioara din mână, pe vrabia de pe gard","Bezele","A apăsa pe accelerație"]],
    [ ["Restaurant","Cerb","Hârciog"], ["Proteză","1984","Mihaela Rădulescu"],["Decât o viață de cioară, mai bine o zi de vultur!","Urzeala Tronurilor","Statuia libertății"]],
    [ ["Microscop","Gardian","Portavion"], ["Facebook","Nichita Stănescu","Pirații din caraibe"],["Pugilism","Pat conjugal","Avocatul diavolului"]],
    [ ["Orchestră","Biserică","Colinde de Crăciun"], ["Motor cu aburi","Pastă de dinți","Heliport"],["Ochii care nu se văd, se uită!","Extraterestru","E ceva putred la mijloc!"]],
    [ ["șurubelniță","Ursuleț de pluș","Coțofană"], ["Fermoar","Machiaj","Plasă de țânțari"],["Uscător de păr","Autostrada Soarelui","Pedant"]],
    [ ["Ananas","Ou","Poștaș"], ["Câine poodle","Asterix și Obelix","Stan și Bran"],["A avea limbariță","Regele Mihai","Iute ca săgeata"]],
    [ ["Grătar","Asasin","Viespe"], ["Nadia Comăneci","Amy Winehouse","Muzicuță"],["Poreclă","A pune gaz pe foc","Care-i graba?"]],
    [ ["Stea căzătoare","Chec","Vin spumant"], ["Ion Țiriac","Vânătorii de fantome","Bridget Jones"],["Scrabble","Gumă de mestecat","Quo vadis"]],
    [ ["Miner","Pușcărie","Moară"], ["Tacă-ți fleanca!","Poseidon","Fructele mâniei"],["Aforism","A închina în cinstea cuiva","Floare la ureche!"]],
    [ ["Căpșună","Artificii","Pompier"], ["Ion Iliescu","Dacia Pitești","Trupe SWAT"],["Fidel Castro","A-ți sufleca mânecile","Luna Amară"]],
    [ ["Reclamă","Seră","Păun"], ["Schelet","Trambulină","James Bond"],["Sadam Husein","Sală de judecată","Alternosfera"]],
    [ ["Air bag","Vulpe","Binoclu"], ["Catamaran","Prințesă","Nu te supăra frate"],["Sabie cu două tăișuri","Cluj Napoca","Jim Carrey"]],
    [ ["Clovn","GPS","Cercel"], ["Desene animate","Chitară","Tango"],["Bate pe altul la cap!","A avea noroc în dragoste","Cei 12 apostoli"]],
    [ ["Club de noapte","Broască","Vânător"], ["Buburuză","Stroboscop","Periuță de dinți"],["A butona televizorul","Jocurile foamei","A-ți ține răsuflarea"]],
    [ ["Tigru","Pește","Cozoroc"], ["Sudoku","Plastelină","Michael Jordan"],["Cine râde la urmă, râde mai bine!","Henri Cuandă","Martin Luther King"]],
    [ ["Metrou","Ceas","Vârcolac"], ["Isaac Asimov","Matriusca","Lara Croft"],["Călcâiul lui Ahile","A face pe prostul","A fi cu ochii în patru"]],
    [ ["Computer","SMS","Folie de aluminiu"], ["Singur acasă","Diablo","Maioneză"],["Loterie","Nicolae Iorga","șotron"]],
    [ ["Robot","Stea de mare","Fotbal"], ["Linie de cale ferată","Limbaj braille","Potcoavă"],["A te grăbi ca fata mare la măritat","Rio de Janeiro","Alb ca varul"]],
    [ ["Portofel","Cupru","Diamant"], ["Plajă","Avocat","Prăjitură"],["Când te arzi cu supă, sufli și în iaurt!","Nu e prost degeaba","Cina cea de taină"]],
    [ ["Cremă de plajă","Statuie","Coteț"], ["îmbujorat","Shrek","Libelulă"],["De la pământ la lună","Shrelock Holmes","Iași"]],
    [ ["Pinguin","Librărie","Doctor"], ["Traian Băsescu","îndulcitor","Croissant"],["Klaus Werner Iohannis","A sta ca pe ace","Memorie fotografică"]],
    [ ["Dovleac","Mămăligă","șapcă"], ["Nicolae Ceaușescu","Chelneriță","Mary Poppins"],["Pe de-a moaca","Apă sfințită","Marco Polo"]],
    [ ["Avion supersonic","Omul invizibil","Radar"], ["Loredana Groza","Koala","Praf de pușcă"],["Cerc de prieteni","Banii nu cresc în copaci!","Când o zbura porcul!"]],
    [ ["Papuci","ștergător de parbriz","Titanic"], ["Bowling","înălbitor","Victor Ponta"],["Mihai Viteazul","Bătut în cap","Leșinat"]],
    [ ["Papagal","Paie","Turnul Eiffel"], ["Rebus","Marilyn Manson","Mihai Eminescu"],["Golum","Keira Knightley","Insula Paștelui"]],
    [ ["Dr. House","Povestea jucăriilor","Cireașă"], ["Cupid","Masa tăcerii","Busolă"],["A demisiona","Tom Cruise","Indiscret"]],
    [ ["Parapantă","Suc de fructe","Cârmă"], ["Nădragi","Jurassic Park","Ghilotină"],["Muștar Dijon","A da cu banul","Hermione Granger"]],
    [ ["Lapte","Rinocer","Unicorn"], ["Struț","Sărmă ghimpată","Elena Udrea"],["Drumul spre iad, e pavat cu intenții bune!","π","Înapoi în viitor"]],
    [ ["Pantera Roz","Zaruri","Simpsons"], ["Căsnicie","Samurai","Venus de Milo"],["Tăcerea e de aur!","Colosseumul de la Roma","Războiul din Vietnam"]],
    [ ["Intersecție","Moș Crăciun","Viticultor"], ["Miss România","Revoluția franceză","Valiză"],["Lasă-o mai moale!","Orașul interzis","Decrepitudine"]],
    [ ["Echipament pentru scufundări","Ghete","Ferrari"], ["Chirie","Luceafărul","Scară rulantă"],["A-ți deschide inima","Sibiu","Baseball"]],
    [ ["Ambulanță","Seringă","Pijama"], ["Magnet","Paloș","Tomberon"],["Este ce este","A-ți da cu stângu-dreptul","Alcatraz"]],
    [ ["Ping pong","Mănuși","Perforator"], ["Oedip","Post radio","Cezariană"],["Rupt de oboseală","Natalie Portman","Capela Sistină"]],
    [ ["Telefon mobil","Telescop","Girafă"], ["Hannibal Lecter","Numele trandafirului","Prăjitor de pâine"],["A fost odată ca niciodată ...","Limbă ascuțită!","Audrey Hepburn"]],
    [ ["Pisică neagră","Fulg de nea","Bucătărie"], ["Animal Planet","Terminatorul","Circ"],["Ion Mincu","Cireșarii","Clonare"]],
    [ ["Bancă","Dormitor","Fluier"], ["Arhimede","Vârful Moldoveanu","Filantropica"],["A avea mână liberă","Ștefan cel Mare","Evrica!"]],
    [ ["Vioară","Friptură","Egipt"], ["Vocea României","Flaut","Neveste disperate"],["Mușcă-ți limba!","Sigmund Freud","Ștefan Bănică Jr."]],
    [ ["Ventilator","Cafea","Jucărie"], ["Salată de fructe","Batman","Andrian Năstase"],["Angelina Jolie","Manga","Andreea Marin"]],
    [ ["Dinozaur","Drujbă","Ștrumfii"], ["Vadim Tudor","Coloniștii din Catan","Brașov"],["Brânză de burduf în coajă de brad","Cerere în căsătorie","Analfabet"]],
    [ ["Spanac","Barjă","Moștenire"], ["Dune","Moise","Andreea Esca"],["Revoluția din 1989","ie","Războiul stelelor"]],
    [ ["Harry Potter","lac","Coca-Cola"], ["Carcassonne","Stand by me","Sărmăluțe în foi de viță"],["A fi a cincea roată de la căruță","A baga mâna în foc","Coșmar"]],
    [ ["Pasărea Phoenix","Săritură cu prăjina","Trompetă"], ["Saună","Romeo și Julieta","Turnul din Pisa"],["A te trezi cu fața la pernă","Stilou","La paștele cailor"]],
    [ ["Urs polar","Vrăjitoare","Om de zăpadă"], ["Coloana infinitului","Săpun","Baghetă"],["Lună de miere","A luat-o pe arătură","A fi îndrăgostit lulea"]],
    [ ["Pană","Nucă de cocos","Gară"], ["Parașută","Catapultă","Clește de rufe"],["Calul de dar, nu se caută de dinți!","Coș de cumpărături","Cenzură"]],
    [ ["Puzzle","101 Dalmațieni","Fluture"], ["Wolverine","Dixit","Bărbații în negru (MIB)"],["A-și lua nasul la purtare","A trăi viața la maxim","Bătrân și înțelept"]],
    [ ["Pădurar","țânțar","Cuptor cu microunde"], ["Simona Halep","A fi ușă de biserică","Cuțit de tartinat"],["A fi cu picioarele pe pământ","București","înfometat"]],
    [ ["Eră glaciară","Delfin","Căpiță de fân"], ["Ticket to ride","Tastatură","Bruce Lee"],["Paris","A lăsa gură cască","A începe ceva cu stângul"]],
    [ ["Epoca de gheață","Mirodenii","Tarzan"], ["Pe aripile vântului","Ocean’s eleven","Arhitectură"],["Mahmur","A dormi iepurește","Snoopy"]],
  ];
}

?>
