<?php
class ConceptCardsDE {
  static $cards = [
    [ ["Biene","Flughafen","Adler"], ["2001: Odyssee im Weltraum","Rock me Amadeus","Ein Platz für Tiere"],["Hoffnungsloser Fall","Mord im Orient-Express","Atemlos"]],
    [ ["Airbag","Aladin","Krankenwagen"], ["Luftkissenfahrzeug","Bauer","Magnet"],["Eine verhängnisvolle Affäre","Mimose","Locker vom Hocker"]],
    [ ["Engel","Gießkanne","Kopfschmerztablette"], ["Nick Knatterton","Albus Dumbledore","Alf"],["Auf der Suche nach der verlorenen Zeit","Al Capone","Ali Baba"]],
    [ ["Mörder","Autoradio","Vogel Strauß"], ["Amy Winehouse","Angry Birds","Telefonbuch"],["Öl ins Feuer gießen","American Beauty","Auf die Tube drücken"]],
    [ ["Avatar","Kampfflieger","Badewanne"], ["Aphrodite","Wasserfarben","Spinne"],["Ein Silberstreif am Horizont","Bis zu den Zähnen bewaffnet sein","Die Wogen glätten"]],
    [ ["Wal","Banane","Bank"], ["Armbrust","Regenbogen","Archimedes"],["Bei den Blinden ist der Einäugige ein König","Staubsauger","Einen Freibrief haben"]],
    [ ["Grill","Barbie","Bücherei"], ["Harlekin","Aufzug","Süßstoff"],["Prinzessin auf der Erbse","Zwei linke Hände haben","Hummeln im Hintern haben"]],
    [ ["Schneewittchen und die 7 Zwerge","Weizen","Spongebob Schwammkopf"], ["Asterix und Obelix","Atlantis","Vom Winde verweht"],["Da läuft mir das Wasser im Munde zusammen","Blut und Wasser schwitzen","Einen Kater haben"]],
    [ ["Konservendose","Pfefferspray","Schneemann"], ["Rechtsanwalt","Bagheera","Baguette"],["Jemandem einen Floh ins Ohr setzen","Kopf in den Wolken haben","Ein großes Herz haben"]],
    [ ["Stiefel","Ohrringe","Backstein"], ["Miete","Schaukel","Balu"],["Das Herz in die Hand nehmen","Pi mal Daumen","Ein Seebär"]],
    [ ["Feuerzeug","Christstollen","Holzfäller"], ["Bambi","Comic","Barbar"],["Höhenangst","Jemandem ein Ohr abkauen","Mit beiden Beinen im Leben stehen"]],
    [ ["Büro","Sonnenuhr","Kaffee"], ["Staudamm","Dampfschiff","Batman"],["Mehrere Eisen im Feuer haben","Ein schlechtes Gewissen haben","Einen Frosch im Hals haben"]],
    [ ["Schulheft","Turnhose","Lastwagen"], ["Batterie","Einsiedlerkrebs","Bier"],["Auf der faulen Haut liegen","Einen Filmriss haben","Nicht alle Tassen im Schrank haben"]],
    [ ["Löschflugzeug","Ente","Kanarienvogel"], ["Bilbo Beutlin","Billard","Billy the Kid"],["Einen Bärenhunger haben","Hohes Fieber","Fußbad"]],
    [ ["Kantine","Bus","Kreditkarte"], ["Bob Marley","Briefkasten","Atombombe"],["Bajonett","Höhensonne","Aus etwas Kleinholz machen"]],
    [ ["Helm","Keller","Flugdrachen"], ["Stöpsel","Kessel","Bäcker"],["Man muss das Eisen schmieden, solange es noch heiß ist.","Einen Rekord brechen","Stottern"]],
    [ ["Kirsche","Elektrischer Stuhl","Landhaus"], ["Kompass","Bowling","Bowling for Columbine"],["Ben Hur","Xavier Naidoo","Big Ben"]],
    [ ["Schlafzimmer","Sekt","Hut"], ["Keinohrhasen","Bridget Jones","Brigitte Bardot"],["Billy Jean","Verkehrsfunk","Kriegswunden"]],
    [ ["Jäger","Wasserturm","Burg"], ["Zahnbürste","Bruce Lee","Bunker"],["Den Atem anhalten","Baden gehen","Nichtlustig"]],
    [ ["Fledermaus","Kamin","Hemd"], ["Kakerlake","Kaffeemaschine","Taschenrechner"],["Herzzerreißend","Haarbürste","Alles schwarz sehen"]],
    [ ["Pferd","Kaugummi","Schokolade"], ["Chamäleon","Pudel","Captain Future"],["Gerüchteküche","Ein hartnäckiges Gerücht","Bei Rot fahren"]],
    [ ["Kino","Kürbis","Blinklicht"], ["Captain Haddock","Chipkarte","Postkarte"],["Das ist klar wie Kloßbrühe","Das frisst ja kein Brot","Ins Schwarze treffen"]],
    [ ["Glocke","Clown","Coca Cola"], ["Casino Royale","Sandmännchen","Topf"],["Charakterschwein","Jemandem auf den Wecker gehen","Albtraum"]],
    [ ["Schwein","Kompass","Concorde"], ["Biber","Katapult","Catwoman"],["Viele Wege führen nach Rom","Zensur","Freundeskreis"]],
    [ ["Spielekonsole","Muschel","Brieföffner"], ["Aschenputtel","Hirsch","Kaiserschnitt"],["Teufelskreis","Waffenruhe","Die Sixtinische Kapelle"]],
    [ ["Schweizer Taschenmesser","Krabbe","Sonnencreme"], ["Nina Hagen","Ladegerät","Spülung"],["Die Brüder Grimm","Die Katze lässt das Mausen nicht","Ein gebranntes Kind scheut das Feuer"]],
    [ ["Pfannkuchen","Krokodil","Popel"], ["Weg","Zielscheibe","Fifty Shades of Grey"],["Eine Nadel im Heuhaufen suchen","Til Schweiger","Freier Fall"]],
    [ ["Küche","Delfin","Würfel"], ["Zirkus","Tastatur","Schlüssel"],["Klonen","Jemandem das Maul stopfen","Das Kolosseum in Rom"]],
    [ ["Brettspiel","Verkleidung","Drachenflieger"], ["Strichcode","Yvonne Catterfeld","Strumpfhose"],["Seine Sünden beichten","Pfefferminztee","Jemandem das Wort abschneiden"]],
    [ ["Gebiss","Abschleppwagen","Diamant"], ["Buchhalter","Gurke","Keks"],["Primaballerina","David und Goliath","Die Reise zum Mittelpunkt der Erde"]],
    [ ["Wörterbuch","Dinosaurier","Doktor"], ["Wolfsblut","Crocodile Dundee","Croissant"],["Flaschenöffner","Um die Hand anhalten","Gummi geben"]],
    [ ["Dr. House","Drache","Drohne"], ["Amor","Zahnstocher","Cutter"],["Kündigen","Demokratie","Berge versetzen"]],
    [ ["DVD","Leiter","Sonnenfinsternis"], ["Fahrradfahrer","Cyrano de Bergerac","D’Artagnan"],["In Flammen aufgehen","Detektiv","Perlen vor die Säue"]],
    [ ["Schleuse","Schule","Eichhörnchen"], ["Dalai Lama","Herbert Grönemeyer","David Guetta"],["Sich aufs Ohr hauen","Schlafen wie ein Murmeltier","Dragon Ball Z"]],
    [ ["Kirche","Ägypten","Elefant"], ["Zahnpasta","Desperate Housewives","Final Destination"],["E.T.","Mario Barth","Eminem"]],
    [ ["Elfe","Windkraftwerk","Schwert"], ["Teufel","Diabolo","Kaya Yanar"],["Mit ganzem Herzen dabei sein","Ennio Morricone","Das Kriegsbeil ausgraben"]],
    [ ["Spinat","Schnecke","Schwertfisch"], ["Dr. Jekyll","Dumbo","Dynamit"],["Esmeralda","Kriminelle Energie","Im 7. Himmel sein"]],
    [ ["Scheibenwischer","Seestern","Sternschnuppe"], ["Bleichmittel","Blindenschrift","Edward mit den Scherenhänden"],["Dumm wie Bohnenstroh","Weiß wie Schnee","Warmduscher"]],
    [ ["Feuerlöscher","Briefträger","Fee"], ["Elton John","Empire State Building","Dünger"],["Schneckentempo","Blitzschnell sein","Stocktaub sein"]],
    [ ["Fenster","Ferrari","Flöte"], ["Sicherheitsnadel","Rolltreppe","Fast and Furious"],["Hans Guck-in-die-Luft","Todschick sein","Heureka!"]],
    [ ["Fußball","Heidelberger Schloss","Mikrowelle"], ["Hunger","Hufeisen","Reißverschluss"],["Pressewirbel verursachen","Eine Kurve schneiden","Er hat die Weisheit nicht mit Löffeln gefressen"]],
    [ ["Gabel","Erdbeere","Rakete"], ["Forrest Gump","Helmut Kohl","Pommes Frites"],["Jemandem einen Bären aufbinden","Fidel Castro","Fight Club"]],
    [ ["Gewehr","Handschuhe","Garage"], ["Frettchen","Bahnhof","Der weiße Riese"],["Sich in Nichts auflösen","Rauchen wie ein Schlot","Rudi Carrell"]],
    [ ["Wächter","Kuchen","Genie"], ["Loriot","Ghostbusters","Gladiator"],["Gaston","Gummi","Die Chinesische Mauer"]],
    [ ["Giraffe","Wetterhahn","Eiswürfel"], ["Toaster","Krieg und Frieden","Wilhelm Tell"],["Eine Betschwester","Neandertal","Marshmallow"]],
    [ ["Ruder","GPS","Dachboden"], ["Guillotine","Gitarre","Gustave Eiffel"],["Hermine Granger","Pech im Spiel, Glück in der Liebe","Seepferdchen"]],
    [ ["Frosch","Mobiltelefon","Wespe"], ["Blaulicht","Hannibal Lecter","Mundharmonika"],["Die Tribute von Panem","Spiel mir das Lied vom Tod","Das ist doch kein Beinbruch"]],
    [ ["Lichterkette","Turnhalle","Harpune"], ["Hubschrauberlandeplatz","Schwalbe","Hula-Hoop-Reifen"],["Jägerlatein","Inception","Juri Gagarin"]],
    [ ["Harry Potter","Igel","Erbschaft"], ["Das ist die Berliner Luft","Indiana Jones","Jack Bauer"],["Dafür lege ich meine Hand ins Feuer","Aller guten Dinge sind drei","Ich bin dein Vater, Luke"]],
    [ ["Rassel","Hotel","Iglu"], ["Otto Waalkes","Whirlpool","Johanna von Orleans"],["Jean-Claude Van Damme","Hape Kerkeling","Jean-Paul Belmondo"]],
    [ ["Druckerei","iPad","Iron Man"], ["John Lennon","Die Möwe Jonathan","Judas"],["Günther Jauch","Geld zum Fenster hinauswerfen","Das Handtuch werfen"]],
    [ ["Jeans","Ferien","Ferngläser"], ["Jukebox","Julia Roberts","Jumanji"],["Der werfe den ersten Stein","Rotz und Wasser heulen","Jim Carrey"]],
    [ ["Saft","Känguru","Hupe"], ["Jurassic Park","Karaoke","Kill Bill"],["Kopf oder Zahl","Das kleine Arschloch","Kiwi"]],
    [ ["Eiszeit","Der Unsichtbare","Die Mumie"], ["Kalif Storch","Koalabär","Der Exorzist"],["Der Kreml","Das Geld liegt nicht auf der Straße","Der kleine Nick"]],
    [ ["Der rosarote Panther","Unsere kleine Farm","Der Eiffelturm"], ["Ein Käfig voller Narren","Tinker Bell","Dexter"],["Der Weg zur Hölle ist mit guten Vorsätzen gepflastert","Nightmare Before Christmas","Die Osterinseln"]],
    [ ["Der See","Milch","Marsupilami"], ["Das fliegende Klassenzimmer","Am Anfang war das Feuer","The Green Mile"],["Ein gutes Gewissen ist ein sanftes Ruhekissen","Das 5. Rad am Wagen sein","Heimat"]],
    [ ["Findet Nemo","Der Weihnachtsmann","MP3-Spieler"], ["Planet der Affen","Die Französische Revolution","Glücksrad"],["Das Tüpfelchen auf dem i","Die verbotene Stadt","Der Blitz schlägt nie zweimal am selben Ort ein"]],
    [ ["101 Dalmatiner","Die Schlümpfe","Die Simpsons"], ["Der Hauptmann von Köpenick","Haribo","Die Venus von Milo"],["Der 100jährige Krieg","Vietnam Krieg","Reden ist Silber, Schweigen ist Gold"]],
    [ ["Einhorn","Löwe","Wolf im Schafspelz"], ["Lance Armstrong","Schleuder","Zeichensprache"],["Das Mädchen mit den Schwefelhölzern","Der Stein von Rosetta","Vogel-Strauß-Politik"]],
    [ ["Werwolf","Lupe","Schlitten"], ["Lara Croft","Lassie","Im Rausch der Tiefe"],["Der Turm zu Babel","Laika","John Sinclair"]],
    [ ["Sonnenbrille","Infrarotbrille","Nähmaschine"], ["Das Dschungelbuch","Der Name der Rose","Der kleine Däumling"],["Sich das Maul zerreißen","Perry Rhodan","Gehirnwäsche"]],
    [ ["Zauberer","Altersheim","Lehrer"], ["Der kleine Prinz","Sonderzug nach Pankow","Woyzeck"],["Das fünfte Element","Zwei glorreiche Halunken","Der Club der Toten Dichter"]],
    [ ["Blümchen","Ehe","Gasmaske"], ["Der Herr der Ringe","Die Sphinx","Am Tag als Conny Kramer starb"],["5 Freunde","Sonntagszeitung","Sandmännchen"]],
    [ ["Chef","Die Biene Maja","Mechaniker"], ["Das Geisterschiff","Männer sind Schweine","Yeti"],["Die Muppet Show","Tod auf dem Nil","Die Seufzerbrücke"]],
    [ ["Qualle","Meteorit","U-Bahn"], ["Lego","Kontaktlinsen","Die 7 Samurai"],["Die Aufklärung","Achillesferse","Die Tour de France"]],
    [ ["Mikroskop","Minecraft","Jugendlicher"], ["Theo gegen den Rest der Welt","Der Weiße Hai","Heute-Show"],["In 80 Tagen um die Welt","Schwarzarbeit","Der Eiserne Thron"]],
    [ ["Mode","Monopoly","Berg"], ["Buddenbrooks","Die Vögel","Die Säulen der Erde"],["Super Mario Kart","Die 7 Weltwunder","Die Ritter der Tafelrunde"]],
    [ ["Uhr","Fliege","Mühle"], ["Babuschka-Puppen","Tom Sawyer","Früchte des Zorns"],["Die Götter müssen verrückt sein","Das ist kinderleicht","Gefährliche Liebschaften"]],
    [ ["Moskito","Museum","Schwimmen"], ["Die purpurnen Flüsse","Die Sims","Teenage Mutant Ninja Turtles"],["Weiche Knie bekommen","Max und Moritz","Jim Knopf und die Wilde 13"]],
    [ ["Hundehütte","Nest","Ninja"], ["Libelle","Luc Besson","Lucky Luke"],["Der Schuh des Manitu","Fix und Foxi","Der bewegte Mann"]],
    [ ["Nutella","Ei","Oger"], ["Toilettensitz","McDonald’s","MacGyver"],["Lewis Carroll","Daniela Katzenberger","Aus den Augen, aus dem Sinn"]],
    [ ["Orchester","Computer","Eisbär"], ["Dampfmaschine","Kevin - Allein zu Haus","Manneken Pis"],["Lotterie","Flitterwochen","Madame Tussaud"]],
    [ ["Teddybär","Pac-Man","Stroh"], ["Make-up","Margaret Thatcher","Marilyn Manson"],["Todtraurig sein","Sich die Radieschen von unten ansehen","Marco Polo"]],
    [ ["Panther","Aluminiumfolie","Schmetterling"], ["Mary Poppins","Majonäse","Men in Black"],["Himmel und Hölle","Jung gefreit, nie gereut","Mars Attacks!"]],
    [ ["Regenschirm","Sonnenschirm","Blitzableiter"], ["Mutter Teresa","Michael Jordan","Mikrofon"],["Martin Luther King","Maske","Bettler"]],
    [ ["Parkuhr","Parfüm","Zebrastreifen"], ["Mike Tyson","Anke Engelke","Miss Germany"],["Unterschwellige Botschaften","Wasser predigen, Wein trinken","Butter bei die Fische"]],
    [ ["Fischer","Schaufel","Frachtkahn"], ["Mister Bean","Muhammad Ali","Moses"],["Ins Fettnäpfchen treten","Verblendung","Eine Hausfrau hat das im Gefühl"]],
    [ ["Bohrmaschine","Papagei","Knallfrosch"], ["Herr Kartoffelkopf","Kreuzworträtsel","Pfeffermühle"],["Mein Schatz","Sich bis aufs letzte Hemd ausziehen","Stumm wie ein Fisch"]],
    [ ["Peter Pan","Klavier","Elster"], ["Es fährt ein Zug nach Nirgendwo","Schnurrbart","Fliegengitter"],["Unverfroren sein","Auf der Glückswelle reiten","Auf zwei Hochzeiten tanzen"]],
    [ ["Pilot","Gewürz","Tischtennis"], ["Angela Merkel","Ocean’s Eleven","Ödipus"],["Ein Auge riskieren","Den Wald vor lauter Bäumen nicht sehen","Neil Armstrong"]],
    [ ["Pinguin","Pinocchio","Pirat"], ["Onkel Dagobert","Uhrwerk Orange","Orgel"],["Dem Affen Zucker geben","Ein blaues Auge / Veilchen","Augen wie ein Luchs"]],
    [ ["Schwimmbad","Segelflugzeug","Autokennzeichen"], ["Jerry Cotton","Palme","Pamela Anderson"],["Schattenspiel","Wo gehobelt wird, da fallen Späne","Die Büchse der Pandora"]],
    [ ["Klempner","Feder","Fisch"], ["Toilettenpapier","Fallschirm","Töpfern"],["Der Warenkorb","In den Bart murmeln","Gebrochenes Deutsch sprechen"]],
    [ ["Pokémon","Polizist","Apfel"], ["Schlittschuhe","Knecht Ruprecht","Leuchtturm"],["Den Löffel abgeben","Den Kopf verlieren","Stirb langsam"]],
    [ ["Feuerwehrmann","Hafen","Flugzeugträger"], ["Seehund","Stecknadeln","Fluch der Karibik"],["Wer rastet, der rostet","Einen roten Kopf bekommen","Einen Kopfsprung machen"]],
    [ ["Brieftasche","Blumentopf","Ausschalter"], ["Strand","Bohrinsel","Popcorn"],["Je oller, je doller","Popeye","Einen Toast ausbringen"]],
    [ ["Gefängnis","Brunnen","Schlafanzug"], ["Poseidon","Post-it","Mülleimer"],["Jemanden verschaukeln","Gefängnis von Alcatraz","Am St. Nimmerleinstag"]],
    [ ["Radar","Kühlschrank","Fuchs"], ["Schießpulver","Power Rangers","Prinzessin"],["Rain Man","Rapunzel","Das Feuer entfachen"]],
    [ ["Hai","Restaurant","Nashorn"], ["Prison Break","Prothese","Werbung"],["Resident Evil","Zurück in die Zukunft","Jemandem etwas unter die Nase reiben"]],
    [ ["Gardine","Fluss","Roboter"], ["Quidditch","Heizkörper","Eisenbahnstrecke"],["Kommissar Rex","Rio de Janeiro","Robinson Crusoe"]],
    [ ["Rad","Zauberwürfel","Valentinstag"], ["Ratte","Königin","Robin Hood"],["Das Schweigen brechen","Schilf","Die Muskeln spielen lassen"]],
    [ ["Salat","Tannenbaum","Stabhochsprung"], ["Rocky","Rollschuhe","Romeo und Julia"],["Rumknutschen","Auf ex trinken","Der heilige Petrus"]],
    [ ["Free Willy","Taucheranzug","Skorpion"], ["Cap und Capper – Zwei Freunde auf acht Pfoten","Lippenstift","Rugby"],["Saisonarbeiter","Vom Hölzchen aufs Stöckchen kommen","Zur Sache, Schätzchen"]],
    [ ["Spritze","Schlange","Affe"], ["Laserschwert","Der Heilige Gral","Wildschwein"],["Sich selbst ein Bein stellen","Sich graue Haare wachsen lassen","Jemanden hinters Licht führen"]],
    [ ["Sombrero","Seife","Hexe"], ["Wurst","Sauna","Sonic"],["Arschbombe","Mit dem linken Fuß aufstehen","Ein Schlag ins Wasser"]],
    [ ["Fliegende Untertasse","Maus","U-Boot"], ["Tesafilm","Eimer","Klaus Kinski"],["Sich in Schale schmeißen","Nabelschau betreiben","Sie gleichen sich wie ein Ei dem anderen"]],
    [ ["BH","Statue","Steak"], ["Kellnerin","Shrek","Pfeife"],["Stielaugen machen","Däumchen drehen","Sigmund Freud"]],
    [ ["Stethoskop","Teppich","Tarzan"], ["Silikon","Snowboard","Glocke"],["Der Krug geht so lange zum Brunnen bis er bricht","Six feet under","Skyfall"]],
    [ ["Maulwurf","Stier","Teleshopping"], ["Veronica Ferres","Snoopy","Skelett"],["Spirou","Freiheitsstatue","Die Christusstatue in Rio de Janeiro"]],
    [ ["Sturm","Tennis","Tetris"], ["Raumstation","Stephanie von Monaco","Stonehenge"],["Den Anstandswauwau spielen","Rolf Kauka","Mit Schirm, Charme und Melone"]],
    [ ["Tee","Tiger","Tipi"], ["Füllfederhalter","Sudoku","Sushi"],["Die Truman Show","Siegfried der Drachentöter","Tina Turner"]],
    [ ["Sparschwein","Titanic","Rasenmäher"], ["Bleistiftspitzer","Highheels","Tandem"],["Korkenzieher","Ins Gras beißen","Es schüttet aus Kübeln"]],
    [ ["Sonnenblume","Toy Story","Traktor"], ["Terminator","The Artist","Thermoskanne"],["Top Gun","Um den heißen Brei herumreden","Ganz von vorne anfangen"]],
    [ ["Dreirad","Trompete","Kettensäge"], ["Sister Act","Turm von Pisa","Geisterzug"],["Sich auf die Zunge beißen","Jedem Tierchen sein Pläsierchen","Drogen handeln"]],
    [ ["Gartenschlauch","Nachtclub","Kuh"], ["Trampolin","Transformers","Trivial Pursuit"],["Gerichtshof","Zeit totschlagen","Flotte Biene"]],
    [ ["Vampir","Geier","Fahrrad"], ["Troll","Schwarzes Loch","Tsunami"],["Ein ungedeckter Scheck","Schönheitsfleck","Vorbeugen ist besser als nachsehen"]],
    [ ["Freitag, der 13.","Ventilator","Veranda"], ["Tupperware","Twilight – Bis(s) zum Morgengrauen","Impfstoff"],["Jemandem ein Ohr abkauen","Ein Bild sagt mehr als 1000 Worte","Liebesroman"]],
    [ ["Winzer","Wein","Vitamine"], ["Koffer","Klettverschluss","20.000 Meilen unter dem Meer"],["Ein starke Opposition","Wolf im Schafspelz","V wie Vendetta"]],
    [ ["Vulkan","Joghurt","Jo-Jo"], ["Whisky","Pu der Bär","Wolverine"],["Die Seele dem Teufel verkaufen","Toilettenpümpel","Ein Leben auf der Überholspur"]],
    [ ["Yoda","Zebra","Zorro"], ["Woody Allen","Xylophon","The Legend of Zelda"],["Auch ein blindes Huhn findet mal ein Korn","Dieb","Glucke"]],
  ];
}

?>
