<?php
class ConceptCardsIT {
  static $cards = [
    [ ["Ape","Spezia","Dottore"], ["2001: Odissea nello Spazio","Cameriera","Macinapepe"],["Tempo sprecato","Ammazzare il tempo","Eminem"]],
    [ ["Occhiali da sole","Dinosauro","La Carica dei 101"], ["Fast and Furious","Dr. Jekyll","Forrest Gump"],["E.T. l’Extraterrestre","Vendere l’anima al diavolo","Traffico di droga"]],
    [ ["Tagliaerbe","Trattore","Cubetto di ghiaccio"], ["Velcro","Diga","Arancia Meccanica"],["Paura dell’altezza","Perdere i sensi","Ellekappa"]],
    [ ["Meteorite","Nido","Elfo"], ["Eliporto","Coltello da burro","Affitto"],["Scoperchiare il vaso di Pandora","American Beauty","Tirare le cuoia"]],
    [ ["Camera da letto","Montagna","Pipistrello"], ["Tazzina da caffè","Gladiatore","Queen"],["Adam Sandler","Gli Uomini Preferiscono le Bionde","Walt Whitman"]],
    [ ["Profumo","Flauto","Minatore"], ["Chitarra","Quattro Matrimoni e un Funerale","Codice a barre"],["Dopo sbornia","Bianco come la neve","Tex Avery"]],
    [ ["Orologio da polso","Frumento","Ninja"], ["Stuzzicadenti","Il Gabbiano Jonathan Livingston","Aspartame"],["Fortunato al gioco, sfortunato in amore","Rapunzel - L’Intreccio della Torre","Il Trono di Spade"]],
    [ ["Vasca da bagno","Salvadanaio","Sottomarino"], ["Campana","Salsiccia","La Rivoluzione Francese"],["Criminal Minds","Mars Attacks!","La ciliegina sulla torta"]],
    [ ["Cavallo","Tappeto","Vampiro"], ["Radiatore","Peggy Lee","Sigillo"],["Dieci Piccoli Indiani","Lavaggio del cervello","Colosseo"]],
    [ ["Squalo","Spot pubblicitario","Fragola"], ["The Sims","Post-it","Pirati dei Caraibi"],["Avere la coscienza sporca","Illuminismo","Tallone d’Achille"]],
    [ ["Postino","Monopoli","Unicorno"], ["Margaret Thatcher","Atlantide","Biliardo"],["Marshmallow","Cessare il fuoco","Lanciare la prima pietra"]],
    [ ["Parchimetro","Struzzo","Balena"], ["Snowboard","Catwoman","Contadino"],["Marlon Brando","Seppellire l’ascia di guerra","Prendere in giro"]],
    [ ["Pupazzo di neve","Ufficio","Tarzan"], ["Camaleonte","Baguette","LEGO"],["A ognuno il suo","Avere la vista lunga","Vestirsi a puntino"]],
    [ ["Bugs Bunny","Vitamina","Mulino a vento"], ["Balestra","Friends","Ratto"],["Beppe Severgnini","Armato fino ai denti","Scansafatiche"]],
    [ ["Concorde","Statua","Petardo"], ["Birra","Power Rangers","Lassie"],["Chi si ferma è perduto","Martin Luther King","Avere la coscienza pulita"]],
    [ ["Sombrero","Poliziotto","Stella marina"], ["Organo","Ente Nazionale Protezione Animali","Cerniera lampo"],["Il Signor Bonaventura","Il mio tesoro","Non è la fine del mondo"]],
    [ ["Egitto","Cisterna","GPS"], ["Bersaglio","Zanna Bianca","Spazzolino da denti"],["Le Grotte di Lascaux","Menare il can per l’aia","Avere le mani bucate"]],
    [ ["San Valentino","Mattone","Girasole"], ["Gli Uccelli","Valigia","Thermos"],["Lettino abbronzante","Bello e impossibile","Dare le dimissioni"]],
    [ ["Orso polare","Era Glaciale","Castello"], ["Troll","Billy the Kid","Bussola"],["Cacciavite","Dalla terra alla Luna","Gioco della campana"]],
    [ ["Tè","Stagno","Miniera"], ["Bilbo Baggins","Torre di Pisa","I Pilastri della Terra"],["Avere i piedi per terra","Skyfall","Cercare un ago in un pagliaio"]],
    [ ["Prigione","Ventaglio","DVD"], ["Tostapane","McDonald’s","Enjoy the Silence"],["Marco Polo","Mogli e buoi dei paesi tuoi","La Guerra del Vietnam"]],
    [ ["Zebra","Spada","Triciclo"], ["Charlie’s Angels","Scarafaggio","Ghigliottina"],["Agile come una scimmia","Parlare con il cuore in mano","Censura"]],
    [ ["Peperoncino spray","Guanti","Delfino"], ["Baffi","Fischietto","Castoro"],["Trattenere il respiro","Cavalluccio marino","Chi va piano va sano e va lontano"]],
    [ ["Bip Bip","Pinocchio","MP3 player"], ["Johnny Cash","Popcorn","Spilla"],["Il frutto non cade mai lontano dall’albero","Sandra Mondaini","Gettare le perle ai porci"]],
    [ ["Tromba","Cantina","Motosega"], ["Direttorio","Tsunami","Libellula"],["Sbaciucchiarsi","Rosso come un peperone","Piantare in asso qualcuno"]],
    [ ["Corno","Caffè","Pac-Man"], ["Guglielmo Tell","Baloo","Piume di Struzzo"],["La Guerra dei Cento Anni","Fumare come una ciminiera","Farci il callo"]],
    [ ["Carta stagnola","Drago","Leone"], ["Smart card","Tartarughe Ninja alla Riscossa","Cesareo"],["Big Ben","Essere al settimo cielo","Uno Studio in Rosso"]],
    [ ["Innaffiatoio","Arpione","Coca-Cola"], ["Mosè","Beyoncé","Astro Boy"],["Messaggio subliminale","Perdere la calma","Il Castello Errante di Howl"]],
    [ ["Torre Eiffel","Scimmia","Parasole"], ["Pamela Anderson","Guerra e Pace","Tavoletta del WC"],["Non si può fare una frittata senza rompere le uova","Ventosa","Tirato a lucido"]],
    [ ["Iron Man","I Simpson","Razzo"], ["Pattini a rotelle","Mike Tyson","Bill Clinton"],["Sconsigliato ai deboli di cuore","Nei guai fino al collo","Il Buono, il Brutto e il Cattivo"]],
    [ ["Slitta","Insegnante","Veranda"], ["Michael Jordan","Battello a vapore","David Guetta"],["Fare il terzo incomodo","Davide e Golia","Incanalare la collera"]],
    [ ["L’Uomo Invisibile","X Factor","Succo di frutta"], ["Casseruola","Il Miglio Verde","Pubblicità"],["Mendicante","Turner e il Casinaro","Top Gun"]],
    [ ["Farfalla","Cacciabombardiere","Angelo"], ["Piccole Donne","L’Esorcista","Buco nero"],["Un gioco da ragazzi","Mamma oca","Spostare le montagne"]],
    [ ["SpongeBob","Pianoforte","Tagliacarte"], ["Diavolo","Daino","The Sound of Silence"],["Troppo stanco per ragionare lucidamente","Confessare i propri peccati","Richie Rich"]],
    [ ["Granchio","Biancaneve e i Sette Nani","Genio"], ["Il Nome della Rosa","Stand By Me","Cenerentola"],["Stagionale","Silhouette","The Hunger Games"]],
    [ ["Camion","Orco","Ferrari"], ["Nastro adesivo","Zelda","Bob Marley"],["Balbettare","Investigatore","The Mask"]],
    [ ["Canguro","Vigile del fuoco","Dizionario"], ["Dentifricio","Inghiottire","Sushi"],["Charlie Brown","Conoscere i propri limiti","Domenica del Corriere"]],
    [ ["Coltellino svizzero","Tennis","Canadair"], ["With or Without You","Kill Bill","Collant"],["Sgranare gli occhi","Sordo come una campana","The Truman Show"]],
    [ ["Dolce","Tubo da giardino","Avvoltoio"], ["Austin Powers","Fionda","Cartolina"],["La prudenza non è mai troppa","Il silenzio è d’oro","Piovuto dal cielo"]],
    [ ["Estintore","Serpente","Tuta da sommozzatore"], ["Carta igienica","Silicone","Ron Howard"],["Veloce come il fulmine","Testa o croce","Al Capone"]],
    [ ["Lago","Toro","Diamante"], ["Cinquanta Sfumature di Grigio","Altalena","Imagine"],["Gettare la spugna","Le disgrazie non vengono mai sole","Girarsi i pollici"]],
    [ ["Giorno festivo","Aliante","Babbo Natale"], ["Cartucciera","Amy Winehouse","Paracadute"],["Il Quinto Elemento","Raggomitolato","Strappalacrime"]],
    [ ["Lente d’ingrandimento","Binocolo","Stivali"], ["Luce stroboscopica","Biscotto","Faro"],["Avere un rospo in gola","I tre re magi","We Are the Champions"]],
    [ ["Tergicristallo","Serratura","Accendino"], ["Una Notte da Leoni","Batteria","Contabile"],["Furbo come una volpe","Partire con il botto","Jean-Claude Van Damme"]],
    [ ["Zanzara","Maiale","Spinaci"], ["Lenti a contatto","Final Destination","Palma"],["Un disegno vale mille parole","Fraintendere","Clonazione"]],
    [ ["Aquila","Taglialegna","Siringa"], ["Taron e la Pentola Magica","Zio Paperone","Stonehenge"],["Tanto va la gatta al lardo che ci lascia lo zampino","Lama a doppio taglio","Rompere il silenzio"]],
    [ ["Coccodrillo","Bussola","Garage"], ["Argilla","Motore a vapore","Ragno"],["Incubo","Venirsi incontro","Fame da lupo"]],
    [ ["Cuccia","Nuotare","Volare"], ["Afrodite","Scala mobile","Poseidone"],["Ladro","Rain Man","Pugno di ferro in guanto di velluto"]],
    [ ["Dadi","Casa di riposo","Titanic"], ["Il Signore degli Anelli","Braille","Circo"],["Avere un vuoto di memoria","Chiuso come un’ostrica","Fight Club"]],
    [ ["Cinema","Quaderno","Orsacchiotto"], ["La Sfinge di Giza","Jurassic Park","Tappo"],["È quel che è","Lotteria","Pediluvio"]],
    [ ["Lumaca","Mucca","Campana"], ["Il Ritratto di Dorian Gray","Acquerelli","Elton John"],["Billy Jean","L’Attimo Fuggente","Lasciare qualcuno senza parole"]],
    [ ["Pilota","Yo-yo","Maglietta"], ["Empire State Building","Madre Teresa","Archimede"],["Con la testa fra le nuvole","Con le unghie e con i denti","C’Era una Volta il West"]],
    [ ["Aquilone","Volpe","Tenda indiana"], ["Patatine fritte","Casino Royale","Brigitte Bardot"],["Le sette meraviglie del mondo","A tutta birra","Sentire puzza di bruciato"]],
    [ ["Chiesa","Salto con l’asta","Rinoceronte"], ["Marilyn Manson","Tandem","Julia Roberts"],["Rimboccarsi le maniche","La Città Proibita","Cieco come una talpa"]],
    [ ["Carroattrezzi","Calcio","Computer"], ["Sapone","Trucco","Koala"],["The Big Bang Theory","Il Ponte dei Sospiri","Principe Valiant"]],
    [ ["Guardia","Strega","Pantera"], ["Arlecchino","Calamita","Desperate Housewives"],["I colpi di fionda e i dardi dell’oltraggiosa fortuna","Mantenere la calma","Sentirsi l’ultima ruota del carro"]],
    [ ["Rana","Banca","Tigre"], ["Jack Bauer","Giovanna d’Arco","Neil Armstrong"],["I soldi non crescono sugli alberi","Claudio Sorrentino","Quando gli asini voleranno"]],
    [ ["Canarino","Pinguino","Aspirina"], ["Jon Stewart","Scheletro","Cocomero"],["Richard Hatch","Carestia","Yuri Gagarin"]],
    [ ["Idraulico","Aladdin","Metropolitana"], ["Bowling a Columbine","Bridget Jones","John Lennon"],["Uomo avvisato mezzo salvato","Ma Che Siamo Tutti Matti?","Battere il ferro finché è caldo"]],
    [ ["Zucca","Mago","Presa elettrica"], ["Colazione da Tiffany","Men in Black","Jukebox"],["Tuffarsi","Far parlare di sé","Voci di corridoio"]],
    [ ["Chiatta","Eredità","Zorro"], ["Dumbo","Casper","Ciclista"],["Flettere i muscoli","Sapere cosa aspettarsi","Testa dura"]],
    [ ["I Puffi","Eclisse","Margherita"], ["Batman","Secchio","Alf"],["La stele di Rosetta","Sigmund Freud","Più siamo più ci divertiamo"]],
    [ ["Lupo mannaro","Nightclub","Abete"], ["Bruce Lee","Bowling","Mary Poppins"],["Le Relazioni Pericolose","Chiedere la mano di qualcuno","Passare col rosso"]],
    [ ["Stampante","Ombrello","Cars"], ["Il Libro della Giungla","Wolverine","Vaccino"],["Far saltare il tappo","San Pietro","Cattivik"]],
    [ ["Giraffa","Vogue","Topo"], ["Tacchi a spillo","Lo Squalo","Il Pianeta delle Scimmie"],["Dormire come un bambino","Chupa Chups","Darsi la zappa sui piedi"]],
    [ ["Scoiattolo","Igloo","Medusa"], ["Edward Mani di Forbice","Catapulta","Volare"],["Quattro chiacchiere","George W. Bush","Ennio Morricone"]],
    [ ["Maschera antigas","Frigorifero","Cellulare"], ["La Ruota della Fortuna","Blowing in the Wind","Rossetto"],["Rio de Janeiro","Fidel Castro","Moderare i toni"]],
    [ ["Air bag","Pistola","Avatar"], ["Hula hoop","Crocodile Dundee","Shrek"],["Inception","Buttarsi","C’è qualcosa che non quadra"]],
    [ ["Meridiana","Microscopio","Pokémon"], ["Indiana Jones","Spiaggia","Piattaforma petrolifera"],["Come piselli nei loro baccelli","The Avengers","Disturbare qualcuno"]],
    [ ["Vaso da fiori","Pirata","Pigiama"], ["Fertilizzante","Tintin","Chiave"],["Cerchia di amici","Il Sole Sorgerà Ancora","Uscire dal seminato"]],
    [ ["Scorpione","Fata","Cannuccia"], ["Dinamite","Trilli","Sentiero"],["Nascondere la testa sotto la sabbia","Jim Carrey","Braccio di Ferro"]],
    [ ["Comignolo","Pappagallo","Ginnasio"], ["Yeti","Allen Ginsberg","Sacro Graal"],["La Torre di Babele","Sciacquarsi la bocca","Autoreferenziale"]],
    [ ["Portafoglio","Meccanico","Pugile"], ["Trampolino","Bagheera","Sciacquone"],["Lewis Caroll","Tina Turner","Romanzo rosa"]],
    [ ["Nutella","Barbie","Carta di credito"], ["Albus Silente","Dalai Lama","Ferro di cavallo"],["Alla Ricerca del Tempo Perduto","Avere la testa tra le nuvole","Mordersi la lingua"]],
    [ ["Free Willy","Elefante","Mulino"], ["Rugby","Terminator","Transformers"],["Svanire nel nulla","Stare sulle spine","Ben-Hur"]],
    [ ["Tempesta","Insalata","Cucina"], ["Ventimila Leghe Sotto i Mari","D’Artagnan","Capitan Harlock"],["Spazzola","Orgoglio e Pregiudizio","Justin Bieber"]],
    [ ["Macchina da cucire","Luci di natale","Badile"], ["Robin Hood","Temperamatite","Formaggino Mio"],["Ferite di guerra","Italiano stentato","Occhio di falco"]],
    [ ["Pesce spada","Forchetta","La Casa nella Prateria"], ["Whisky","Jumanji","Trivial pursuit"],["American History X","Uomini Che Odiano le Donne","A costo zero"]],
    [ ["Reggiseno","Yogurt","Sonaglio"], ["Avvocato","Linguaggio dei segni","Sbiancante"],["Alcatraz","Snoopy","Robinson Crusoe"]],
    [ ["Harry Potter","Pozzo","Muco"], ["Armonica a bocca","Ascensore","Campo da golf"],["La strada per l’inferno è lastricata di buone intenzioni","Un groppo alla gola","Striscia la Notizia"]],
    [ ["Dentiera","Telescopio a infrarossi","La Mummia"], ["Quidditch","Lucky Luke","Simmenthal"],["Tentare la sorte","Per il rotto della cuffia","Svampito"]],
    [ ["Stetoscopio","Pagliaccio","Vignaiolo"], ["Nave Fantasma","Diablo","Mister Bean"],["Lingua biforcuta","Eureka!","Attizzare"]],
    [ ["Portaerei","Vulcano","Timone"], ["Casella postale","Kate Middleton","L’Uomo Nero"],["Vivere al massimo","Corte","Concimare la terra"]],
    [ ["Ciliegia","Porcospino","Venerdì 13"], ["Bambi","Johnny Carson","Ghostbusters"],["Neo","Democrazia","Strapparsi i capelli"]],
    [ ["Bistecca","Tetris","Matrimonio"], ["Romeo e Giulietta","Hannibal Lecter","Lincoln Memorial"],["Hermione Granger","Jeans scoloriti","Giù per una brutta china"]],
    [ ["Protezione solare","Porto","Cubo di Rubik"], ["Giustizia Finale","Silvio Muccino","Bomba atomica"],["Mi fischiano le orecchie","Muppet Show","Tuffarsi a capofitto"]],
    [ ["Banana","Pesce","Forno a microonde"], ["Rocky","Furetto","Protesi"],["Mi dai sui nervi","Manie di grandezza","Six Feet Under"]],
    [ ["Sedia elettrica","Piscina","La Pantera Rosa"], ["Frank Lloyd Wright","Mio Minipony","Polvere da sparo"],["Calvin and Hobbes","Daytona 500","Cappella Sistina"]],
    [ ["Fiume","Frittella","Yoda"], ["Janeane Garofalo","Ocean’s Eleven","Stazione"],["Isola di Pasqua","50 Volte il Primo Bacio","Mettere la mano sul fuoco"]],
    [ ["Attico","Chewing gum","Piuma"], ["Recinto","Paguro","Cinghiale"],["Assegno scaduto","Statua del Cristo Redentore","Statua della Libertà"]],
    [ ["Orchestra","Lupo","Peter Pan"], ["Maggie Gyllenhaal","Lara Croft","Asterix e Obelix"],["Bofonchiare","Beverly Hills 90210","Cremlino"]],
    [ ["Vino","Ristorante","iPad"], ["Calcolatrice","Sudoku","Tastiera"],["Ritorno al Futuro","Gettare benzina sul fuoco","Parlantina sciolta"]],
    [ ["Assassino","Trapano","Segnale di svolta"], ["Arcobaleno","Salvafreschezza","Hovercraft"],["Stabilire un nuovo record","Carrello della spesa","La Piccola Fiammiferaia"]],
    [ ["Aeroporto","Ceppo di natale","Vespa"], ["Jacuzzi","Cestino dei rifiuti","Linea ferroviaria"],["Madame Tussaud","Lupo solitario","Baionetta"]],
    [ ["Scuola","Anemometro","Baita"], ["Cyrano de Bergerac","Giuda","Edipo"],["Il fumine non cade mai due volte nello stesso punto","Sandman","Ricominciare da zero"]],
    [ ["Attraversamento pedonale","Scala a pioli","Papero"], ["La Maledizione del Forziere Fantasma","Spada laser","Microfono"],["Dragonball Z","Il Cavaliere Oscuro","Sheldon Cooper"]],
    [ ["Hotel","Cioccolato","Cappello"], ["Angry Birds","Treno fantasma","Principessa"],["Ravvivare la fiamma","Andare su tutte le furie","Proporre un brindisi"]],
    [ ["Latte","Ruota","Bicicletta"], ["Mamma Ho Perso l’Aereo","Prison Break","Taylor Swift"],["Dormire con un occhio aperto","Die Hard","Occhio nero"]],
    [ ["Cacciatore","Console per videogiochi","Uovo"], ["Karaoke","Fumetto","Red e Toby"],["Rispettare la coda","Luke, io sono tuo padre","Più vecchio e più saggio"]],
    [ ["Alla Ricerca di Nemo","Tennis da tavolo","Finestra"], ["Sister Act","MacGyver","Il Rosso e il Nero"],["Scendere dal letto col piede sbagliato","Lento come una lumaca","Costruire un impero"]],
    [ ["Drone","Barbecue","Autoradio"], ["Il Piccolo Principe","Cornetto","Lance Armstrong"],["Lontano dagli occhi, lontano dal cuore","Luna di miele","Mani sudate"]],
    [ ["Sonic","Aliante","Ambulanza"], ["Borat","Maionese","Sauna"],["Non tutti i mali vengono per nuocere","Ali Baba","Giunchi"]],
    [ ["Travestimento","Mela","Talpa"], ["Coltello a serramanico","Spilla da balia","Winnie Pooh"],["Il Giro del Mondo in 80 Giorni","I Cavalieri dello Zodiaco","The Nightmare Before Christmas"]],
    [ ["Defibrillatore","Orecchino","Mensa"], ["La Vita è Bella","Cupido","Via col Vento"],["Laika","Caduta libera","V per Vendetta"]],
    [ ["Jeans","Stella cadente","Museo"], ["Miss America","Venere di Milo","Pattini da ghiaccio"],["Steve Martin","Monte Rushmore","Prima ballerina"]],
    [ ["Targa automobilistica","Champagne","Toy Story"], ["Parole crociate","Woody Allen","Foglie d’Erba"],["Kiwi","Pioggia a catinelle","Sudori freddi"]],
    [ ["Masterchef","Gazza","Tende"], ["Cucciolo","Borsa dell’acqua calda","Stazione spaziale"],["Aspirapolvere","Avere carta bianca","Apribottiglie"]],
    [ ["Dr. House","Elmo","Conchiglia"], ["Twilight","Furore","Dexter"],["Senza fiato","Girare il coltello nella piaga","Resident Evil"]],
    [ ["Disco volante","Radar","Robot"], ["Mohammed Ali","Zanzariera","Panettiere"],["Interrompere qualcuno","Rimuginare","Circolo vizioso"]],
    [ ["Pescatore","Parafulmine","Biblioteca"], ["Xilofono","I Sette Samurai","Pollicino"],["Esmeralda","Ci scommetto la testa","Febbre da cavallo"]],
  ];
}

?>
