<?php
class ConceptCardsNL {
  static $cards = [
    [ ["Kers","Barbie","Polsstokspringen"], ["Prison Break","Tandenborstel","Trampoline"],["Een ijzeren hand in een fluwelen handschoen","De eeuw van de verlichting","De 100-jarige oorlog"]],
    [ ["Haai","Bibliotheek","Panter"], ["De Heilige Graal","Batterij","Muggenhor"],["Veel inkt doen vloeien","The Transporter","Het zandmannetje"]],
    [ ["Harpoen","Takelwagen","Maya de bij"], ["De Sfinx","Orgel","Moeder Teresa"],["Laika","Vliegensvlug vertrekken","Dead Poets Society"]],
    [ ["Graan","Pokémon","Conservenblik"], ["The Artist","Zwaluw","Lance Armstrong"],["De tijd doden","Once upon a time in the West","Oorlogswond"]],
    [ ["Egypte","Roer","Kikker"], ["Mike Tyson","Guus Meeuwis","De Avonden"],["Nadenken voor je spreekt","De eerste steen gooien","Oorlogswinter"]],
    [ ["Pinguïn","Slak","Harry Potter"], ["De Kleine Prins","Plakband","Suske & Wiske"],["Jean-Claude Van Damme","Smelten als sneeuw voor de zon","Water bij de wijn doen"]],
    [ ["Drone","Put","Spaarpot"], ["Frank en Frey","Koffer","Roltrap"],["Batman","Een blauw oog","Democratie"]],
    [ ["Tetris","Heks","Aardbei"], ["Waterspoeling","Parachute","Dalai Lama"],["Al Capone","Tintelende benen hebben","David Letterman"]],
    [ ["iPad","Krab","Iron Man"], ["Helikopterplatform","Fluitje","Rocky"],["Het Colosseum van Rome","Struisvogelpolitiek","Eminem"]],
    [ ["Vitamine","Mol","Vliegende schotel"], ["Casper","De Vliegende Hollander","Regenboog"],["Millennium","Door een rood licht rijden","De stilte breken"]],
    [ ["Slang","Briefopener","Kauwgom"], ["Julia Roberts","Lucky Luke","Jukebox"],["Spreken is zilver, zwijgen is goud","Zonnebank","Zout in de wond wrijven"]],
    [ ["Spelconsole","Keuken","Meer"], ["Karaoke","Schaats","Brigitte Bardot"],["Charles Baudelaire","Zeemansbenen hebben","Op twee oren slapen"]],
    [ ["Café","Monopoly","Schop"], ["The Blue Lagoon","Barcode","Everzwijn"],["Met zijn hoofd in de wolken leven","“I am your father” (filmquote)","Lepeltje lepeltje slapen"]],
    [ ["Kerstverlichting","Kelder","Zolder"], ["Laserzwaard","Woody Allen","Bakker"],["Voor iedereen klaar staan","Kuifje","De Toren van Babel"]],
    [ ["Tennis","Hotel","Badkuip"], ["Poedel","Prinses","Bridget Jones"],["Het gezinsbudget","Back to the Future","Vriendenkring"]],
    [ ["Bussen","Houthakker","De Roze Panter"], ["Assepoester","Stuwdam","Sudoku"],["Barack Obama","Beastie Boys","Ramptoerist"]],
    [ ["Reus","Diamant","Zwembad"], ["MacGyver","Bever","Reclame"],["Mars Attacks!","Rain Man","De strijdbijl begraven"]],
    [ ["Deltavlieger","Museum","Zwaard"], ["The Name of the Rose","Croissant","Klittenband"],["De tijd zal het leren","Achillespees","Een gladde tong hebben"]],
    [ ["Blusapparaat","IJsblokje","Tuinslang"], ["Botermesje","Hoefijzer","Doel"],["Over een andere boeg gooien","Tussen zes planken liggen","Het Kremlin"]],
    [ ["Zebrapad","Schorpioen","Wesp"], ["Jason Bourne","Edward Scissorhands","“Het is een nacht” (lied)"],["Zeepaardje","Het meisje met de zwavelstokjes","Met de duimen draaien"]],
    [ ["Bewaker","Metro","Jeans"], ["Samson","Brievenbus","Kathedraal"],["Fight Club","De 7 wereldwonderen","Zo onschuldig zijn als een lammetje"]],
    [ ["Visser","Elf","Parfum"], ["Het Rad van Fortuin","De 7 Samoerai","Hoelahoep"],["Hoogtevrees","Een schorre stem hebben","V for Vendetta"]],
    [ ["Zonnebloem","De Simpsons","Vleermuis"], ["Alf","Jacuzzi","Amy Winehouse"],["Een kater hebben","Spartacus","Na regen komt zonneschijn"]],
    [ ["Boormachine","Onweer","Dolfijn"], ["Josje Huisman","Zelda","The Nanny"],["Het hinkelspel","Bedelaarster","Bergen verzetten"]],
    [ ["GPS","Chocolade","Luchthaven"], ["Power Rangers","Men in Black","Atoombom"],["Sterdanseres","Hongersnood","Eureka!"]],
    [ ["Schrift","De onzichtbare man","Berg"], ["Tandpasta","Stoommachine","Kameleon"],["Iets op je sloffen kunnen","Parels voor de zwijnen","Een Kletskous"]],
    [ ["Verrekijker","Windmolen","Tipi"], ["Mozes","Crocodile Dundee","Koala"],["Zo dom zijn als het achtereind van een varken","De vlam weer doen oplaaien","Zijn zonden opbiechten"]],
    [ ["Kantine","MP3-speler","De IJstijd"], ["Radiator","Aquarel","Smeerkaas"],["2 Unlimited","Sixtijnse Kapel","Ergens omheen draaien"]],
    [ ["Muis","Blusvliegtuig","Handschoenen"], ["Fret","Margaret Thatcher","De Chinese muur"],["Een gewaarschuwd man telt voor twee","Jim Carrey","Navelstaren"]],
    [ ["Haven","Molen","Garage"], ["Hannibal Lecter","Klei","Desperate Housewives"],["Als twee druppels water op elkaar lijken","The Mask","De sprong wagen"]],
    [ ["Spuit","Weerwolf","Elektrische stoel"], ["Ciske de Rat","Mohammed Ali","Zwart gat"],["Er de buik van vol hebben","Criminal Minds","Een boom van een kerel"]],
    [ ["Zorro","Maaimachine","De Kerstman"], ["Koningin Maxima","Robin Hood","Fifty Shades of Grey"],["Grey’s Anatomy","Het 5de wiel aan de wagen","In de 7de hemel zijn"]],
    [ ["Teleshoppen","Ruitenwisser","Genie"], ["Ritssluiting","Mr. Bean","Sauna"],["Billy Jean","Met de deur in huis vallen","Ali Baba"]],
    [ ["Politieman","Erfenis","Zwaardvis"], ["Broodrooster","Komkommer","Libelle"],["Detective","Madame Tussaud","Een blackout hebben"]],
    [ ["Vruchtensap","De dageraad","Vlinder"], ["Schommel","Sister Act","Stokbrood"],["Geluk in het spel, ongeluk in de liefde","Liam Neeson","Helemaal in de war zijn"]],
    [ ["Egel","Draak","Zonnebril"], ["Manneken Pis","Stef Bos","Dynamiet"],["Game of Thrones","Dweilen met de kraan open","Nachtmerrie"]],
    [ ["Sonic","Postbode","Helm"], ["Robbedoes","Miss Nederland","Xylofoon"],["Zwemmen in het geluk","Dief","Kopje onder gaan"]],
    [ ["Vos","Duikpak","Mijnwerker"], ["Microfoon","Asterix en Obelix","Het platteland"],["Klamme handjes","Martin Luther King","De Grotten van Valkenburg"]],
    [ ["Nest","Paraplu","Gasmasker"], ["Olieboorplatform","WC-bril","The Dark Knight"],["Kurkentrekker","Hoge koorts hebben","Kop of munt gooien"]],
    [ ["Venster","Little House on the Prairie","Standbeeld"], ["Jeanne d’Arc","Joey Tribbiani","Lassie"],["Tongzoenen","Honger als een paard hebben","De steen van Rosetta"]],
    [ ["De Smurfen","Tractor","School"], ["Kill Bill","Oedipus","Dumbo"],["Liefde maakt blind","Stotteren","Vrijheidsbeeld"]],
    [ ["Ekster","Mug","Tapijt"], ["Kookpan","Zwarte Piet","Professor Barabas"],["Het standbeeld van Christus de Verlosser","Geld groeit niet aan bomen","Philippe Geubels"]],
    [ ["Giraffe","Free Willy","Koe"], ["Koffiekan","Transformers","De Yeti"],["Er voor spek en bonen bijzitten","De stier bij de horens vatten","Een toast uitbrengen"]],
    [ ["Sluis","Vampier","Zwemmen"], ["Sushi","Mest","Bunker"],["Van de hak op de tak springen","Hevig verzet","The Truman Show"]],
    [ ["Aluminiumfolie","Dokter","Nummerplaat"], ["Prothese","A Clockwork Orange","The X-Files"],["Hoge bomen vangen veel wind","Hersenspoeling","Uit het oog, uit het hart"]],
    [ ["Rivier","Aspirine","Feestdag"], ["Biljart","Psycho","The Fast and The Furious"],["Toiletontstopper","Met Sint-Juttemis","Vrije val"]],
    [ ["Pannenkoeken","Rubik’s kubus","Zonnebrandcrème"], ["Duivel","In de Gloria","Zwaailicht"],["The Hunger Games","Top Gun","Zwemwater binnen krijgen"]],
    [ ["Woordenboek","Kwal","Barbecue"], ["The Exorcist","Ilse de Lange","Guillotine"],["Zwartboek","Klonen","Halloween"]],
    [ ["Microscoop","Duikboot","Hoed"], ["Vuurtoren","Siliconen","Atlantis"],["Een keizerrijk bouwen","Drugshandel","De Verboden Stad"]],
    [ ["Mode","Zeester","Portefeuille"], ["Pepermolen","Teenage Mutant Ninja Turtles","Snowboard"],["Censuur","Kippenvel","Popeye"]],
    [ ["Aladin","Pinokkio","Zebra"], ["Twilight","Strand","Mayonaise"],["De Brug der Zuchten","The Good, the Bad and the Ugly","De vuurproef doorstaan"]],
    [ ["Wijn","Raket","Fluit"], ["Spin","Circus","Oplader"],["Een beeld zegt meer dan duizend woorden","Lonely Planet","“My Precious” (filmquote)"]],
    [ ["Vingerhoed","Driewieler","Vermomming"], ["Advocaat","Gladiator","Mary Poppins"],["De bliksem slaat nooit twee keer op dezelfde plaats in","Het hart breken","Stranger Things"]],
    [ ["Pompoen","Vrijdag de 13de","Magnetron"], ["Wasknijper","Snor","Jack Bauer"],["Fidel Castro","Om iemands hand vragen","De Deltawerken"]],
    [ ["Bioscoop","Margriet","Fiets"], ["Skelet","Dr Jekyll","Kruiswoordraadsel"],["Robinson Crusoe","Skyfall","De doos van Pandora openen"]],
    [ ["Schuit","Schelp","Papegaai"], ["March of the Penguins","Captain America","Cookies"],["Commissaris Rex","Over zijn toeren zijn","Chinese Schimmen"]],
    [ ["Windwijzer","Airbag","Teddybeer"], ["Warme kruik","Panty","Lippenstift"],["Rio de Janeiro","Kwezel","Van de aarde naar de maan"]],
    [ ["Knipperlicht","Spongebob Squarepants","Parkeermeter"], ["Winnie de Poeh","Gone with the Wind","Zeep"],["Men kan geen omelet maken zonder eieren te breken","Valse verwijten treffen nooit doel","Tussen twee vuren zitten"]],
    [ ["Titanic","Eend","Wolf"], ["Post-it","Romeo en Julia","Paard van Troje"],["Zijn woede in bedwang houden","Geruchten uit de wandelgangen","Geld over de balk smijten"]],
    [ ["Bliksemafleider","Beha","Dr House"], ["Spoorwegrails","Bier","Mondharmonica"],["Tuitende oren hebben","Ben-Hur","Roken als een schoorsteen"]],
    [ ["Yoda","Pacman","Minecraft"], ["The Walking Dead","Bel","François Mitterrand"],["Seizoensarbeider","Geruchten die de ronde doen","Met het verkeerde been uit bed stappen"]],
    [ ["Salade","Fee","Yoghurt"], ["Tandenstoker","The Bold & The Beautiful","Katapult"],["Debat aanwakkeren","Big Ben","Onderbreken"]],
    [ ["Thee","Vlieger","Sneeuwwitje en de zeven dwergen"], ["Rekenmachine","Japie Krekel","WC-papier"],["Bij de buren is het gras altijd groener","Zeer handig zijn","Met de ogen rollen"]],
    [ ["Bureau","Geweer","Restaurant"], ["Chipkaart","Vaccin","New Kids"],["Een rollende steen vergaart geen mos","E.T. the Extra-Terrestrial","Tante Sidonia"]],
    [ ["Dinosaurus","Banaan","Eendracht"], ["Magneet","Bleekwater","2001: A Space Odyssey"],["The Avengers","De ogen uitkijken","Kurt Cobain"]],
    [ ["Gymzaal","Melk","Brandweerman"], ["The Green Mile","De Drie Musketiers","Archimedes"],["De Drie Koningen","Cirkelredenering","Paaseiland"]],
    [ ["Avatar","DVD","Clown"], ["Billy the Kid","Scream","Keizersnede"],["Zijn allerbeste kleren aantrekken","Schaamrood op de kaken","Sneller dan de bliksem zijn"]],
    [ ["Gieter","Aap","Kamer"], ["Ocean’s Eleven","Veiligheidsspeld","Penoza"],["De scherpe hoeken afronden","Voetbad","In de put zitten"]],
    [ ["Ladder","Trompet","Appel"], ["Kakkerlak","Armand","Bob Marley"],["Zo klaar als een klontje","Sabreren","Cruella De Vil"]],
    [ ["Autoradio","Struisvogel","Kerstboom"], ["Cupido","Sandra Bullock","Diablo"],["Courteney Cox","Weten waaraan zich te houden","Zijn hart uitstorten"]],
    [ ["Biefstuk","Champagne","Stethoscoop"], ["Brailleschrift","Rugby","Palmboom"],["Ontslag nemen","Riet","Niet op komen dagen"]],
    [ ["Monteur","Nutella","Tijger"], ["Vulpen","Gitaar","De Hulk"],["Een ezel stoot zich geen twee keer aan dezelfde steen","Kiwi","David tegen Goliath"]],
    [ ["Kanarie","Stopcontact","Baksteen"], ["Michael Jordan","Toetsenbord","Terminator"],["The Fantastic Four","Overgevoelig zijn","Met beide voeten op de grond blijven"]],
    [ ["Paard","Watertoren","Jager"], ["Judas","Ruimtestation","Casino Royale"],["De weg naar de hel is geplaveid met goede voornemens","Drop","The Godfather"]],
    [ ["Mobiele telefoon","Kunstgebit","Vlieg"], ["Pride and Prejudice","Planet of the Apes","Beyoncé"],["Afstanden kunnen inschatten","De Rode Ridder","Een moedervlek"]],
    [ ["Computer","Spar","Spinazie"], ["David Guetta","Koningin","Popcorn"],["Zich in het ootje laten nemen","Zijn adem inhouden","Nog half slapen"]],
    [ ["IJsbeer","Engel","Wiel"], ["Aphrodite","Stoomboot","Spooktrein"],["Over koetjes en kalfjes praten","Iemand de pas afsnijden","De kers op de taart"]],
    [ ["Radar","Jojo","Ventilator"], ["Angry Birds","Poseidon","Boekhouder"],["Rechtbank","Onbeperkte volmacht hebben","Hans Teeuwen"]],
    [ ["Orkest","Walvis","Voetzoeker"], ["Jurassic Park","Wolverine","Kruisboog"],["Inception","De Vietnam oorlog","Woezel & Pip"]],
    [ ["Donald Duck","Tarzan","Kerk"], ["Buskruit","Vuilnisbak","Bruce Lee"],["Bajonet","Marco Polo","Subliminale boodschap"]],
    [ ["Piano","Vallende ster","Kangoeroe"], ["Theo Maassen","De Sims","Shrek"],["Hoe meer gekken, hoe meer vreugde","The X-Men","Een naald in een hooiberg zoeken"]],
    [ ["Ninja","Voetbal","Loep"], ["Indiana Jones","De Venus van Milo","Oorlog en Vrede"],["Snoopy","Zijn ziel aan de duivel verkopen","Vol gas geven"]],
    [ ["Gebak","Naaimachine","Leeuw"], ["Briefkaart","Twintigduizend mijlen onder zee","Empire State Building"],["Er schuilt een addertje onder het gras","Een goed begin is het halve werk","Een record breken"]],
    [ ["Pyjama","De 101 Dalmatiërs","Krokodil"], ["Gustave Eiffel","Kapitein Haddock","Home Alone"],["In het land der blinden is éénoog koning","Stofzuiger","Onbesuisd zijn"]],
    [ ["Bij","Ambulance","Zwitsers mes"], ["Huur","Rat","Thermosfles"],["Er als de kippen bij zijn","Tina Turner","De loterij"]],
    [ ["Ei","Veer","Koelkast"], ["Harlekijn","Stripverhaal","Weg"],["Het ijzer smeden zolang het heet is","Doktersroman","Tot de tanden gewapend"]],
    [ ["Bloempot","Slee","Vulkaan"], ["Trivial Pursuit","Hovercraft","Pinguins van Madagascar"],["Rapunzel","Zijn koelbloedigheid verliezen","Dat brengt leven in de brouwerij"]],
    [ ["Sombrero","Eenhoorn","Jachtvliegtuig"], ["Dromen zijn bedrog","Jumanji","Bumba"],["Escape from Alcatraz","Hermelien Griffel","Het zout in de pap niet waard zijn"]],
    [ ["Zonnewijzer","Snottebel","Gevangenis"], ["Pamela Anderson","Zeehond","De Franse Revolutie"],["Blind als een mol","Stevie Wonder","De weg kwijt zijn"]],
    [ ["Eekhoorn","Vliegdekschip","Robot"], ["Reservoir Dogs","Lift","Sleutel"],["The Fifth Element","Het bewustzijn verliezen","Zich van de domme houden"]],
    [ ["Meteoriet","Schoorsteen","Nemo"], ["Bilbo Baggins","Ghostbusters","Bambi"],["De laatste loodjes wegen het zwaarst","De Muppet Show","Een vreselijk karakter hebben"]],
    [ ["Stier","Moordenaar","Piloot"], ["Make-up","Whisky","The Flintstones"],["Watertanden","Arendsoog","Een ongedekte cheque"]],
    [ ["Stro","Coca-Cola","Mummie"], ["Fietser","Tupperware","John Lennon"],["De kruik gaat zolang te water tot ze barst","Harry Mulisch","Elkaar in de haren vliegen"]],
    [ ["Huis","Sneeuwpop","Chef"], ["Trol","Gebarentaal","Tinker Bell"],["Het Atomium","Resident Evil","A Song of Ice and Fire"]],
    [ ["Peter Pan","Aansteker","Vrachtwagen"], ["Heremietkreeft","Stop","Elton John"],["Nicolas Sarkozy","De borst nat maken","Zo dom als een gans zijn"]],
    [ ["Neushoorn","Tovenaar","Parasol"], ["Lara Croft","Final Destination","Neil Armstrong"],["Iemand de mond snoeren","Karakter","Passievrucht"]],
    [ ["Sint-Valentijn","Wijnmaker","Arend"], ["Worst","Superman","Rolschaatsen"],["The Matrix","Robin Williams","Zijn handen vol hebben"]],
    [ ["Pingpong","Loodgieter","Vis"], ["Marilyn Manson","Filmtechnicus","Loft"],["De reis om de wereld in 80 dagen","De bladzijde omdraaien","The Nightmare Before Christmas"]],
    [ ["Kompas","Creditcard","Vork"], ["Klein Duimpje","The Lord of the Rings","Zoetje"],["Als bijen naar de honing","Zo traag als een slak zijn","Die Hard"]],
    [ ["Gordijnen","Varken","Toy Story"], ["Contactlenzen","Zwerkbal","Pirates of the Caribbean"],["Joeri Gagarin","Een slecht geweten hebben","Zwartwerken"]],
    [ ["Olifant","Traangasgranaat","Piraat"], ["Jaws","Stonehenge","K3"],["Haarborstel","De ware aard komt altijd boven","Matroesjka’s"]],
    [ ["Rammelaar","Veranda","Klok"], ["Puntenslijper","Jaarboek","Hert"],["Ik steek er mijn hand voor in het vuur","Grijs haar krijgen","Gum"]],
    [ ["Expeditie Robinson","De Eiffeltoren","Nachtclub"], ["Casablanca","Emmer","Toren van Pisa"],["De tak afzagen waar men op zit","De handdoek in de ring gooien","Sigmund Freud"]],
    [ ["Burcht","Onderbroek","Bejaardentehuis"], ["Landbouwer","Naaldhak","Friet"],["Mompelen","Ieder zijn eigen smaak","De Ronde van Frankrijk"]],
    [ ["Kettingzaag","Chalet","Infrarood bril"], ["The Birds","Mc Donald’s","Tsunami"],["Doodsangsten uitstaan","Sint-Pietersbasiliek","Marco Borsato"]],
    [ ["Iglo","Spaanse peper","Laarzen"], ["Star Wars","Artsen Zonder Grenzen","The Jungle Book"],["Tim Burton","Spekjes","Flesopener"]],
    [ ["Horloge","Drukkerij","Zweefvliegtuig"], ["Serveerster","James Bond","Luc Besson"],["Als een lopend vuurtje","Een ongeluk begaan","Zo doof als een kwartel zijn"]],
    [ ["Oorring","Ferrari","Defibrillator"], ["Luke Skywalker","Forrest Gump","Lego"],["Bij de pinken zijn","Stan Lee","Een brok in de keel krijgen"]],
    [ ["Gier","Huwelijk","Onderwijzer"], ["Tandem","Station","Navigatiesysteem"],["De zondagskrant","Brandschoon zijn","American Beauty"]],
    [ ["Bank","Hemd","Eclips"], ["Bowlen","Wilhelm Tell","Boogschutter"],["Het regent pijpestelen","Cars","Dat is niet duur"]],
  ];

}

?>
