<?php
class ConceptCardsDK {
  static $cards = [
    [ ["Hjul","Swimming pool","Kænguru"], ["Rotte","Lykkehjulet","Karaoke"],["Robinson Crusoe","Storhedsvanvid","Falkeblik"]],
    [ ["Lynafleder","Fredag den 13.","MP3-afspiller"], ["Mikrofon","Tupperware","Austin Powers"],["Maske","Tale ørerne af folk","Garfield"]],
    [ ["Finding Nemo","Hjelm","Vin"], ["Apernes planet","Prop","Velcro"],["Danser som en sommerfugl, stikker som en bi","Glasuren på lagkagen","Smed, mens jernet er varmt"]],
    [ ["Mursten","Schweizerkniv","Ordbog"], ["Baloo","Beyoncé","Ulvehunden"],["Søstærk","Walt Whitman","Oplukker"]],
    [ ["Badekar","Notesbog","Stetoskop"], ["Edderkop","Batteri","Silikone"],["Mødes på halvvejen","Løfter aldrig en lillefinger","Død og begravet"]],
    [ ["Traktor","Skal","Rubiks terning"], ["Termokande","Rådyr","Dronning"],["Start på en frisk","Våbenhvile","Bryd tavsheden"]],
    [ ["Brandslukningsfly","Egern","Engel"], ["Bilbo Sækker","David Guetta","Kaptajn Klo"],["Hungry like the wolf","Dragonball Z","På sporet af den tabte tid"]],
    [ ["Troldmand","Pindsvin","Nummerplade"], ["Den lille prins","Indiana Jones","Pamela Anderson"],["Hvor der handles, der spildes","Hjernevask","Én ulykke kommer sjældent alene"]],
    [ ["Bor","Kontor","Margurit"], ["Mr. Potato Head","Dæmning","Ringenes herre"],["På et hængende hår","Aftalt spil","Døde poeters klub"]],
    [ ["Plejehjem","Vampyr","Stige"], ["Der er et yndigt land","Trold","Cyrano de Bergerac"],["Fifth Element","En dækningsløs check","Detekiv"]],
    [ ["Krokodille","Kanariefugl","Klaver"], ["Målskive","Billy the Kid","Overskæg"],["David Letterman","Fodbad","Ikke for de svaglige"]],
    [ ["Hjertestarter","Tetris","Hval"], ["Stregkode","Stonehenge","Armbrøst"],["Bekend dine synder","The Avengers","Støvsuger"]],
    [ ["Kælder","Løve","Solur"], ["Varmedunk","Slangebøsse","Dampskib"],["Sæt en ny rekord","Pigen med svovlstikkerne","Have noget på samvittigheden"]],
    [ ["Svæveflyver","Tandprotese","Krabbe"], ["Palmetræ","Revisor","Magasin"],["Få det ind med modermælken","Silhuet","Prima ballerina"]],
    [ ["Skorpion","Sværdfisk","Perfume"], ["Rugby","Dynamit","Linda P"],["Ud af det blå","Være i den syvende himmel","Skjulte budskaber"]],
    [ ["Lastbil","Mus","Parkometer"], ["Øl","Spand","Mike Tyson"],["Hovedløs","Navlepilleri","Tigger"]],
    [ ["Kampfly","Horn","Haj"], ["Vandfarver","Kill Bill","Fangeflugt"],["Bevæbnet til tænderne","Kiwifrugt","Gentænd gnisten"]],
    [ ["Lærer","Chokolade","Peberspray"], ["Rød og sort","Buzz Lightyear","Bagheera"],["Den gode, den onde og den grusomme","Køre over for rødt","Gå med skyklapper på"]],
    [ ["Pilot","Gasmaske","Pinocchio"], ["Neil Armstrong","Lægge røret på","A Clockwork Orange"],["Være på vippen","Søndagsavisen","Blande tingene sammen"]],
    [ ["Zebra","Mekaniker","DVD"], ["Xylofon","Yeti","Cyklist"],["Blind som en muldvarp","En studie i rødt","Ryge ud med et brag"]],
    [ ["Ko","Gris","Vindue"], ["Trivial Pursuit","Bæver","Sikkerhedsnål"],["Klar, parat, start","Det er ikke verdens undergang","Distræt"]],
    [ ["Tipi","Skjorte","Raket"], ["Sushi","Lommeregner","Pommes frites"],["Tina Turner","Gruble over","Fight Club"]],
    [ ["Stikkontakt","Blikkenslager","Barbie"], ["Popcorn","Toiletpapir","Elevator"],["Skipper Skræk","Åbne Pandoras æske","Smidig som en abekat"]],
    [ ["Yoghurt","Paraply","Ninja"], ["Peter Plys","Moder Teresa","Lucky Luke"],["Svupper","Mars Attacks!","Jens Fup"]],
    [ ["Fisker","Flod","Ildslukker"], ["Mister Bean","Radiator","Elton John"],["Trække sig selv op ved hårrødderne","Turner og hund","Sløv som en snegl"]],
    [ ["Vejrhane","Gymnasium","Veranda"], ["Krig og Fred","Svale","Vaccine"],["Lascaux-grotterne","Inception","Romantisk bog"]],
    [ ["Gaffel","Pistol","Flagermus"], ["Forrest Gump","Fritte","Kakerlak"],["Kend dine grænser","Forsvinde i den blå luft","Hjerteskærende"]],
    [ ["Snejl","Zorro","Bilradio"], ["Dumbo","Zelda","Angry Birds"],["Criminal Minds","Hønemor","American Beauty"]],
    [ ["Julemad","Flue","Pandekage"], ["Tegneserie","Little Women","Sti"],["Det er som at lede efter en nål i en høstak","At have røde ører","Guderne går amok"]],
    [ ["Tyr","Fyrtræ","Pac-Man"], ["Tintin","Rulleskøjter","Margaret Thatcher"],["Tåle den vilde skæbnes pileskud og stenkast","Cristo Redentor-statuen","Snave"]],
    [ ["Peter Pan","Græsslåmaskine","Blinklys"], ["Blowing in the Wind","Tandemcykel","Postkort"],["Lukket som en østers","Det regner med skomagerdrenge","Få afløb for sin vrede"]],
    [ ["Bjerg","Hotel","Iglo"], ["Jordens søjler","Jacuzzi","Jeanne d’Arc"],["Verdens syv vidundere","Steve Martin","Marlon Brando"]],
    [ ["Pirat","Cykel","Sparegris"], ["Organ","Tsunami","Blyantspidser"],["Blåt øje","Godt begyndt er halvt fuldendt","Proptrækker"]],
    [ ["Storm","Vitamin","Klokke"], ["Rumstation","En verdensomsejling under havet","Casino Royale"],["Være det tredje hjul","V for Vendetta","Stædig som et æsel"]],
    [ ["Kranbil","Symaskine","Harpun"], ["Agurk","Tommelise","Hulahopring"],["David og Goliat","Richie Rich","Yuri Gagarin"]],
    [ ["Grib","Jeans","iPad"], ["Sort hul","Jukebox","Jonathan Livingston Havmåge"],["Skønhedsplet","Kast den første sten","Det er penge ud af vinduet"]],
    [ ["Nutella","Slæde","Sværd"], ["Toiletsæde","Lords of Dogtown","Jon Stewart"],["California Man","Hunden Laika","Begrave stridsøksen"]],
    [ ["Det lille hus på prærien","National fridag","Vulkan"], ["Fingerbøl","Julia Roberts","Whiskey"],["Nightmare Before Christmas","Drenge vil være drenge","Sælge sin sjæl til djævelen"]],
    [ ["Lås","And","Forstørrelsesglas"], ["Dalai Lama","Billiard","Lassie"],["Ligge i fosterstilling","Brændende feber","Babelstårnet"]],
    [ ["Skorsten","Avatar","Sombrero"], ["Kaffekande","Afrodite","Pølse"],["Hårbørste","Bag hver sky skinner solen","Springe ud i det"]],
    [ ["Brønd","Valentine’s Day","Bi"], ["Post-it","Robin Hood","Rumrejsen 2001"],["Lade nogen i stikken","Rørsiv","Trille tommelfingre"]],
    [ ["Snehvide og de syv små dværge","Geni","Minecraft"], ["Asterix og Obelix","Gladiator","Dødens gab"],["Bryde ud i koldsved","Mount Rushmore","Jorden rundt på 80 dage"]],
    [ ["Solformørkelse","Garage","Loft"], ["D’Artagnan","Den leende ko","Frank Lloyd Wright"],["Kaste perler for svin","Omar Mazouk","Søhest"]],
    [ ["Meteorit","Museum","Køleskab"], ["Kontaktlinser","The Sims","Power Rangers"],["Oplysningstiden","Svedige håndflader","Rain Man"]],
    [ ["Printer","Alpehytte","Gulvtæppe"], ["John Lennon","Bowling for Columbine","Snowboard"],["Jes Dorph","Big Ben","Skyfall"]],
    [ ["Elefant","Lighter","Elver"], ["Final Destination","Bambi","Djævlen"],["Eminem","Højdeskræk","Vide, hvad man kan vente"]],
    [ ["Potteplante","Drage","Svømning"], ["Boreplatform","Tandstik","Teenage Mutant Ninja Turtles"],["Jo flere jo bedre","Demokrati","Stolthed og fordomme"]],
    [ ["Aladdin","Drage","Æble"], ["Landmand","Bager","Fyrtårn"],["Du går mig på nerverne","Stamme","Tabe besindelsen"]],
    [ ["Biler","Yoda","Undervandsbåd"], ["Postkasse","Woody Allen","Dan Turéll"],["Drømmeseng","Tyv","Som to dråber vand"]],
    [ ["Biograf","Slange","Pelle Gris"], ["The Hardy Boys","Den hellige gral","The Sound of Silence"],["Krystalklart","Rykke håret ud af hovedet","The Muppet Show"]],
    [ ["Matador","Salat","Skole"], ["Fuglene","Rocky","Johnny Cash"],["Solnedgang","Spille med musklerne","Sove som en sten"]],
    [ ["Skovl","Gardiner","Forklædning"], ["Muhammad Ali","Quidditch","Taylor Swift"],["Træde i spinaten","Hælde salt i såret","Blåøjet pige"]],
    [ ["Brandmand","Trold","Spilkonsol"], ["LEGO","MacGyver","Askepot"],["Sukkenes bro","Biker Jens","Ond cirkel"]],
    [ ["Tennis","Lufthavn","Hat"], ["Kate Middleton","Enjoy the Silence","Brigitte Bardot"],["Tex Avery","Tre små kinesere","Krigsskader"]],
    [ ["Bokser","Hvede","Kantine"], ["Eremitkrabbe","Atlantis","Bob Marley"],["Få hukommelsestab","Mine tænder løber i vand","Bajonet"]],
    [ ["Bussemand","Aspirin","Abe"], ["Fifty Shades of Grey","Alf","Vildsvin"],["Frit fald","Ali Baba","Ud at køre med de skøre"]],
    [ ["Solbriller","Vandkande","Fe"], ["Junglebogen","Albus Dumbledore","Gødning"],["Order of the Stick","Al Capone","Døv som et brædt"]],
    [ ["Ulv","Befri Willy","Iron Man"], ["Tegnesprog","Læbestift","Judas"],["Rosettastenen","Sankt Peter","Smide håndklædet i ringen"]],
    [ ["Politimand","Banan","Rede"], ["Bøhmanden","Regnbue","Luc Besson"],["Blandt de blinde er den et-øjede konge","Stille træskoene","De tre vise mænd"]],
    [ ["Hest","Kreditkort","Flyvende tallerken"], ["Kamæleon","Atombombe","Tape"],["Smalltalk","Skabe et imperium","Klædt på til fest"]],
    [ ["Te","Pokémon","Mesterkok"], ["Pen","Isskøjter","Spøgelsesskib"],["The Truman Show","Gebrokkent dansk","Sandman"]],
    [ ["Drone","Mumien","Borg"], ["Hobbykniv","Eksorsisten","Bunker"],["At flytte bjerge","Ferris Bueller","Sten og Stoffer"]],
    [ ["Isterning","Struds","Ægteskab"], ["William Tell","Telefonbog","Sfinksen i Giza"],["Skumfidus","Træde på sømmet","De fem-bøgerne"]],
    [ ["Restaurant","Stil","Muldvarp"], ["Protese","Leaves of Grass","Maggie Gyllenhaal"],["Resident Evil","Game of Thrones","Frihedsgudinden"]],
    [ ["Mikroskop","Vagt","Hangarskib"], ["Kærlighed ved første blik","Ron Howard","Pirates of the Caribbean"],["Daytona 500","Landgangsbrød","Blive postkasserød"]],
    [ ["Orkester","Kirke","Julelys"], ["Dampmaskine","Tandpasta","Heliport"],["Ude af øje, ude af sind","E.T.","Der foregår noget uldent"]],
    [ ["Fear Factor","Teddybjørn","Skade"], ["Lynlås","Makeup","Myggenet"],["Springe køen over","Madame Tussaud","Springe ud i det"]],
    [ ["Ananas","Æg","Postbud"], ["Puddel","McDonald’s","Empire State Building"],["Løsne tungebåndet","Lewis Caroll","Lynhurtig"]],
    [ ["Barbecue","Snigmorder","Hveps"], ["Harlekin","Amy Winehouse","Harmonika"],["Trumpetbukser","Hælde benzin på bålet","Hvor brænder det?"]],
    [ ["Stjerneskud","Kage","Champagne"], ["Edward Saksehånd","Ghostbusters","Bridget Jones"],["En flue på væggen","Tyggegummi","Jo mere man ved"]],
    [ ["Minearbejder","Fængsel","Mølle"], ["Vent... Sig det ikke!","Poseidon","Vredens druer"],["Sort arbejde","Udbringe en skål","Let som en leg"]],
    [ ["Jordbær","Kineser","Brandmand"], ["Bill Clinton","Peberkværn","Sæl"],["Fidel Castro","Smøre ærmerne op","Die Hard"]],
    [ ["Infomercial","Haveslange","Hjulben"], ["Skelet","Trampolin","Den grønne mil"],["Friste skæbnen","Hof","I morgen er der atter en dag"]],
    [ ["Air bag","Ræv","Kikkert"], ["Luftpudebåd","Prinsesse","Jumanji"],["Tveægget sværd","Tangled","Jim Carrey"]],
    [ ["Klovn","GPS","Ørenring"], ["Casper","Guitar","Swing"],["Gå nogen på nerverne","Held i spil, uheld i kærlighed","God til at bedømme afstande"]],
    [ ["Natklub","Frø","Jæger"], ["Transformers","Strobelys","Tandbørste"],["Slå tiden ihjel","The Hunger Games","Holde vejret"]],
    [ ["Tiger","Fisk","Parasol"], ["Sudoku","Modelervoks","Michael Jordan"],["Prins Valiant","Mumle i skægget","Martin Luther King"]],
    [ ["Metro","Ur","Varulv"], ["Syv Samuraier","Russiske dukker","Lara Croft"],["Akilleshæl","Bikermus fra Mars","Begrave hovedet i sandet"]],
    [ ["Computer","Vindmølle","Sølvpapir"], ["Alene Hjemme","Diablo","Mayonnaise"],["Lotteri","Ennio Morricone","Springe buk"]],
    [ ["Robot","Søstjerne","Fodbold"], ["Jernbane","Blindskrift","Hestesko"],["Rio de Janeiro","Hvid som sne","Dækket af tatoveringer"]],
    [ ["Tegnebog","Konservesdåse","Diamant"], ["Strand","Advokat","Cookie"],["Tålmodighed er en dyd","Det lugter uldent","Fra Jorden til Månen"]],
    [ ["Solskærm","Statue","Hundehus"], ["Tandtråd","Shrek","Guldsmed"],["Brændt barn skyr ilden","Trille tommelfingre","De gådefulde byer af guld"]],
    [ ["Pingvin","Bibliotek","Læge"], ["Onkel Joakim","Aspartam","Croissant"],["George W. Bush","Min fod sover","Som skudt ud af en kanon"]],
    [ ["Græskar","BH","Panter"], ["Chipkort","Servitrice","Mary Poppins"],["Kvit og frit","Jeg tror ikke mine egne øjne","Marco Polo"]],
    [ ["Concord","Den usynlige mand","Radar"], ["Catwoman","Koala","Krudt"],["Venskabskreds","Penge gror ikke på træerne","Når helvede fryser til is"]],
    [ ["Elektrisk stol","Vindusvisker","Titanic"], ["Bowling","Blegemiddel","Stilethæl"],["Justin Bieber","Dum som et redskabsskur","Besvime"]],
    [ ["Papegøje","Strå","Eiffeltårnet"], ["Krydsogtværs","Marilyn Manson","Dexter"],["Min dyrebare","Død og begravet","Påskeøen"]],
    [ ["Dr. House","Toy Story","Kirsebær"], ["Amor","The Artist","Kompas"],["Træde tilbage","Tæske en hest til døde","Ben-Hur"]],
    [ ["Hang glider","Frugtjuice","Ror"], ["Nylonstrømper","Jurassic Park","Guillotine"],["At afbryde nogen","Slå plat og krone","Hermione Granger"]],
    [ ["Mælk","Næsehorn","Enhjørning"], ["The Quest for Fire","Reklame","Lance Armstrong"],["Tomme trusler rører mig ikke","Tilbage til fremtiden","Stilhed er guld"]],
    [ ["Den lyserøde panter","Terninger","Simpsons"], ["The Birdcage","Nøgle","Venus de Milo"],["Vejen til helvede er brolagt med gode intentioner","Colosseum","Vietnam-krigen"]],
    [ ["Fodgængerfelt","Julemanden","Vindyrker"], ["Miss America","Den franske revolution","Kuffert"],["Skrue lidt ned","Den forbudte by","Se rødt"]],
    [ ["Støvler","Dykkergrej","Ferrari"], ["Lejekontrakt","Mads og Mikkel","Rulletrapper"],["Have hjertet udenpå","Sæsonpræget","Stadset op"]],
    [ ["Ambulance","Kanyle","Pyjamas"], ["Magnet","Lyssværd","Skraldespand"],["Det er, hvad det er","Skyde sig selv i foden","Alcatraz"]],
    [ ["Bordtennis","Handsker","Hobbykniv"], ["Ødipus","Station","Kejsersnit"],["Så træt, man ser dobbelt","Ryge som en skorsten","Det Sixtinske Kapel"]],
    [ ["Mobiltelefon","Infrarødt teleskop","Giraf"], ["Hannibal Lecter","I rosens navn","Brødrister"],["Once Upon a Time in the West","Tvedelt tunge","Pebermø"]],
    [ ["Ørn","Solsikke","Køkken"], ["Animal Planet","Terminator","Cirkus"],["Åndeløs","Top Gun","Kloning"]],
    [ ["Bank","Soveværelse","Fløjte"], ["Arkimedes","Borat","Fast and Furious"],["Få frie tøjler","Billy Jean","Eureka!"]],
    [ ["Trehjulet cykel","Bøf","Egypten"], ["Halløj i klosteret","Fløjte","Desperate Housewives"],["Holde tand for tunge","Sigmund Freud","Adam Sandler"]],
    [ ["Vifte","Kaffe","Rangle"], ["Twilight","Batman","Johnny Carson"],["Et billede siger mere end tusind ord","Have en tudse i halsen","Jean-Claude Van Damme"]],
    [ ["Dinosaur","Motorsav","Smølferne"], ["Crocodile Dundee","Spøgelsestog","Den leende ko-ost"],["Anmode om en kvindes hånd","Narkosmugling","Hundredårskrigen"]],
    [ ["Spinat","Pram","Kulturarv"], ["Dr. Jekyll","Moses","Jack Bauer"],["Esmeralda","Mænd der hader kvinder","Luke, I am your father"]],
    [ ["Harry Potter","Sø","Coca-Cola"], ["Leaving on a Jet Plane","Stand By Me","Kasserolle"],["Jeg vil satse mit liv på det","Føle sig som det tredje hjul","Mareridt"]],
    [ ["Sonic the Hedgehog","Stangspring","Trompet"], ["Sauna","Romeo og Juliet","Det skæve tårn i Pisa"],["Få det forkerte ben ud af sengen","Lade propperne springe","Hver sin smag"]],
    [ ["Isbjørn","Heks","Snemand"], ["Lincoln Memorial","Sæbe","Baguette"],["Hvedebrødsdage","Ude på dybt vand","Det vejer tungt på samvittigheden"]],
    [ ["Fjer","Kokosnød","Havn"], ["Faldskærm","Katapult","Tøjklemme"],["Indkøbsvogn","Censur","En rullesten samler ikke mos"]],
    [ ["Yo-yo","101 dalmatinere","Sommerfugl"], ["Wolverine","Livet er smukt","Men in Black"],["Lynet slår ikke ned det samme sted to gange","Lev livet fuldt ud","Ældre og klogere"]],
    [ ["Skovhugger","Myg","Mikrobølgeovn"], ["Doris Day","Boondock Saints","Smørkniv"],["Have fødderne solidt plantet på jorden","Farlige forbindelser","Sult"]],
    [ ["Ice Age","Delfin","Vandtårn"], ["Den sorte gryde","Tastatur","Bruce Lee"],["Kreml","Gøre nogen stum af forbavselse","I galhalsen"]],
    [ ["Svampebob Firkant","Krydderier","Tarzan"], ["Borte med blæsten","Ocean’s Eleven","Korncirkel"],["Tømmermænd","Sove med ét øje åbent","Snoopy"]],
  ];
}

?>
