<?php
class ConceptCardsNOR {
  static $cards = [
    [ ["Hjul","Basseng","Kenguru"], ["Rotte","Lykkehul","Karaoke"],["Robinson Crusoe","Stormannsgalskap","Falkeblikk"]],
    [ ["Lysstav","Fredag den trettende","Mp3 spiller"], ["Mikrofon","Tupperware","Austin Powers"],["Maske","Å tale er sølv, å tie er gull.","Penny Arcade"]],
    [ ["Oppdrag Nemo","Hjelm","Vin"], ["Apeplaneten","Pugge","Borrelås"],["Ikke selg skinnet før bjørnen er skutt.","Toppen av kransekaken","Smi mens jernet er varmt"]],
    [ ["Murstein","Sveitsisk militærkniv","Ordbok"], ["Baloo","Beyoncé","Ulvehunden"],["Sett sjøbein","Henrik Wergeland","Flaskeåpner"]],
    [ ["Badekar","Notisbok","Stetoskop"], ["Edderkopp","Batteri","Silikon"],["Møtes på halvveien","Ikke gjøre et slag","Seks fot under"]],
    [ ["Traktor","Skjell","Rubiks kube"], ["Termos","Rådyr","Dronning"],["Gjør en frisk start","Våpenhvile","Bryte stillheten"]],
    [ ["Brannfly","Ekorn","Engel"], ["Bilbo Lommelun","David Guetta","Kaptein Harlock"],["Sulten som en ulv","Dragonball Z","Å huske gamledager"]],
    [ ["Magiker","Pinnsvin","bilskilt"], ["Den lille prinsen","Indiana Jones","Pamela Anderson"],["Man kan ikke lage omelett uten å knuse egg","Hjernevasking","Dårlige ting skjer alltid i tre"]],
    [ ["Drill","Kontor","Tusenfryd"], ["Herr Potethode","Damm","Ringenes herre"],["Bare tannhinnen er ennu urørt på mig","Ta en dykketur","Grip dagen"]],
    [ ["Gamlehjem","Vampyr","Stige"], ["Over bakkar og berg...","Troll","Cyrano de Bergerac"],["Det femte element","En dårlig sjekk","Detektiv"]],
    [ ["Krokodille","Kanarifugl","Piano"], ["Målet","Billy the Kid","Bart"],["Aksel Hennie","Fotbad","Ikke for de med svakt hjerte"]],
    [ ["Hjertestarter","Tetris","Hval"], ["Strekkode","Stonehenge","Armbrøst"],["Tilstå dine synder","The Avengers","Støvsuger"]],
    [ ["Kjeller","Løve","Solur"], ["Varmeflaske","Sprettert","Dampbåt"],["Sett en ny rekord","Piken med svovelstikkene","Har dårlig samvittighet"]],
    [ ["Glidefly","Gebiss","Krabbe"], ["Palmetre","Regnskapsfører","Ammunisjonsmagasin"],["Det er bedre med en fugl i hånda enn ti på taket.","Siluett","Prima ballerina"]],
    [ ["Skorpion","Sverdfisk","Parfyme"], ["Rugby","Dynamitt","Kurt Nilsen"],["Fra venstre banehalvdel","Å være i den syvende himmel","Subliminal melding"]],
    [ ["lastebil","Mus","Parkeringsautomat"], ["Øl","Bøtte","Mike Tyson"],["Tankeløs","Navlebeskuende","Tigger"]],
    [ ["Jagerfly","Horn","Hai"], ["Vannfarger","Kill Bill","Prison Break"],["Væpnet til tennene","Kiwifrukt","Tenne flammen"]],
    [ ["Lærer","Sjokolade","Pepperspray"], ["Rødt og svart","Astro Boy","Bagheera"],["Den gode, den onde og den grusomme","Kjøre på rødt","Ha hodet ditt i skyene"]],
    [ ["Pilot","Gassmaske","Pinocchio"], ["Neil Armstrong","Legger på telefonen","A Clockwork Orange"],["Klatre over gjerdet","Søndagsavisen","Skyggelegg saken"]],
    [ ["Sebra","Mekaniker","DVD"], ["Xylofon","Avskyelig snømann","Syklist"],["Forvirre saken","En studie i rødt","Styrter i flammer"]],
    [ ["Ku","Gris","Vindu"], ["Trivial Pursuit","Bever","Sikkerhetsnål"],["Klar for start","Det er ikke verdens ende","Fraværende"]],
    [ ["Tipi","Skjorte","Rakett"], ["Sushi","Kalkulator","Pommes Frites"],["Tina Turner","Gruble over","Fight club"]],
    [ ["Salg","Rørlegger","Barbie"], ["Popcorn","Toalettpapir","Heis"],["Skipper´n","Åpne Pandoras eske","Smidig som en ape"]],
    [ ["Yoghurt","Paraply","Ninja"], ["Ole Brumm","Mor Teresa","Lucky Luke"],["Stempel","Mars Attacs!","Billy"]],
    [ ["Fisker","Elv","Brannslukker"], ["Mister Bean","Radiator","Elton John"],["De gamle bukkene har de stiveste hornene","Turner og Hooch","Treig som en snile"]],
    [ ["Værhane","Gymnasium","Veranda"], ["Krig og fred","Svelge","Vaksine"],["Lascaux grotten","Inception","Kjærlighetsroman"]],
    [ ["Gaffel","Gevær","Balltre/flaggermus"], ["Forrest Gump","Ilder","Kakerlakk"],["Kjenn dine begrensninger","Forsvinne i tynne luften","Hjerteskjærende"]],
    [ ["Snegle","Zorro","Bilstereo"], ["Dumbo","Zelda","Angry Birds"],["Criminal minds","Hønemor","American Beauty"]],
    [ ["Rullekake","Fly","Pannekake"], ["Tegneserie","Småfrøkner","Sti"],["Det er som å lete etter nåla i høystakken","Det gjør vondt i ørene","Gudene må være gale"]],
    [ ["Okse","Grantreet","Pac-Man"], ["Tintin","Rulleskøyte","Margaret Tatcher"],["Bedre med trøtte armer enn tomme tarmer","Statuen av Kristus frelseren","Kosing"]],
    [ ["Peter Pan","Gressklipper","Blinklys"], ["Blåse i vinden","Sykkel bygd for to","Postkort"],["Stum som en østers","Det regner hunder og katter","Kanaliser ditt sinne"]],
    [ ["Fjell","Hotell","Iglo"], ["Stormenes tid","Boblebad","Jeanne d`Arc"],["Verdens syv underverker","Steve Martin","Marlon Brando"]],
    [ ["Pirat","Sykkel","Sparebøsse"], ["Orgel","Tsunami","Blyantspisser"],["Blåveis","Ingen er så brukbar som poteten","Korketrekker"]],
    [ ["Storm","Vitamin","Bjelle"], ["Romstasjon","En vedensomseiling under havet","Casino Royale"],["Tredje hjul på vogna","V for Vendetta","Sta som et esel"]],
    [ ["Bergningsbil","Symaskin","Harpun"], ["Agurk","Tommeliten","Rockering"],["David og Goliat","Morten Harket","Yuri Gagarin"]],
    [ ["Gribb","Dongeribukse","iPad"], ["Sort hull","Jukeboks","Måken"],["Skjønnhetsflekk","Kast den første steinen","Penger rett ut av vinduet"]],
    [ ["Nutella","Slede","Sverd"], ["Toalettsete","Lords of Dogtown","Jon Stewart"],["Kon-Tiki","Thor Heyerdahl","Begrave stridsøksen"]],
    [ ["Lille huset på prærien","Offentlig høytidsdag","Vulkan"], ["Tingeling","Julia Roberts","Whiskey"],["Et førjulsmareritt","Gutter vil være gutter","Selg din sjel til djevelen"]],
    [ ["Lås","And","Forstørrelsesglass"], ["Dalai Lama","Biliard","Lassie"],["Krøllet sammen som en ball","Brennende feber","Babels tårn"]],
    [ ["Pipe","Avatar","Sombrero"], ["Kaffekanne","Afrodite","Pølse"],["Hårbørste","Det er lys i enden av tunnelen","Hopp i det"]],
    [ ["Brønn","Valentinsdag","Bie"], ["Post-it","Robin Hood","2001 - en romodyssé"],["Dukket ikke opp på daten","Siv","Spinn dine hjul"]],
    [ ["Snøhvit og de syv dvergene","Geni","Minecraft"], ["Asterix og Obelix","Gladiator","Haisommer"],["Bryt ut i kaldsvette","Mount Rushmore","Jorden rundt på 80 dager"]],
    [ ["Formørkelse","Garsje","Loft"], ["D’Artagnan","Mr. Lee","Jens Stoltenberg"],["Kaste perler for svin","Aziz Ansari","Sjøhest"]],
    [ ["Meteoritt","Museum","Fryser"], ["Kontaktlinser","Sims","Power Rangers"],["Opplysningstiden","Klamme hender","Rain Man"]],
    [ ["Skriver","Hytte","Teppe"], ["John Lennon","Bowling for Columbine","Snowboard"],["Bjørn Sundquist","Big Ben","Skyfall"]],
    [ ["Elefant","Lighter","Alv"], ["Final Destination","Bambi","Djevelen"],["Eminem","Vær redd for høyder","Vit hva du kan vente deg"]],
    [ ["Blomsterpotte","Dragen","Svømme"], ["Oljeplattform","Tannpirker","Teenage Mutant Ninja Turtles"],["Jo fler jo bedre","Demokrati","Stolthet og fordom"]],
    [ ["Aladdin","Drage","Eple"], ["Gårdbruker","Baker","Fyrtårn"],["Du går meg på nervene","Stamme","Mist hodet ditt"]],
    [ ["Biler","Yoda","Ubåt"], ["Postkasse","Woody Allen","Henrik Ibsen"],["Solseng","Tyv","Så like som to dråper vann"]],
    [ ["Kino","Slange","Pelle Gris"], ["Hardy guttene","Den hellige gral","Lyden av stillhet"],["Vær krystallklar","Dra ut håret ditt","Kristoffer Joner"]],
    [ ["Monopol","Salat","Skole"], ["Fuglene","Rocky","Johnny Cash"],["Nils Ole Oftebro","Flekse musklene","Sove som en stein"]],
    [ ["Spade","Gardiner","Forkledning"], ["Muhammad Ali","Rumpeldunk","Taylor Swift"],["Tramp i klaveret","Vri om kniven","Brunøyd jente"]],
    [ ["Manet","Troll","Spillkonsoll"], ["LEGO","MacGyver","Askepott"],["Sukkenes bro","Richard Hatch","Ond sirkel"]],
    [ ["Tennis","Flyplass","Hatt"], ["Kate Middelton","Nyt stillheten","Birgitte Bardot"],["Tex Avery","Ti små indianere","Krigsskader"]],
    [ ["Bokser","Hvete","Vannflaske"], ["Eremittkrabbe","Atlantis","Bob Marley"],["Minnet forfaller","Munnen løper i vann","Bajonett"]],
    [ ["Snørr","Paracet","Apekatt"], ["Fifty Shades of Grey","Alf","Villsvin"],["Fritt fall","Ali Baba","Bli lurt"]],
    [ ["Solbriller","Vannkanne","Fe"], ["Jungelboken","Albus Humlesnurr","Gjødsel"],["Stavordenen","Al Capone","Stokk døv"]],
    [ ["Ulv","Free Willy","Iron Man"], ["Tegnspråk","Leppestift","Judas"],["Rosettasteinen","St. Peter","Kast inn håndkledet"]],
    [ ["Politimann","Banan","Rede"], ["Busemann","Regnbue","Luc Besson"],["I de blindes kongedømme er den enyde mann konge","Spark bøtta","Tre vise menn"]],
    [ ["Hest","Kredittkort","Flyvende tallerken"], ["Kemeleon","Atombombe","Scotch tape"],["Snakk rundt vannkjøleren","Bygg et kongerike","Stivpyntet"]],
    [ ["Te","Pokémon","Master Chef"], ["Penn","Skøyter","Spøkelsesskip"],["Kristofer Hivju","Dårlig engelsk","Ole lukkøye"]],
    [ ["Drone","Mumien","Slott"], ["Lommekniv","Exorcisten","Sandfelle"],["Å flytte fjell","Rolv Wesenlund","Tommy og tigeren"]],
    [ ["Isbit","Struts","Giftemål"], ["William Tell","Katalog","Sfinksen i Giza"],["Marshmallow","Tråkk pedalen i bånn","The Boxcar Children"]],
    [ ["Resturant","Stil","Føflekk"], ["Protese","Løv av gress","Maggie Gyllenhaal"],["Resident Evil","Game of Thrones","Frihetsstatuen"]],
    [ ["Mikroskop","Vakt","Hangarskip"], ["Hvorfor ble jeg gift","Ron Howard","Pirates of the Caribbean"],["Martin Schanche","Dagobert","Det er ille å bake og aldri smake"]],
    [ ["Orkester","Kirke","Juletrelys"], ["Dampmaskin","Tannpasta","Helikopterplattform"],["Ute av syne, ute av sinn","E.T.","Det foregår noe muffens"]],
    [ ["Fear Factor","Teddybjørn","Skjære"], ["Glidelås","Sminke","Myggnetting"],["Snik i køen","Madame Tussaud","Gå i gang med en gang"]],
    [ ["Ananas","Egg","Postmann"], ["Puddel","McDonald’s","Empire State Bygningen"],["Småprate","Jo Nesbø","Rask som et olja lyn"]],
    [ ["Grilling","Snikmorder","Veps"], ["Harlekin","Amy Winehouse","Munnspill"],["Høyvannsbukser","Helle bensin på bålet","Hvor brenner det?"]],
    [ ["Stjerneskudd","Kake","Champagne"], ["Edward Saksehånd","Ghostbusters","Bridget Jones"],["Flue på veggen","Tyggis","Jo mer du vet"]],
    [ ["Gruvearbeider","Fengsel","Mølle"], ["Vent, Vent... Ikke fortell meg det!","Poseidon","Vredens druer"],["Måneskinn","Ta en skål","Lett som en plett"]],
    [ ["Jordbær","Kinaputt","Brannmann"], ["Bill Clinton","Pepperkvern","Segl"],["Fidel Castro","Brett opp ærmene","Die Hard"]],
    [ ["Infomercial","Hageslange","Bippe stankelben"], ["Skjelett","Trampoline","Den grønne mil"],["Utfordre skjebenen","Domstol","Også solen stiger"]],
    [ ["Air Bag","Rev","Kikkert"], ["Svevebåt","Prinsesse","Jumanji"],["Dobbelegged sverd","Sammentvunnet","Jim Carrey"]],
    [ ["Klovn","GPS","Ørering"], ["Casper","Gitar","En huske"],["Plag noen","Flaks i kort uhell i kjærlighet","Et godt øye for avstandsmåling"]],
    [ ["Nattklubb","Frosk","Jeger"], ["Transformers","Strobelys","Tannbørste"],["Drep tiden","The Hunger Games","Hold pusten"]],
    [ ["Tiger","Fisk","Parasoll"], ["Sudoku","Modeleringsleire","Michael Jordan"],["Prins Valiant","Mumle","Martin Luther King"]],
    [ ["Undergrunn","Klokke","Varulv"], ["De syv Samuraier","Russisk kone","Lara Croft"],["Akilleshelen","Knights of the Zodiac","Begrav hodet i sanden"]],
    [ ["Datamaskin","Vindmølle","Aluminiumsfolie"], ["Hjemme alene","Diablo","Majones"],["Lotteri","Ennio Morricone","Hoppe paradis"]],
    [ ["Robot","Sjøstjerne","Fotball"], ["Togrute","Blindeskrift","Hestesko"],["Rio de Janeiro","Hvit som snø","Få mange tatoveringer"]],
    [ ["Lommebok","Tinnboks","Diamant"], ["Strand","Advokat","Kjeks"],["Idioter hater i vei","Jeg lukter lunta","From the Earth to the Moon"]],
    [ ["Solskjerm","Statue","Hundehus"], ["Spyle ned","Shrek","Øyenstikker"],["Bitter er selv den søteste kvinne","Tvinn tommeltotter","Det var en gang et menneske"]],
    [ ["Pingvin","Bibliotek","Doktor"], ["Onkel Skrue","Aspartam","Croissant"],["George W. Bush","På tå og hev","Start med et brak"]],
    [ ["Gresskar","Brystholder","Panter"], ["Smartkort","Kelner","Mary Poppins"],["Det er gratis","Få øye på","Marco Polo"]],
    [ ["Concord","Den usynlige mannen","Radar"], ["Catwoman","Koala","Krutt"],["Vennesirkelen","Penger vokser ikke på trær","Når griser flyr"]],
    [ ["Den elektriske stolen","Vindusvisker","Titanic"], ["Bowling","Blekemiddel","Stiletthel"],["Justin Bieber","Dum som en stut","Besvim"]],
    [ ["Papegøye","Sugerør","Eiffeltårnet"], ["Kryssord","Marilyn Manson","Dexter"],["Min kostligste","Den siste hvile","Påskeøya"]],
    [ ["Doktor House","Toy Story","Kirsebær"], ["Cupido","Kunstneren","Kompass"],["Si opp","Gå rundt grøten","Ben-Hur"]],
    [ ["Hang glider","Fruktjuice","Ror"], ["Strømpebukse","Jurassic Park","Giljotin"],["Å avbryte noen","Flipp en mynt","Hermine Grang"]],
    [ ["Melk","Nesehorn","Enhjørning"], ["The Quest for Fire","Reklame","Lance Armstrong"],["Kjepper og stein kan brekke mine ben","Tilbake til fremtiden","Stilleten er gyllen"]],
    [ ["Den rosa panteren","Terninger","Simpsons"], ["Lånte fjær","Nøkkel","Venus de Milo"],["Veien til helvete er brolagt med gode intensjoner","Colosseum","Vietnamkrigen"]],
    [ ["Fotovergang","Julenissen","Vinmaker"], ["Miss America","Den franske revulusjon","Koffert"],["Ro det ned litt","Den forbudte by","Vær ekstremt irritert"]],
    [ ["Støvler","Dykkerutstyr","Ferrari"], ["Leie","To gode venner","Heis"],["Bare et knust hjerte er helt","Sesong","Vær oppjaget"]],
    [ ["Ambulanse","Sprøyte","Pysjamas"], ["Magnet","Lyssabel","Søppelbøtte"],["Det er hva det er","Skyt deg selv i foten","Alkatraz"]],
    [ ["Bordtennis","Hansker","Papirsaks"], ["Ødipus","Stasjon","Keisersnitt"],["For trøtt til å tenke rett","Røyk som en skorstein","Det sikstinske kapell"]],
    [ ["Mobiltelefon","Infrarødt teleskop","Sjiraff"], ["Hanibal Lecter","Rosens navn","Brødrister"],["Det var en gang i vesten","Kløvet tunge","Kirkekvinne"]],
    [ ["Ørn","Solsikke","Kjøkken"], ["Animal Planet","Terminator","Sirkus"],["Åndeløs","Top Gun","Kloning"]],
    [ ["Bank","Soverom","Fløyte"], ["Arkimedes","Borat","Fast and Furious"],["Å bli gitt frie tøyler","Billy Jean","Eureka!"]],
    [ ["Trehjulsykkel","Biff","Egypt"], ["Sister Act","Plystre","Frustrerte fruer"],["Bit deg i tungen","Sigmund Freud","Adam Sandler"]],
    [ ["Vifte","Kaffe","Skrangle"], ["Skumring","Batman","Johnny Carson"],["Et bilde er verdt tusen ord","Han har en frosk i halsen","Jean-Claude Van Damme"]],
    [ ["Dinosaur","Motorsag","Smurfene"], ["Crocodile Dundee","Spøkelsestoget","Den leende ku ost"],["Be om noens hånd","Narkotikasmugling","Hundreårskrigen"]],
    [ ["Spinat","Seilbåt","Arv"], ["Dr. Jekyll","Moses","Jack Bauer"],["Ane Dahl Torp","Jenta som lekte med ilden","Luke, I am your father"]],
    [ ["Harry Potter","Innsjø","Coca-Cola"], ["Leaving on a Jet Plane","Stand by me","Kasserolle"],["Jeg føler meg som femte hvul på vogna","Jeg vedder livet mitt","Mareritt"]],
    [ ["Sonic the Hedgehog","Stavhopp","Trompet"], ["Badstu","Romeo og Julie","Skjeve tårnet i pisa"],["Den som intet hjerte har, kan alltid tåle","Stå opp på gal side av sengen","Dra opp korken"]],
    [ ["Isbjørn","Heks","Snømann"], ["Stortinget","Såpe","Baguette"],["Bryllupsreise","Ute i ugresset","Å veie ens hjerte"]],
    [ ["Fjær","Kokosnøtt","Havn"], ["Fallskjerm","Katapult","Klesklype"],["Handlekurv","Sensur","En rullende stein samler ikke mose"]],
    [ ["Yo-Yo","101 Dalamatinere","Sommerfugl"], ["Wolverine","Livet er vakkert","Men in Black"],["Lynet slår aldri ned to ganger på samme sted","Lev livet fullt ut","Eldre og visere"]],
    [ ["Tømmerhogger","Mygg","Mikrobølgeovn"], ["Peggy Lee","Max Manus","Smørkniv"],["Ha bena plantet på jorden","Farlig begjær","Sult"]],
    [ ["Istid","Delfin","Vanntårn"], ["Den sorte gryte","Tastatur","Bruce Lee"],["Kremlin","Gjøre noen målløse","Vranghalsen"]],
    [ ["Svampebob firkant","Krydder","Tarzan"], ["Tatt av vinden","Ocean’s Eleven","åkersirkler"],["Fyllesyk","Sove med ett øye åpent","Snoopy"]],
  ];

}

?>
