<?php
class ConceptCardsFI {
  static $cards = [
    [ ["Pyörä","Uima-allas","Kenguru"], ["Rotta","Onnenpyörä","Karaoke"],["Robinson Crusoe","Suuruudenhulluus","Haukankatse"]],
    [ ["Ukkosenjohdatin","Perjantai 13. päivä","MP3-soitin"], ["Mikrofoni","Tupperware","Austin Powers"],["Naamio","Puhua kuin ruuneperi","Fingerpori"]],
    [ ["Nemoa etsimässä","Kypärä","Viini"], ["Apinoiden planeetta","Tulppa","Velcro"],["Piste i:n päälle","Takoa kun rauta on kuuma","Susi lampaan vaatteissa"]],
    [ ["Tiili","Sveitsin armeijan linkkuveitsi","Sanakirja"], ["Mowgli","Paula Koivuniemi","Valkohammas"],["Vuotaa kuin seula","Pentti Saarikoski","Pullonavaaja"]],
    [ ["Kylpyamme","Muistikirja","Stetoskooppi"], ["Hämähäkki","Paristo","Silikoni"],["Tasajako","Laiskajaakko","Mullan alla"]],
    [ ["Traktori","Simpukka","Rubikin kuutio"], ["Termospullo","Kauris","Kuningatar"],["Aloittaa puhtaalta pöydältä","Tulitauko","Murtaa hiljaisuus"]],
    [ ["Palonsammutuslentokone","Orava","Enkeli"], ["Bilbo Reppuli","Elastinen","Kapteeni Haddock"],["Sudennälkä","Muumit","Kadonnutta aikaa etsimässä"]],
    [ ["Taikuri","Siili","Rekisterikilpi"], ["Pikku Prinssi","Indiana Jones","Pamela Anderson"],["Rapatessa roiskuu","Aivopesu","Vahinko ei tule kello kaulassa"]],
    [ ["Pora","Toimisto","Päivänkakkara"], ["Röllipeikko","Pato","Taru sormusten herrasta"],["Rimaa hipoen","Sopupeli","Kuolleiden runoilijoiden seura"]],
    [ ["Vanhainkoti","Vampyyri","Tikapuut"], ["Porilaisten marssi","Peikko","Aki Kaurismäki"],["Viides elementti","Katteeton shekki","Yksityisetsivä"]],
    [ ["Krokotiili","Kanarialintu","Piano"], ["Maalitaulu","Billy the Kid","Viikset"],["Kati Outinen","Jalkakylpy","Ei heikkohermoisille"]],
    [ ["Sydämentahdistin","Tetris","Valas"], ["Viivakoodi","Stonehenge","Varsijousi"],["Paha saa palkkansa","Kostajat","Pölynimuri"]],
    [ ["Kellari","Leijona","Aurinkokello"], ["Kuumavesipullo","Linko","Höyrylaiva"],["Tehdä uusi ennätys","Tulitikkutyttö","Huono omatunto"]],
    [ ["Pelastusvene","Tekohampaat","Rapu"], ["Palmu","Kirjanpitäjä","Lipas"],["Omena ei putoa kauas puusta","Siluetti","Priimaballeriina"]],
    [ ["Skorpioni","Miekkakala","Hajuvesi"], ["Pesäpallo","Dynamiitti","Arto Nyberg"],["Lyödä ällikällä","Olla seitsemännessä taivaassa","Kuudes aisti"]],
    [ ["Rekka","Hiiri","Pysäköintimittari"], ["Olut","Ämpäri","Mike Tyson"],["Vainoharhainen","Omaan napaan tuijottelu","Kerjäläinen"]],
    [ ["Hävittäjäkone","Torvi","Hai"], ["Vesivärit","Kummisetä","Vankilapako"],["Hampaisiin asti aseistettu","Kiivi","Vanha suola janottaa"]],
    [ ["Opettaja","Suklaa","Pippurisuihke"], ["Seitsemän veljestä","Aku Ankka","Risto Räppääjä"],["Hyvät, pahat ja rumat","Ajaa päin punaisia","Kulkea pää pilvissä"]],
    [ ["Lentäjä","Kaasunaamari","Pinokkio"], ["Neil Armstrong","Joka päivä ja jokaikinen yö","Kellopeli appelsiini"],["Olla kahden vaiheilla","Sanomalehti","Niin makaa kuin petaa"]],
    [ ["Seepra","Mekaanikko","DVD"], ["Ksylofoni","Jeti / Lumimies","Pyöräilijä"],["Sokea kuin lepakko","Kalevala","Turmiolan Tommi"]],
    [ ["Lehmä","Sika","Ikkuna"], ["Trivial Pursuit","Majava","Hakaneula"],["Aika kultaa muistot","Se ei ole maailman loppu","Hajamielinen"]],
    [ ["Tiipii","Paita","Raketti"], ["Sushi","Taskulaskin","Ranskalaiset perunat"],["Tina Turner","Murehtia","Fight Club"]],
    [ ["Pistorasia","Putkimies","Barbie"], ["Popcorn","Vessapaperi","Hissi"],["Kippari-Kalle","Lampun henki","Notkea kuin rautakanki"]],
    [ ["Jogurtti","Sateenvarjo","Ninja"], ["Nalle Puh","Äiti Teresa","Lucky Luke"],["Karhupumppu","Hävisi kuin pieru Saharaan","Masi"]],
    [ ["Kalastaja","Joki","Vaahtosammutin"], ["Mister Bean","Lämpöpatteri","Elton John"],["Ottaa itseään niskasta kiinni","Yksi lensi yli käenpesän","Etananvauhtia"]],
    [ ["Tuuliviiri","Liikuntasali","Veranta"], ["Sota ja rauha","Pääskynen","Rokotus"],["Näsinneula","Inception","Rakkausromaani"]],
    [ ["Haarukka","Ase","Lepakko"], ["Forrest Gump","Fretti","Torakka"],["Tietää omat rajansa","Kadota kuin tuhka tuuleen","Sydäntäsärkevä"]],
    [ ["Etana","Zorro","Autostereot"], ["Dumbo","Zelda","Angry Birds"],["Criminal Minds – FBI-tutkijat","Kanaemo","American Beauty"]],
    [ ["Riisipuuro","Kärpänen","Pannukakku"], ["Sarjakuva","Häräntappoase","Polku"],["Kuin etsisi neulaa heinäsuovasta","Korvia kuumottaa","Tuntematon sotilas"]],
    [ ["Härkä","Mänty","Pac-Man"], ["Tintti","Rullaluistin","Margaret Thatcher"],["Painua niin pitkälle kuin pippuri kasvaa","Kolmen sepän patsas","Kuhertelu"]],
    [ ["Peter Pan","Ruohonleikkuri","Auton vilkku"], ["Maamme laulu","Tandempyörä","Postikortti"],["Sopii kuin nenä päähän","Sataa kuin saavista kaataen","Maltti on valttia"]],
    [ ["Vuori","Hotelli","Iglu"], ["Carcassonne","Poreamme","Jeanne d’Arc"],["Maailman seitsemän ihmettä","Steve Martin","Marlon Brando"]],
    [ ["Merirosvo","Polkupyörä","Säästöpossu"], ["Urut","Tsunami","Kynänterotin"],["Musta silmä","Hädässä ystävä tunnetaan","Korkkiruuvi"]],
    [ ["Myrsky","Vitamiini","Kello"], ["Avaruusasema","Salaisuuksien saari","Casino Royale"],["Olla kolmantena pyöränä","V niinkuin verikosto","Itsepäinen aasi"]],
    [ ["Hinausauto","Ompelukone","Harppuuna"], ["Kurkku","Peukaloinen","Hulavanne"],["Daavid ja Goljat","Riku Rikas","Juri Gagarin"]],
    [ ["Korppikotka","Farkut","iPad"], ["Musta aukko","Jukeboksi","The Wall"],["Kauneuspilkku","Kankkunen","Heittää rahaa kankkulan kaivoon"]],
    [ ["Mämmi","Reki","Miekka"], ["WC-istuin","Totoro","Conan O’Brien"],["Suo siellä, vetelä täällä","Laika","Haudata sotakirves"]],
    [ ["Pieni talo preerialla","Arkipyhä","Tulivuori"], ["Helinä-keiju","Julia Roberts","Viski"],["Painajainen Elm streetillä","Pojat ovat poikia","Myydä sielunsa paholaiselle"]],
    [ ["Lukko","Ankka","Suurennuslasi"], ["Dalai Lama","Biljardi","Lassie"],["Happamia, sanoi kettu pihlajanmarjoista","Kääriytyneenä kerälle","Baabelin torni"]],
    [ ["Savupiippu","Avatar","Sombrero"], ["Kahvipannu","Afrodite","Makkara"],["Hiusharja","Jokaisella pilvellä on hopeareunus","Raskas työ vaatii raskaat huvit"]],
    [ ["Kaivo","Ystävänpäivä","Mehiläinen"], ["Post-it-lappu","Robin Hood","2001: Avaruusseikkailu"],["Tehdä oharit","Puupuhaltimet","Ketunhäntä kainalossa"]],
    [ ["Lumikki ja seitsemän kääpiötä","Nero","Minecraft"], ["Asterix ja Obelix","Gladiaattori","Tappajahai"],["Kylmä hiki","Mount Rushmore","Maailman ympäri 80 päivässä"]],
    [ ["Auringonpimennys","Autotalli","Ullakko"], ["Kolme muskettisoturia","Uuno Turhapuro","Frank Lloyd Wright"],["Helmiä sioille","Ruben Stiller","Merihevonen"]],
    [ ["Meteoriitti","Museo","Jääkaappi"], ["Piilolinssi","Sims","Power Rangers"],["Valistuksen aika","Hikiset kädet","Sademies"]],
    [ ["Tulostin","Mökki","Matto"], ["John Lennon","Popeda","Lumilauta"],["Cheek","Big Ben","James Bond"]],
    [ ["Elefantti","Sytytin","Haltia"], ["Papillon","Bambi","Paholainen"],["Eminem","Korkean paikan kammo","Tietää mitä odottaa"]],
    [ ["Kukkaruukku","Lohikäärme","Uiminen"], ["Teini-ikäiset mutanttininjakilpikonnat","Öljynporauslautta","Hammastikku"],["Työ tekijäänsä kiittää","Demokratia","Ylpeys ja ennakkoluulo"]],
    [ ["Aladdin","Leija","Omena"], ["Maanviljelijä","Leipuri","Majakka"],["Hermoraunio","Änkytys","Menettää malttinsa"]],
    [ ["Autot","Yoda","Sukellusvene"], ["Postilaatikko","Woody Allen","Jules Verne"],["Solarium","Varas","Kuin kaksi marjaa"]],
    [ ["Elokuvateatteri","Käärme","Putte Possu"], ["Viisikko","Graalin malja","The Sound of Silence"],["Kristallinkirkas","Lyhyestä virsi kaunis","Muppetit"]],
    [ ["Monopoly","Salaatti","Koulu"], ["Linnut","Rocky","Timo Soini"],["Pokeri","Pullistella lihaksiaan","Nukkua kuin tukki"]],
    [ ["Lapio","Verhot","Valeasu"], ["Muhammad Ali","Huispaus","Jenni Vartiainen"],["Toimii kuin junan vessa","Kääntää veistä haavassa","Tuolta saapuu Charlie Brown"]],
    [ ["Meduusa","Jättiläinen","Pelikonsoli"], ["LEGO","Ihmemies MacGyver","Tuhkimo"],["Huokausten silta","Matti Nykänen","Noidankehä"]],
    [ ["Tennis","Lentokenttä","Hattu"], ["Catherine, Cambridgen herttuatar","Stairway to Heaven","Brigitte Bardot"],["Tex Willer","Agatha Christie","Sotavamma"]],
    [ ["Nyrkkeilijä","Vehnä","Kenttäpullo"], ["Katkarapu","Atlantis","Bob Marley"],["Menettää muistinsa","Munkkipossu","Pistin"]],
    [ ["Räkä","Aspiriini","Apina"], ["Fifty Shades of Grey","Alf","Villisika"],["Vapaapudotus","Ali Baba","Joutua huijatuksi"]],
    [ ["Aurinkolasit","Kastelukannu","Keiju"], ["Viidakkokirja","Albus Dumbledore","Lannoite"],["Viivi ja Wagner","Al Capone","Puhua kuuroille korville"]],
    [ ["Susi","Free Willy – Pelastakaa Willy","Iron Man"], ["Viittomakieli","Huulipuna","Juudas"],["Rosettan kivi","Pyhä Pietari","Heittää pyyhe kehään"]],
    [ ["Poliisi","Banaani","Pesä"], ["Mörkö","Sateenkaari","Luc Besson"],["Sokeiden valtakunnassa, yksisilmäinen on kuningas","Heittää lusikka nurkkaan","Kolme viisasta miestä"]],
    [ ["Hevonen","Luottokortti","Lentävä lautanen"], ["Kameleontti","Ydinpommi","Teippi"],["Puhumatta paras","Pojasta polvi paranee","Nauru pidentää ikää"]],
    [ ["Tee","Pokémon","MasterChef"], ["Lyijykynä","Luistin","Aavelaiva"],["The Truman Show","Slangi","Nukkumatti"]],
    [ ["Lennokki","Muumio","Linna"], ["Askarteluveitsi","Manaaja","Hiekkaeste"],["Siirtää vuoria","Vääpeli Körmy","Lassi ja Leevi"]],
    [ ["Jääpala","Strutsi","Avioliitto"], ["Wilhelm Tell","Hakemisto","Sfinksi"],["Vaahtokarkki","Kaasu pohjaan","Sinuhe Egyptiläinen"]],
    [ ["Ravintola","Tyyli","Luomi"], ["Proteesi","Hymiö","Jasper Pääkkönen"],["Resident Evil","Valtaistuinpeli","Vapaudenpatsas"]],
    [ ["Mikroskooppi","Vartija","Lentotukialus"], ["Komisario Palmu","Spede Pasanen","Pirates of the Caribbean"],["Tour de France","Urho Kekkonen","Lopussa kiitos seisoo"]],
    [ ["Orkesteri","Kirkko","Jouluvalot"], ["Höyrykone","Hammastahna","Helikopterikenttä"],["Poissa silmistä, poissa mielestä","E.T.","Tähän on koira haudattuna"]],
    [ ["Pelkokerroin","Nallekarhu","Harakka"], ["Vetoketju","Luomiväri","Hyttysverkko"],["Etuilla jonossa","Madame Tussaud","Maija Vilkkumaa"]],
    [ ["Ananas","Kananmuna","Postimies"], ["Puudeli","McDonald’s","Empire State Building"],["Ylpeys käy lankeemuksen edellä","Liisa ihmemaassa","Salamannopea"]],
    [ ["Grillaaminen","Salamurhaaja","Ampiainen"], ["Harlekiini","Samuli Edelman","Huuliharppu"],["Yrittänyttä ei laiteta","Kaataa bensaa liekkeihin","Ei savua ilman tulta"]],
    [ ["Tähdenlento","Kakku","Shampanja"], ["Saksikäsi-Edward","Haamujengi","Bridget Jones"],["Seinäruusu","Purukumi","Tieto lisää tuskaa"]],
    [ ["Kaivostyöläinen","Vankila","Mylly"], ["Uutisvuoto","Poseidon","Vihan hedelmät"],["Harmaa talous","Kohottaa malja","Helppo nakki"]],
    [ ["Mansikka","Ilotulitus","Palomies"], ["Bill Clinton","Pippurimylly","Hylje"],["Fidel Castro","Kääriä hihat","Die Hard"]],
    [ ["Ostos-TV","Puutarhaletku","Maantiekiitäjä"], ["Luuranko","Trampoliini","Vihreä maili"],["Tuntematon sotilas","Tuomioistuin","Jäähyväiset aseille"]],
    [ ["Turvatyyny","Kettu","Kiikarit"], ["Ilmatyynyalus","Prinsessa","Karate Kid"],["Kaksiteräinen miekka","Kaksin karkuteillä","Jim Carrey"]],
    [ ["Klovni","GPS","Korvarengas"], ["Pikku kakkonen","Kitara","Keinu"],["Häiritä jotakuta","Vahinko ei tule kello kaulassa","Toivossa on hyvä elää"]],
    [ ["Yökerho","Sammakko","Metsästäjä"], ["Transformersit","Strobovalo","Hammasharja"],["Tappaa aikaa","Nälkäpeli","Pidätellä hengitystään"]],
    [ ["Tiikeri","Kalastaja","Aurinkovarjo"], ["Sudoku","Muovailuvaha","Michael Jordan"],["Prinssi Rohkea","Pelastuspartio Bernard ja Bianca","Martin Luther King"]],
    [ ["Metro","Rannekello","Ihmissusi"], ["Seitsemän samuraita","Maatuskanuket","Lara Croft"],["Akilleen kantapää","Henkien kätkemä","Siinä paha missä mainitaan"]],
    [ ["Tietokone","Tuulimylly","Alumiinifolio"], ["Yksin kotona","Diablo","Majoneesi"],["Lotto","Clint Eastwood","Ruutuhyppy"]],
    [ ["Robotti","Meritähti","Jalkapallo"], ["Rautatie","Sokeainkirjoitus","Hevosenkenkä"],["Rio de Janeiro","Vitivalkoinen","Rahalla saa ja hevosella pääsee"]],
    [ ["Lompakko","Säilyketölkki","Timantti"], ["Ranta","Lakimies","Keksi"],["Oma apu, paras apu","Maasta se pienikin ponnistaa","Olipa kerran elämä"]],
    [ ["Aurinkorasva","Patsas","Koirankoppi"], ["Värisuora","Shrek","Sudenkorento"],["Kotini on linnani","Pyöritellä peukaloitaan","Afrikan tähti"]],
    [ ["Pingviini","Kirjasto","Lääkäri"], ["Roope-setä","Aspartaami","Voisarvi"],["Joka leikkiin ryhtyy, se leikin kestäköön","George W. Bush","Kerta kiellon päälle"]],
    [ ["Kurpitsa","Rintaliivit","Pantteri"], ["Sirukortti","Tarjoilja","Maija Poppanen"],["Se ei pelaa joka pelkää","Hätä keinon keksii","Marco Polo"]],
    [ ["Sopimus","Uuno Turhapuro","Tutka"], ["Kissanainen","Koala","Ruuti"],["Ystäväjoukko","Raha ei kasva puissa","Kun lehmät lentävät"]],
    [ ["Sähkötuoli","Tuulilasinpyyhin","Titanic"], ["Keilaaminen","Valkaisuaine","Stilettikorko"],["Justin Bieber","Tyhmä kuin saapas","Pyörtyä"]],
    [ ["Papukaija","Juomapilli","Eiffel-torni"], ["Ristisanatehtävä","Marilyn Manson","Dexter"],["Aarteeni","Puskea koiranputkea","Pääsiäissaari"]],
    [ ["Salatut elämät","Toy Story","Kirsikka"], ["Amor","The Artist","Kompassi"],["Irtisanoutua","Kiertää kuin kissa kuumaa puuroa","Ben-Hur"]],
    [ ["Riippuliidin","Hedelmämehu","Peräsin"], ["Sukkahousut","Jurassic Park","Giljotiini"],["Keskeyttää joku","Heittää kolikkoa","Hermione Granger"]],
    [ ["Maito","Sarvikuono","Yksisarvinen"], ["Maa on syntinen laulu","Mainos","Lance Armstrong"],["Vaatteet tekevät miehen","Paluu tulevaisuuteen","Vaikeneminen on kultaa"]],
    [ ["Vaaleanpunainen Pantteri","Arpakuutio","Simpsonit"], ["Lainahöyhenissä","Avain","Milon Venus"],["Tie helvettiin on kivetty hyvillä aikomuksilla","Rooman Colosseum","Vietnamin sota"]],
    [ ["Suojatie","Joulupukki","Panimo"], ["Miss Suomi","Talvisota","Matkalaukku"],["Ei nimi miestä pahenna","Kielletty kaupunki","Ei kannettu vesi kaivossa pysy"]],
    [ ["Saappaat","Sukellusvarusteet","Ferrari"], ["Vuokrasopimus","Topi ja Tessu","Liukuportaat"],["Käsi sydämellä","Kauppa se on joka kannattaa","Suomalaisuuden liitto"]],
    [ ["Ambulanssi","Ruisku","Pyjamat"], ["Magneetti","Valomiekka","Roskis"],["Se on mitä on","Ampua itseään jalkaan","Alcatraz"]],
    [ ["Pöytätennis","Hansikkaat","Paperileikkuri"], ["Oidipus","Asema","Keisarileikkaus"],["Tuonelan joutsen","Polttaa kuin korsteeni","Presidentinlinna"]],
    [ ["Kännykkä","Teleskooppi","Kirahvi"], ["Hannibal Lecter","Ruusun nimi","Leivänpaahdin"],["Huuliharppukostaja","Kaksihaarainen kieli","James Potkukelkka"]],
    [ ["Kotka","Auringonkukka","Keittiö"], ["Avara luonto","Terminaattori","Sirkus"],["Pihalla kuin lumiukko","Top Gun – Lentäjistä parhaat","Kloonaus"]],
    [ ["Pankki","Makuuhuone","Huilu"], ["Arkhimedes","Borat","Fast and Furious"],["Antaa vapaat kädet","Billy Jean","Heureka!"]],
    [ ["Kolmipyörä","Pihvi","Egypti"], ["Nunnia ja konnia","Vihellys","Täydelliset naiset"],["Purra hammasta","Sigmund Freud","Adam Sandler"]],
    [ ["Tuuletin","Kahvi","Helistin"], ["Twilight – Houkutus","Batman","Niilo Tarvajärvi"],["Kuva kertoo enemmän kuin tuhat sanaa","Kaktus kurkussa","Jean-Claude Van Damme"]],
    [ ["Dinosaurus","Moottorisaha","Smurffit"], ["Krokotiilimies","Aavejuna","Koskenlaskija"],["Pyytää jonkun kättä","Huumeiden salakuljetus","Satavuotinen sota"]],
    [ ["Pinaatti","Proomu","Perintö"], ["Tohtori Jekyll","Mooses","Jack Bauer"],["Jean Sibelius","Miehet jotka vihaavat naisia","Kaveria ei jätetä"]],
    [ ["Harry Potter","Järvi","Coca-Cola"], ["Puhelinlangat laulaa","Moottoritie on kuuma","Maksalaatikko"],["Pistää vaikka päänsä pantiksi","Mustasukkainen","Painajainen"]],
    [ ["Clash of Clans","Seiväshyppy","Trumpetti"], ["Sauna","Romeo ja Julia","Pisan kalteva torni"],["Nousta väärällä jalalla","Sukeltajantauti","Yksi pitää äidistä, toinen tyttärestä"]],
    [ ["Jääkarhu","Noita","Lumiukko"], ["Sibeliusmonumentti","Saippua","Patonki"],["Kuherruskuukausi","Sofien valinta","Katsoo kuin halpaa makkaraa"]],
    [ ["Höyhen","Kookospähkinä","Satama"], ["Laskuvarjo","Katapultti","Pyykkipoika"],["Ostoskärry","Sensuuri","Vierivä kivi ei sammaloidu"]],
    [ ["Jojo","101 dalmatialaista","Perhonen"], ["Wolverine","Kaunis elämä","Men in Black – Miehet mustissa"],["Salama ei iske kahdesti samaan paikkaan","Sammua kuin saunalyhty","Vanhempi ja viisaampi"]],
    [ ["Metsuri","Hyttynen","Mikroaaltouuni"], ["Elvis Presley","Pulp Fiction – Tarinoita väkivallasta","Voiveitsi"],["Pitää jalat visusti maassa","Kurkunleikkaajien saari","Nälänhätä"]],
    [ ["Jääkausi","Delfiini","Vesitorni"], ["Hiidenpata","Näppäimistö","Bruce Lee"],["Kremlin","Suku on pahin","Nätti kuin sika pienenä"]],
    [ ["Paavo Pesusieni","Mauste","Tarzan"], ["Tuulen viemää","Ocean’s Eleven","Viljaympyrä"],["Krapula","Sääli on sairautta","Ressu"]],
  ];
}

?>
