<?php
class ConceptCardsFR {
  static $cards = [
    [ ["Chalet","Pompier","Crabe"], ["Moustache","Phoque","Chargeur"],["Big Ben","Ne pas avoir froid aux yeux","La cerise sur le gâteau"]],
    [ ["Piano","Le monde de Nemo","Maya l’abeille"], ["Bowling for Columbine","La Planète des singes","Le vent nous portera"],["Piège de cristal","Chassez le naturel, il revient au galop","Le Muppet Show"]],
    [ ["Déguisement","Restaurant","Étoile filante"], ["Cœur de Pirate","Prothèse","Edward aux mains d’argent"],["Couleur menthe à l’eau","Resident Evil","Être fleur bleue"]],
    [ ["Ambulance","Parfum","Pie"], ["Aimant","Mimie Mathy","Moustiquaire"],["À la bonne franquette","Message subliminal","Nager dans le bonheur"]],
    [ ["Zèbre","Bureau","Mécanicien"], ["Xylophone","Barrage","Le Yéti"],["Avoir les quatre fers en l’air","Le Parfum de la dame en noir","Les Malheurs de Sophie"]],
    [ ["Natation","Tricycle","Chocolat"], ["Les Tortues Ninja","Sister Act","Capitaine Flam"],["Tourner sept fois sa langue dans sa bouche","Brûler un feu rouge","Jeter la première pierre à quelqu’un"]],
    [ ["Jeans","Masterchef","Hérisson"], ["Jukebox","Le Vaisseau Fantôme","Indiana Jones"],["Le marchand de sable","Jamais deux sans trois","Avoir les oreilles qui sifflent"]],
    [ ["Bûche de Noël","Cochon","Piscine"], ["Bande dessinée","Castor","OSS 117"],["Ce n’est pas la mer à boire","Œil de lynx","Tourner la page"]],
    [ ["Tracteur","Coca-Cola","Cantine"], ["Thermos","Casserole","Bob Marley"],["Cauchemar","Baïonnette","Fondre comme neige au soleil"]],
    [ ["Fusil","Girouette","Citrouille"], ["Furet","Guerre et Paix","Carte à puce"],["La foudre ne tombe jamais deux fois au même endroit","Grotte de Lascaux","Ça ne mange pas de pain"]],
    [ ["Les 101 Dalmatiens","Statue","Les Schtroumpfs"], ["La Vache et le Prisonnier","Shrek","La vache qui rit"],["Se tourner les pouces","La guerre de 100 ans","Charles Baudelaire"]],
    [ ["Couteau suisse","Ferrari","Vitamine"], ["Chantal Goya","Escalator","Vingt mille lieues sous les mers"],["Être tiré à quatre épingles","V pour Vendetta","Un chaud lapin"]],
    [ ["Vache","Kangourou","Télé-achat"], ["Trivial Pursuit","Karaoké","Squelette"],["Tant va la cruche à l’eau qu’à la fin elle se casse","Kid Paddle","Être plus rapide que l’éclair"]],
    [ ["Facteur","Rideaux","Bombe lacrymogène"], ["Empire State Building","Quidditch","Bagheera"],["Retourner le couteau dans la plaie","Avoir la tête dans les nuages","Avoir une faim de loup"]],
    [ ["Canadair","GPS","Caleçon"], ["Bilbon Sacquet","Guitare","Bernard l’hermite"],["Heureux au jeu, malheureux en amour","Avoir un trou de mémoire","Caractère de cochon"]],
    [ ["Cloche","Hochet","Une boîte de nuit"], ["Casino Royale","Jacques Martin","Transformers"],["Jean-Claude Van Damme","Tuer le temps","L’étrange Noël de Monsieur Jack"]],
    [ ["La Petite Maison dans la prairie","Guirlande électrique","Plaque d’immatriculation"], ["La fée Clochette","Héliport","Pamela Anderson"],["On ne fait pas d’omelette sans casser des œufs","Il y a anguille sous roche","Faut pas pousser mémé dans les orties"]],
    [ ["Fourchette","Épée","Tirelire"], ["Forrest Gump","Jamel Debouzze","Taille-crayon"],["Enterrer la hache de guerre","Tire-bouchon","Avoir le pied marin"]],
    [ ["Brique","Banque","Sorcière"], ["Baloo","Archimède","Savon"],["Avoir carte blanche","Se mélanger les pinceaux","Parler dans sa barbe"]],
    [ ["Poisson","Avion de chasse","Jus de fruits"], ["Pâte à modeler","Aquarelle","Jurassic Park"],["Armé jusqu’aux dents","Jouer à pile ou face","Un roman à l’eau de rose"]],
    [ ["Véranda","Gouvernail","Soucoupe volante"], ["Vaccin","Guillotine","Scotch"],["Hermione Granger","Se mettre sur son 31","Les Chevaliers du Zodiaque"]],
    [ ["Montre","Abeille","Puits"], ["Les Poupées russes","2001 : l’Odyssée de l’espace","Post-it"],["Pisser dans un violon","Poser un lapin","Bénabar"]],
    [ ["Chaise électrique","Pingouin","Deltaplane"], ["Bowling","Oncle Picsou","Collant"],["Nicolas Sarkozy","Couper la parole","Noyer le poisson"]],
    [ ["Pinocchio","Génie","Mineur"], ["Orange mécanique","Gladiateur","Les grosses têtes"],["Spartacus","Le travail au noir","Skyfall"]],
    [ ["Tapis","Thé","Zorro"], ["Snowboard","Stylo","Zelda"],["The Truman show","Ne dormir que d’un œil","Les 7 boules de cristal"]],
    [ ["Piment","Monopoly","Lait"], ["Ocean’s Eleven","Les Oiseaux","La Guerre du feu"],["La bave du crapaud n’atteint pas la blanche colombe","Six feet under","Gaston Lagaffe"]],
    [ ["Stéthoscope","Gardien","Titanic"], ["Silicone","Gérard Jugnot","Talon aiguille"],["Tomber dans les pommes","Tribunal","Battre le fer tant qu’il est chaud"]],
    [ ["Tuyau d’arrosage","Casque","Le Père Noël"], ["Trampoline","Bouchon","La Révolution française"],["La parole est d’argent, mais le silence est d’or","La Cité interdite","Nager entre deux eaux"]],
    [ ["Pilote","Pyjama","Licorne"], ["Neil Armstrong","Poubelle","Harmonica"],["Se ressembler comme deux gouttes d’eau","La prison d’Alcatraz","Il n’y a pas le feu au lac"]],
    [ ["Guêpe","Autruche","Sous-marin"], ["Lance Armstrong","Annuaire","Serge Gainsbourg"],["Appuyer sur le champignon","Fight Club","Tous les goûts sont dans la nature"]],
    [ ["Fusée","Trompette","Paratonnerre"], ["Frites","Tour de Pise","Microphone"],["Masque","Démissionner","Déplacer des montagnes"]],
    [ ["Dr House","Drone","Ours en peluche"], ["Cupidon","Cutter","Maquillage"],["Madame Tussauds","Al Capone","Se rincer l’œil"]],
    [ ["Arrosoir","Soutien-gorge","Réfrigérateur"], ["Albus Dumbledore","Serveuse","Power Rangers"],["Rain Man","Malheureux comme les pierres","L’île de Pâques"]],
    [ ["Pacman","La Tour Eiffel","Scorpion"], ["Margaret Thatcher","La grande muraille","Rugby"],["Sauter du coq à l’âne","Chat échaudé craint l’eau froide","Fidel Castro"]],
    [ ["Crème solaire","Fraise","Pêcheur"], ["Chasse d’eau","François Mitterrand","Mister Bean"],["Mettre du beurre dans les épinards","Avoir des sueurs froides","Porter un toast"]],
    [ ["Blanche-Neige et les Sept Nains","Prison","Porte-avions"], ["Astérix et Obélix","Poséidon","Pirates des Caraïbes"],["Piquer un fard","Un chèque en bois","Les mains moites"]],
    [ ["Vampire","Musée","Camion"], ["Troll","Les Sims","Bière"],["Avoir une cervelle de moineau","Gad Elmaleh","Clouer le bec"]],
    [ ["Garage","Dauphin","Égypte"], ["Géant Vert","Clavier","Desperate Housewives"],["Élie Semoun","Passer l’arme à gauche","Dormir sur ses deux oreilles"]],
    [ ["Policier","École","Pirate"], ["Père Fouettard","Daniel Balavoine","Orgue"],["Œil au beurre noir","Avoir le vertige","Censure"]],
    [ ["Briquet","Compas","Aigle"], ["Bambi","Catapulte","30 millions d’amis"],["À bout de souffle","Être bête comme ses pieds","Le Bon, la Brute et le Truand"]],
    [ ["Essuie-glace","Maîtresse d’école","GSM"], ["Eau de Javel","Le Rouge et le Noir","Hannibal Lecter"],["Il était une fois dans l’Ouest","Youri Gagarine","J’en mettrais ma main au feu"]],
    [ ["Harpon","Harry Potter","Pot de fleurs"], ["Hula-hoop","Il est 5 h, Paris s’éveille","Plate-forme pétrolière"],["Plus on est de fous, plus on rit","Être sourd comme un pot","L’enfer est pavé de bonnes intentions"]],
    [ ["Fée","La Panthère Rose","Moulin"], ["Engrais","La Cage aux folles","Les Raisins de la colère"],["Les doigts dans le nez","Banc solaire","Décapsuleur"]],
    [ ["Cars","Dictionnaire","Steak"], ["Boîte aux lettres","Croc-Blanc","Sifflet"],["Sigmund Freud","Vendre son âme au diable","Faire une queue de poisson"]],
    [ ["Volcan","Fort Boyard","Dinosaure"], ["Whisky","Fermeture Éclair","Crocodile Dundee"],["Demander la main de quelqu’un","Être lent comme un escargot","Canaliser sa colère"]],
    [ ["Extincteur","Clignotant","Vendredi 13"], ["Elton John","Carte postale","Tupperware"],["Un moulin à paroles","Roseau","Alimenter un débat"]],
    [ ["Saint-Valentin","Assassin","Montagne"], ["Robin des Bois","Amy Winehouse","Les Piliers de la terre"],["Les 7 Merveilles du monde","Cercle d’amis","Mon précieux"]],
    [ ["Concorde","Perroquet","Tarzan"], ["Catwoman","Mots-croisés","Sonnette"],["Snoopy","Manger les pissenlits par la racine","La Bicyclette bleue"]],
    [ ["Paille","Le Marsupilami","Épinard"], ["Marilyn Manson","La ligne verte","Docteur Jekyll"],["Esmeralda","Aspirateur","The Avengers"]],
    [ ["Baleine","Tetris","Œuf"], ["Arbalète","Stonehenge","Mac Donald"],["Lewis Carroll","Rompre le silence","Bison Futé"]],
    [ ["Rubik’s Cube","Champagne","Console de jeux"], ["Reine","Bridget Jones","Cendrillon"],["Cercle vicieux","Kiwi","Confesser ses péchés"]],
    [ ["Klaxon","Défibrillateur","Sombrero"], ["Kill Bill","Code-barres","Saucisse"],["Se jeter à l’eau","Largo Winch","Le Colisée"]],
    [ ["Machine à coudre","Dé","Chambre"], ["Le Petit Poucet","Clef","Brice de Nice"],["Billy Jean","Une levée de boucliers","Casser les pieds à quelqu’un"]],
    [ ["Vigneron","Clown","Loup-garou"], ["Valise","Casper","Lara Croft"],["Un petit dessin vaut mieux qu’un long discours","La politique de l’autruche","Tenir la chandelle"]],
    [ ["Tempête","Parasol","Ventilateur"], ["Station spatiale","Michael Jordan","Twilight"],["Martin Luther King","Rouler une pelle","Dormir en chien de fusil"]],
    [ ["Sapin","Écluse","Boîte de conserve"], ["Rollers","Dalaï Lama","Avocat"],["Avoir la puce à l’oreille","Voleur","Boule et Bill"]],
    [ ["Yoda","Château fort","Éclipse"], ["Woody Allen","Bunker","D’Artagnan"],["Donner de la confiture aux cochons","Inception","Clonage"]],
    [ ["Gymnase","Cuisine","Lac"], ["Hirondelle","Cirque","La guerre des boutons"],["La cinquième roue du carrosse","De la terre à la lune","Famine"]],
    [ ["Diamant","Four micro-ondes","Cadran solaire"], ["Cookies","Fil à couper le beurre","Bâteau à vapeur"],["Avoir mauvaise conscience","Trafic de drogue","Ben-Hur"]],
    [ ["Tronçonneuse","Cerise","Bibliothèque"], ["Train-fantôme","Boussole","Aspartame"],["Avoir des fourmis dans les jambes","Les Liaisons dangereuses","C’est clair comme de l’eau de roche"]],
    [ ["Moustique","Cinéma","Loup"], ["Les Rivières pourpres","Capitaine Haddock","Langue des signes"],["La pierre de Rosette","La Petite Fille aux allumettes","Bruit de couloir"]],
    [ ["Lion","Cheval","Perceuse"], ["Lance-pierre","Caméléon","Monsieur Patate"],["Mon petit doigt m’a dit","Ouvrir la boîte de Pandore","Ali Baba"]],
    [ ["Plombier","Aspirine","Iron Man"], ["Papier toilette","Alf","Judas"],["Jeter l’éponge","Chute libre","Une main de fer dans un gant de velours"]],
    [ ["Crotte de nez","Vin","Taupe"], ["Cinquante nuances de Grey","Velcro","Sophie Marceau"],["Statue de la Liberté","Mendiante","Ne pas avoir les yeux en face des trous"]],
    [ ["Parcmètre","Ping-pong","Tigre"], ["Mike Tyson","Œdipe","Sudoku"],["Thorgal","Démarrer sur les chapeaux de roue","Bain de pieds"]],
    [ ["Docteur","Canari","Masque à gaz"], ["Croissant","Billy the Kid","Le téléphone pleure"],["Le Journal du dimanche","Danseuse étoile","Hunger Games"]],
    [ ["Dentier","Grenouille","Marguerite"], ["Comptable","Gyrophare","Le Seigneur des anneaux"],["Le Cercle des poètes disparus","Marco Polo","Chapelle Sixtine"]],
    [ ["Panthère","Coupe papier","Magicien"], ["Mary Poppins","Césarienne","Le Petit Prince"],["Lavage de cerveau","Vivre à cent à l’heure","Les Mystérieuses Cités d’or"]],
    [ ["Yo-yo","Niche","Nid"], ["Wolverine","Libellule","Luc Besson"],["Les Rois mages","Loana","Être tête en l’air"]],
    [ ["Ogre","Fenêtre","Taureau"], ["MacGyver","Épingle à nourrice","Spirou"],["La statue du Christ Rédempteur","La marelle","Avoir des doigts de fée"]],
    [ ["Papier aluminium","Barbie","Échelle"], ["Mayonnaise","Ascenseur","Cyrano de Bergerac"],["Détective","Avoir l’eau à la bouche","Mouiller sa chemise"]],
    [ ["Blé","Barbecue","Ange"], ["Atlantide","Arlequin","Albator"],["À la recherche du temps perdu","Pierre qui roule n’amasse pas mousse","Avoir de l’eau dans les caves"]],
    [ ["Port","Pétard","Hôtel"], ["Pince à linge","Moulin à poivre","Jacuzzi"],["Jean-Marie Bigard","Le Tour de France","L’argent ne pousse pas sur les arbres"]],
    [ ["Microscope","L’Homme invisible","Cave"], ["Les Bronzés font du ski","Koala","Bouillotte"],["Battre un record","Avoir un chat dans la gorge","Muet comme une carpe"]],
    [ ["Café","Peter Pan","Radar"], ["Batman","Mourir pour des idées","Poudre à canon"],["Parler français comme une vache espagnole","Quand les poules auront des dents","Loterie"]],
    [ ["Ordinateur","Pokémon","Chewing-gum"], ["Maman, j’ai raté l’avion","Patins à glace","Caniche"],["Bruit qui court","L’Élève Ducobu","Robinson Crusoé"]],
    [ ["La Momie","Roue","Pomme"], ["L’Exorciste","Rat","Phare"],["Perdre son sang froid","À double tranchant","Un homme averti en vaut deux"]],
    [ ["Airbag","Vélo","Escargot"], ["Aéroglisseur","Tsunami","Dumbo"],["Esprits criminels","Tomber des cordes","Être blanc comme neige"]],
    [ ["Tondeuse","Étoile de mer","Avatar"], ["Tandem","Écriture braille","Aphrodite"],["Après la pluie, le beau temps","Briser le cœur","Se faire rouler dans la farine"]],
    [ ["Chauve-souris","Singe","Espadon"], ["Cafard","Sanglier","Dynamite"],["Être au septième ciel","Faire couler beaucoup d’encre","Lune de miel"]],
    [ ["Football","Ours blanc","Gâteau"], ["Fer à cheval","Manneken-Pis","Ghostbusters"],["Gomme","Mariage pluvieux, mariage heureux","Avoir le cœur gros"]],
    [ ["Papillon","Bonhomme de neige","Parapluie"], ["Men in Black","Baguette","Mère Teresa"],["Mars Attacks !","Christophe Dechavanne","Bégayer"]],
    [ ["Crocodile","Cerf-volant","Héritage"], ["Cible","Boulanger","Jack Bauer"],["Je suis ton père","Ombre chinoise","Les Tuniques Bleues"]],
    [ ["Planeur","Ninja","DVD"], ["Palmier","Lucky Luke","Cycliste"],["Descendre en flammes","Se lever du pied gauche","Démocratie"]],
    [ ["Sonic","Dragon","Vautour"], ["Sauna","Cure-dent","Trou noir"],["Un grain de beauté","Le Pont des Soupirs","Bloquer sa respiration"]],
    [ ["Méduse","Chasseur","Métro"], ["Lego","Brosse à dents","Les 7 Samouraïs"],["Le talon d’Achille","Grenouille de bénitier","Jeux de mains, jeux de vilains"]],
    [ ["Girafe","Jour férié","Yaourt"], ["Grille-pain","Julia Roberts","Winnie l’ourson"],["Ventouse à toilette","Le siècle des Lumières","Le Cinquième Élément"]],
    [ ["Météorite","Maison de retraite","Baignoire"], ["Lentilles de contact","Le plat pays","Araignée"],["Arrondir les angles","Avoir le compas dans l’œil","Blessure de guerre"]],
    [ ["Boucle d’oreille","Chapeau","Chemise"], ["Balançoire","Brigitte Bardot","Calculatrice"],["Broyer du noir","Boire la tasse","Avoir un poil dans la main"]],
    [ ["Château d’eau","Cahier","Éolienne"], ["Bruce Lee","Batterie","Diablo"],["Ennio Morricone","Jean-Pierre Pernaut","Jim Carrey"]],
    [ ["Imprimerie","Jumelles","Mariage"], ["John Lennon","Jumanji","Le Sphinx"],["Le Club des Cinq","Ranimer la flamme","Loin des yeux, loin du cœur"]],
    [ ["Requin","Orchestre","L’Âge de glace"], ["Prison break","Machine à vapeur","Kirikou"],["Le Kremlin","Eurêka !","Popeye"]],
    [ ["Flûte","Prise électrique","Autoradio"], ["Fast and Furious","Pop-corn","Angry Birds"],["American Beauty","Mettre les pieds dans le plat","Millénium"]],
    [ ["Pelle","Péniche","Robot"], ["Mohamed Ali","Moïse","Rails de chemin de fer"],["Rio de Janeiro","Le Trône de fer","Bâtir un empire"]],
    [ ["Mode","Carte de crédit","Lunettes de soleil"], ["Les Lettres de mon moulin","Bombe atomique","Le Livre de la jungle"],["Lanfeust de Troy","La tour de Babel","E.T. l’extra-terrestre"]],
    [ ["Loupe","Église","Bottes"], ["Lassie","Dentifrice","Bail"],["Avoir le cœur sur la main","Mettre de l’eau dans son vin","Se regarder le nombril"]],
    [ ["Passage piéton","Souris","Canard"], ["Miss France","Seau","Billard"],["Avoir une fièvre de cheval","Le panier de la ménagère","Jean-Paul Belmondo"]],
    [ ["Plume","Igloo","Bûcheron"], ["Parachute","Jeanne d’Arc","Barbara"],["Avoir les pieds sur terre","Les dieux sont tombés sur la tête","Dragon Ball Z"]],
    [ ["Mouche","Écureuil","Serpent"], ["Les Quatre filles du docteur March","David Guetta","Saint Graal"],["Se faire des cheveux blancs","Tex Avery","Laïka"]],
    [ ["Tennis","Luge","Les Simpsons"], ["Stéphanie de Monaco","Le Grand Bleu","La Vénus de Milo"],["La guerre du Viêt Nam","À fleur de peau","La Folie des grandeurs"]],
    [ ["Aladdin","Lecteur MP3","Bob l’éponge"], ["Agriculteur","La Roue de la fortune","Autant en emporte le vent"],["Avoir la gueule de bois","Eminem","Saint Pierre"]],
    [ ["Éléphant","Sauvez Willy","Cheminée"], ["Destination finale","Rouge à lèvres","Cafetière"],["Brosse à cheveux","Tina Turner","Le crime de l’Orient-Express"]],
    [ ["Tipi","Aéroport","Coquillage"], ["Sushi","Trois nuits par semaine","Cerf"],["Chercher une aiguille dans une botte de foin","Cessez-le-feu","Rex, chien flic"]],
    [ ["Rivière","Renard","Saut à la perche"], ["Radiateur","Princesse","Roméo et Juliette"],["Scier la branche sur laquelle on est assis","Raiponce","Sabrer le champagne"]],
    [ ["Crêpes","Lunette infrarouge","Grenier"], ["Chemin","Sabre laser","Gustave Eiffel"],["Hippocampe","Les Visiteurs","Langue de vipère"]],
    [ ["Nutella","Seringue","Glaçon"], ["Lunette de toilette","Le Nom de la rose","Guillaume Tell"],["Guimauve","Jeter l’argent par les fenêtres","Fumer comme un pompier"]],
    [ ["iPad","Gants","Dépanneuse"], ["Jonathan Livingston le goéland","Gare","Concombre"],["David contre Goliath","Tourner autour du pot","Saisonnier"]],
    [ ["Toy Story","Scaphandre","Minecraft"], ["The Artist","Rox et Rouky","Les Dents de la mer"],["Le Tour du monde en 80 jours","Rouler des mécaniques","Retour vers le futur"]],
    [ ["Salade","Rhinocéros","Tournesol"], ["Rocky","Publicité","Terminator"],["Au royaume des aveugles, les borgnes sont rois","Top Gun","En avoir le cœur net"]],
    [ ["Elfe","Banane","Portefeuille"], ["Diable","Arc-en-ciel","Plage"],["Piquer une tête","Myope comme une taupe","Mère poule"]],
  ];

}

?>
