<?php
class ConceptCardsPL {
  static $cards = [
    [ ["Pszczoła","Lotnisko","Orzeł"], ["Odyseja kosmiczna","Dolewać oliwy do ognia","Animal Planet"],["Kręcić się w kółko","Entliczek pentliczek","Nóż w wodzie"]],
    [ ["Poduszka powietrzna","Aladyn","Karetka"], ["Poduszkowiec","Rolnik","Magnes"],["Miecz obosieczny","Zaraz mnie szlag trafi","Jest jak jest"]],
    [ ["Anioł","Konewka","Aspiryna"], ["Kapitan Hak","Albus Dumbledore","Alf"],["Poszukiwacze Zaginionej Arki","Al Capone","Ali Baba"]],
    [ ["Zabójca","Radio samochodowe","Struś"], ["Madonna","Angry Birds","Książka telefoniczna"],["Zawsze tam gdzie ty","Braveheart","Gaz do dechy"]],
    [ ["Awatar","Myśliwiec","Wanna"], ["Afrodyta","Akwarele","Pająk"],["Nie ma tego złego, co by na dobre nie wyszło","Uzbrojony po zęby","Spotkać się w pół drogi"]],
    [ ["Wieloryb","Banan","Bank"], ["Kusza","Tęcza","Archimedes"],["Za siedmioma górami, za siedmioma lasami","Dać komuś wolną rękę","Rybaczki"]],
    [ ["Grill","Barbie","Biblioteka"], ["Mim","Winda","Słodzik"],["W królestwie ślepców jednooki królem","Zwinny jak małpa","Siedzieć jak na szpilkach"]],
    [ ["Królewna Śnieżka i siedmiu krasnoludków","Pszenica","Myszka Miki"], ["Asteriks i Obeliks","Atlantyda","Przeminęło z wiatrem"],["Oblać się zimnym potem","Ślinka cieknie","Kac"]],
    [ ["Puszka","Gaz pieprzowy","Bałwan"], ["Prawnik","Janosik","Bagietka"],["Czuć pismo nosem","Z głową w chmurach","Leżeć na żołądku"]],
    [ ["Buty","Kolczyk","Cegła"], ["Dzierżawa","Huśtawka","Miś Uszatek"],["Mieć serce na dłoni","Mieć wyczucie","Wziąć się w garść"]],
    [ ["Zapalniczka","Makowiec","Drwal"], ["Bambi","Komiks","Anna Jantar"],["Lęk wysokości","Pieką mnie uszy","Stąpać twardo po ziemi"]],
    [ ["Biuro","Zegar słoneczny","Kawa"], ["Tama","Parowiec","Batman"],["Dać nurka","Mieć nieczyste sumienie","Mieć muchy w nosie"]],
    [ ["Notatnik","Bokser","Ciężarówka"], ["Bateria","Krab pustelnik","Piwo"],["Wymigiwać się od pracy","Mieć lukę w pamięci","Roztrzepany"]],
    [ ["Helikopter gaśniczy","Kaczka","Kanarek"], ["Bilbo Baggins","Bilard","Baba Jaga"],["Głodny jak wilk","Wysoka gorączka","Miednica"]],
    [ ["Stołówka","Riksza","Karta kredytowa"], ["Bob Marley","Skrzynka pocztowa","Bomba atomowa"],["Bagnet","Leżak do opalania","Budować imperium"]],
    [ ["Kask","Piwnica","Latawiec"], ["Wtyczka","Termofor","Piekarz"],["Kuć żelazo póki gorące","Pobić rekord","Jąkać się"]],
    [ ["Wiśnia","Krzesło elektryczne","Domek letniskowy"], ["Kompas","Kręgle","Ania z Zielonego Wzgórza"],["Ben Hur","Justin Bieber","Big Ben"]],
    [ ["Sypialnia","Szampan","Kapelusz"], ["Diabeł","Bridget Jones","Brigitte Bardot"],["Michael Jackson","Podejdź no do płota","Rany wojenne"]],
    [ ["Myśliwy","Wieża ciśnień","Zamek"], ["Szczoteczka do zębów","Bruce Lee","Bunkier"],["Wstrzymać oddech","Wleciało nie w tę dziurkę","Kajko i Kokosz"]],
    [ ["Nietoperz","Komin","Koszula"], ["Karaluch","Dzbanek do kawy","Kalkulator"],["Złamać komuś serce","Szczotka do włosów","Zamartwiać się"]],
    [ ["Koń","Guma do żucia","Czekolada"], ["Kameleon","Pudel","Pszczółka Maja"],["Przejechać na czerwonym świetle","Ploteczki","Luźna pogawędka"]],
    [ ["Kino","Dynia","Kierunkowskaz"], ["Czterdziestolatek","Karta magnetyczna","Pocztówka"],["Czysty jak łza","To nic nie kosztuje","Dać upust złości"]],
    [ ["Dzwonek","Klaun","Coca - Cola"], ["James Bond","Duszek Kacper","Zapiekanka"],["Uparty jak osioł","Zawracać komuś głowę","Koszmar"]],
    [ ["Świnia","Kompas","Motolotnia"], ["Bóbr","Katapulta","Kobieta-kot"],["To nie koniec świata","Cenzura","Zgrana paczka"]],
    [ ["Konsola do gier","Muszla","Nożyczki"], ["Kopciuszek","Sarna","Cesarskie cięcie"],["Błędne koło","Zawieszenie broni","Kaplica Sykstyńska"]],
    [ ["Scyzoryk szwajcarski","Krab","Filtr przeciwsłoneczny"], ["Beyonce","Magazynek","Spłuczka"],["Czym skorupka za młodu nasiąknie, tym na starość trąci","Witold Gombrowicz","Dmuchać na zimne"]],
    [ ["Naleśnik","Krokodyl","Gile z nosa"], ["Ścieżka","Cel","Pięćdziesiąt twarzy Greya"],["Szukać igły w stogu siana","Krzysztof Ibisz","Swobodne spadanie"]],
    [ ["Kuchnia","Delfin","Kości do gry"], ["Cyrk","Klawiatura","Klucz"],["Klonowanie","Kogoś zamurowało","Koloseum"]],
    [ ["Defibrylator","Przebranie","Paralotnia"], ["Kod paskowy","Natalia Kukulska","Rajstopy"],["Wyznać grzechy","Orła cień","Przerwać komuś"]],
    [ ["Sztuczna szczęka","Laweta","Diament"], ["Księgowa","Ogórek","Ciasteczko"],["Myśleć o niebieskich migdałach","Primabalerina","Dawid i Goliat"]],
    [ ["Słownik","Dinozaur","Lekarz"], ["Biały kieł","Bazyliszek","Francuski rogalik"],["Otwieracz do butelek","Poprosić kogoś o rękę","Ruszyć z kopyta"]],
    [ ["Dr House","Smok","Truteń"], ["Amor","Wykałaczka","Nożyk do tapet"],["Złożyć dymisję","Demokracja","Przenosić góry"]],
    [ ["DVD","Drabina","Zaćmienie"], ["Rowerzysta","Kamil Stoch","D’Artagnan"],["Lec w gruzach","Gwiezdne wojny","Perły przed wieprze"]],
    [ ["Zamek w drzwiach","Szkoła","Wiewiórka"], ["Dalajlama","Krzysztof Krawczyk","Pasta do zębów"],["Zwinięty w kłębek","Spać jak niemowlę","Dragon Ball"]],
    [ ["Kościół","Egipt","Słoń"], ["Shakira","Gotowe na wszystko","Oszukać przeznaczenie"],["E.T.","Adam Małysz","Eminem"]],
    [ ["Elf","Wiatrak","Miecz"], ["Borat","Diablo","Kuba Wojewódzki"],["Wiedzieć, czego się spodziewać","Clint Eastwood","Zakopać topór wojenny"]],
    [ ["Szpinak","Ślimak","Ryba piła"], ["Dr Jekyll","Słoń Dumbo","Dynamit"],["Moda na sukces","Zabójcze umysły","Być w siódmym niebie"]],
    [ ["Wycieraczki","Rozgwiazda","Spadająca gwiazda"], ["Wybielacz","Alfabet Braille’a","Edward Nożycoręki"],["Głupi jak but","Biały jak śnieg","Odludek"]],
    [ ["Gaśnica","Listonosz","Wróżka"], ["Elton John","Pałac Kultury i Nauki","Nawóz"],["Ślimacze tempo","Szybki jak błyskawica","Głuchy jak pień"]],
    [ ["Okno","Ferrari","Flet"], ["Agrafka","Ruchome schody","Szybcy i wściekli"],["Roztargniony","Zrobić się na bóstwo","Eureka!"]],
    [ ["Piłka nożna","Familiada","Kuchenka mikrofalowa"], ["Podkowa","Zamek błyskawiczny","Nóż do masła"],["Być w centrum uwagi","Wepchnąć się w kolejkę","Głód"]],
    [ ["Widelec","Truskawka","Rakieta"], ["Forrest Gump","Lech Wałęsa","Frytki"],["Znać swoje granice","Fidel Castro","Podziemny krąg"]],
    [ ["Pistolet","Rękawiczki","Garaż"], ["Fretka","Stacja","Czarnoksiężnik z Krainy Oz"],["Rozpłynąć się w powietrzu","Kopcić jak lokomotywa","Szymon Majewski"]],
    [ ["Strażnik","Ciasto","Geniusz"], ["Andrzej Wajda","Pogromcy duchów","Gladiator"],["Bigos","Guma do żucia","Góra Kościuszki"]],
    [ ["Żyrafa","Drogowskaz","Kostka lodu"], ["Toster","Wojna i pokój","Wilhelm Tell"],["Moherowy beret","Jaskinie w Lascaux","Ptasie mleczko"]],
    [ ["Ster","GPS","Strych"], ["Gilotyna","Święto państwowe","Maria Konopnicka"],["Kto nie ma szczęścia w kartach, ten ma szczęście w miłości","Hermiona Granger","Konik morski"]],
    [ ["Żaba","Telefon komórkowy","Osa"], ["Stroboskop","Hannibal Lecter","Harmonijka ustna"],["Pewnego razu na dzikim zachodzie","Igrzyska śmierci","Nie ma dymu bez ognia"]],
    [ ["Lampki na choinkę","Sala gimnastyczna","Harpun"], ["Lądowisko dla helikopterów","Jaskółka","Hula hop"],["Coś tu śmierdzi","Incepcja","Jurij Gagarin"]],
    [ ["Harry Potter","Jeż","Testament"], ["Wsiąść do pociągu byle jakiego","Indiana Jones","Porucznik Borewicz"],["Ręczyć głową","Nieszczęścia chodzą parami","Luke, jestem twoim ojcem."]],
    [ ["Grzechotka","Hotel","Igloo"], ["Karol Strasburger","Jacuzzi","Joanna d’Arc"],["Jean-Claude Van Damme","Bohdan Smoleń","Michał Żebrowski"]],
    [ ["Drukarka","iPad","Iron Man"], ["John Lennon","Kod Leonarda da Vinci","Judasz"],["Tomasz Lis","Wyrzucać pieniądze w błoto","Rzucić ręcznik"]],
    [ ["Dżinsy","Gitara","Lornetka"], ["Szafa grająca","Julia Roberts","Pulp Fiction"],["Niech pierwszy rzuci kamieniem","Mężczyźni są jak dzieci","Jim Carrey"]],
    [ ["Sok owocowy","Kangur","Róg"], ["Park jurajski","Karaoke","Kill Bill"],["Rzucić monetą","Rysunki Mleczki","Owoc kiwi"]],
    [ ["Epoka lodowcowa","Wywiad z wampirem","Mumia"], ["Zaczarowany ołówek","Miś koala","Egzorcysta"],["Kreml","Pieniądze nie leżą na ulicy","Cezary Pazura"]],
    [ ["Różowa Pantera","Domek na prerii","Wieża Eiffla"], ["Testosteron","Dzwoneczek","Dexter"],["Piekło jest wybrukowane dobrymi chęciami","Ojciec Chrzestny","Wyspa Wielkanocna"]],
    [ ["Jezioro","Mleko","Struś Pędziwiatr"], ["Wypijmy za błędy","Walka o ogień","Zielona mila"],["Kto pod kim dołki kopie, ten sam w nie wpada","Ziemia obiecana","Polewa lukrowa"]],
    [ ["Gdzie jest Nemo?","Święty Mikołaj","Odtwarzacz mp3"], ["Planeta małp","Francuska rewolucja","Koło fortuny"],["Spływa po kimś jak po kaczce","Zakazane Miasto","Mania wielkości"]],
    [ ["101 Dalmatyńczyków","Smerfy","Simpsonowie"], ["Życie jest piękne","Twarożek","Wenus z Milo"],["Piorun nigdy nie uderza dwa razy w to samo miejsce","Wojna stuletnia","Wojna w Wietnamie"]],
    [ ["Jednorożec","Lew","Wilk"], ["Lance Armstrong","Proca","Język migowy"],["Milczenie jest złotem","Dziewczynka z zapałkami","Kamień z Rosetty"]],
    [ ["Wilkołak","Szkło powiększające","Sanki"], ["Lara Croft","Lassie","Jesteś Bogiem"],["Chować głowę w piasek","Wieża Babel","Pies Łajka"]],
    [ ["Okulary przeciwsłoneczne","Teleskop","Maszyna do szycia"], ["Księga dżungli","Imię róży","Tomcio Paluch"],["South Park","Rozwidlony język","Bill Gates"]],
    [ ["Magik","Dom starców","Nauczyciel"], ["Mały książę","Bo do tanga trzeba dwojga","Chłopi"],["Pranie mózgu","Piąty Element","Dobry, zły i brzydki"]],
    [ ["Stokrotka","Małżeństwo","Maska gazowa"], ["Władca Pierścieni","Sfinks","Wisieć na telefonie"],["Stowarzyszenie umarłych poetów","Muminki","Tygodnik"]],
    [ ["MasterChef","Kaczor Donald","Mechanik"], ["Statek widmo","Słodkiego miłego życia","Yeti"],["Conan Barbarzyńca","Muppety","Brunet wieczorową porą"]],
    [ ["Meduza","Meteoryt","Metro"], ["Klocki LEGO","Soczewki kontaktowe","Siedmiu samurajów"],["Most Westchnień","Wiek Oświecenia","Pięta achillesowa"]],
    [ ["Mikroskop","Minecraft","Górnik"], ["Pretty Woman","Szczęki","Jeden z dziesięciu"],["Formuła 1","W 80 dni dookoła świata","Praca na czarno"]],
    [ ["Styl","Monopol","Góra"], ["Dziady","Ptaki","Filary ziemi"],["Gra o Tron","Upadły rycerz","Siedem cudów świata"]],
    [ ["Zegarek","Mucha","Młyn"], ["Człowiek z marmuru","Pan Samochodzik","Akademia Pana Kleksa"],["Czarodziejki z Księżyca","W pustyni i w puszczy","Bułka z masłem"]],
    [ ["Komar","Muzeum","Pływanie"], ["Święty","Simsy","Wojownicze Żółwie Ninja"],["Niebezpieczne związki","Spocone dłonie","Duma i uprzedzenie"]],
    [ ["Psia buda","Gniazdo","Ninja"], ["Ważka","Quentin Tarantino","Lucky Luke"],["Tajemnicze złote miasta","Trzech mędrców ze wschodu","Bolek i Lolek"]],
    [ ["Nutella","Jajko","Ogr"], ["Deska klozetowa","McDonald’s","MacGyver"],["Flinstonowie","Lewis Carroll","Piotr Fronczewski"]],
    [ ["Orkiestra","Komputer","Niedźwiedź polarny"], ["Silnik parowy","Kevin sam w domu","Zamek w Malborku"],["Co z oczu, to z serca","Loteria","Miesiąc miodowy"]],
    [ ["Pluszowy miś","Pac-Man","Słoma"], ["Makijaż","Margaret Thatcher","Marilyn Manson"],["Biednemu zawsze wiatr w oczy","Muzeum figur woskowych","Wąchać kwiatki od spodu"]],
    [ ["Puma","Folia aluminiowa","Motyl"], ["Calineczka","Majonez","Faceci w czerni"],["Marco Polo","Gra w klasy","Zmądrzeć na stare lata"]],
    [ ["Parasolka","Parasol przeciwsłoneczny","Piorunochron"], ["Matka Teresa","Michael Jordan","Mikrofon"],["Marsjanie atakują!","Martin Luther King","Maska"]],
    [ ["Parkomat","Perfumy","Przejście dla pieszych"], ["Mike Tyson","Artur Andrus","Miss Polonia"],["Żebrak","Przekaz podprogowy","Spuścić z tonu"]],
    [ ["Rybak","Łopata","Barka"], ["Jaś Fasola","Muhammad Ali","Mojżesz"],["Zosia Samosia","Wetknąć kij w mrowisko","Dziewczyna z tatuażem"]],
    [ ["Wiertło","Papuga","Petarda"], ["Reksio","Krzyżówka","Młynek do pieprzu"],["O mały włos","Mój skarbie","Zakasać rękawy"]],
    [ ["Piotruś Pan","Pianino","Sroka"], ["Wszystko się może zdarzyć","Wąsy","Moskitiera"],["Milczeć jak grób","Dla ludzi o mocnych nerwach","Skoczyć na głęboką wodę"]],
    [ ["Pilot","Przyprawa","Tenis stołowy"], ["Neil Armstrong","C.K. Dezerterzy","Edyp"],["Pozostać neutralnym","Pomroczność jasna","Idzie jak po grudzie"]],
    [ ["Pingwin","Pinokio","Pirat"], ["Wujek Sknerus","Mechaniczna pomarańcza","Organy"],["George W. Bush","Zagmatwać sprawę","Podbite oko"]],
    [ ["Basen","Szybowiec","Tablica rejestracyjna"], ["Kapitan Kloss","Palma","Pamela Anderson"],["Gdzie drwa rąbią, tam wióry lecą","Sokoli wzrok","Sylwetka"]],
    [ ["Hydraulik","Pióro","Ryba"], ["Papier toaletowy","Spadochron","Modelina"],["Otworzyć puszkę Pandory","Koszyk na zakupy","Mamrotać coś pod nosem"]],
    [ ["Pokemon","Policjant","Jabłko"], ["Jazda na łyżwach","Wielka stopa","Latarnia morska"],["Łamana angielszczyzna","Kopnąć w kalendarz","Stracić panowanie nad sobą"]],
    [ ["Strażak","Port","Lotniskowiec"], ["Foka","Klamerka","Piraci z Karaibów"],["Toczący się kamień nie obrasta mchem","Szklana pułapka","Czerwony jak burak"]],
    [ ["Portfel","Doniczka","Gniazdko elektryczne"], ["Plaża","Platforma wiertnicza","Popcorn"],["Porywać się z motyką na słońce","W grupie raźniej","Popeye"]],
    [ ["Więzienie","Studnia","Piżama"], ["Posejdon","Karteczki samoprzylepne","Kosz na śmieci"],["Wznieść toast","Wystawić kogoś do wiatru","Alcatraz"]],
    [ ["Radar","Lodówka","Lis"], ["Proch strzelniczy","Power Rangers","Księżniczka"],["Prędzej mi kaktus na ręce wyrośnie","Deszczowa piosenka","Zaplątani"]],
    [ ["Rekin","Restauracja","Nosorożec"], ["Zagubieni","Proteza","Reklama"],["Smalić cholewki","Resident Evil","Powrót do przyszłości"]],
    [ ["Zasłony","Rzeka","Robot"], ["Quidditch","Grzejnik","Tory kolejowe"],["Kopać leżącego","Gliniarz i prokurator","Rio de Janeiro"]],
    [ ["Koło","Kostka Rubika","Walentynki"], ["Szczur","Queen","Robin Hood"],["Robinson Crusoe","Przerwać milczenie","Szuwary"]],
    [ ["Sałatka","Jodła","Skok o tyczce"], ["Rocky","Jazda na rolkach","Romeo i Julia"],["Prężyć muskuły","Migdalić się","Oszaleć na czyimś punkcie"]],
    [ ["Szminka","Akwalung","Skorpion"], ["Uwolnić orkę","Piękna I Bestia","Rugby"],["Święty Piotr","Sezonowy","Ni stąd, ni zowąd"]],
    [ ["Strzykawka","Wąż","Małpa"], ["Miecz świetlny","Święty Graal","Dzik"],["Wywieść kogoś w pole","Rwać sobie włosy z głowy","Baba z wozu, koniom lżej"]],
    [ ["Sombrero","Mario","Wiedźma"], ["Kiełbasa","Sauna","Mydło"],["Postawić wszystko na jedną kartę","Wstać lewą nogą","Być drobiazgowym"]],
    [ ["Latający spodek","Mysz","Łódź podwodna"], ["Taśma samoprzylepna","Wiadro","Wisława Szymborska"],["Wystroić się jak na bal","Zapatrzony w siebie","Jak dwie krople wody"]],
    [ ["Biustonosz","Pomnik","Stek"], ["Kelnerka","Shrek","Gwizdek"],["Wpaść w oko","Zbijać bąki","Zygmunt Freud"]],
    [ ["Stetoskop","Dywan","Tarzan"], ["Silikon","Deska snowboardowa","Dzwonek"],["Świat według Kiepskich","Skyfall","Snoopy"]],
    [ ["Kret","Byk","Szkielet"], ["Anna Przybylska","Thorgal","Kryptoreklama"],["Pomnik Chrystusa w Świebodzinie","Statua Wolności","Kusić los"]],
    [ ["Burza","Tenis","Tetris"], ["Stacja kosmiczna","Kate Middleton","Stonehenge"],["Piąte koło u wozu","Walt Disney","The Avengers"]],
    [ ["Herbata","Tygrys","Wigwam"], ["Długopis","Sudoku","Sushi"],["Truman Show","Szewczyk Dratewka","Tina Turner"]],
    [ ["Świnka skarbonka","Titanic","Kosiarka do trawy"], ["Temperówka","Szpilki","Tandem"],["Korkociąg","Zemdleć","Leje jak z cebra"]],
    [ ["Słonecznik","Toy Story","Traktor"], ["Terminator","Artysta","Termos"],["Top Gun","Nie owijać w bawełnę","Zacząć wszystko od początku"]],
    [ ["Hulajnoga","Trąbka","Piła mechaniczna"], ["Zakonnica w przebraniu","Krzywa wieża w Pizie","Pociąg widmo"],["Każda potwora znajdzie swojego amatora","Ugryźć się w język","Przemyt narkotyków"]],
    [ ["Wąż ogrodowy","Klub nocny","Krowa"], ["Trampolina","Transformers","Chińczyk"],["Sąd","Zabijać czas","Marcujące koty"]],
    [ ["Wampir","Sęp","Rower"], ["Troll","Czarna dziura","Tsunami"],["Przezorny zawsze ubezpieczony","Czek bez pokrycia","Pieprzyk"]],
    [ ["Piątek trzynastego","Wachlarz","Weranda"], ["Pojemniki na żywność","Zmierzch","Szczepionka"],["Jeden obraz wart więcej niż tysiąc słów","Buzia mu się nie zamyka","Romansidło"]],
    [ ["Browarnik","Wino","Witamina"], ["20 000 mil podmorskiej żeglugi","Walizka","Zapięcie na rzepy"],["Doprowadzać do szału","Wilk w owczej skórze","V jak Vendetta"]],
    [ ["Wulkan","Jogurt","Jojo"], ["Whiskey","Kubuś Puchatek","Wolverine"],["Zaprzedać duszę diabłu","Szczotka do butów","Żyć pełnią życia"]],
    [ ["Mistrz Yoda","Zebra","Zorro"], ["Woody Allen","Saksofon","Wiedźmin"],["Złodziej","Ślepy jak kret","Kwoka"]],
  ];
}

?>
