<?php
class ConceptCardsSW {
  static $cards = [
    [ ["Hjul","Pool","Känguru"], ["Råtta","Lyckohjulet","Karaoke"],["Robinson Kruse","Storhetsvansinne","Skarpsynt"]],
    [ ["Åskledare","Fredagen den 13:e","MP3 Spelare"], ["Mikrofon","Tupperware","Austin Powers"],["Mask","Hålla låda","Spelhall"]],
    [ ["Hitta Nemo","Hjälm","Vin"], ["Apornas planet","Propp","Kardborreband"],["Kronan på verket","Smida medan järnet är varmt","Ta i med hårdhandskarna"]],
    [ ["Tegelsten","Fällkniv","Ordbok"], ["Baloo","Beyoncé","Varghunden"],["Kasta yxan i sjön","August Strindberg","Flasköppnare"]],
    [ ["Badkar","Häfte","Stetoskop"], ["Spindel","Batteri","Silikon"],["Mötas halvvägs","Slö som en hösäck","Sex fot under"]],
    [ ["Traktor","Skal","Rubiks Kub"], ["Termosflaska","Hjort","Drottning"],["Ligga i startgroparna","Eldupphör","Tystnaden talar för sig själv"]],
    [ ["Brandflyg","Ekorre","Ängel"], ["Bilbo Baggins","David Guetta","Kapten Haddock"],["Hungrig som en varg","Dragonball Z","På spaning efter den tid som flytt"]],
    [ ["Trollkarl","Igelkott","Registerplåt"], ["Den lille prinsen","Indiana Jones","Pamela Anderson"],["Lägg inte alla ägg i samma korg","Hjärntvätt","Alla goda ting är tre"]],
    [ ["Borr","Kontor","Prästkrage"], ["Mr. Potato Head","Damm","Sagan om ringen"],["Det var nära ögat","Stå på näsan","Döda poeters sällskap"]],
    [ ["Ålderdomshem","Vampyr","Stege"], ["Du gamla, du fria","Troll","Cyrano de Bergerac"],["The Fifth Element","En oinlöst check","Detektiv"]],
    [ ["Krokodil","Kanariefågel","Piano"], ["Måltavla","Billy the Kid","Mustasch"],["Simon Cowell","Fotbad","Inte för de svaghjärtade"]],
    [ ["Defibrillator","Tetris","Val"], ["Streckkod","Stonehenge","Armborst"],["Bekänn dina synder","The Avengers","Dammsugare"]],
    [ ["Källare","Lejon","Solur"], ["Varmvattenflaska","Slunga","Ångbåt"],["Sätta ett nytt rekord","Flickan med svavelstickorna","Dåligt samvete"]],
    [ ["Glidflygplan","Löständer","Kräfta"], ["Palm","Bokförare","Magasin"],["Äpplet faller inte långt från trädet","Siluett","Prima ballerina"]],
    [ ["Skorpion","Svärdfisk","Parfym"], ["Rugby","Dynamit","Babben Larsson"],["Bli tagen på sängen","Segla på ljusröda moln","Dolda budskap"]],
    [ ["Lastbil","Mus","Parkeringsmätare"], ["Öl","Hink","Mike Tyson"],["Virrig","Navelskådning","Tiggare"]],
    [ ["Stridsflyg","Horn","Haj"], ["Vattenfärger","Kill Bill","Prison Break"],["Beväpnad till tänderna","Kiwifrukt","Gammal kärlek rostar aldrig"]],
    [ ["Lärare","Chokolad","Pepparsprej"], ["Kristina från Duvemåla","Stålmannen","Bagheera"],["Den gode, den onde, den fule","Köra mot rött ljus","Ha huvudet bland molnen"]],
    [ ["Pilot","Gasmask","Pinocchio"], ["Neil Armstrong","Fångad av en stormvind","A Clockwork Orange"],["Att äta kakan och ha den kvar","Söndagstidningen","Prata i nattmössan"]],
    [ ["Zebra","Mekaniker","DVD"], ["Xylofon","Yeti","Cyklist"],["Kärleken är blind","En studie i rött","Gå åt skogen"]],
    [ ["Ko","Gris","Fönster"], ["Trivial Pursuit","Bäver","Säkerhetsnål"],["Vara het på gröten","Slutet gott, allting gott","Tankspridd"]],
    [ ["Tipi","Skjorta","Raket"], ["Sushi","Kalkylator","Pommes frites"],["Tina Turner","Gråta över spilld mjölk","Fight Club"]],
    [ ["Affär","Rörmokare","Barbi"], ["Popkorn","Toapapper","Hiss"],["Popeye","Att öppna Pandoras ask","Vig som en apa"]],
    [ ["Yoghurt","Paraply","Ninja"], ["Nalle Puh","Moder Teresa","Lucky Luke"],["Vaskrensare","Mars Attacks!","Knasen"]],
    [ ["Fiskare","Flod","Skumsläckare"], ["Mister Bean","Värmeelement","Elton John"],["Ta sig själv i kragen","Sunes sommar","Långsam som en snigel"]],
    [ ["Vindflöjel","Idrottshall","Veranda"], ["Krig och fred","Svala","Vaccin"],["Lascauxgrottan","Inception","Kärleksroman"]],
    [ ["Gaffel","Pistol","Fladdermus"], ["Forrest Gump","Vessla","Kackerlacka"],["Veta sina egna gränser","Gå upp i rök","Hjärtskärrande"]],
    [ ["Snigel","Zorro","Bilstereo"], ["Dumbo","Zelda","Angry Birds"],["Criminal Minds","Hönsmamma","American Beauty"]],
    [ ["Julgran","Fluga","Pannkaka"], ["Serietidning","Unga kvinnor","Stig"],["Som att leta efter en nål i en höstack","Vara torr bakom öronen","Gudarnas skymning"]],
    [ ["Tjur","Gran","Pac-Man"], ["Tintin","Rullskridskor","Margaret Thatcher"],["Att vara eller inte vara","Cristo Redentor","Hångel"]],
    [ ["Peter Pan","Gräsklippare","Blinker"], ["Blowing in the Wind","Tandemcykel","Vykort"],["Sitter som berget","Regnet står som spön i backen","Arg som ett bi"]],
    [ ["Berg","Hotell","Igloo"], ["Rosornas krig","Bubbelbad","Jeanne d’Arc"],["Världen Sju Underverk","Steve Martin","Marlon Brando"]],
    [ ["Pirat","Cykel","Spargris"], ["Organ","Tsunami","Pennvässare"],["Blåtira","Vara på sin vakt","Korkskruv"]],
    [ ["Storm","Vitamin","Klocka"], ["Rymdstation","En världsomsegling under havet","Casino Royale"],["Att vara det tredje hjulet","V for Vendetta","Envis"]],
    [ ["Bärgningsbil","Symaskin","Harpun"], ["Gurka","Tummeliten","Tunnband"],["David och Goljat","Richie Rich","Yuri Gagarin"]],
    [ ["Asgam","Jeans","iPad"], ["Svart hål","Jukebox","Zlatan Ibrahimovic"],["Födelsemärke","Att kasta den första stenen","Kasta pengar i sjön"]],
    [ ["Nutella","Släde","Svärd"], ["Toalettstol","Snabba cash","Jon Stewart"],["Mamma Mia!","Laïka","Gräva ned stridsyxan"]],
    [ ["Lilla huset på prärien","Allmän helgdag","Vulkan"], ["Tingeling","Julia Roberts","Whiskey"],["The Nightmare Before Christmas","Pojkar kommer alltid att vara pojkar","Sälja sin själ till djävulen"]],
    [ ["Lås","Anka","Förstoringsglas"], ["Dalai Lama","Biljard","Lassie"],["Slå sina påsar ihop","Reta gallfeber på någon","Babels torn"]],
    [ ["Skorsten","Avatar","Sombrero"], ["Kaffepanna","Afrodite","Korv"],["Hårborste","Varje moln har en silverkant","Det må bära eller brista"]],
    [ ["Brunn","Alla hjärtans dag","Bi"], ["Post-it lapp","Robin Hood","2001: Ett rymdäventyr"],["Att ge nobben åt någon","Sjögräs","Gå i gamla hjulspår"]],
    [ ["Snövit och de sju dvärgarna","Snille","Minecraft"], ["Asterix och Obelix","Gladiator","Hajen"],["Kallsvett","Mount Rushmore","Jorden runt på 80 dagar"]],
    [ ["Solförmörkelse","Garage","Vindsutrymme"], ["D’Artagnan","IKEA","Björn Borg"],["Kasta pärlor för svin","Aziz Ansari","Sjöhäst"]],
    [ ["Meteorit","Museum","Kylskåp"], ["Kontaktlins","The Sims","Power Rangers"],["Upplysningstiden","Svettiga handflator","Rain Man"]],
    [ ["Printer","Alphydda","Matta"], ["John Lennon","Bowling for Columbine","Snöbräde"],["Mark Levengood","Big Ben","Skyfall"]],
    [ ["Elefant","Tändare","Alv"], ["Final Destination","Bambi","Djävul"],["Eminem","Höjdskräck","Veta vad man kan förvänta sig"]],
    [ ["Blomkruka","Drake","Simma"], ["Oljeplatform","Tandpetare","Teenage Mutant Ninja Turtles"],["Ju fler desto roligare","Demokrati","Stolthet och Fördom"]],
    [ ["Aladdin","Leksaksdrake","Äppel"], ["Bonde","Bagare","Fyrtorn"],["Du går mig på nerverna","Stamma","Att förlora besinningen"]],
    [ ["Bilar","Yoda","U-båt"], ["Postlåda","Woody Allen","Björn Ranelid"],["Solarium","Tjuv","Lika som bär"]],
    [ ["Biograf","Orm","Kalle Anka"], ["Bröderna Hardy","Den heliga gralen","The Sound of Silence"],["Kristallklart","Lyfta sig själv i håret","Mupparna"]],
    [ ["Monopol","Sallad","Skola"], ["The Birds","Rocky","Johnny Cash"],["Knightfall","Visa sig på styva linan","Sova som en stock"]],
    [ ["Spade","Gardiner","Förklädnad"], ["Muhammad Ali","Quidditch","Taylor Swift"],["Ge järnet","Strö salt i såren","Brown-eyed Girl"]],
    [ ["Manet","Jätte","Spelkonsol"], ["LEGO","MacGyver","Askungen"],["Suckarnas bro","Harrison Ford","Ond cirkel"]],
    [ ["Tennis","Flygplats","Hatt"], ["Kronprinsessan Victoria","Låt maten tysta mun","Brigitte Bardot"],["George Lucas","Tio små indianpojkar","Krigsskador"]],
    [ ["Boxare","Vete","Matsal"], ["Eremitkräfta","Atlantis","Bob Marley"],["Lägga något på minne","Aptitretande","Bajonett"]],
    [ ["Snorkråka","Aspirin","Apa"], ["Fifty Shades of Grey","ALF","Vildsvin"],["Fritt fall","Ali Baba","Åka på en blåsning"]],
    [ ["Solglasögon","Vattenkanna","Älva"], ["Djungelboken","Album Dumbledore","Gödsel"],["Order of the Stick","Al Capone","Flitig som en myra"]],
    [ ["Varg","Rädda Willy","Iron Man"], ["Teckenspråk","Läppstift","Judas"],["Rosettastenen","Sankte Per","Kasta in handduken"]],
    [ ["Polisman","Banan","Bo"], ["Näcken","Regnbåge","Max von Sydow"],["I de blindas rike är den enögde kung","Kasta veven","Tre vise män"]],
    [ ["Häst","Kreditkort","Flygande tefat"], ["Kameleont","Atombomb","Målartejp"],["Skvallertidning","Bygga ett imperium","Kejsarens nya kläder"]],
    [ ["Té","Pokémon","Mästarkock"], ["Penna","Skridskoåkning","Spökskepp"],["The Truman Show","Dålig engelska","Jon Blund"]],
    [ ["Drönare","Mumien","Slott"], ["Mattkniv","Exorcisten","Sandbunker"],["Att flytta berg","Breakfast Club","Kalle och Hobbe"]],
    [ ["Iskub","Struts","Äktenskap"], ["William Tell","Register","Sfinxen i Giza"],["Skumgodis","Tryck på gasen","Barna Hedenhös"]],
    [ ["Restaurang","Stil","Mullvad"], ["Protes","Röda rummet","Maggie Gyllenhaal"],["Resident Evil","Game of Thrones","Frihetsgudinnan"]],
    [ ["Mikroskop","Vakt","Hangarfartyg"], ["Tomten är far till alla barnen","Ron Howard","Pirates of the Caribbean"],["Daytona 500","Dagobert","Röd som en tomat"]],
    [ ["Orkester","Kyrka","Julljus"], ["Ångmaskin","Tandkräm","Helikopterplatform"],["Det man inte vet, det lider man inte av","E.T.","Ana ugglor i mossen"]],
    [ ["Fear Factor","Nallebjörn","Skata"], ["Dragkedja","Smink","Myggnät"],["Tränga sig före i kön","Madame Tussaud","Kasta sig huvudstupa in"]],
    [ ["Ananas","Ägg","Postman"], ["Pudel","McDonald’s","Empire State Building"],["Löst prat","Lewis Carroll","Snabb som blixten"]],
    [ ["Barbecue","Lönnmördare","Geting"], ["Harlekin","Amy Winehouse","Munspel"],["Capribyxor","Slänga bensin på elden","Ha eld i baken"]],
    [ ["Stjärnfall","Tårta","Champanj"], ["Saxhand Edward","Ghostbusters","Bridget Jones"],["Panelhöna","Tuggummi","Ju mer du vet"]],
    [ ["Gruvarbetare","Fängelse","Kvarn"], ["Sunes sommar","Poseidon","Vredens druvor"],["Extraknäck","Höja ett glas för någon","Lätt som en plätt"]],
    [ ["Jordgubbe","Smällare","Brandman"], ["Bill Clinton","Pepparkvarn","Säl"],["Fidel Castro","Kavla upp ärmarna","Die Hard"]],
    [ ["TV-reklam","Trädgårdssslang","Hjulben"], ["Skelett","Trampolin","Den gröna milen"],["Utmana ödet","Domstol","Ronja Rövardotter"]],
    [ ["Airbag","Räv","Kikare"], ["Svävarfarkost","Prinsessa","Jumanji"],["Tve-eggat svärd","Trassel","Jim Carrey"]],
    [ ["Clown","GPS","Örhänge"], ["Casper","Gitarr","Gunga"],["Störa någon","Tur i spel, otur i kärlek","Ett öga för detaljer"]],
    [ ["Nattklubb","Groda","Jägare"], ["Transformers","Stroboskop","Tandborste"],["Döda tid","Hungerspelen","Hålla andan"]],
    [ ["Tiger","Fisk","Parasoll"], ["Sudoku","Modellera","Michael Jordan"],["Prins Valiant","Mumla i skägget","Martin Luther King"]],
    [ ["Metro","Armbandsur","Varulv"], ["De sju samurajerna","Rysk trädocka","Lara Croft"],["Akilleshäl","Naruto","Begrava huvudet i sanden"]],
    [ ["Dator","Väderkvarn","Aluminiumfolie"], ["Ensam Hemma","Diablo","Majonnäs"],["Lotteri","Ennio Morricone","Hoppa hage"]],
    [ ["Robot","Sjöstjärna","Fotboll"], ["Tågbana","Punktskrift","Hästsko"],["Rio de Janeiro","Vit som snö","Få synlighet i pressen"]],
    [ ["Plånbok","Tenn","Diamant"], ["Strand","Advokat","Kaka"],["Sakta men säkert","Fattig som en kyrkråtta","Från jorden till månen"]],
    [ ["Sololja","Staty","Hundkoja"], ["Spola","Shrek","Trollslända"],["Bränt barn skyr elden","Rulla på tummarna","De sju städerna av guld"]],
    [ ["Pingvin","Bibliotek","Doktor"], ["Farbror Joakim","Aspartam","Croissant"],["George W. Bush","Ha myror i byxorna","Inleda med en smäll"]],
    [ ["Pumpa","Behå","Panter"], ["Smartkort","Servitris","Mary Poppins"],["Kostar ingenting","Tummen mitt i handen","Marco Polo"]],
    [ ["Överljudsflygplan","Den osynliga mannen","Radar"], ["Catwoman","Koala","Krut"],["Vänkrets","Pengar växer inte på träd","När helvetet fryser till is"]],
    [ ["Elektriska stolen","Vindrutetorkare","Titanic"], ["Bowling","Blekmedel","Stilettklack"],["Justin Bieber","Dum som en gås","Svimma"]],
    [ ["Papegoja","Sugrör","Eiffeltornet"], ["Korsord","Marilyn Manson","Dexter"],["Min älskade","Spelar harpa i himlen","Påskön"]],
    [ ["Dr. House","Toy Story","Körsbär"], ["Cupido","The Artist","Kompass"],["Uppsägning","Gå som katten kring het gröt","Ben-Hur"]],
    [ ["Glidflygning","Fruktsaft","Roder"], ["Strumpbyxor","Jurassic Park","Giljotin"],["Avbryta någon som talar","Singla slant","Hermione Granger"]],
    [ ["Mjölk","Noshörning","Enhörning"], ["Hungerspelen","Reklam","Lance Armstrong"],["Tomma tunnor skramlar mest","Tillbaka till framtiden","Tiga är guld"]],
    [ ["Den rosa pantern","Tärningar","Simpsons"], ["The Birdcage","Nyckel","Venus de Milo"],["Vägen till helvetet är kantad med goda föresatser","Colosseum","Vietnamkriget"]],
    [ ["Övergångsställe","Jultomten","Vinmakare"], ["Miss America","Den franska revolutionen","Kappsäck"],["Lugn i stormen","Den Förbjudna Staden","Trampa på en öm tå"]],
    [ ["Stövlar","Dykutrustning","Ferrari"], ["Hyra","Micke och Molle","Rulltrappa"],["Vända kappan efter vinden","Säsong","Vara eld och lågor"]],
    [ ["Ambulans","Spruta","Pyjamas"], ["Magnet","Ljussabel","Soptunna"],["Det är som det är","Skjuta sig själv i foten","Alcatraz"]],
    [ ["Bordtennis","Handskar","Brevkniv"], ["Oidipus","Station","Kejsarsnitt"],["För trött för att tänka klart","Röka som en skorsten","Sixtinska kapellet"]],
    [ ["Mobiltelefon","Infrarött teleskop","Giraff"], ["Hannibal Lecter","Rosens namn","Brödrost"],["Once Upon a Time in the West","Kluven tunga","Kyrkoorgel"]],
    [ ["Örn","Solros","Kök"], ["Animal Planet","The Terminator","Cirkus"],["Andlös","Top Gun","Kloning"]],
    [ ["Bank","Sovrum","Flöjt"], ["Arkimedes","Borat","Fast and Furious"],["Fria tyglar","Billy Jean","Eureka!"]],
    [ ["Trehjuling","Biff","Egypten"], ["Sister Act – En värsting till syster","Vissla","Desperate Housewives"],["Håll din tunga","Sigmund Freud","Adam Sandler"]],
    [ ["Fläkt","Kaffe","Skallra"], ["Twilight","Batman","Conan O’Brian"],["En bild är värd mer än tusen ord","Göra en höna av en fjäder","Jean-Claude Van Damme"]],
    [ ["Dinosaurie","Motorsåg","Smurfarna"], ["Crocodile Dundee","Spöktåg","Falukorv"],["Be om någons hand","Drogsmuggling","Hundraårskriget"]],
    [ ["Spenat","Pråm","Arv"], ["Dr. Jekyll","Moses","Jack Bauer"],["Esmeralda","Män som hatar kvinnor","Luke, I am your father"]],
    [ ["Harry Potter","Sjö","Coca-Cola"], ["Vem tänder stjärnorna?","Stand By Me","Leverlåda"],["Lova guld och gröna skogar","Känna sig som det femte hjulet","Mardröm"]],
    [ ["Sonic the Hedgehog","Stavhopp","Trumpet"], ["Bastu","Romeo och Julia","Det lutande tornet i Pisa"],["Vakna på fel sida","Styv i korken","Lika barn leka bäst"]],
    [ ["Isbjörn","Häxa","Snögubbe"], ["Estoniamonumentet","Tvål","Baguette"],["Bröllopsresa","Ta sig vatten över huvudet","Hjärtat i halsgropen"]],
    [ ["Fjäder","Kokosnöt","Hamn"], ["Fallskärm","Katapult","Klädnypa"],["Köpkorg","Censur","Smida medan järnet är varmt"]],
    [ ["Jojo","101 Dalmatiner","Fjäril"], ["Wolverine","La vita è bella – Livet är underbart","Men in Black"],["Blixten slår inte ner två gånger på samma ställe","Lev livet till det yttersta","Äldre och klokare"]],
    [ ["Skogshuggare","Mygga","Mikrovågsugn"], ["Marilyn Monroe","Boondock Saints","Smörkniv"],["Ha fötterna stadigt på jorden","Farliga Föbindelser","Svält"]],
    [ ["Istiden","Delfin","Vattentorn"], ["Den svarta kitteln","Tangentbord","Bruce Lee"],["Kreml","Göra någon ordlös","I vrångstrupen"]],
    [ ["Svampbob Fyrkant","Krydda","Tarzan"], ["Borta med vinden","Ocean’s Eleven","Sädesfältscirkel"],["Baksmälla","Sova med ena ögat öppet","Snobben"]],
  ];

}

?>
