<?php
class ConceptCardsEN {
  static $cards = [
[ ["Wheel","Pool","Kangaroo"], ["Rat","Wheel of fortune","Karaoke"], ["Robinson Crusoe","Delusions of grandeur","Eagle-eyed"],],
[ ["Lightning rod","Friday the 13th","MP3 player"], ["Microphone","Tupperware","Austin Powers"], ["Mask","Talk the hind legs off a donkey","Penny Arcade"],],
[ ["Finding Nemo","Helmet","Wine"], ["Planet of the Apes","Plug","Velcro"], ["The icing on the cake","Strike while the iron is hot","An iron fist in a velvet glove"],],
[ ["Brick","Swiss Army knife","Dictionary"], ["Baloo","Beyoncé","White Fang"], ["Get your sea legs","Walt Whitman","Bottle opener"],],
[ ["Bathtub","Notebook","Stethoscope"], ["Spider","Battery","Silicone"], ["Meet you halfway","Never do a lick of work","Six feet under"],],
[ ["Tractor","Shell","Rubik's Cube"], ["Thermos","Deer","Queen"], ["Make a fresh start","Ceasefire","Break the silence"],],
[ ["Fire-fighting plane","Squirrel","Angel"], ["Bilbo Baggins","David Guetta","Captain Harlock"], ["Hungry like the wolf","Dragon Ball Z","Remembrance of Things Past"],],
[ ["Magician","Hedgehog","License plate"], ["The Little Prince","Indiana Jones","Pamela Anderson"], ["Can't make an omelette without breaking a few eggs","Brainwash","Bad things always come in threes"],],
[ ["Drill","Office","Daisy"], ["Mr. Potato Head","Dam","The Lord of the Rings"], ["By the skin of your teeth","Take a dive","Dead Poets Society"],],
[ ["Retirement home","Vampire","Ladder"], ["This Land Is Your Land","Troll","Cyrano de Bergerac"], ["The Fifth Element","A bad check","Detective"],],
[ ["Crocodile","Canary","Piano"], ["Target","Billy the Kid","Moustache"], ["Adam Carolla","Footbath","Not for the faint of heart"],],
[ ["Defibrillator","Tetris","Whale"], ["Barcode","Stonehenge","Crossbow"], ["Confess your sins","The Avengers","Vacuum cleaner"],],
[ ["Cellar","Lion","Sundial"], ["Hot water bottle","Slingshot","Steamboat"], ["Set a new record","The Little Match Girl","Have a guilty conscience"],],
[ ["Glider","Dentures","Crab"], ["Palm tree","Accountant","Ammo clip"], ["What's bred in the bone comes out in the flesh","Silhouette","Prima ballerina"],],
[ ["Scorpion","Swordfish","Perfume"], ["Rugby","Dynamite","Janeane Garofalo"], ["Out of left field","Be on cloud nine","Subliminal message"],],
[ ["Truck","Mouse","Parking meter"], ["Beer","Bucket","Mike Tyson"], ["Scatterbrained","Navel gazing","Beggar"],],
[ ["Fighter plane","Horn","Shark"], ["Watercolors","Kill Bill","Prison break"], ["Armed to the teeth","Kiwi fruit","Rekindle the flame"],],
[ ["Teacher","Chocolate","Pepper spray"], ["Moby Dick","Astro Boy","Bagheera"], ["The Good, the Bad and the Ugly","Run a red light","Have your head in the clouds"],],
[ ["Pilot","Gas mask","Pinocchio"], ["Neil Armstrong","Hanging on the Telephone","A Clockwork Orange"], ["Straddle the fence","Sunday paper","Confuse the issue"],],
[ ["Zebra","Mechanic","DVD"], ["Xylophone","Yeti","Cyclist"], ["Blind as a bat","A Study in Scarlet","Down in flames"],],
[ ["Cow","Pig","Window"], ["Trivial Pursuit","Beaver","Safety pin"], ["If it ain't broke, don't fix it","It's not the end of the world","Absent-minded"],],
[ ["Tepee","Shirt","Rocket"], ["Sushi","Calculator","French fries"], ["Tina Turner","Brood over","Fight Club"],],
[ ["Outlet","Plumber","Barbie"], ["Popcorn","Toilet paper","Elevator"], ["Popeye","Open Pandora's box","Monkey see, monkey do"],],
[ ["Yogurt","Umbrella","Ninja"], ["Winnie-the-Pooh","Mother Teresa","Lucky Luke"], ["Plunger","Mars Attacks!","Beetle Bailey"],],
[ ["Fisherman","River","Fire extinguisher"], ["Mister Bean","Radiator","Elton John"], ["Pull yourself up by your bootstraps","Turner and Hooch","Slow as a snail"],],
[ ["Weathervane","Gymnasium","Veranda"], ["War and Peace","Swallow","Vaccine"], ["The Lascaux caves","Inception","Romance novel"],],
[ ["Fork","Gun","Bat"], ["Forrest Gump","Ferret","Cockroach"], ["Know your limits","Disappear into thin air","Heartbreaking"],],
[ ["Snail","Zorro","Car stereo"], ["Dumbo","Zelda","Angry Birds"], ["Criminal Minds","Mother hen","American Beauty"],],
[ ["Yule log","Fly","Pancake"], ["Comic book","Little Women","Path"], ["Like looking for a needle in a haystack","My ears are burning","The Gods Must be Crazy"],],
[ ["Bull","Fir tree","Pac-Man"], ["Tintin","Roller skate","Margaret Thatcher"], ["Suffer the slings and arrows of outrageous fortune","Statue of Christ the Redeemer","Snogging"],],
[ ["Peter Pan","Lawnmower","Turn signal"], ["Blowing in the Wind","Tandem bicycle","Postcard"], ["Happy as a clam","Raining cats and dogs","Channel your anger"],],
[ ["Mountain","Hotel","Igloo"], ["The Pillars of the Earth","Jacuzzi","Joan of Arc"], ["The Seven Wonders of the World","Steve Martin","Marlon Brando"],],
[ ["Pirate","Bike","Piggy bank"], ["Organ","Tsunami","Pencil sharpener"], ["Black eye","Forewarned is forearmed","Corkscrew"],],
[ ["Storm","Vitamin","Bell"], ["Space station","Twenty Thousand Leagues Under The Sea","Casino Royale"], ["Be a third wheel","V for Vendetta","Pig-headed"],],
[ ["Tow truck","Sewing machine","Harpoon"], ["Cucumber","Tom Thumb","Hula hoop"], ["David and Goliath","Richie Rich","Yuri Gagarin"],],
[ ["Vulture","Jeans","iPad"], ["Black hole","Jukebox","Jonathan Livingston Seagull"], ["Beauty mark","Cast the first stone","Pour money down the drain"],],
[ ["Nutella","Sled","Sword"], ["Toilet seat","Lords of Dogtown","Jon Stewart"], ["Encino Man","Laïka","Bury the hatchet"],],
[ ["Little House on the Prairie","Public holiday","Volcano"], ["Tinkerbell","Julia Roberts","Whiskey"], ["The Nightmare Before Christmas","Boys will be boys","Sell your soul to the devil"],],
[ ["Lock","Duck","Magnifying glass"], ["Dalai Lama","Billiards","Lassie"], ["Curled up in a ball","Raging fever","Tower of Babel"],],
[ ["Chimney","Avatar","Sombrero"], ["Coffee pot","Aphrodite","Sausage"], ["Hairbrush","Every cloud has a silver lining","Take the plunge"],],
[ ["Well","Valentine's Day","Bee"], ["Post-it note","Robin Hood","2001: A Space Odyssey"], ["Stand somebody up","Reeds","Spin your wheels"],],
[ ["Snow White and the Seven Dwarfs","Genius","Minecraft"], ["Tom and Jerry","Gladiator","Jaws"], ["Break out in a cold sweat","Mount Rushmore","Around the World in 80 Days"],],
[ ["Eclipse","Garage","Attic"], ["D'Artagnan","Jolly Green Giant","Frank Lloyd Wright"], ["Cast pearls before swine","Aziz Ansari","Seahorse"],],
[ ["Meteorite","Museum","Refrigerator"], ["Contact lens","The Sims","Power Rangers"], ["Age of Enlightenment","Clammy hands","Rain Man"],],
[ ["Printer","Chalet","Carpet"], ["John Lennon","Bowling for Columbine","Snowboard"], ["Ted Koppel","Big Ben","Skyfall"],],
[ ["Elephant","Lighter","Elf"], ["Final Destination","Bambi","Devil"], ["Eminem","Be scared of heights","Know what to expect"],],
[ ["Flowerpot","Dragon","Swimming"], ["Oil rig","Toothpick","Teenage Mutant Ninja Turtles"], ["The more the merrier","Democracy","Pride and Prejudice"],],
[ ["Aladdin","Kite","Apple"], ["Farmer","Baker","Lighthouse"], ["You're getting on my last nerve","Stammer","Lose your cool"],],
[ ["Cars","Yoda","Submarine"], ["Mailbox","Woody Allen","Allen Ginsberg"], ["Tanning bed","Thief","Like two peas in a pod"],],
[ ["Cinema","Snake","Porky Pig"], ["The Hardy Boys","Holy Grail","The Sound of Silence"], ["Be crystal clear","Pull your hair out","The Muppet Show"],],
[ ["Monopoly","Salad","School"], ["The Birds","Rocky","Johnny Cash"], ["Knightfall","Flex your muscles","Sleep like a baby"],],
[ ["Shovel","Drapes","Disguise"], ["Muhammad Ali","Quidditch","Taylor Swift"], ["Put your foot in your mouth","Twist the knife in the wound","Brown-eyed girl"],],
[ ["Jellyfish","Ogre","Game console"], ["LEGO","MacGyver","Cinderella"], ["The Bridge of Sighs","Richard Hatch","Vicious circle"],],
[ ["Tennis","Airport","Hat"], ["Kate Middleton","Enjoy the Silence","Brigitte Bardot"], ["Tex Avery","Ten Little Indians","War wounds"],],
[ ["Boxer","Wheat","Canteen"], ["Hermit crab","Atlantis","Bob Marley"], ["Have a memory lapse","Mouth-watering","Bayonet"],],
[ ["Booger","Aspirin","Monkey"], ["Fifty Shades of Grey","Alf","Wild boar"], ["Freefall","Ali Baba","Be taken for a ride"],],
[ ["Sunglasses","Watering can","Fairy"], ["The Jungle Book","Albus Dumbledore","Fertilizer"], ["Order of the Stick","Al Capone","Be deaf as a door-post"],],
[ ["Wolf","Free Willy","Iron Man"], ["Sign language","Lipstick","Judas"], ["The Rosetta stone","Saint Peter","Throw in the towel"],],
[ ["Policeman","Banana","Nest"], ["The Bogeyman","Rainbow","Luc Besson"], ["In the land of the blind, the one-eyed man is king","Kick the bucket","Three wise men"],],
[ ["Horse","Credit card","Flying saucer"], ["Chameleon","Atomic bomb","Scotch tape"], ["Watercooler talk","Build an empire","Dressed to the nines"],],
[ ["Tea","Pokémon","Master chef"], ["Pen","Ice skate","Ghost Ship"], ["The Truman Show","Broken English","Sandman"],],
[ ["Drone","The Mummy","Castle"], ["Utility knife","The Exorcist","Sand trap"], ["Move mountains","Ferris Bueller","Calvin and Hobbes"],],
[ ["Ice cube","Ostrich","Marriage"], ["William Tell","Directory","The Sphinx of Giza"], ["Marshmallow","Step on the gas","The Boxcar Children"],],
[ ["Restaurant","Style","Mole"], ["Prosthesis","Leaves of Grass","Maggie Gyllenhaal"], ["Resident Evil","Game of Thrones","Statue of Liberty"],],
[ ["Microscope","Guard","Aircraft carrier"], ["Why Did I Get Married","Ron Howard","Pirates of the Caribbean"], ["Daytona 500","Dagwood","Turn beet red"],],
[ ["Orchestra","Church","Christmas lights"], ["Steam engine","Toothpaste","Heliport"], ["Out of sight, out of mind","E.T. the Extra-Terrestrial","There's something fishy going on"],],
[ ["Fear Factor","Teddy bear","Magpie"], ["Zipper","Makeup","Mosquito netting"], ["Cut in line","Madame Tussaud","Dive right in"],],
[ ["Pineapple","Egg","Mailman"], ["Poodle","McDonald’s","Empire State Building"], ["Loose talk","Lewis Carroll","Fast as lightning"],],
[ ["Barbecue","Assassin","Wasp"], ["Harlequin","Amy Winehouse","Harmonica"], ["Highwater jeans","Add fuel to the fire","Where's the fire?"],],
[ ["Shooting star","Cake","Champagne"], ["Edward Scissorhands","Ghostbusters","Bridget Jones"], ["Wallflower","Bubblegum","The More You Know"],],
[ ["Miner","Prison","Mill"], ["Wait, Wait... Don’t Tell Me!","Poseidon","The Grapes of Wrath"], ["Moonlighting","Drink a toast","Piece of cake"],],
[ ["Strawberry","Firecracker","Fireman"], ["Bill Clinton","Pepper mill","Seal"], ["Fidel Castro (Ruz)","Roll up your sleeves","Die Hard"],],
[ ["Infomercial","Garden hose","Roadrunner"], ["Skeleton","Trampoline","The Green Mile"], ["Tempt fate","Court","The Sun Also Rises"],],
[ ["Air bag","Fox","Binoculars"], ["Hovercraft","Princess","Jumanji"], ["Double-edged sword","Tangled","Jim Carrey"],],
[ ["Clown","GPS","Earring"], ["Casper","Guitar","Swing"], ["Bother somebody","Lucky at cards, unlucky in love","A good eye for distance"],],
[ ["Nightclub","Frog","Hunter"], ["Transformers","Strobe light","Toothbrush"], ["Kill time","The Hunger Games","Hold your breath"],],
[ ["Tiger","Fish","Parasol"], ["Sudoku","Modeling clay","Michael Jordan"], ["Prince Valiant","Mutter under your breath","Martin Luther King"],],
[ ["Subway","Watch","Werewolf"], ["Seven Samurai","The Russian Dolls","Lara Croft"], ["Achilles' heel","Knights of the Zodiac","Bury your head in the sand"],],
[ ["Computer","Windmill","Tinfoil"], ["Home Alone","Diablo","Mayonnaise"], ["Lottery","Ennio Morricone","Hopscotch"],],
[ ["Robot","Starfish","Soccer"], ["Railway line","Braille","Horseshoe"], ["Rio de Janeiro","White as snow","Much ink has been spilled over this"],],
[ ["Wallet","Tin","Diamond"], ["Beach","Lawyer","Cookie"], ["Fools rush in","Smell a rat","From the Earth to the Moon"],],
[ ["Sunscreen","Statue","Doghouse"], ["Flush","Shrek","Dragonfly"], ["Once bitten, twice shy","Twiddle your thumbs","The Flintstones"],],
[ ["Penguin","Library","Doctor"], ["Uncle Scrooge","Aspartame","Croissant"], ["George W. Bush","On pins and needles","Start off with a bang"],],
[ ["Pumpkin","Bra","Panther"], ["Smart card","Waitress","Mary Poppins"], ["Doesn't cost anything","Get an eyeful","Marco Polo"],],
[ ["Concord","The Invisible Man","Radar"], ["Catwoman","Koala","Gunpowder"], ["Circle of friends","Money doesn't grow on trees","When pigs fly"],],
[ ["Electric chair","Windshield wiper","Titanic"], ["Bowling","Bleach","Stiletto heel"], ["Justin Bieber","Dumb as a box of rocks","Pass out"],],
[ ["Parrot","Straw","The Eiffel Tower"], ["Crossword puzzle","Marilyn Manson","Dexter"], ["My precious","Pushing up the daisies","Easter Island"],],
[ ["House M.D.","Toy Story","Cherry"], ["Cupid","The Artist","Compass"], ["Resign","Beat around the bush","Ben-Hur"],],
[ ["Hang glider","Fruit juice","Rudder"], ["Pantyhose","Jurassic Park","Guillotine"], ["Interrupt someone","Flip a coin","Hermione Granger"],],
[ ["Milk","Rhinoceros","Unicorn"], ["The Quest for Fire","Advertisement","Lance Armstrong"], ["Sticks and stones may break my bones","Back to the Future","Silence is golden"],],
[ ["The Pink Panther","Dice","The Simpsons"], ["The Birdcage","Key","Venus de Milo"], ["The road to hell is paved with good intentions","The Roman Colosseum","Vietnam War"],],
[ ["Crosswalk","Santa Claus","Winemaker"], ["Miss America","The French Revolution","Suitcase"], ["Tone it down a little","The Forbidden City","Get your hackles up"],],
[ ["Boots","Diving gear","Ferrari"], ["Lease","The Fox and the Hound","Escalator"], ["Wearing your heart on your sleeve","Seasonal","Be all spruced up"],],
[ ["Ambulance","Syringe","Pajamas"], ["Magnet","Lightsaber","Garbage can"], ["Boys will be boys","Shoot yourself in the foot","Alcatraz"],],
[ ["Table tennis","Gloves","Paper cutter"], ["Oedipus","Station","Caesarean section"], ["Too tired to think straight","Smoke like a chimney","Sistine Chapel"],],
[ ["Cellphone","Infrared telescope","Giraffe"], ["Hannibal Lecter","The Name of the Rose","Toaster"], ["Once Upon a Time in the West","Forked tongue","Church lady"],],
[ ["Eagle","Sunflower","Kitchen"], ["Animal Planet","The Terminator","Circus"], ["Breathless","Top Gun","Cloning"],],
[ ["Bank","Bedroom","Flute"], ["Archimedes","Borat","Fast and Furious"], ["Give free rein","Billy Jean","Eureka!"],],
[ ["Tricycle","Steak","Egypt"], ["Sister Act","Whistle","Desperate Housewives"], ["Bite your tongue","Sigmund Freud","Adam Sandler"],],
[ ["Fan","Coffee","Rattle"], ["Twilight","Batman","Johnny Carson"], ["A picture is worth a thousand words","Have a frog in your throat","Jean-Claude Van Damme"],],
[ ["Dinosaur","Chainsaw","The Smurfs"], ["Crocodile Dundee","Ghost train","The Laughing Cow cheese"], ["Ask for someone's hand","Drug trafficking","The Hundred Years' War"],],
[ ["Spinach","Barge","Heritage"], ["Dr. Jekyll","Moses","Jack Bauer"], ["Esmeralda","The Girl With the Dragon Tattoo","Luke, I am your father"],],
[ ["Harry Potter","Lake","Coca-Cola"], ["Leaving on a Jet Plane","Stand By Me","Casserole"], ["I'd stake my life on it","Fall asleep at the wheel","Nightmare"],],
[ ["Sonic the Hedgehog","Pole vault","Trumpet"], ["Sauna","Romeo and Juliet","Leaning Tower of Pisa"], ["Get up on the wrong side of bed","Pop the cork","Different strokes for different folks"],],
[ ["Polar bear","Witch","Snowman"], ["Lincoln Memorial","Soap","Baguette"], ["Honeymoon","Be deep in the weeds","Weigh on someone's mind"],],
[ ["Feather","Coconut","Port"], ["Parachute","Catapult","Clothespin"], ["Shopping cart","Censorship","A rolling stone gathers no moss"],],
[ ["Yo-yo","101 Dalmatians","Butterfly"], ["Wolverine","Life is Beautiful","Men in Black"], ["Lightning doesn't strike twice in the same place","Live life to the fullest","Older and wiser"],],
[ ["Lumberjack","Mosquito","Microwave oven"], ["Peggy Lee","Boondock Saints","Butterknife"], ["Keep your feet on the ground","Dangerous Liaisons","Starvation"],],
[ ["Ice Age","Dolphin","Water tower"], ["The Black Cauldron","Keyboard","Bruce Lee"], ["Kremlin","Leave someone speechless","Down the wrong hatch"],],
[ ["SpongeBob SquarePants","Spice","Tarzan"], ["Gone With The Wind","Ocean's Eleven","Crop circle"], ["Hungover","Sleep with one eye open","Snoopy"],],
];

}

?>
