<?php
class ConceptCardsDE {
  static $cards = [
    [ ["Biene","Flughafen","Adler"], ["2001: Odyssee im Weltraum","Rock me Amadeus","Ein Platz für Tiere"],["Hoffnungsloser Fall","Mord im Orient-Express","Atemlos"]],
    [ ["Airbag","Aladin","Krankenwagen"], ["Luftkissenfahrzeug","Bauer","Magnet"],["Eine verhängnisvolle Affäre","Mimose","Locker vom Hocker"]],
    [ ["Engel","Gießkanne","Kopfschmerztablette"], ["Nick Knatterton","Albus Dumbledore","Alf"],["Auf der Suche nach der verlorenen Zeit","Al Capone","Ali Baba"]],
    [ ["Mörder","Autoradio","Vogel Strauß"], ["Amy Winehouse","Angry Birds","Telefonbuch"],["Öl ins Feuer gießen","American Beauty","Auf die Tube drücken"]],
    [ ["Avatar","Kampfflieger","Badewanne"], ["Aphrodite","Wasserfarben","Spinne"],["Ein Silberstreif am Horizont","Bis zu den Zähnen bewaffnet sein","Die Wogen glätten"]],
    [ ["Wal","Banane","Bank"], ["Armbrust","Regenbogen","Archimedes"],["Bei den Blinden ist der Einäugige ein König","Staubsauger","Einen Freibrief haben"]],
    [ ["Grill","Barbie","Bücherei"], ["Harlekin","Aufzug","Süßstoff"],["Prinzessin auf der Erbse","Zwei linke Hände haben","Hummeln im Hintern haben"]],
    [ ["Schneewittchen und die 7 Zwerge","Weizen","Spongebob Schwammkopf"], ["Asterix und Obelix","Atlantis","Vom Winde verweht"],["Da läuft mir das Wasser im Munde zusammen","Blut und Wasser schwitzen","Einen Kater haben"]],
    [ ["Konservendose","Pfefferspray","Schneemann"], ["Rechtsanwalt","Bagheera","Baguette"],["Jemandem einen Floh ins Ohr setzen","Kopf in den Wolken haben","Ein großes Herz haben"]],
    [ ["Stiefel","Ohrringe","Backstein"], ["Miete","Schaukel","Balu"],["Das Herz in die Hand nehmen","Pi mal Daumen","Ein Seebär"]],
    [ ["Feuerzeug","Christstollen","Holzfäller"], ["Bambi","Comic","Barbar"],["Höhenangst","Jemandem ein Ohr abkauen","Mit beiden Beinen im Leben stehen"]],
    [ ["Büro","Sonnenuhr","Kaffee"], ["Staudamm","Dampfschiff","Batman"],["Mehrere Eisen im Feuer haben","Ein schlechtes Gewissen haben","Einen Frosch im Hals haben"]],
    [ ["Schulheft","Turnhose","Lastwagen"], ["Batterie","Einsiedlerkrebs","Bier"],["Auf der faulen Haut liegen","Einen Filmriss haben","Nicht alle Tassen im Schrank haben"]],
    [ ["Löschflugzeug","Ente","Kanarienvogel"], ["Bilbo Beutlin","Billard","Billy the Kid"],["Einen Bärenhunger haben","Hohes Fieber","Fußbad"]],
    [ ["Kantine","Bus","Kreditkarte"], ["Bob Marley","Briefkasten","Atombombe"],["Bajonett","Höhensonne","Aus etwas Kleinholz machen"]],
    [ ["Helm","Keller","Flugdrachen"], ["Stöpsel","Kessel","Bäcker"],["Man muss das Eisen schmieden, solange es noch heiß ist.","Einen Rekord brechen","Stottern"]],
    [ ["Kirsche","Elektrischer Stuhl","Landhaus"], ["Kompass","Bowling","Bowling for Columbine"],["Ben Hur","Xavier Naidoo","Big Ben"]],
    [ ["Schlafzimmer","Sekt","Hut"], ["Keinohrhasen","Bridget Jones","Brigitte Bardot"],["Billy Jean","Verkehrsfunk","Kriegswunden"]],
    [ ["Jäger","Wasserturm","Burg"], ["Zahnbürste","Bruce Lee","Bunker"],["Den Atem anhalten","Baden gehen","Nichtlustig"]],
    [ ["Fledermaus","Kamin","Hemd"], ["Kakerlake","Kaffeemaschine","Taschenrechner"],["Herzzerreißend","Haarbürste","Alles schwarz sehen"]],
    [ ["Pferd","Kaugummi","Schokolade"], ["Chamäleon","Pudel","Captain Future"],["Gerüchteküche","Ein hartnäckiges Gerücht","Bei Rot fahren"]],
    [ ["Kino","Kürbis","Blinklicht"], ["Captain Haddock","Chipkarte","Postkarte"],["Das ist klar wie Kloßbrühe","Das frisst ja kein Brot","Ins Schwarze treffen"]],
    [ ["Glocke","Clown","Coca Cola"], ["Casino Royale","Sandmännchen","Topf"],["Charakterschwein","Jemandem auf den Wecker gehen","Albtraum"]],
    [ ["Schwein","Kompass","Concorde"], ["Biber","Katapult","Catwoman"],["Viele Wege führen nach Rom","Zensur","Freundeskreis"]],
    [ ["Spielekonsole","Muschel","Brieföffner"], ["Aschenputtel","Hirsch","Kaiserschnitt"],["Teufelskreis","Waffenruhe","Die Sixtinische Kapelle"]],
    [ ["Schweizer Taschenmesser","Krabbe","Sonnencreme"], ["Nina Hagen","Ladegerät","Spülung"],["Die Brüder Grimm","Die Katze lässt das Mausen nicht","Ein gebranntes Kind scheut das Feuer"]],
    [ ["Pfannkuchen","Krokodil","Popel"], ["Weg","Zielscheibe","Fifty Shades of Grey"],["Eine Nadel im Heuhaufen suchen","Til Schweiger","Freier Fall"]],
    [ ["Küche","Delfin","Würfel"], ["Zirkus","Tastatur","Schlüssel"],["Klonen","Jemandem das Maul stopfen","Das Kolosseum in Rom"]],
    [ ["Brettspiel","Verkleidung","Drachenflieger"], ["Strichcode","Yvonne Catterfeld","Strumpfhose"],["Seine Sünden beichten","Pfefferminztee","Jemandem das Wort abschneiden"]],
    [ ["Gebiss","Abschleppwagen","Diamant"], ["Buchhalter","Gurke","Keks"],["Primaballerina","David und Goliath","Die Reise zum Mittelpunkt der Erde"]],
    [ ["Wörterbuch","Dinosaurier","Doktor"], ["Wolfsblut","Crocodile Dundee","Croissant"],["Flaschenöffner","Um die Hand anhalten","Gummi geben"]],
    [ ["Dr. House","Drache","Drohne"], ["Amor","Zahnstocher","Cutter"],["Kündigen","Demokratie","Berge versetzen"]],
    [ ["DVD","Leiter","Sonnenfinsternis"], ["Fahrradfahrer","Cyrano de Bergerac","D’Artagnan"],["In Flammen aufgehen","Detektiv","Perlen vor die Säue"]],
    [ ["Schleuse","Schule","Eichhörnchen"], ["Dalai Lama","Herbert Grönemeyer","David Guetta"],["Sich aufs Ohr hauen","Schlafen wie ein Murmeltier","Dragon Ball Z"]],
    [ ["Kirche","Ägypten","Elefant"], ["Zahnpasta","Desperate Housewives","Final Destination"],["E.T.","Mario Barth","Eminem"]],
    [ ["Elfe","Windkraftwerk","Schwert"], ["Teufel","Diabolo","Kaya Yanar"],["Mit ganzem Herzen dabei sein","Ennio Morricone","Das Kriegsbeil ausgraben"]],
    [ ["Spinat","Schnecke","Schwertfisch"], ["Dr. Jekyll","Dumbo","Dynamit"],["Esmeralda","Kriminelle Energie","Im 7. Himmel sein"]],
    [ ["Scheibenwischer","Seestern","Sternschnuppe"], ["Bleichmittel","Blindenschrift","Edward mit den Scherenhänden"],["Dumm wie Bohnenstroh","Weiß wie Schnee","Warmduscher"]],
    [ ["Feuerlöscher","Briefträger","Fee"], ["Elton John","Empire State Building","Dünger"],["Schneckentempo","Blitzschnell sein","Stocktaub sein"]],
    [ ["Fenster","Ferrari","Flöte"], ["Sicherheitsnadel","Rolltreppe","Fast and Furious"],["Hans Guck-in-die-Luft","Todschick sein","Heureka!"]],
    [ ["Fußball","Heidelberger Schloss","Mikrowelle"], ["Hunger","Hufeisen","Reißverschluss"],["Pressewirbel verursachen","Eine Kurve schneiden","Er hat die Weisheit nicht mit Löffeln gefressen"]],
    [ ["Gabel","Erdbeere","Rakete"], ["Forrest Gump","Helmut Kohl","Pommes Frites"],["Jemandem einen Bären aufbinden","Fidel Castro","Fight Club"]],
    [ ["Gewehr","Handschuhe","Garage"], ["Frettchen","Bahnhof","Der weiße Riese"],["Sich in Nichts auflösen","Rauchen wie ein Schlot","Rudi Carrell"]],
    [ ["Wächter","Kuchen","Genie"], ["Loriot","Ghostbusters","Gladiator"],["Gaston","Gummi","Die Chinesische Mauer"]],
    [ ["Giraffe","Wetterhahn","Eiswürfel"], ["Toaster","Krieg und Frieden","Wilhelm Tell"],["Eine Betschwester","Neandertal","Marshmallow"]],
    [ ["Ruder","GPS","Dachboden"], ["Guillotine","Gitarre","Gustave Eiffel"],["Hermine Granger","Pech im Spiel, Glück in der Liebe","Seepferdchen"]],
    [ ["Frosch","Mobiltelefon","Wespe"], ["Blaulicht","Hannibal Lecter","Mundharmonika"],["Die Tribute von Panem","Spiel mir das Lied vom Tod","Das ist doch kein Beinbruch"]],
    [ ["Lichterkette","Turnhalle","Harpune"], ["Hubschrauberlandeplatz","Schwalbe","Hula-Hoop-Reifen"],["Jägerlatein","Inception","Juri Gagarin"]],
    [ ["Harry Potter","Igel","Erbschaft"], ["Das ist die Berliner Luft","Indiana Jones","Jack Bauer"],["Dafür lege ich meine Hand ins Feuer","Aller guten Dinge sind drei","Ich bin dein Vater, Luke"]],
    [ ["Rassel","Hotel","Iglu"], ["Otto Waalkes","Whirlpool","Johanna von Orleans"],["Jean-Claude Van Damme","Hape Kerkeling","Jean-Paul Belmondo"]],
    [ ["Druckerei","iPad","Iron Man"], ["John Lennon","Die Möwe Jonathan","Judas"],["Günther Jauch","Geld zum Fenster hinauswerfen","Das Handtuch werfen"]],
    [ ["Jeans","Ferien","Ferngläser"], ["Jukebox","Julia Roberts","Jumanji"],["Der werfe den ersten Stein","Rotz und Wasser heulen","Jim Carrey"]],
    [ ["Saft","Känguru","Hupe"], ["Jurassic Park","Karaoke","Kill Bill"],["Kopf oder Zahl","Das kleine Arschloch","Kiwi"]],
    [ ["Eiszeit","Der Unsichtbare","Die Mumie"], ["Kalif Storch","Koalabär","Der Exorzist"],["Der Kreml","Das Geld liegt nicht auf der Straße","Der kleine Nick"]],
    [ ["Der rosarote Panther","Unsere kleine Farm","Der Eiffelturm"], ["Ein Käfig voller Narren","Tinker Bell","Dexter"],["Der Weg zur Hölle ist mit guten Vorsätzen gepflastert","Nightmare Before Christmas","Die Osterinseln"]],
    [ ["Der See","Milch","Marsupilami"], ["Das fliegende Klassenzimmer","Am Anfang war das Feuer","The Green Mile"],["Ein gutes Gewissen ist ein sanftes Ruhekissen","Das 5. Rad am Wagen sein","Heimat"]],
    [ ["Findet Nemo","Der Weihnachtsmann","MP3-Spieler"], ["Planet der Affen","Die Französische Revolution","Glücksrad"],["Das Tüpfelchen auf dem i","Die verbotene Stadt","Der Blitz schlägt nie zweimal am selben Ort ein"]],
    [ ["101 Dalmatiner","Die Schlümpfe","Die Simpsons"], ["Der Hauptmann von Köpenick","Haribo","Die Venus von Milo"],["Der 100jährige Krieg","Vietnam Krieg","Reden ist Silber, Schweigen ist Gold"]],
    [ ["Einhorn","Löwe","Wolf im Schafspelz"], ["Lance Armstrong","Schleuder","Zeichensprache"],["Das Mädchen mit den Schwefelhölzern","Der Stein von Rosetta","Vogel-Strauß-Politik"]],
    [ ["Werwolf","Lupe","Schlitten"], ["Lara Croft","Lassie","Im Rausch der Tiefe"],["Der Turm zu Babel","Laika","John Sinclair"]],
    [ ["Sonnenbrille","Infrarotbrille","Nähmaschine"], ["Das Dschungelbuch","Der Name der Rose","Der kleine Däumling"],["Sich das Maul zerreißen","Perry Rhodan","Gehirnwäsche"]],
    [ ["Zauberer","Altersheim","Lehrer"], ["Der kleine Prinz","Sonderzug nach Pankow","Woyzeck"],["Das fünfte Element","Zwei glorreiche Halunken","Der Club der Toten Dichter"]],
    [ ["Blümchen","Ehe","Gasmaske"], ["Der Herr der Ringe","Die Sphinx","Am Tag als Conny Kramer starb"],["5 Freunde","Sonntagszeitung","Sandmännchen"]],
    [ ["Chef","Die Biene Maja","Mechaniker"], ["Das Geisterschiff","Männer sind Schweine","Yeti"],["Die Muppet Show","Tod auf dem Nil","Die Seufzerbrücke"]],
    [ ["Qualle","Meteorit","U-Bahn"], ["Lego","Kontaktlinsen","Die 7 Samurai"],["Die Aufklärung","Achillesferse","Die Tour de France"]],
    [ ["Mikroskop","Minecraft","Jugendlicher"], ["Theo gegen den Rest der Welt","Der Weiße Hai","Heute-Show"],["In 80 Tagen um die Welt","Schwarzarbeit","Der Eiserne Thron"]],
    [ ["Mode","Monopoly","Berg"], ["Buddenbrooks","Die Vögel","Die Säulen der Erde"],["Super Mario Kart","Die 7 Weltwunder","Die Ritter der Tafelrunde"]],
    [ ["Uhr","Fliege","Mühle"], ["Babuschka-Puppen","Tom Sawyer","Früchte des Zorns"],["Die Götter müssen verrückt sein","Das ist kinderleicht","Gefährliche Liebschaften"]],
    [ ["Moskito","Museum","Schwimmen"], ["Die purpurnen Flüsse","Die Sims","Teenage Mutant Ninja Turtles"],["Weiche Knie bekommen","Max und Moritz","Jim Knopf und die Wilde 13"]],
    [ ["Hundehütte","Nest","Ninja"], ["Libelle","Luc Besson","Lucky Luke"],["Der Schuh des Manitu","Fix und Foxi","Der bewegte Mann"]],
    [ ["Nutella","Ei","Oger"], ["Toilettensitz","McDonald’s","MacGyver"],["Lewis Carroll","Daniela Katzenberger","Aus den Augen, aus dem Sinn"]],
    [ ["Orchester","Computer","Eisbär"], ["Dampfmaschine","Kevin - Allein zu Haus","Manneken Pis"],["Lotterie","Flitterwochen","Madame Tussaud"]],
    [ ["Teddybär","Pac-Man","Stroh"], ["Make-up","Margaret Thatcher","Marilyn Manson"],["Todtraurig sein","Sich die Radieschen von unten ansehen","Marco Polo"]],
    [ ["Panther","Aluminiumfolie","Schmetterling"], ["Mary Poppins","Majonäse","Men in Black"],["Himmel und Hölle","Jung gefreit, nie gereut","Mars Attacks!"]],
    [ ["Regenschirm","Sonnenschirm","Blitzableiter"], ["Mutter Teresa","Michael Jordan","Mikrofon"],["Martin Luther King","Maske","Bettler"]],
    [ ["Parkuhr","Parfüm","Zebrastreifen"], ["Mike Tyson","Anke Engelke","Miss Germany"],["Unterschwellige Botschaften","Wasser predigen, Wein trinken","Butter bei die Fische"]],
    [ ["Fischer","Schaufel","Frachtkahn"], ["Mister Bean","Muhammad Ali","Moses"],["Ins Fettnäpfchen treten","Verblendung","Eine Hausfrau hat das im Gefühl"]],
    [ ["Bohrmaschine","Papagei","Knallfrosch"], ["Herr Kartoffelkopf","Kreuzworträtsel","Pfeffermühle"],["Mein Schatz","Sich bis aufs letzte Hemd ausziehen","Stumm wie ein Fisch"]],
    [ ["Peter Pan","Klavier","Elster"], ["Es fährt ein Zug nach Nirgendwo","Schnurrbart","Fliegengitter"],["Unverfroren sein","Auf der Glückswelle reiten","Auf zwei Hochzeiten tanzen"]],
    [ ["Pilot","Gewürz","Tischtennis"], ["Angela Merkel","Ocean’s Eleven","Ödipus"],["Ein Auge riskieren","Den Wald vor lauter Bäumen nicht sehen","Neil Armstrong"]],
    [ ["Pinguin","Pinocchio","Pirat"], ["Onkel Dagobert","Uhrwerk Orange","Orgel"],["Dem Affen Zucker geben","Ein blaues Auge / Veilchen","Augen wie ein Luchs"]],
    [ ["Schwimmbad","Segelflugzeug","Autokennzeichen"], ["Jerry Cotton","Palme","Pamela Anderson"],["Schattenspiel","Wo gehobelt wird, da fallen Späne","Die Büchse der Pandora"]],
    [ ["Klempner","Feder","Fisch"], ["Toilettenpapier","Fallschirm","Töpfern"],["Der Warenkorb","In den Bart murmeln","Gebrochenes Deutsch sprechen"]],
    [ ["Pokémon","Polizist","Apfel"], ["Schlittschuhe","Knecht Ruprecht","Leuchtturm"],["Den Löffel abgeben","Den Kopf verlieren","Stirb langsam"]],
    [ ["Feuerwehrmann","Hafen","Flugzeugträger"], ["Seehund","Stecknadeln","Fluch der Karibik"],["Wer rastet, der rostet","Einen roten Kopf bekommen","Einen Kopfsprung machen"]],
    [ ["Brieftasche","Blumentopf","Ausschalter"], ["Strand","Bohrinsel","Popcorn"],["Je oller, je doller","Popeye","Einen Toast ausbringen"]],
    [ ["Gefängnis","Brunnen","Schlafanzug"], ["Poseidon","Post-it","Mülleimer"],["Jemanden verschaukeln","Gefängnis von Alcatraz","Am St. Nimmerleinstag"]],
    [ ["Radar","Kühlschrank","Fuchs"], ["Schießpulver","Power Rangers","Prinzessin"],["Rain Man","Rapunzel","Das Feuer entfachen"]],
    [ ["Hai","Restaurant","Nashorn"], ["Prison Break","Prothese","Werbung"],["Resident Evil","Zurück in die Zukunft","Jemandem etwas unter die Nase reiben"]],
    [ ["Gardine","Fluss","Roboter"], ["Quidditch","Heizkörper","Eisenbahnstrecke"],["Kommissar Rex","Rio de Janeiro","Robinson Crusoe"]],
    [ ["Rad","Zauberwürfel","Valentinstag"], ["Ratte","Königin","Robin Hood"],["Das Schweigen brechen","Schilf","Die Muskeln spielen lassen"]],
    [ ["Salat","Tannenbaum","Stabhochsprung"], ["Rocky","Rollschuhe","Romeo und Julia"],["Rumknutschen","Auf ex trinken","Der heilige Petrus"]],
    [ ["Free Willy","Taucheranzug","Skorpion"], ["Cap und Capper – Zwei Freunde auf acht Pfoten","Lippenstift","Rugby"],["Saisonarbeiter","Vom Hölzchen aufs Stöckchen kommen","Zur Sache, Schätzchen"]],
    [ ["Spritze","Schlange","Affe"], ["Laserschwert","Der Heilige Gral","Wildschwein"],["Sich selbst ein Bein stellen","Sich graue Haare wachsen lassen","Jemanden hinters Licht führen"]],
    [ ["Sombrero","Seife","Hexe"], ["Wurst","Sauna","Sonic"],["Arschbombe","Mit dem linken Fuß aufstehen","Ein Schlag ins Wasser"]],
    [ ["Fliegende Untertasse","Maus","U-Boot"], ["Tesafilm","Eimer","Klaus Kinski"],["Sich in Schale schmeißen","Nabelschau betreiben","Sie gleichen sich wie ein Ei dem anderen"]],
    [ ["BH","Statue","Steak"], ["Kellnerin","Shrek","Pfeife"],["Stielaugen machen","Däumchen drehen","Sigmund Freud"]],
    [ ["Stethoskop","Teppich","Tarzan"], ["Silikon","Snowboard","Glocke"],["Der Krug geht so lange zum Brunnen bis er bricht","Six feet under","Skyfall"]],
    [ ["Maulwurf","Stier","Teleshopping"], ["Veronica Ferres","Snoopy","Skelett"],["Spirou","Freiheitsstatue","Die Christusstatue in Rio de Janeiro"]],
    [ ["Sturm","Tennis","Tetris"], ["Raumstation","Stephanie von Monaco","Stonehenge"],["Den Anstandswauwau spielen","Rolf Kauka","Mit Schirm, Charme und Melone"]],
    [ ["Tee","Tiger","Tipi"], ["Füllfederhalter","Sudoku","Sushi"],["Die Truman Show","Siegfried der Drachentöter","Tina Turner"]],
    [ ["Sparschwein","Titanic","Rasenmäher"], ["Bleistiftspitzer","Highheels","Tandem"],["Korkenzieher","Ins Gras beißen","Es schüttet aus Kübeln"]],
    [ ["Sonnenblume","Toy Story","Traktor"], ["Terminator","The Artist","Thermoskanne"],["Top Gun","Um den heißen Brei herumreden","Ganz von vorne anfangen"]],
    [ ["Dreirad","Trompete","Kettensäge"], ["Sister Act","Turm von Pisa","Geisterzug"],["Sich auf die Zunge beißen","Jedem Tierchen sein Pläsierchen","Drogen handeln"]],
    [ ["Gartenschlauch","Nachtclub","Kuh"], ["Trampolin","Transformers","Trivial Pursuit"],["Gerichtshof","Zeit totschlagen","Flotte Biene"]],
    [ ["Vampir","Geier","Fahrrad"], ["Troll","Schwarzes Loch","Tsunami"],["Ein ungedeckter Scheck","Schönheitsfleck","Vorbeugen ist besser als nachsehen"]],
    [ ["Freitag, der 13.","Ventilator","Veranda"], ["Tupperware","Twilight – Bis(s) zum Morgengrauen","Impfstoff"],["Jemandem ein Ohr abkauen","Ein Bild sagt mehr als 1000 Worte","Liebesroman"]],
    [ ["Winzer","Wein","Vitamine"], ["Koffer","Klettverschluss","20.000 Meilen unter dem Meer"],["Ein starke Opposition","Wolf im Schafspelz","V wie Vendetta"]],
    [ ["Vulkan","Joghurt","Jo-Jo"], ["Whisky","Pu der Bär","Wolverine"],["Die Seele dem Teufel verkaufen","Toilettenpümpel","Ein Leben auf der Überholspur"]],
    [ ["Yoda","Zebra","Zorro"], ["Woody Allen","Xylophon","The Legend of Zelda"],["Auch ein blindes Huhn findet mal ein Korn","Dieb","Glucke"]],

    [ ["Puppenhaus","Kugelschreiber","Fossil"], ["Grippe","Vaiana","Pokerchip"],["Nofretete","Den Stier bei den Hörnern packen","Escape Room"]],
    [ ["Garnele","Sand","Mathematik"], ["Dachs","ICE","Cluedo"],["Dr. Watson","Ein Geheimnis verraten","Silo"]],
    [ ["Zahnarzt","Sägewerk","Ameise"], ["Sensenmann","Sahnetorte","Konrad Adenauer"],["Distel","Bibis Beauty Palace","Der Apfel fällt nicht weit vom Stamm"]],
    [ ["Mönch","Paradies","Schürze"], ["Hot Dog","Südafrika","Ich – einfach unverbesserlich"],["Walt Disney","Gleich und Gleich gesellt sich gern","Verkehrsschild"]],
    [ ["Schwamm","Krankenhaus","Pikachu"], ["Wolfgang Amadeus Mozart","Skilift","Kleingarten"],["Notlüge","Jemanden über den grünen Klee loben","Die Ritter der Kokosnuss"]],
    [ ["Darm","PlayStation","Kapitän"], ["Jaguar","Orden","X-Men"],["Mad Max","Justin Bieber","Der Glaube versetzt Berge"]],
    [ ["Jagd","Axt","Pups"], ["Lightning McQueen","Mekka","Sauerkraut"],["Schmutzige Wäsche in der Öffentlichkeit waschen","Quentin Tarantino","Alphabet"]],
    [ ["Medikament","Karussell","Mona Lisa"], ["Magma","Graffiti","Tomb Raider"],["Einen Kompromiss schließen","Radioaktivität","Wirbelsäule"]],
    [ ["Formel 1","Ballett","Portemonnaie"], ["The Walking Dead","Hieroglyphen","Spülmaschine"],["Nichts Halbes und nichts Ganzes","Wall-E","Christopher Street Day"]],
    [ ["Spieß","Brücke","Schubkarre"], ["Bürgersteig","Deutschland sucht den Superstar","Brauerei"],["Der Dunkle Turm","Periodensystem","Error 404"]],
    [ ["Gewitter","Limonade","Brief"], ["Curling","Kloster","Tinnitus"],["Sich ins gemachte Nest setzen","Ochsenschwanzsuppe","Gollum"]],
    [ ["Kanalisation","Wecker","Lieferant"], ["Moskau","Pythagoras","Schlafsack"],["1984","Johnny Cash","Gemeinsam sind wir stark"]],
    [ ["Pony","Wassermühle","Himbeere"], ["Schraube","Times Square","Teleskop"],["Rock ’n’ Roll","Die Niagarafälle","Schummeln"]],
    [ ["Bar","Basteln","Holzbein"], ["Albert Einstein","Der Pate","Lasertag"],["Takeshi’s Castle","Musikantenknochen","Joachim Löw"]],
    [ ["Schreien","Bogenschießen","Die Minions"], ["Eragon","Panzer","Speck"],["Mittelalter","Wind und Wetter trotzen","Son Goku"]],
    [ ["Socke","Pudelmütze","Donut"], ["Kühlergrill","Klebstoff","Polarstern"],["Döner","Jura","Geld wie Heu haben"]],
    [ ["Wurfstern","Hocker","Taxi"], ["Wasserski","Krater","Grashüpfer"],["Cool Runnings","Eine Gelegenheit verpassen","Die Bremer Stadtmusikanten"]],
    [ ["Chirurg","Bauernhof","Luftballon"], ["Athen","Umweltverschmutzung","Punkrock"],["Die Chroniken von Narnia","Etwas durch die Blume sagen","Hipster"]],
    [ ["Rabe","Brezel","Einrad"], ["Miraculix","Nelson Mandela","Angelhaken"],["Fitnessstudio","Alchemie","Die fabelhafte Welt der Amélie"]],
    [ ["London","Nadel","Tanzen"], ["Metallica","Erbsenzähler","Litschi"],["Donald Duck","Surfen","Rapmusik"]],
    [ ["Faulpelz","Der König der Löwen","Glühbirne"], ["Manschetten","Ludwig XIV","Brüssel"],["Rammbock","The Big Bang Theory","Christo"]],
    [ ["Drehtür","Spaghetti","Bison"], ["Spitzhacke","Dreizack","Madonna"],["UdSSR","Zu Hause die Hosen anhaben","House of Cards"]],
    [ ["E-Mail","Hulk","Maurer"], ["Raumschiff Enterprise","Kreuzzug","Wirt"],["Kraken","Madagaskar","Marilyn Monroe"]],
    [ ["Karawane","Kipplaster","Alarm"], ["Wickie und die starken Männer","Frisbee","Lotusblüte"],["Etwas für einen Apfel und ein Ei kaufen","Elon Musk","Zwieback"]],
    [ ["Algen","Stretchlimousine","Las Vegas"], ["Jacke wie Hose","Die Fantastischen Vier","Bonsai"],["Hybridauto","Gremlins","Dr. Oetker"]],
    [ ["Unterwäsche","Eisberg","Schach"], ["Tom und Jerry","Marionette","Verlies"],["Stranger Things","E-Sport","Textmarker"]],
    [ ["Schneeball","Riese","Captain Hook"], ["Facebook","Bagel","Jonglieren"],["Aragorn","David Copperfield","Kalifornien"]],
    [ ["China","Hummer","Wüste"], ["Betrüger","Die drei Musketiere","Trockner"],["Candle-Light-Dinner","Instagram","Offene Türen einrennen"]],
    [ ["Friseur","Das Weiße Haus","Schauspielerin"], ["Haarausfall","Leichtathletik","Sturmtruppler"],["Luftdruck","Die unendliche Geschichte","Erdmännchen"]],
    [ ["Wandern","Zitrone","Ampel"], ["Grönland","Rodeln","LKW"],["Illuminati","Odin","John Travolta"]],
    [ ["Kröte","Regenwurm","Darts"], ["Geschirr","Call of Duty","Pearl Harbor"],["Paralympische Spiele","Bushaltestelle","Zuckerwatte"]],
    [ ["Flamingo","Tigger","Meer"], ["Jazz","Einsame Insel","Excalibur"],["Steven Spielberg","Hyperaktiv","Für etwas Feuer und Flamme sein"]],
    [ ["Tageszeitung","Goldbarren","Lachs"], ["Terrier","Bill Gates","Pinzette"],["Die Berliner Mauer","Final Fantasy","Die Würfel sind gefallen"]],
    [ ["Angriff","Brokkoli","Zaubertrank"], ["Marathon","Modellbau","Ausweis"],["Deniz Yücel","Susi und Strolch","Joystick"]],
    [ ["Koch","James Bond","Friedhof"], ["Handfeger","Ziemlich beste Freunde","Jogginghose"],["Asteroid","Wilhelm Busch","Candy Crush"]],
    [ ["Rotkäppchen","Eule","Astronaut"], ["Fabrik","Sprungbrett","Queen Elisabeth II"],["Union","Seinen Senf dazugeben","Red Hot Chili Peppers"]],
    [ ["Tomate","Gorilla","Gummiband"], ["Dungeons & Dragons","Rückenwind","Breaking Bad"],["Edith Piaf","Godzilla","Die kleine Raupe Nimmersatt"]],
    [ ["Weinen","Kabine","Apotheker"], ["Tattoo","Zeppelin","Spiegel"],["James Cameron","Die Hände in Unschuld waschen","Gandalf"]],
    [ ["King Kong","Der Schiefe Turm von Pisa","Schatulle"], ["Adamsapfel","Satellit","Zentaur"],["Uran","Die Friedenspfeife rauchen","Agatha Christie"]],
    [ ["Kobold","Polizei","Singen"], ["Commander Spock","Dolch","Traum"],["Quarks & Co","Visitenkarte","Emoji"]],
    [ ["Priester","Hamster","Aubergine"], ["Skateboard","1001 Nacht","Wonder Woman"],["Da wird der Hund in der Pfanne verrückt","Saxophon","Der Schwarze Tod"]],
    [ ["Steinzeit","Kanu","Perücke"], ["Florida","Dornröschen","Der Vatikan"],["David Bowie","Kleider machen Leute","Orchidee"]],
    [ ["Hahn","Stoppuhr","Großmutter"], ["Geographie","Green Lantern","Einatmen"],["Rettungswagen","Immanuel Kant","Satyr"]],
    [ ["Schnuller","Disco","Roller"], ["Eurovision Song Contest","Rezeption","Elvis"],["Spermium","Columbo","Gänsehaut"]],
    [ ["Handschellen","Paris","Plüschtier"], ["Lasso","Knieprothese","Wodka"],["Platzpatrone","Black Swan","Gottesanbeterin"]],
    [ ["Laden","Ritter","Kannibale"], ["Umkleidekabine","Cheerleader","Eidechse"],["Nicht alle beisammen haben","Katzencafé","Black Mirror"]],
    [ ["Wassermelone","Butter","Hitzewelle"], ["Kamera","Hypnotiseur","Buzz Lightyear"],["Zahlenschloss","Bräutigam","Hamlet"]],
    [ ["Zyklop","Rohr","Krawatte"], ["Oasis","Yoga","Apfelstrudel"],["Pulp Fiction","Eye of the Tiger","Das Bermudadreieck"]],
    [ ["Mohnblume","Erdöl","Taube"], ["Tag der deutschen Einheit","Michael Jackson","Greif"],["Matthias Schweighöfer","Käpt’n Blaubär","Dumm wie Brot"]],
    [ ["Kleiderschrank","Mammut","Glatze"], ["Einbruch","BH","Tim und Struppi"],["Heute kann es regnen, stürmen oder schneien","Mundgeruch","Richard Löwenherz"]],
    [ ["Hirte","Die Eiskönigin","Star Wars"], ["Minigolf","Rambo","Katy Perry"],["Perlenschnur","Albert Camus","Konfuzius"]],
    [ ["Badeanzug","Kamm","Riesenrad"], ["Heißluftballon","Trojanisches Pferd","Olympische Winterspiele"],["Zirkusdirektor","Bitter","Daft Punk"]],
    [ ["Meise","Arbeitsloser","Eckzahn"], ["Flipperautomat","Eishockey","Rübe"],["Brexit","Bilderrätsel","Per Anhalter durch die Galaxis"]],
    [ ["Biologie","Pylon","Golf"], ["Origami","Luigi","Pfau"],["Mit jemandem unter einer Decke stecken","Will Smith","Der Struwwelpeter"]],
    [ ["Halskette","Schlagzeuger","Gespenst"], ["Umzug","Google","Börse"],["Klassische Musik","Noch ist nicht aller Tage Abend","Pixel"]],
    [ ["Springseil","Salz","Weltreise"], ["Güterwagen","Greenpeace","Dieselmotor"],["Pfadfinder","Gerechtigkeit","Minotaurus"]],
    [ ["Strohhalm","Schinken","Kerze"], ["Scheinheilig","Nagellack","Mousse au Chocolat"],["Immobilienmakler","Schau mir in die Augen, Kleines!","Risiko"]],
    [ ["Schaf","Boje","Quark"], ["Heuschrecke","Thunfisch","Der Joker"],["Die Zeit heilt alle Wunden","Bulldogge","Ultraviolett"]],
    [ ["Journalist","Käse","König"], ["Hängematte","Pantomime","Architekt"],["Horst Lichter","Cthulhu","Hut ab"]],
    [ ["Rettich","Tisch","Zigarre"], ["Game of Thrones","Muffin","Wurzel"],["Britney Spears","Planierraupe","Merlin"]],
    [ ["Model","Kreisel","Windel"], ["Uniform","Auf Holz klopfen","Erste Hilfe"],["Rumpelstilzchen","Viele Köche verderben den Brei","Atmosphäre"]],
    [ ["Salami","Märchenprinz","Ring"], ["Domino","Wolkenkratzer","Stalaktit"],["Snapchat","Nirvana","Schule schwänzen"]],
    [ ["Zombie","Gans","Springbrunnen"], ["Silvester","Hausstaubmilbe","Michael Schumacher"],["Uranus","Starsky & Hutch","Kaltlassen"]],
    [ ["Lesen","Wasserhahn","Schere, Stein, Papier"], ["Kaviar","Stromzähler","Fischstäbchen"],["Kronleuchter","Eins führt zum anderen","Matrix"]],
    [ ["Abrissbirne","Seerose","Geige"], ["Guardians of the Galaxy","Kreisverkehr","Hamburger"],["Raus aus den Federn!","Garfield","Tony Hawk"]],
    [ ["Pizza","Schlaflied","Blind"], ["Regel","Saphir","Piranha"],["Furzkissen","Vorbild","Sherlock Holmes"]],
    [ ["Lampe","Vegetarier","Herde"], ["Burj Khalifa","Schlagsahne","Donkey Kong"],["Counter-Strike","Alles im Griff","Wikipedia"]],
    [ ["Kilt","Sumoringer","Suppe"], ["Dr. Frankenstein","Anrufbeantworter","Den Kopf in den Sand stecken"],["Spielautomat","Kundendienst","Alter Schwede"]],
    [ ["Geburtstag","Bohnen","Peitsche"], ["Tretboot","USB-Stick","Inspektor Gadget"],["Beleidigte Leberwurst","Psychose","Ärzte ohne Grenzen"]],
    [ ["Birne","Lutscher","Arnold Schwarzenegger"], ["Ouzo","Fliegenklatsche","Klebezettel"],["Urinal","Twitter","Tyrion Lennister"]],
    [ ["Bonbon","Mandarine","Raumschiff"], ["Trichter","RoboCop","Leonardo da Vinci"],["Quinoa","DuckTales","Sia"]],
    [ ["Flasche","Rechter Winkel","Kleeblatt"], ["Krematorium","ADAC","Kung Fu Panda"],["Steinbock","Gaius Julius Cäsar","Halbschatten"]],
    [ ["Tinte","Wasserkocher","Casino"], ["Das Glück der Erde liegt auf dem Rücken der Pferde","Fächer","Belagerung"],["Crashtest","Tschernobyl","Koloss von Rhodos"]],
    [ ["Meerjungfrau","Käfig","Die Bibel"], ["Spielhalle","Universum","How I Met Your Mother"],["Utopie","Die Glücksbärchis","Titanium"]],
    [ ["Reis","Antenne","Elch"], ["Marmelade","Renaissance","Krimi"],["Widder","Der Ton macht die Musik","Scarface"]],
    [ ["Streichholz","Champignon","Panda"], ["Rettungsschwimmer","Hello Kitty","Die Feuerzangenbowle"],["Tigerenten Club","Josef Stalin","Der Große Wagen"]],
    [ ["Zoo","Hölle","T-Rex"], ["Koralle","Fön","Gleichgeschlechtliche Ehe"],["Wie vom Erdboden verschluckt","Zypern","Inspektor Clouseau"]],
    [ ["Seiltänzerin","Tausendfüßler","Europa"], ["Diplomat","Schallplatte","NASA"],["Bis über beide Ohren in Arbeit stecken","Das Guinnessbuch der Rekorde","Wikingerschiff"]],
    [ ["Luftschlange","Krücke","Shampoo"], ["Schiedsrichter","Wladimir Putin","Rutsche"],["Ultraschall","Schief singen","Star Trek"]],
    [ ["Dach","Angel","Der Kalte Krieg"], ["Auster","Mars","Pocahontas"],["Kaleidoskop","Souvenir","Jemanden ans Messer liefern"]],
    [ ["Spider-Man","Rucksack","Zwerg"], ["Panini","Katana","Groot"],["Herztransplantation","Die Katze im Sack kaufen","Pompeji"]],
    [ ["Pyramide","Pistole","Kätzchen"], ["Homer Simpson","Trapez","Zucchini"],["Jemandem etwas aus der Nase ziehen","Bleifuß","Erich Kästner"]],
    [ ["Nilpferd","Anker","Dusche"], ["Regisseur","Geysir","Am Rockzipfel hängen"],["Alice im Wunderland","Alles nur geklaut","Seilrutsche"]],
    [ ["Kindertagesstätte","Zukunft","Granate"], ["Achterbahn","Gymnastik","AC/DC"],["Jane Austen","Sich wie die Axt im Walde benehmen","Kermit der Frosch"]],
    [ ["Indien","Zug","Tresor"], ["R2-D2","Kissen","Passepartout"],["Zoomania","Helene Fischer","Gin Tonic"]],
    [ ["Falschgeld","Reise","Mais"], ["Hier spielt die Musik","Kranich","Netflix"],["Mojito","Katastrophe","Martin Scorsese"]],
    [ ["Werkzeugkasten","Tierarzt","Waschmaschine"], ["Dudelsack","Psychologe","Poesie"],["Saw","Retten, was noch zu retten ist","Roger Federer"]],
    [ ["Tempel","Goldmedaille","Honig"], ["Roulade","Praktikant","Atomkraftwerk"],["Die Addams Family","Punsch","Exoskelett"]],
    [ ["Schriftsteller","Fernsteuerung","Micky Maus"], ["Zuckerstange","Tunnel","Voldemort"],["YouTube","Die Ärzte","Chuck Norris"]],
    [ ["Fernrohr","Muttertag","Sprechen"], ["Erneuerbare Energie","Dirk Nowitzki","Lebkuchenherz"],["Nächtliche Ruhestörung","Dackel","Lügen wie gedruckt"]],
    [ ["Nasenbär","Gürtel","Zaun"], ["Professor","Niere","Hydra"],["Sich ein Beispiel nehmen","Ein Königreich für ein Lama","Kartoffelgratin"]],
    [ ["Tauchen","Kristallkugel","Fliegender Teppich"], ["SMS","Töpferei","Triumphbogen"],["Stille Wasser sind tief","Stanley Kubrick","Röntgenstrahlung"]],
    [ ["Karotte","Murmel","Wald"], ["Antivirenprogramm","Die Oscarverleihung","Überfall"],["Einen Besen fressen","Steuerhinterziehung","Conan der Barbar"]],
    [ ["Fast Food","Laufen","Smoking"], ["Doping","Sonnenuntergang","Wiedervereinigung"],["Optimus Prime","National Geographic","Teleportation"]],
    [ ["Hühnerstall","Gehirn","Fußmatte"], ["Durchfall","Triceratops","Königsallee"],["Marie Curie","An den Haaren herbeiziehen","Die Schöne und das Biest"]],
    [ ["Straßenbahn","Brot","Lama"], ["Sandwich","Efeu","Eistee"],["Doctor Who","GTA (Grand Theft Auto)","Mittelmeer"]],
    [ ["Förster","Großvater","Karamell"], ["Schiffbruch","Cowboy","Gentleman"],["Trampen","Karla Kolumna","Mazedonien"]],
    [ ["Pfeffer","Springform","Boxen"], ["Jeep","Fischernetz","Klimawandel"],["Tinder","Niveaulos","Jon Schnee"]],
    [ ["Bauchnabel","Erbse","Boutique"], ["Massage","Kutsche","Tomatensoße"],["Spion","Pippi Langstrumpf","Ins andere Lager wechseln"]],
    [ ["Musiker","Hund","Bett"], ["Naruto","Affentheater","Heidi Klum"],["Kopf und Kragen riskieren","Blade Runner","Hungerlohn"]],
    [ ["Putenbrust","Taschentuch","Übelkeit"], ["Blaumachen","Bundespräsident","Playboy"],["Magic: The Gathering","La La Land","Gandhi"]],
    [ ["Kastanie","Toilette","Storch"], ["Schatzinsel","Lebkuchenhaus","Fußgänger"],["Charlie Chaplin","Da ist Hopfen und Malz verloren","Schnitzeljagd"]],
    [ ["Nuss","Waisenkind","Huhn"], ["Meister Proper","Flanke","Käsekuchen"],["Ehrgeiz","Sido","Die Zelte aufschlagen"]],
    [ ["Kamel","Konzert","Boule"], ["Couscous","Internet","Richter"],["Grammatik","Tortenschlacht","Chewbacca"]],
    [ ["Pantoffel","Oper","Informatiker"], ["Ananas","One Piece","Photosynthese"],["World of Warcraft","Bruce Willis","Tomaten auf den Augen haben"]],
    [ ["Pendel","Akkordeon","Dompteur"], ["Lunge","Johann Sebastian Bach","Rock am Ring"],["Milchmädchenrechnung","BB-8","Balliste"]],
    [ ["Aquarium","Aprikose","Blut"], ["Hagrid","Deadpool","Zwille"],["Einem alten Hasen wie mir kann man nichts mehr vormachen","Geldwäsche","Der Hobbit"]],
    [ ["Baustelle","Kleid","Rüstung"], ["Omelett","Sieb","Krypta"],["Im Geld schwimmen","Frühjahrsputz","Western"]],
    [ ["Gift","Rechnung","Karneval"], ["Äquator","Der Denker","Die Sendung mit der Maus"],["Machu Picchu","Der Klügere gibt nach","Space Invaders"]],
    [ ["Schwangerschaft","Skifahren","Vase"], ["Liebe macht blind","Safari","Rasiermesser"],["Möge die Macht mit dir sein!","Entenhausen","Freischaffender Künstler"]],
  ];
}

?>
