<?php
class ConceptCardsCS {
  static $cards = [
    [ ["Včela","Letiště","Orel"], ["2001: Vesmírná odysea","Skákal pes přes oves","Safari"],["Marná práce","Deset malých černoušků","Bez dechu"]],
    [ ["Airbag","Aladin","Ambulance"], ["Vznášedlo","Farmář","Magnet"],["Obouruční meč","Už tě mám plné zuby","Co se stalo, stalo se"]],
    [ ["Anděl","Konev na zalévání","Aspirin"], ["Sherlock Holmes","Večerníček","Alf"],["Hledání ztraceného času","Al Capone","Ali Baba"]],
    [ ["Vrah","Autorádio","Pštros"], ["Helena Vondráčková","Angry Birds","Adresář"],["Přilít olej do ohně","Americká krása","Šlápnout na plyn"]],
    [ ["Avatar","Stíhačka","Vana"], ["Afrodita","Vodové barvy (vodovky)","Pavouk"],["Všechno zlé je k něčemu dobré","Po zuby ozbrojený","Potkat se v půli cesty"]],
    [ ["Velryba","Banán","Banka"], ["Kuše","Duha","Archimédés"],["Vysavač","Mezi slepými jednooký králem","Mít volnou ruku"]],
    [ ["Grilování","Barbie","Knihovna"], ["Harlekýn","Výtah","Umělé sladidlo"],["Příliš krátké kalhoty","Drzý jako opice","Být jak na jehlách"]],
    [ ["Sněhurka a sedm trpaslíků","Pšenice","Bob a Bobek, králíci z klobouku"], ["Asterix a Obelix","Atlantida","Jih proti Severu"],["Běhá mráz po zádech","Sbíhají se sliny","Kocovina"]],
    [ ["Konzerva","Pepřový sprej","Sněhulák"], ["Právník","Pan Tau","Bageta"],["Něco na tom smrdí","Mít hlavu v oblacích","Nést si svůj kříž"]],
    [ ["Holínky","Náušnice","Cihla"], ["Pronájem","Houpačka","Hloupý Honza"],["Srdce na dlani","Dobrý odhad","Přizpůsobit se nové situaci"]],
    [ ["Zapalovač","Vánoční stromeček","Dřevorubec"], ["Bambi","Komiks","Čtyřlístek"],["Strach z výšek","Zvonění v uších","Stát nohama pevně na zemi"]],
    [ ["Kancelář","Sluneční hodiny","Káva"], ["Přehrada","Parník","Batman"],["Potápět se","Černé svědomí","Knedlík v krku"]],
    [ ["Notebook","Boxer","Náklaďák"], ["Baterie","Krab poustevník","Pivo"],["Práce kvapná málo platná","Výpadek paměti","Roztržitost"]],
    [ ["Hasicí letadlo","Kachna","Kanárek"], ["Bilbo Pytlík","Kulečník","Billy the Kid"],["Hlad jako vlk","Být v jednom ohni","Mytí nohou"]],
    [ ["Kantýna","Auta","Kreditní karta"], ["Bob Marley","Poštovní schránka","Atomová bomba"],["Bajonet","Solárium","Vybudovat říši"]],
    [ ["Přilba","Sklep","Papírový drak"], ["Zátka","Ohřívací láhev","Pekař"],["Kuj železo, dokud je žhavé","Udělat nový rekord","Koktání"]],
    [ ["Třešeň","Elektrické křeslo","Horská chata"], ["Buzola","Bowling","Jáchyme, hoď ho do stroje"],["Pyšná princezna","Justin Bieber","Big Ben"]],
    [ ["Ložnice","Šampaňské","Klobouk"], ["Charlie Chaplin","Bridget Jonesová","Brigitte Bardot"],["Škoda lásky","Videostop","Válečná zranění"]],
    [ ["Lovec","Vodárenská věž","Hrad"], ["Zubní kartáček","Bruce Lee","Tekutý písek"],["Zatajení dechu","Vsadit na nesprávného koně","Křemílek a Vochomůrka"]],
    [ ["Netopýr","Komín","Tričko"], ["Šváb","Konvice na kávu","Kalkulačka"],["Zlomené srdce","Kartáč na vlasy","Být nerozhodný"]],
    [ ["Kůň","Žvýkačka","Čokoláda"], ["Chameleon","Pudl","Ferda Mravenec"],["Pomluva","Volná diskuze","Jízda na červenou"]],
    [ ["Kino","Dýně","Směrovka"], ["Rychlé šípy","SIM karta","Pohlednice"],["Krystalicky čisté","Nic to nestojí","Zkrotit hněv"]],
    [ ["Zvonek","Klaun","Coca-Cola"], ["Casino Royale","Casper","Forma na dort"],["Tvrdohlavý jako mezek","Někoho obtěžovat","Noční můra"]],
    [ ["Prase","Kompas","Vrtulník"], ["Bobr","Katapult","Kočičí žena"],["Konec světa","Cenzura","Okruh přátel"]],
    [ ["Herní konzole","Mušle","Nůž na papír"], ["Popelka","Jelen","Císař"],["Začarovaný kruh","Klid zbraní","Sixtinská kaple"]],
    [ ["Švýcarský nůž","Krab","Opalovací krém"], ["Beyoncé","Zásobník","Proud"],["Jablko nepadá daleko od stromu","Karel Jaromír Erben","Co tě nezabije, to tě posílí"]],
    [ ["Palačinka","Krokodýl","Holub"], ["Cesta","Cíl","Padesát odstínů šedi"],["Hledání jehly v kupce sena","Oldřich Kaiser","Volný pád"]],
    [ ["Kuchyně","Delfín","Kostka"], ["Cirkus","Klávesnice","Klíč"],["Klonování","Oněmět úžasem","Římské koloseum"]],
    [ ["Defibrilátor","Převlek","Rogalo"], ["Čárový kód","Aneta Langerová","Punčocháče"],["Doznat se ke hříchům","Holka modrooká","Přerušit někoho"]],
    [ ["Umělý chrup","Odtahový vůz","Diamant"], ["Účetní","Okurka","Sušenka"],["Baletka","David a Goliáš","Ze Země na Měsíc"]],
    [ ["Slovník","Dinosaurus","Doktor"], ["Bílý tesák","Krokodýl Dundee","Croissant"],["Otvírák","Podat pomocnou ruku","Velký třesk"]],
    [ ["Dr. House","Drak","Bezpilotní letoun"], ["Amor","Párátko","Nůž"],["Rezignovat","Demokracie","Láska hory přenáší"]],
    [ ["DVD","Žebřík","Zatmění"], ["Cyklista","Cyrano z Bergeracu","D’Artagnan"],["Pád hořícího letadla","Detektiv","Házet perly sviním"]],
    [ ["Zámek","Škola","Veverka"], ["Dalajláma","Johnny Cash","Alois Jirásek"],["Stočený do klubíčka","Spát jako nemluvně","Mach a Šebestová"]],
    [ ["Kostel","Egypt","Slon"], ["Zubní pasta","Zoufalé manželky","Nezvratný osud"],["E. T. mimozemšťan","Miroslav Donutil","Eminem"]],
    [ ["Elf","Vodní mlýn","Meč"], ["Ďábel","Diablo","Jan Rosák"],["Vědět, co očekávat","Antonín Dvořák","Zakopat válečnou sekeru"]],
    [ ["Špenát","Hlemýžď","Mečoun"], ["Dr. Jekyll","Dumbo","Dynamit"],["Esmeralda","Myšlenky zločince","Šťastný jako blecha"]],
    [ ["Fialka","Mořská hvězdice","Padající hvězda"], ["Bělidlo","Braillovo písmo","Střihoruký Edward"],["Chytrý jako rádio","Bílý jako sníh","Stěrač (u auta)"]],
    [ ["Hasicí přístroj","Listonoš","Víla"], ["Elton John","Empire State Building","Hnojivo"],["Pomalý jako šnek","Rychlý jako blesk","Hluchý jako poleno"]],
    [ ["Okno","Ferrari","Flétna"], ["Zavírací špendlík","Eskalátor","Rychle a zběsile"],["Duchem nepřítomný","Hodit se do gala","Pravěk"]],
    [ ["Fotbal","Az-kvíz","Mikrovlnná trouba"], ["Podkova","Zip","Nůž na máslo"],["Inkoust","Předbíhat ve frontě","Smrt hladem"]],
    [ ["Vidlička","Jahoda","Raketa"], ["Forrest Gump","Bill Clinton","Hranolky"],["Znát své meze","Fidel Castro","Klub rváčů"]],
    [ ["Pistole","Rukavice","Garáž"], ["Stuha","Nádraží","Svatý Václav"],["Rozplynout se ve vzduchu","Kouřit jako fabrika","Jan Werich"]],
    [ ["Strážce","Koláč","Genius"], ["Filip Renč","Krotitelé duchů","Gladiátor"],["Dršťková polévka","Bublifuk","Karlův most"]],
    [ ["Žirafa","Větrná korouhvička","Kostka ledu"], ["Toustovač","Vojna a mír","Vilém Tell"],["Bílá paní","Propast Macocha","Gumoví medvídci"]],
    [ ["Kormidlo","GPS","Podkroví"], ["Gilotina","Kytara","Jan Kaplický"],["Hermiona Grangerová","Štěstí ve hře, neštěstí v lásce","Mořský koník"]],
    [ ["Žába","Mobilní telefon","Vosa"], ["Stroboskop","Hannibal Lecter","Harmonika"],["Adéla ještě nevečeřela","Tenkrát na západě","Pelíšky"]],
    [ ["Vánoční osvětlení","Gymnázium","Harpuna"], ["Heliport","Vlaštovka","Hula hop"],["Něco je špatně","Počátek","Jurij Gagarin"]],
    [ ["Harry Potter","Ježek","Dědictví"], ["Mezipřistání","Indiana Jones","František Křižík"],["Hliník se odstěhoval do Humpolce","Na to vsadím krk","Neštěstí nechodí samo"]],
    [ ["Chrastítko","Hotel","Iglú"], ["Rudolf Hrušínský","Masážní vana","Johanka z Arku"],["Jean-Claude Van Damme","Vlasta Burian","Marlon Brando"]],
    [ ["Tiskárna","Tablet","Iron Man"], ["John Lennon","Na Větrné hůrce","Jidáš"],["Věra Chytilová","Házet peníze do kanálu","Hodit ručník do ringu"]],
    [ ["Džíny","Státní svátek","Dalekohled"], ["Jukebox","Julia Roberts","Jumanji"],["Hodit jako první kamenem","Chlapci a chlapi","Jim Carrey"]],
    [ ["Ovocný džus","Klokan","Roh"], ["Jurský park","Karaoke","Kill Bill"],["Hodit si mincí","Google","Kiwi"]],
    [ ["Doba ledová","Neviditelný muž","Mumie"], ["Šípková Růženka","Koala","Vymítač ďábla"],["Vatikán","Peníze nerostou na stromech","Igor Hnízdo"]],
    [ ["Růžový panter","S čerty nejsou žerty","Eiffelova věž"], ["Ptačí klec","Zvonilka","Dexter"],["Cesta do pekla je dlážděna dobrými úmysly","Ukradené Vánoce","Velikonoční ostrov"]],
    [ ["Jezero","Mléko","Tom a Jerry"], ["Krok za krokem","Rytíři kulatého stolu","Zelená míle"],["Být jako páté kolo u vozu","Mít hroší kůži","Stařec a moře"]],
    [ ["Hledá se Nemo","Ježíšek","MP3 přehrávač"], ["Planeta opic","Francouzská revoluce","Kolo štěstí"],["Třešnička na dortu","Zakázané město","Ztráta iluzí"]],
    [ ["101 dalmatinů","Šmoulové","Simpsonovi"], ["Život je krásný","Veselá kráva","Věstonická Venuše"],["Blesk neuhodí dvakrát do stejného místa","Stoletá válka","Válka ve Vietnamu"]],
    [ ["Jednorožec","Lev","Vlk"], ["Emil Zátopek","Prak","Znaková řeč"],["Mlčeti zlato","Hans Christian Andersen","Galileo Galilei"]],
    [ ["Vlkodlak","Lupa","Sáňky"], ["Lara Croft","Lassie","Jára Cimrman - ležící spící"],["Strkat hlavu do písku","Babylonská věž","Pes Lajka"]],
    [ ["Sluneční brýle","Infračervený dalekohled","Šicí stroj"], ["Kniha džunglí","Jméno růže","Otesánek"],["Pat a Mat","Klevetit","Sám doma a bohatý"]],
    [ ["Kouzelník","Domov důchodců","Učitel"], ["Malý princ","Má vlast","Červený a černý"],["Vymývání mozku","Pátý element","Hodný, zlý a ošklivý"]],
    [ ["Sedmikráska","Manželství","Plynová maska"], ["Pán prstenů","Sfinga","Metallica"],["Společnost mrtvých básníků","Honzíkova cesta","Nedělní tisk"]],
    [ ["Šéfkuchař","Rákosníček","Mechanik"], ["Loď duchů","Když muž se ženou snídá","Yeti"],["Spider-Man","Marečku, podejte mi pero","Sherlock Holmes"]],
    [ ["Medúza","Meteorit","Metro"], ["LEGO","Kontaktní čočky","Sedm samurajů"],["Zeď nářků","Bedřich Smetana","Achillova pata"]],
    [ ["Mikroskop","Minecraft","Horník"], ["Prodaná nevěsta","Čelisti","Mladá fronta"],["Formule 1","Cesta kolem světa za 80 dní","Ordinace v růžové zahradě"]],
    [ ["Styl","Dostihy a sázky","Hora"], ["Dobrý voják Švejk","Ptáci","Cesta do pravěku"],["Hra o trůny","Příběh rytíře","Sedm divů světa"]],
    [ ["Hodinky","Moucha","Mlýn"], ["Matrjoška","Lovci mamutů","S tebou mě baví svět"],["Nemocnice na kraji města","Bohové musí být šílení","To zvládnu jako nic"]],
    [ ["Komár","Muzeum","Plavání"], ["Pokrevní bratři","The Sims","Želvy Ninja"],["Lež má krátké nohy","Studené ruce","Pýcha a předsudek"]],
    [ ["Psí bouda","Hnízdo","Ninja"], ["Šídlo","Zdeněk Svěrák","Šťastný Luke"],["Poklad na Stříbrném jezeře","Tři veteráni","Copak je to za vojáka"]],
    [ ["Nutella","Vejce","Obr"], ["Záchodové prkénko","McDonald’s","MacGyver"],["Eva tropí hlouposti","Božena Němcová","Jan Kraus"]],
    [ ["Orchestr","Počítač","Lední medvěd"], ["Parní stroj","Sám doma","Pyramidy"],["Sejde z očí, sejde z mysli","Loterie","Líbánky"]],
    [ ["Plyšový medvídek","Pac-Man","Seno"], ["Makeup","Margaret Thatcherová","Marilyn Manson"],["Madame Tussauds","Mít pech","Být pod drnem"]],
    [ ["Panter","Alobal","Motýl"], ["Mary Poppins","Majonéza","Muži v černém"],["Marco Polo","Skákání panáka","Tři zlaté vlasy děda Vševěda"]],
    [ ["Deštník","Slunečník","Hromosvod"], ["Matka Tereza","Michael Jordan","Mikrofon"],["Mars útočí!","Martin Luther King","Maska"]],
    [ ["Parkovací automat","Parfém","Přechod pro chodce"], ["Mike Tyson","Lucie Bílá","Miss krásy"],["Žebrák","Podprahové sdělení","Obrousit hrany"]],
    [ ["Rybář","Rýč","Člun"], ["Mr. Bean","Muhammad Ali","Mojžíš"],["Co si člověk neudělá sám, to nemá","Skočit do toho rovnýma nohama","Muži, kteří nenávidí ženy"]],
    [ ["Vrtačka","Papoušek","Petarda"], ["Maxipes Fík","Křížovka","Mlýnek na pepř"],["Držet se zuby nehty","Lucifer","Vyhrnout si rukávy"]],
    [ ["Petr Pan","Piano","Straka"], ["Poslední kovboj","Knír","Moskytiéra"],["Studený jako psí čumák","Nic pro slabé povahy","Ponořit se do toho"]],
    [ ["Pilot","Koření","Stolní tenis"], ["Neil Armstrong","Dannyho parťáci","Oidipus"],["Spát s jedním okem otevřeným","Sedět na dvou židlích","Utahaný jako kotě"]],
    [ ["Tučňák","Pinocchio (Pinokio)","Pirát"], ["Strýček Skrblík","Mechanický pomeranč","Varhany"],["Tomáš Garrigue Masaryk","Zamést problém pod koberec","Monokl"]],
    [ ["Bazén","Bezmotorový kluzák","Poznávací značka"], ["Austin Powers","Palma","Pamela Anderson"],["Zrak jako ostříž","Silueta","Když se kácí les, létají třísky"]],
    [ ["Instalatér","Pírko","Ryba"], ["Toaletní papír","Padák","Plastelína"],["Otevřít Pandořinu skříňku","Nákupní vozík","Mumlat si pod vousy"]],
    [ ["Pokémon","Policista","Jablko"], ["Brusle","Indián","Maják"],["Hovorová mluva","Natáhnout bačkory","Přestat se ovládat"]],
    [ ["Požárník","Přístav","Letadlová loď"], ["Pečeť","Kolíček","Piráti z Karibiku"],["Smrtonosná past","Rolling Stones","Červenat se"]],
    [ ["Peněženka","Květináč","Prodejna"], ["Pláž","Ropná plošina","Popcorn"],["Blbý a blbější","Čím více lidí, tím větší zábava","Pepek námořník"]],
    [ ["Vězení","Studna","Pyžamo"], ["Poseidon","Poznámkový blok","Odpadkový koš"],["Přípitek","Postavit se na nohy","Alcatraz"]],
    [ ["Radar","Lednička","Liška"], ["Střelný prach","Spejbl a Hurvínek","Princezna"],["Až zamrzne peklo","Rain Man","Na vlásku"]],
    [ ["Žralok","Restaurace","Nosorožec"], ["Útěk z vězení","Protéza","Reklama"],["Rozdmýchat plamen","Resident Evil","Návrat do budoucnosti"]],
    [ ["Závěsy","Řeka","Robot"], ["Perníková chaloupka","Radiátor","Železniční trať"],["Otáčet nožem v ráně","Komisař Rex","Rio de Janeiro"]],
    [ ["Kolo","Rubikova kostka","Den svatého Valentýna"], ["Krysa","Královna","Robin Hood"],["Robinson Crusoe","Prolomit ticho","Rákosí"]],
    [ ["Salát","Jedle","Skok o tyči"], ["Rocky","Kolečkové brusle","Romeo a Julie"],["Napnout svaly","Líbat se","Vybuchnout vzteky"]],
    [ ["Zachraňte Willyho!","Potápěcí přístroj","Škorpión"], ["Rtěnka","Zlatovláska","Rugby"],["Svatý Petr","Sezónní","Koukat jako sůva z nudlí"]],
    [ ["Stříkačka","Had","Opice"], ["Světelný meč","Svatý Grál","Divoké prase"],["Střelit se do nohy","Ztratit hlavu","Projížďka"]],
    [ ["Sombrero","Winx Club","Čarodějnice"], ["Klobása","Sauna","Mýdlo"],["Vlézt do chomoutu","Vstát levou nohou","Jít do detailu"]],
    [ ["Létající talíř (UFO)","Myš","Ponorka"], ["Lepicí páska","Vědro","Karel Hynek Mácha"],["Oblečený jako ze škatulky","Sebestřednost","Podobný jako vejce vejci"]],
    [ ["Podprsenka","Socha","Stejk"], ["Servírka","Shrek","Píšťala"],["Stát jako opařený","Nemít do čeho píchnout","Sigmund Freud"]],
    [ ["Stetoskop","Koberec","Tarzan"], ["Silikon","Snowboard","Zvon"],["Odpočívej v pokoji","Agent 007","Rumcajs"]],
    [ ["Krtek","Býk","Televizní reklama"], ["Dagmar Patrasová","Tintin","Kostlivec"],["Socha svobody","Socha Krista Spasitele","Pokoušet osud"]],
    [ ["Bouře","Tenis","Tetris"], ["Vesmírná stanice","Kate Middleton","Stonehenge"],["Dělat křena","Walt Disney","Fantastická čtyřka"]],
    [ ["Čaj","Tygr","Týpí (indiánský stan)"], ["Pero","Sudoku","Sushi"],["Show Jana Krause","Třetí princ","Tina Turner"]],
    [ ["Prasátko (kasička)","Titanic","Sekačka na trávu"], ["Ořezávátko","Jehlový podpatek","Dvojkolo"],["Vývrtka","Promoce","Padají trakaře"]],
    [ ["Slunečnice","Toy Story","Traktor"], ["Terminátor","Umělec","Termoska"],["Top Gun","Chodit kolem horké kaše","Začít znovu"]],
    [ ["Tříkolka","Trumpeta","Motorová pila"], ["Slunce, seno, jahody","Šikmá věž v Pise","Vlak duchů"],["Kousnout se do jazyka","Tisíc lidí, tisíc chutí","Pašování drog"]],
    [ ["Hadice na zalévání","Noční klub","Kráva"], ["Trampolína","Transformers","Chcete být milionářem"],["Soudní síň","Zabíjet čas","Netrpělivost"]],
    [ ["Upír","Sup","Motorka"], ["Obr Koloděj","Černá díra","Tsunami"],["Nekrytý šek","Znaménko krásy","Štěstí přeje připraveným"]],
    [ ["Pátek 13.","Vějíř","Veranda"], ["Míšeňský porcelán","Stmívání","Vakcína"],["Kdo jinému jámu kopá, sám do ní padá","Obrázek vydá za tisíc slov","Romantický příběh"]],
    [ ["Vinař","Víno","Vitamín"], ["Kufr","Suchý zip","Dvacet tisíc mil pod mořem"],["Hnout někomu žlučí","Jako slon v porcelánu","V jako Vendeta"]],
    [ ["Sopka","Jogurt","Jo-jo"], ["Whisky","Medvídek Pú","Rosomák"],["Zaprodat duši ďáblu","Potápěč","Žít život naplno"]],
    [ ["Yoda","Zebra","Zorro mstitel"], ["Woody Allen","Xylofón","Sabrina, mladá čarodějnice"],["Zloděj","Slepý jako netopýr","Mateřská láska"]],
  ];
}

?>
