<?php
class ConceptCardsFR {
  static $cards = [
    [ ["Chalet","Pompier","Crabe"], ["Moustache","Phoque","Chargeur"],["Big Ben","Ne pas avoir froid aux yeux","La cerise sur le gâteau"]],
    [ ["Piano","Le monde de Nemo","Maya l’abeille"], ["Bowling for Columbine","La Planète des singes","Le vent nous portera"],["Piège de cristal","Chassez le naturel, il revient au galop","Le Muppet Show"]],
    [ ["Déguisement","Restaurant","Étoile filante"], ["Cœur de Pirate","Prothèse","Edward aux mains d’argent"],["Couleur menthe à l’eau","Resident Evil","Être fleur bleue"]],
    [ ["Ambulance","Parfum","Pie"], ["Aimant","Mimie Mathy","Moustiquaire"],["À la bonne franquette","Message subliminal","Nager dans le bonheur"]],
    [ ["Zèbre","Bureau","Mécanicien"], ["Xylophone","Barrage","Le Yéti"],["Avoir les quatre fers en l’air","Le Parfum de la dame en noir","Les Malheurs de Sophie"]],
    [ ["Natation","Tricycle","Chocolat"], ["Les Tortues Ninja","Sister Act","Capitaine Flam"],["Tourner sept fois sa langue dans sa bouche","Brûler un feu rouge","Jeter la première pierre à quelqu’un"]],
    [ ["Jeans","Masterchef","Hérisson"], ["Jukebox","Le Vaisseau Fantôme","Indiana Jones"],["Le marchand de sable","Jamais deux sans trois","Avoir les oreilles qui sifflent"]],
    [ ["Bûche de Noël","Cochon","Piscine"], ["Bande dessinée","Castor","OSS 117"],["Ce n’est pas la mer à boire","Œil de lynx","Tourner la page"]],
    [ ["Tracteur","Coca-Cola","Cantine"], ["Thermos","Casserole","Bob Marley"],["Cauchemar","Baïonnette","Fondre comme neige au soleil"]],
    [ ["Fusil","Girouette","Citrouille"], ["Furet","Guerre et Paix","Carte à puce"],["La foudre ne tombe jamais deux fois au même endroit","Grotte de Lascaux","Ça ne mange pas de pain"]],
    [ ["Les 101 Dalmatiens","Statue","Les Schtroumpfs"], ["La Vache et le Prisonnier","Shrek","La vache qui rit"],["Se tourner les pouces","La guerre de 100 ans","Charles Baudelaire"]],
    [ ["Couteau suisse","Ferrari","Vitamine"], ["Chantal Goya","Escalator","Vingt mille lieues sous les mers"],["Être tiré à quatre épingles","V pour Vendetta","Un chaud lapin"]],
    [ ["Vache","Kangourou","Télé-achat"], ["Trivial Pursuit","Karaoké","Squelette"],["Tant va la cruche à l’eau qu’à la fin elle se casse","Kid Paddle","Être plus rapide que l’éclair"]],
    [ ["Facteur","Rideaux","Bombe lacrymogène"], ["Empire State Building","Quidditch","Bagheera"],["Retourner le couteau dans la plaie","Avoir la tête dans les nuages","Avoir une faim de loup"]],
    [ ["Canadair","GPS","Caleçon"], ["Bilbon Sacquet","Guitare","Bernard l’hermite"],["Heureux au jeu, malheureux en amour","Avoir un trou de mémoire","Caractère de cochon"]],
    [ ["Cloche","Hochet","Une boîte de nuit"], ["Casino Royale","Jacques Martin","Transformers"],["Jean-Claude Van Damme","Tuer le temps","L’étrange Noël de Monsieur Jack"]],
    [ ["La Petite Maison dans la prairie","Guirlande électrique","Plaque d’immatriculation"], ["La fée Clochette","Héliport","Pamela Anderson"],["On ne fait pas d’omelette sans casser des œufs","Il y a anguille sous roche","Faut pas pousser mémé dans les orties"]],
    [ ["Fourchette","Épée","Tirelire"], ["Forrest Gump","Jamel Debouzze","Taille-crayon"],["Enterrer la hache de guerre","Tire-bouchon","Avoir le pied marin"]],
    [ ["Brique","Banque","Sorcière"], ["Baloo","Archimède","Savon"],["Avoir carte blanche","Se mélanger les pinceaux","Parler dans sa barbe"]],
    [ ["Poisson","Avion de chasse","Jus de fruits"], ["Pâte à modeler","Aquarelle","Jurassic Park"],["Armé jusqu’aux dents","Jouer à pile ou face","Un roman à l’eau de rose"]],
    [ ["Véranda","Gouvernail","Soucoupe volante"], ["Vaccin","Guillotine","Scotch"],["Hermione Granger","Se mettre sur son 31","Les Chevaliers du Zodiaque"]],
    [ ["Montre","Abeille","Puits"], ["Les Poupées russes","2001 : l’Odyssée de l’espace","Post-it"],["Pisser dans un violon","Poser un lapin","Bénabar"]],
    [ ["Chaise électrique","Pingouin","Deltaplane"], ["Bowling","Oncle Picsou","Collant"],["Nicolas Sarkozy","Couper la parole","Noyer le poisson"]],
    [ ["Pinocchio","Génie","Mineur"], ["Orange mécanique","Gladiateur","Les grosses têtes"],["Spartacus","Le travail au noir","Skyfall"]],
    [ ["Tapis","Thé","Zorro"], ["Snowboard","Stylo","Zelda"],["The Truman show","Ne dormir que d’un œil","Les 7 boules de cristal"]],
    [ ["Piment","Monopoly","Lait"], ["Ocean’s Eleven","Les Oiseaux","La Guerre du feu"],["La bave du crapaud n’atteint pas la blanche colombe","Six feet under","Gaston Lagaffe"]],
    [ ["Stéthoscope","Gardien","Titanic"], ["Silicone","Gérard Jugnot","Talon aiguille"],["Tomber dans les pommes","Tribunal","Battre le fer tant qu’il est chaud"]],
    [ ["Tuyau d’arrosage","Casque","Le Père Noël"], ["Trampoline","Bouchon","La Révolution française"],["La parole est d’argent, mais le silence est d’or","La Cité interdite","Nager entre deux eaux"]],
    [ ["Pilote","Pyjama","Licorne"], ["Neil Armstrong","Poubelle","Harmonica"],["Se ressembler comme deux gouttes d’eau","La prison d’Alcatraz","Il n’y a pas le feu au lac"]],
    [ ["Guêpe","Autruche","Sous-marin"], ["Lance Armstrong","Annuaire","Serge Gainsbourg"],["Appuyer sur le champignon","Fight Club","Tous les goûts sont dans la nature"]],
    [ ["Fusée","Trompette","Paratonnerre"], ["Frites","Tour de Pise","Microphone"],["Masque","Démissionner","Déplacer des montagnes"]],
    [ ["Dr House","Drone","Ours en peluche"], ["Cupidon","Cutter","Maquillage"],["Madame Tussauds","Al Capone","Se rincer l’œil"]],
    [ ["Arrosoir","Soutien-gorge","Réfrigérateur"], ["Albus Dumbledore","Serveuse","Power Rangers"],["Rain Man","Malheureux comme les pierres","L’île de Pâques"]],
    [ ["Pacman","La Tour Eiffel","Scorpion"], ["Margaret Thatcher","La grande muraille","Rugby"],["Sauter du coq à l’âne","Chat échaudé craint l’eau froide","Fidel Castro"]],
    [ ["Crème solaire","Fraise","Pêcheur"], ["Chasse d’eau","François Mitterrand","Mister Bean"],["Mettre du beurre dans les épinards","Avoir des sueurs froides","Porter un toast"]],
    [ ["Blanche-Neige et les Sept Nains","Prison","Porte-avions"], ["Astérix et Obélix","Poséidon","Pirates des Caraïbes"],["Piquer un fard","Un chèque en bois","Les mains moites"]],
    [ ["Vampire","Musée","Camion"], ["Troll","Les Sims","Bière"],["Avoir une cervelle de moineau","Gad Elmaleh","Clouer le bec"]],
    [ ["Garage","Dauphin","Égypte"], ["Géant Vert","Clavier","Desperate Housewives"],["Élie Semoun","Passer l’arme à gauche","Dormir sur ses deux oreilles"]],
    [ ["Policier","École","Pirate"], ["Père Fouettard","Daniel Balavoine","Orgue"],["Œil au beurre noir","Avoir le vertige","Censure"]],
    [ ["Briquet","Compas","Aigle"], ["Bambi","Catapulte","30 millions d’amis"],["À bout de souffle","Être bête comme ses pieds","Le Bon, la Brute et le Truand"]],
    [ ["Essuie-glace","Maîtresse d’école","GSM"], ["Eau de Javel","Le Rouge et le Noir","Hannibal Lecter"],["Il était une fois dans l’Ouest","Youri Gagarine","J’en mettrais ma main au feu"]],
    [ ["Harpon","Harry Potter","Pot de fleurs"], ["Hula-hoop","Il est 5 h, Paris s’éveille","Plate-forme pétrolière"],["Plus on est de fous, plus on rit","Être sourd comme un pot","L’enfer est pavé de bonnes intentions"]],
    [ ["Fée","La Panthère Rose","Moulin"], ["Engrais","La Cage aux folles","Les Raisins de la colère"],["Les doigts dans le nez","Banc solaire","Décapsuleur"]],
    [ ["Cars","Dictionnaire","Steak"], ["Boîte aux lettres","Croc-Blanc","Sifflet"],["Sigmund Freud","Vendre son âme au diable","Faire une queue de poisson"]],
    [ ["Volcan","Fort Boyard","Dinosaure"], ["Whisky","Fermeture Éclair","Crocodile Dundee"],["Demander la main de quelqu’un","Être lent comme un escargot","Canaliser sa colère"]],
    [ ["Extincteur","Clignotant","Vendredi 13"], ["Elton John","Carte postale","Tupperware"],["Un moulin à paroles","Roseau","Alimenter un débat"]],
    [ ["Saint-Valentin","Assassin","Montagne"], ["Robin des Bois","Amy Winehouse","Les Piliers de la terre"],["Les 7 Merveilles du monde","Cercle d’amis","Mon précieux"]],
    [ ["Concorde","Perroquet","Tarzan"], ["Catwoman","Mots-croisés","Sonnette"],["Snoopy","Manger les pissenlits par la racine","La Bicyclette bleue"]],
    [ ["Paille","Le Marsupilami","Épinard"], ["Marilyn Manson","La ligne verte","Docteur Jekyll"],["Esmeralda","Aspirateur","The Avengers"]],
    [ ["Baleine","Tetris","Œuf"], ["Arbalète","Stonehenge","Mac Donald"],["Lewis Carroll","Rompre le silence","Bison Futé"]],
    [ ["Rubik’s Cube","Champagne","Console de jeux"], ["Reine","Bridget Jones","Cendrillon"],["Cercle vicieux","Kiwi","Confesser ses péchés"]],
    [ ["Klaxon","Défibrillateur","Sombrero"], ["Kill Bill","Code-barres","Saucisse"],["Se jeter à l’eau","Largo Winch","Le Colisée"]],
    [ ["Machine à coudre","Dé","Chambre"], ["Le Petit Poucet","Clef","Brice de Nice"],["Billy Jean","Une levée de boucliers","Casser les pieds à quelqu’un"]],
    [ ["Vigneron","Clown","Loup-garou"], ["Valise","Casper","Lara Croft"],["Un petit dessin vaut mieux qu’un long discours","La politique de l’autruche","Tenir la chandelle"]],
    [ ["Tempête","Parasol","Ventilateur"], ["Station spatiale","Michael Jordan","Twilight"],["Martin Luther King","Rouler une pelle","Dormir en chien de fusil"]],
    [ ["Sapin","Écluse","Boîte de conserve"], ["Rollers","Dalaï Lama","Avocat"],["Avoir la puce à l’oreille","Voleur","Boule et Bill"]],
    [ ["Yoda","Château fort","Éclipse"], ["Woody Allen","Bunker","D’Artagnan"],["Donner de la confiture aux cochons","Inception","Clonage"]],
    [ ["Gymnase","Cuisine","Lac"], ["Hirondelle","Cirque","La guerre des boutons"],["La cinquième roue du carrosse","De la terre à la lune","Famine"]],
    [ ["Diamant","Four micro-ondes","Cadran solaire"], ["Cookies","Fil à couper le beurre","Bâteau à vapeur"],["Avoir mauvaise conscience","Trafic de drogue","Ben-Hur"]],
    [ ["Tronçonneuse","Cerise","Bibliothèque"], ["Train-fantôme","Boussole","Aspartame"],["Avoir des fourmis dans les jambes","Les Liaisons dangereuses","C’est clair comme de l’eau de roche"]],
    [ ["Moustique","Cinéma","Loup"], ["Les Rivières pourpres","Capitaine Haddock","Langue des signes"],["La pierre de Rosette","La Petite Fille aux allumettes","Bruit de couloir"]],
    [ ["Lion","Cheval","Perceuse"], ["Lance-pierre","Caméléon","Monsieur Patate"],["Mon petit doigt m’a dit","Ouvrir la boîte de Pandore","Ali Baba"]],
    [ ["Plombier","Aspirine","Iron Man"], ["Papier toilette","Alf","Judas"],["Jeter l’éponge","Chute libre","Une main de fer dans un gant de velours"]],
    [ ["Crotte de nez","Vin","Taupe"], ["Cinquante nuances de Grey","Velcro","Sophie Marceau"],["Statue de la Liberté","Mendiante","Ne pas avoir les yeux en face des trous"]],
    [ ["Parcmètre","Ping-pong","Tigre"], ["Mike Tyson","Œdipe","Sudoku"],["Thorgal","Démarrer sur les chapeaux de roue","Bain de pieds"]],
    [ ["Docteur","Canari","Masque à gaz"], ["Croissant","Billy the Kid","Le téléphone pleure"],["Le Journal du dimanche","Danseuse étoile","Hunger Games"]],
    [ ["Dentier","Grenouille","Marguerite"], ["Comptable","Gyrophare","Le Seigneur des anneaux"],["Le Cercle des poètes disparus","Marco Polo","Chapelle Sixtine"]],
    [ ["Panthère","Coupe papier","Magicien"], ["Mary Poppins","Césarienne","Le Petit Prince"],["Lavage de cerveau","Vivre à cent à l’heure","Les Mystérieuses Cités d’or"]],
    [ ["Yo-yo","Niche","Nid"], ["Wolverine","Libellule","Luc Besson"],["Les Rois mages","Loana","Être tête en l’air"]],
    [ ["Ogre","Fenêtre","Taureau"], ["MacGyver","Épingle à nourrice","Spirou"],["La statue du Christ Rédempteur","La marelle","Avoir des doigts de fée"]],
    [ ["Papier aluminium","Barbie","Échelle"], ["Mayonnaise","Ascenseur","Cyrano de Bergerac"],["Détective","Avoir l’eau à la bouche","Mouiller sa chemise"]],
    [ ["Blé","Barbecue","Ange"], ["Atlantide","Arlequin","Albator"],["À la recherche du temps perdu","Pierre qui roule n’amasse pas mousse","Avoir de l’eau dans les caves"]],
    [ ["Port","Pétard","Hôtel"], ["Pince à linge","Moulin à poivre","Jacuzzi"],["Jean-Marie Bigard","Le Tour de France","L’argent ne pousse pas sur les arbres"]],
    [ ["Microscope","L’Homme invisible","Cave"], ["Les Bronzés font du ski","Koala","Bouillotte"],["Battre un record","Avoir un chat dans la gorge","Muet comme une carpe"]],
    [ ["Café","Peter Pan","Radar"], ["Batman","Mourir pour des idées","Poudre à canon"],["Parler français comme une vache espagnole","Quand les poules auront des dents","Loterie"]],
    [ ["Ordinateur","Pokémon","Chewing-gum"], ["Maman, j’ai raté l’avion","Patins à glace","Caniche"],["Bruit qui court","L’Élève Ducobu","Robinson Crusoé"]],
    [ ["La Momie","Roue","Pomme"], ["L’Exorciste","Rat","Phare"],["Perdre son sang froid","À double tranchant","Un homme averti en vaut deux"]],
    [ ["Airbag","Vélo","Escargot"], ["Aéroglisseur","Tsunami","Dumbo"],["Esprits criminels","Tomber des cordes","Être blanc comme neige"]],
    [ ["Tondeuse","Étoile de mer","Avatar"], ["Tandem","Écriture braille","Aphrodite"],["Après la pluie, le beau temps","Briser le cœur","Se faire rouler dans la farine"]],
    [ ["Chauve-souris","Singe","Espadon"], ["Cafard","Sanglier","Dynamite"],["Être au septième ciel","Faire couler beaucoup d’encre","Lune de miel"]],
    [ ["Football","Ours blanc","Gâteau"], ["Fer à cheval","Manneken-Pis","Ghostbusters"],["Gomme","Mariage pluvieux, mariage heureux","Avoir le cœur gros"]],
    [ ["Papillon","Bonhomme de neige","Parapluie"], ["Men in Black","Baguette","Mère Teresa"],["Mars Attacks !","Christophe Dechavanne","Bégayer"]],
    [ ["Crocodile","Cerf-volant","Héritage"], ["Cible","Boulanger","Jack Bauer"],["Je suis ton père","Ombre chinoise","Les Tuniques Bleues"]],
    [ ["Planeur","Ninja","DVD"], ["Palmier","Lucky Luke","Cycliste"],["Descendre en flammes","Se lever du pied gauche","Démocratie"]],
    [ ["Sonic","Dragon","Vautour"], ["Sauna","Cure-dent","Trou noir"],["Un grain de beauté","Le Pont des Soupirs","Bloquer sa respiration"]],
    [ ["Méduse","Chasseur","Métro"], ["Lego","Brosse à dents","Les 7 Samouraïs"],["Le talon d’Achille","Grenouille de bénitier","Jeux de mains, jeux de vilains"]],
    [ ["Girafe","Jour férié","Yaourt"], ["Grille-pain","Julia Roberts","Winnie l’ourson"],["Ventouse à toilette","Le siècle des Lumières","Le Cinquième Élément"]],
    [ ["Météorite","Maison de retraite","Baignoire"], ["Lentilles de contact","Le plat pays","Araignée"],["Arrondir les angles","Avoir le compas dans l’œil","Blessure de guerre"]],
    [ ["Boucle d’oreille","Chapeau","Chemise"], ["Balançoire","Brigitte Bardot","Calculatrice"],["Broyer du noir","Boire la tasse","Avoir un poil dans la main"]],
    [ ["Château d’eau","Cahier","Éolienne"], ["Bruce Lee","Batterie","Diablo"],["Ennio Morricone","Jean-Pierre Pernaut","Jim Carrey"]],
    [ ["Imprimerie","Jumelles","Mariage"], ["John Lennon","Jumanji","Le Sphinx"],["Le Club des Cinq","Ranimer la flamme","Loin des yeux, loin du cœur"]],
    [ ["Requin","Orchestre","L’Âge de glace"], ["Prison break","Machine à vapeur","Kirikou"],["Le Kremlin","Eurêka !","Popeye"]],
    [ ["Flûte","Prise électrique","Autoradio"], ["Fast and Furious","Pop-corn","Angry Birds"],["American Beauty","Mettre les pieds dans le plat","Millénium"]],
    [ ["Pelle","Péniche","Robot"], ["Mohamed Ali","Moïse","Rails de chemin de fer"],["Rio de Janeiro","Le Trône de fer","Bâtir un empire"]],
    [ ["Mode","Carte de crédit","Lunettes de soleil"], ["Les Lettres de mon moulin","Bombe atomique","Le Livre de la jungle"],["Lanfeust de Troy","La tour de Babel","E.T. l’extra-terrestre"]],
    [ ["Loupe","Église","Bottes"], ["Lassie","Dentifrice","Bail"],["Avoir le cœur sur la main","Mettre de l’eau dans son vin","Se regarder le nombril"]],
    [ ["Passage piéton","Souris","Canard"], ["Miss France","Seau","Billard"],["Avoir une fièvre de cheval","Le panier de la ménagère","Jean-Paul Belmondo"]],
    [ ["Plume","Igloo","Bûcheron"], ["Parachute","Jeanne d’Arc","Barbara"],["Avoir les pieds sur terre","Les dieux sont tombés sur la tête","Dragon Ball Z"]],
    [ ["Mouche","Écureuil","Serpent"], ["Les Quatre filles du docteur March","David Guetta","Saint Graal"],["Se faire des cheveux blancs","Tex Avery","Laïka"]],
    [ ["Tennis","Luge","Les Simpsons"], ["Stéphanie de Monaco","Le Grand Bleu","La Vénus de Milo"],["La guerre du Viêt Nam","À fleur de peau","La Folie des grandeurs"]],
    [ ["Aladdin","Lecteur MP3","Bob l’éponge"], ["Agriculteur","La Roue de la fortune","Autant en emporte le vent"],["Avoir la gueule de bois","Eminem","Saint Pierre"]],
    [ ["Éléphant","Sauvez Willy","Cheminée"], ["Destination finale","Rouge à lèvres","Cafetière"],["Brosse à cheveux","Tina Turner","Le crime de l’Orient-Express"]],
    [ ["Tipi","Aéroport","Coquillage"], ["Sushi","Trois nuits par semaine","Cerf"],["Chercher une aiguille dans une botte de foin","Cessez-le-feu","Rex, chien flic"]],
    [ ["Rivière","Renard","Saut à la perche"], ["Radiateur","Princesse","Roméo et Juliette"],["Scier la branche sur laquelle on est assis","Raiponce","Sabrer le champagne"]],
    [ ["Crêpes","Lunette infrarouge","Grenier"], ["Chemin","Sabre laser","Gustave Eiffel"],["Hippocampe","Les Visiteurs","Langue de vipère"]],
    [ ["Nutella","Seringue","Glaçon"], ["Lunette de toilette","Le Nom de la rose","Guillaume Tell"],["Guimauve","Jeter l’argent par les fenêtres","Fumer comme un pompier"]],
    [ ["iPad","Gants","Dépanneuse"], ["Jonathan Livingston le goéland","Gare","Concombre"],["David contre Goliath","Tourner autour du pot","Saisonnier"]],
    [ ["Toy Story","Scaphandre","Minecraft"], ["The Artist","Rox et Rouky","Les Dents de la mer"],["Le Tour du monde en 80 jours","Rouler des mécaniques","Retour vers le futur"]],
    [ ["Salade","Rhinocéros","Tournesol"], ["Rocky","Publicité","Terminator"],["Au royaume des aveugles, les borgnes sont rois","Top Gun","En avoir le cœur net"]],
    [ ["Elfe","Banane","Portefeuille"], ["Diable","Arc-en-ciel","Plage"],["Piquer une tête","Myope comme une taupe","Mère poule"]],

    [ ["Armure","Mouchoir","Chantier"], ["Station de ski","Marionnette","Stalactite"],["Moyen Âge","Psychose","Confucius"]],
    [ ["Casino","Iceberg","Escrime"], ["Photocopieuse","Centrale nucléaire","Netflix"],["San Goku","Souvenir","Faire la courte échelle"]],
    [ ["Smoking","Maçon","Grenade"], ["Pythagore","Liberté, Égalité, Fraternité","Miroir"],["On ne peut pas à la fois être juge et partie","Chandelier","Alchimiste"]],
    [ ["Beurre","Shampooing","La Reine des neiges"], ["Lierre","Stromæ","Psychologue"],["Croque-mitaine","La Belle et la Bête","Martin Scorsese"]],
    [ ["Fourmi","Tutu","Couche"], ["Grue","Hiéroglyphe","Les Mille et Une Nuits"],["Cadenas","Le Monde de Narnia","Counter-Strike"]],
    [ ["Marcher","Bille","La Joconde"], ["Cupcake","Deadpool","Ivresse"],["Star Trek","Passer l’éponge","Jean Dujardin"]],
    [ ["Bague","Vaisseau spatial","Médaille d’or"], ["Tatouage","Bacon","Cornemuse"],["Gladiator","Ne pas faire dans la dentelle","Livre dont vous êtes le héros"]],
    [ ["Magasin","Béquille","Poney"], ["Macaron","Michael Schumacher","BB-8"],["Vieux loup de mer","Les Caraïbes","Emoji"]],
    [ ["Limonade","Poivre","Ancre"], ["Skateboard","Rose des vents","Naufrage"],["Kaléidoscope","Suricate","Kuzco"]],
    [ ["Pendule","Lutin","La tour de Pise"], ["Origami","Internet","Curling"],["Doctor Who","Uranium","Illusionniste"]],
    [ ["Poulailler","Médicament","Scierie"], ["Ananas","Assiéger","Yannick Noah"],["Urinoir","Rester de marbre","Les Fleurs du mal"]],
    [ ["Pantoufle","Caramel","Limace"], ["Vis","Paon","Pom-pom girl"],["Agatha Christie","Scout","Ultrason"]],
    [ ["Cerveau","Mille-pattes","Orphelin"], ["Confiture","Frankenstein","Premier Ministre"],["Atmosphère","Daft Punk","Silo"]],
    [ ["Boule de neige","Désert","Dentiste"], ["Magma","The Voice","Nouvel An chinois"],["Les Diables rouges","Gollum","Justice"]],
    [ ["Vase","Chômeur","Tir à l’arc"], ["Trapèze","Stagiaire","Athènes"],["Passer sur le billard","Sia","Sherlock Holmes"]],
    [ ["Oie","Chirurgien","Las Vegas"], ["Hamac","Friends","Hydre"],["Astéroïde","Piège à loup","Wikipédia"]],
    [ ["Dompteur","Imprimante","Koh-Lanta"], ["Sardine","Kung Fu Panda","Katy Perry"],["Californie","La Famille Addams","Crash-test"]],
    [ ["Babar","Moule","Tabouret"], ["Excalibur","Flash McQueen","Poésie"],["Conan le Barbare","Les Mystérieuses Cités d’or","Obsolescence programmée"]],
    [ ["Chien","Europe","Robinet"], ["Plongeoir","Pastis","AC/DC"],["House of Cards","Odin","Entarteur"]],
    [ ["Tigrou","Vomir","Cannibale"], ["Vague","Airsoft","Eurovision"],["Coluche","Enfiler des perles","Tom Sawyer"]],
    [ ["Marmotte","Berceuse","Aubergine"], ["Trampoline","Dopage","La Renaissance"],["Aragorn","Scarface","Tinder"]],
    [ ["Conduire","Musicien","Crèche"], ["Bigorneau","Oui-Oui","Hypnotiseur"],["Spermatozoïde","Hipster","Les Béruriers noirs"]],
    [ ["Pizza","Ceinture","Peigne"], ["Cowboy","Buzz l’Éclair","Le cheval de Troie"],["Candy Crush","Mauvaise haleine","Radioactivité"]],
    [ ["Nombril","Sable","Boîte à outils"], ["Terrier","Hagrid","Jet-ski"],["Twitter","Se prendre pour le centre du monde","Humidité"]],
    [ ["Flamant rose","Mammouth","Chronomètre"], ["Falbala","Routier","Palme d’or"],["Garfield","Nirvana","Être de mauvais poil"]],
    [ ["Fossile","Alarme","La Bible"], ["Dominos","Emmanuel Macron","Piéton"],["Ne pas y aller avec le dos de la cuillère","Les chevaliers de la Table ronde","Snoop Dogg"]],
    [ ["Hibou","Noix","Croisade"], ["Rire jaune","Dexter","Vernis à ongles"],["Ne pas vendre la peau de l’ours avant de l’avoir tué","Ombre","Quand la musique est bonne"]],
    [ ["Soupe","Corde à sauter","Bricolage"], ["Pèlerinage","Luigi","The Walking Dead"],["Mad Max","Groom","Colosse aux pieds d’argile"]],
    [ ["Chèvre","La Maison Blanche","Enfer"], ["Vinyle","Rambo","Vladimir Poutine"],["Illuminati","Auto-stop","Laver son linge sale en famille"]],
    [ ["Miel","Carte bancaire","Canine"], ["Choucroute","Wonder Woman","Tavernier"],["Travailler au noir","Fête du slip","Alphabet"]],
    [ ["Petit pois","Maillot de bain","Le Roi Lion"], ["R2-D2","Louis XVI","Punk"],["Malédiction","Gandalf","Il y a de l’eau dans le gaz"]],
    [ ["Sang","Écrivain","Manège"], ["Sac de couchage","Litchi","Nelson Mandela"],["Blake et Mortimer","Surligneur","Pompéi"]],
    [ ["Framboise","Longue-vue","Kilt"], ["Jeep","Groot","Monastère"],["Johnny Cash","Acide","1984"]],
    [ ["Brochette","Chèque","Anniversaire"], ["Bretzel","Carte d’identité","RoboCop"],["Cthulhu","Croire dur comme fer","Red Hot Chili Peppers"]],
    [ ["Radio","Saucisson","Cercueil"], ["Colle","Les Experts","Moscou"],["Kermit la grenouille","Bête comme ses pieds","Balle à blanc"]],
    [ ["Maïs","Cigogne","Allumette"], ["Huître","Équateur","Marie-Antoinette"],["Planter sa tente","Tourniquet","Pelleteuse"]],
    [ ["Bouée","Cartable","Cage"], ["Bretelle","Professeur","Tomb Raider"],["L’union fait la force","Néfertiti","Escape Room"]],
    [ ["Pastèque","Biberon","Chevalier"], ["Pince","Grippe","Le Penseur"],["Espion","Service après-vente","Tomber sur un os"]],
    [ ["Hache","Mickey Mouse","Coiffeur"], ["Frisbee","Diarrhée","Le Marathon de Paris"],["Machine à sous","L’habit ne fait pas le moine","Voiture hybride"]],
    [ ["Encre","Bison","Paillasson"], ["Coussin","Athlétisme","Le Parrain"],["Couper la poire en deux","René Descartes","Le Club Dorothée"]],
    [ ["Chaton","Nain","Pain au chocolat"], ["Locomotive","Toboggan","Télescope"],["Les Bisounours","Les chutes du Niagara","De fil en aiguille"]],
    [ ["Brocolis","Garde forestier","Violon"], ["Katana","Entonnoir","Groenland"],["YouTube","Kebab","En prendre de la graine"]],
    [ ["Coq","Mannequin","Mathématique"], ["Navet","Hamburger","Vendeur"],["Donald Duck","Avoir les dents longues","Space Invaders"]],
    [ ["Courir","Moine","Pistolet"], ["Acrobate","Quiche","NASA"],["Titeuf","Être payé au lance-pierre","Tchernobyl"]],
    [ ["Aquarium","Ampoule","Lingot d’or"], ["Agrafeuse","Bruxelles","Bustier"],["Marc Levy","Bar à chats","Pour une bouchée de pain"]],
    [ ["Sel","Tétine","Alligator"], ["Pion","Inspecteur Gadget","Playboy"],["Entrer comme dans un moulin","Tyrion Lannister","Surf"]],
    [ ["Panda","Limousine","Toilettes"], ["Piranha","Sucre d’orge","Bill Gates"],["Bruce Willis","Starsky et Hutch","Titanium"]],
    [ ["Sucette","Hippopotame","Cône de signalisation"], ["Coucher de soleil","Tricératops","Toucher du bois"],["Will Smith","Uranus","Fumer le calumet de la paix"]],
    [ ["Crier","Ours","Ascenseur"], ["Wagon","Tomates farcies","Le Vatican"],["Ramener sa fraise","Gandhi","Père Fouras"]],
    [ ["Pikachu","Jambon","Taxi"], ["Ballon de baudruche","Pioche","Géographie"],["L’arbre qui cache la forêt","Joseph Staline","Cyprien"]],
    [ ["Algue","Homard","Serpentin"], ["Uniforme","Centaure","Réceptionniste"],["Charlie Chaplin","The Big Bang Theory","Faire la pluie et le beau temps"]],
    [ ["Mer","Pain","Abattoir"], ["Caviar","Rêve","Afrique du Sud"],["Rouler sur l’or","Claire Chazal","Trébuchet"]],
    [ ["Riz","Paris","Patron"], ["Nœud papillon","Mousquetaire","Panini"],["Stranger Things","Mensonge","Akhenaton"]],
    [ ["Carotte","Fouet","Police"], ["Pédalo","Tombe","Maître-nageur"],["Trader","Le mur de Berlin","Dofus"]],
    [ ["Bavoir","Pipe","Pharmacien"], ["Poumon","Clafoutis","Gentleman"],["E-sport","Être de mèche","David Fincher"]],
    [ ["Abricot","Allumer le feu","Fontaine"], ["SMS","Moi, moche et méchant","Serpillière"],["Hellfest","Biscotte","Reservoir Dogs"]],
    [ ["Roi","Sumo","James Bond"], ["Sèche-linge","L’Île au trésor","Racine"],["Chanter comme une casserole","Arrêt de bus","Alice au pays des merveilles"]],
    [ ["Radis","Collier","Trottinette"], ["Cachot","Trottoir","Morue"],["National Geographic","C’est pas sorcier","Norman"]],
    [ ["Tomate","Doudou","La seconde guerre mondiale"], ["Chauve","Les Gardiens de la Galaxie","Rond-point"],["Jon Snow","Prendre le taureau par les cornes","RnB"]],
    [ ["E-mail","Barbe","Kayak"], ["Mime","Nicolas Hulot","Usine"],["Salle de musculation","Satyre","Gin tonic"]],
    [ ["Lire","Hulk","Grand-père"], ["Lasso","Fête nationale","Champs-Élysées"],["Capricorne","Le triangle des Bermudes","Teckel"]],
    [ ["Pleurer","Ski","Caravane"], ["Salopette","Oasis","Les Tontons flingueurs"],["Tirer par les cheveux","Ramsès","Porter la culotte"]],
    [ ["Melon","Tambour","Bouilloire"], ["Trident","Borne d’arcade","SPA"],["Manger à tous les râteliers","Se rincer l’œil","Erreur 404"]],
    [ ["Citron","Éponge","Canicule"], ["Griffon","Pompe à essence","Scénariste"],["Kraken","Magic : L’Assemblée","Être charrette"]],
    [ ["Danser","Potiron","Cigare"], ["Blaireau","Green Lantern","Crématorium"],["Union","Chuck Norris","Tchater"]],
    [ ["Actrice","Temple","La Fête de la musique"], ["Muffin","Potager","Avoir la tête dans le cul"],["Chewbacca","Grégory Lemarchal","Kaamelott"]],
    [ ["Jambe de bois","Pierre-papier-ciseaux","Marin"], ["Règle","Déménager","Monsieur Propre"],["Dîner en tête-à-tête","Avoir plusieurs cordes à son arc","Black Swan"]],
    [ ["Langue","Informaticien","Machine à laver"], ["Clou","Jaguar","Homer Simpson"],["Sauver les meubles","Rasta Rockett","Utopie"]],
    [ ["Haricot vert","Canne à pêche","Prêtre"], ["Calèche","Couscous","Greenpeace"],["Fifi Brindacier","Saw 6","Bulldog"]],
    [ ["Coquelicot","Boule de cristal","Discothèque"], ["Dirigeable","Acarien","Call of Duty"],["Tirer les vers du nez","Rock’n’Roll","Mamie Nova"]],
    [ ["Accordéon","Stylo","Brouette"], ["Geyser","Construire","Kalachnikov"],["Faire l’école buissonnière","Docteur Watson","Rhum arrangé"]],
    [ ["Table","Bougie","Lycée"], ["Univers","Corail","One Piece"],["Monsieur Loyal","Saxophone","Sage comme une image"]],
    [ ["Hôpital","Télécommande","Momie"], ["Lézard","Laser game","Facebook"],["Collier de nouilles","Les jeux Paralympiques","Pulp Fiction"]],
    [ ["Fromage","Troupeau","Coffre-fort"], ["Antivirus","Pearl Harbor","Albert Einstein"],["Columbo","Raconter des salades","Gérard Depardieu"]],
    [ ["Douche","Chasse","Menottes"], ["Omelette","Cabine d’essayage","Google"],["Britney Spears","Exosquelette","Mojito"]],
    [ ["Casquette","Voyager","Monocycle"], ["Tank","La Cigale et la Fourmi","Kinésithérapeute"],["Jura","Enfoncer des portes ouvertes","Le Guinness des records"]],
    [ ["Armoire","Fantôme","Funambule"], ["Carrousel","Le Joker","Gay Pride"],["Vertèbre","John Travolta","Sortir de ses gonds"]],
    [ ["Cravate","Nénuphar","Tablette"], ["Arbitre","Réalisateur","Noir Désir"],["Ce n’est pas à un vieux singe qu’on apprend à faire des grimaces","Natoo","Albert Camus"]],
    [ ["Ver de terre","Plongée","Équitation"], ["Rein","Game of Thrones","Île déserte"],["Tapage nocturne","Chardon","Médecins sans frontières"]],
    [ ["Toupie","Lama","Salon de coiffure"], ["Vodka","Hello Kitty","Poterie"],["Blanchir de l’argent","Minotaure","Qui dort dîne"]],
    [ ["Bus","Échecs","Concert"], ["Couvent","Draguer","Shéhérazade"],["La casa de papel","Drakkar","Hyperactivité"]],
    [ ["Poire","Tapis volant","Cimetière"], ["Vaisselle","Naruto","Floride"],["La Belle et le Clochard","Louper le coche","Baliste"]],
    [ ["Paresseux","Cabane","Végétarien"], ["Crème chantilly","Madonna","Pollution"],["Brexit","La huitième merveille du monde","Chapeau l’artiste"]],
    [ ["Élastique","Clémentine","Fléchette"], ["Bagel","Dialogue de sourds","Énergie verte"],["Plein aux as","Madagascar","Snapchat"]],
    [ ["Lampe","Montgolfière","Pétrole"], ["Lotus","Fredonner","La Mecque"],["Marie Curie","Peste noire","Rafael Nadal"]],
    [ ["Boxe","Pet","Journaliste"], ["Flan","Donkey Kong","Pare-buffle"],["Gremlins","Corto Maltese","Froid de canard"]],
    [ ["Lettre","Toit","Écologie"], ["Hot dog","Respirer","X-Men"],["Hamlet","James Cameron","Pile ou face"]],
    [ ["Corbeau","Les Minions","Voiture télécommandée"], ["Saphir","Clé USB","Pocahontas"],["Steven Spielberg","Vendre la mèche","Tartiflette"]],
    [ ["Crapaud","Pyramide","Grande roue"], ["Mousse au chocolat","Juge","Voldemort"],["Chasse au trésor","Commissaire Maigret","Qui vole un œuf vole un bœuf"]],
    [ ["Spiderman","Aveugle","Astronaute"], ["Tunnel","Gymnastique","Donjons et Dragons"],["Émile Zola","Tableau périodique des éléments","Téléportation"]],
    [ ["Chaussette","Dinde","Moulin à eau"], ["Appareil photo","Tintin","Entreprise"],["Ficus","Colonel Moutarde","Risquer sa peau"]],
    [ ["Bonnet","Aiguille","Égout"], ["Dague","Hockey sur glace","Times Square"],["GTA (Grand Theft Auto)","Avoir un balai dans le cul","Amer"]],
    [ ["Le Petit Chaperon rouge","Pile","Formule 1"], ["Bloc-notes","Intouchables","Climatisation"],["Carte de visite","Montrer patte blanche","Risk"]],
    [ ["Poupée","Gobelet en plastique","Mario"], ["Jeton","Roulade","Eragon"],["Ultraviolet","La madeleine de Proust","Bête à manger du foin"]],
    [ ["Bar","Capitaine Crochet","Donut"], ["Rasoir","Cluedo","Le Canard enchaîné"],["Wall-E","Didier Deschamps","Bonnet blanc et blanc bonnet"]],
    [ ["Équerre","Berger","Chine"], ["Sandwich","Minigolf","Michael Jackson"],["Rap","La Grande Ourse","Tony Hawk"]],
    [ ["Chanter","Paradis","Le prince charmant"], ["Poisson pané","Bâiller","Pomme d’Adam"],["Jacques Brel","Coussin péteur","URSS"]],
    [ ["Pont","Biche","T. rex"], ["Éventail","Teddy Riner","La Belle au bois dormant"],["Tyrolienne","Walt Disney","Jean de La Fontaine"]],
    [ ["Lit","Poison","King Kong"], ["Satellite","Dora l’exploratrice","Taxidermiste"],["Ver à soie","Tricheur","Quinoa"]],
    [ ["Train","Gorille","Bourse"], ["Graffiti","Cheesecake","La Grande Muraille de Chine"],["Contre vent et marées","Amélie Poulain","Rayon X"]],
    [ ["Crevette","La Marseillaise","Shuriken"], ["Linge sale","Cambriolage","Safari"],["David Bowie","Rébus","Intermittent du spectacle"]],
    [ ["Poulet","Robe","Vacances"], ["Courgette","Sèche-cheveux","Mars"],["Joystick","Au ras des pâquerettes","Matrix"]],
    [ ["Hamster","Slip","Facture"], ["Jongleur","Passe-partout","Gratte-ciel"],["Jeter de l’huile sur le feu","Goldorak","Pixel"]],
    [ ["Bonbon","Réveil","Âge de pierre"], ["Samuraï","Cratère","Jazz"],["Richard Cœur de Lion","Dame pipi","Les chiens ne font pas des chats"]],
    [ ["Téléphone","Vétérinaire","Zombie"], ["Tapette à mouches","Stormtrooper","Diplomate"],["Zootopie","Macédoine","Panneau de signalisation"]],
    [ ["Spaghetti","Mouton","Cyclope"], ["Hameçon","Architecte","Radin"],["Marilyn Monroe","La La Land","Les chiens aboient, la caravane passe"]],
    [ ["Zoo","Démolir","Forêt"], ["Palme","Passoire","Mozart"],["Godzilla","Changer son fusil d’épaule","Avoir le vent en poupe"]],
    [ ["Géant","Ouragan","Pétanque"], ["Bonzaï","Lave-vaisselle","Léonard de Vinci"],["Patrick Sébastien","Vercingétorix","Western"]],
    [ ["Indien","Pigeon","Intestin"], ["Yoga","Sauterelle","Arc de triomphe"],["Stanley Kubrick","Final Fantasy","Prendre la mouche"]],
    [ ["Champignon","Bulldozer","Golf"], ["Thé glacé","Compteur électrique","Metallica"],["Langue de bœuf","Justin Bridou","Grammaire"]],
  ];

}

?>
