<?php
class ConceptCardsBR {
  static $cards = [
    [ ["Roda","Piscina","Canguru"], ["Camundongo","Show do Milhão","Karaokê"],["Robinson Crusoé","Ilusão de grandeza","Olho de águia"]],
    [ ["Para-raios","Sexta-feira 13","MP3 player"], ["Microfone","Pote","Austin Powers"],["Máscara","Falar como um papagaio","Super Mario Bros."]],
    [ ["Procurando Nemo","Capacete","Vinho"], ["Planeta dos Macacos","Plugue","Velcro"],["A cereja do bolo","Fazer um negócio da China","Lobo em pele de cordeiro"]],
    [ ["Tijolo","Canivete suíço","Dicionário"], ["Timão e Pumba","Beyoncé","O Iluminado"],["Dar a volta por cima","Carlos Drummond de Andrade","Abridor de garrafas"]],
    [ ["Banheira","Notebook","Estetoscópio"], ["Aranha","Bateria","Silicone"],["Dar o braço a torcer","Deixar na mão","Sete palmos abaixo da terra"]],
    [ ["Trator","Concha","Cubo Mágico"], ["Térmica","Veado","Rainha"],["Recomeçar do zero","Cessar-fogo","Quebrando o silêncio"]],
    [ ["Caminhão de bombeiro","Esquilo","Anjo"], ["Bilbo Bolseiro","David Guetta","Capitão Gancho"],["Fome de leão","Dragonball Z","Em Busca do Tempo Perdido"]],
    [ ["Mágico","Porco-espinho","Placa de carro"], ["O Pequeno Príncipe","Indiana Jones","Ivete Sangalo"],["Não se faz omelete sem quebrar os ovos","Lavagem cerebral","Desgraça pouca é bobagem"]],
    [ ["Furadeira","Escritório","Margarida"], ["Cabeça de Batata","Represa","O Senhor dos Anéis"],["Por um fio","Simular uma falta","Sociedade dos Poetas Mortos"]],
    [ ["Asilo","Vampiro","Escada"], ["Aquarela do Brasil","Troll","Cyrano de Bergerac"],["O Quinto Elemento","Cheque voador","Detetive"]],
    [ ["Crocodilo","Canário","Piano"], ["Alvo","Lampião","Bigode"],["Fábio Porchat","Banho de Espuma","Haja Coração"]],
    [ ["Desfibrilador","Tetris","Baleia"], ["Código de barras","Stonehenge","Besta"],["Confesse seus pecados","Os Vingadores","Aspirador de pó"]],
    [ ["Porão","Leão","Relógio de sol"], ["Bolsa de água quente","Estilingue","Barco a vapor"],["Bater um recorde","A roupa nova do imperador","Ter a consciência pesada"]],
    [ ["Asa-delta","Dentadura","Caranguejo"], ["Palmeira","Contador","Munição"],["A maçã não cai longe do pé","Silhueta","Primeira-bailarina"]],
    [ ["Escorpião","Peixe-espada","Perfume"], ["Rugby","Dinamite","Danilo Gentili"],["Veio do nada","Nadar num mar de rosas","Mensagem subliminar"]],
    [ ["Caminhão","Rato","Parquímetro"], ["Cerveja","Balde","Mike Tyson"],["Cabeça de vento","Olhar para o próprio umbigo","Mendigo"]],
    [ ["Avião de combate","Buzina","Tubarão"], ["Aquarela","Kill Bill","Prison break"],["Armado até os dentes","Lichia","Reacender a chama"]],
    [ ["Professor","Chocolate","Spray de pimenta"], ["O Código da Vinci","Ben 10","O Rei Leão"],["Três Homens em Conflito","Passar o sinal vermelho","Ter a cabeça nas nuvens"]],
    [ ["Piloto","Máscara de gás","Pinóquio"], ["Neil Armstrong","Metamorfose Ambulante","Laranja Mecânica"],["Ficar em cima do muro","Jornal de domingo","Trocar alhos por bugalhos"]],
    [ ["Zebra","Mecânico","DVD"], ["Xilofone","Abominável Homem das Neves","Ciclista"],["Cego como uma toupeira","Dom Casmurro","A vaca foi pro brejo"]],
    [ ["Vaca","Porco","Janela"], ["Imagem & Ação","Castor","Alfinete"],["Aos trancos e barrancos","Não é o fim do mundo","Distraído"]],
    [ ["Oca","Camisa","Foguete"], ["Sushi","Calculadora","Batata frita"],["Tina Turner","Ponderar","Clube da Luta"]],
    [ ["Loja","Encanador","Barbie"], ["Pipoca","Papel higiênico","Elevador"],["Popeye","Abrir a caixa de Pandora","Ágil como um gato"]],
    [ ["Iogurte","Guarda-chuva","Ninja"], ["Ursinho Puff","Madre Teresa","Pica-Pau"],["Pistão","Marte Ataca!","Recruta Zero"]],
    [ ["Pescador","Rio","Extintor de incêndio"], ["Mister Bean","Radiador","Elton John"],["Matar a cobra e mostrar o pau","Uma Dupla quase Perfeita","Lento como uma lesma"]],
    [ ["Cata-vento","Ginásio","Varanda"], ["Guerra e Paz","Andorinha","Vacina"],["Floresta Amazônica","A Origem","Romance"]],
    [ ["Garfo","Arma","Morcego"], ["Forrest Gump","Furão","Barata"],["Conhecer seus limites","Sumir do mapa","De partir o coração"]],
    [ ["Caracol","Zorro","Som automotivo"], ["Dumbo","Zelda","Angry Birds"],["Mentes Criminosas","Mãe coruja","Beleza Americana"]],
    [ ["Fogueira de São João","Voar","Panqueca"], ["História em quadrinhos","A Casa das Sete Mulheres","Caminho"],["Procurar agulha em palheiro","Estar com as orelhas queimando","Os Deuses Devem Estar Loucos"]],
    [ ["Touro","Pinheiro","Pac-Man"], ["Tintin","Patins","Margaret Thatcher"],["Por mares nunca antes navegados","Estátua do Cristo Redentor","Dar uns amassos"]],
    [ ["Peter Pan","Cortador de grama","Pisca-pisca"], ["Pra não dizer que não falei das flores","Bicicleta para dois","Cartão postal"],["Firme como uma rocha","Chover canivetes","Canalizar a raiva"]],
    [ ["Montanha","Hotel","Iglu"], ["Os Pilares da Terra","Hidromassagem","Joana d’Arc"],["As Sete Maravilhas do Mundo","Eddie Murphy","Marlon Brando"]],
    [ ["Pirata","Bicicleta","Cofrinho"], ["Órgão","Tsunami","Apontador"],["Olho roxo","Melhor prevenir que remediar","Saca-rolhas"]],
    [ ["Tempestade","Vitamina","Sino"], ["Estação espacial","Vinte Mil Léguas Submarinas","007 - Casino Royale"],["Segurar vela","V de Vingança","Cabeça-dura"]],
    [ ["Guincho","Máquina de costura","Arpão"], ["Pepino","O Pequeno Polegar","Bambolê"],["Davi e Golias","Riquinho Rico","Yuri Gagarin"]],
    [ ["Urubu","Jeans","Tablet"], ["Buraco negro","Jukebox","A Moreninha"],["Pinta","Atirar a primeira pedra","Jogar dinheiro pelo ralo"]],
    [ ["Nutella","Trenó","Espada"], ["Vaso sanitário","O Senhor das Armas","Jô Soares"],["Um morto muito louco","Laika","Fazer as pazes"]],
    [ ["Selva de Pedra","Feriado Nacional","Vulcão"], ["Sininho","Julia Roberts","Uísque"],["O Estranho Mundo de Jack","Touro Indomável","Vender a alma ao diabo"]],
    [ ["Fechadura","Pato","Lente de aumento"], ["Dalai Lama","Bilhar","Lassie"],["Encolhido feito Tatu-Bola","Queimando de febre","Torre de Babel"]],
    [ ["Chaminé","Avatar","Sombreiro"], ["Cacau","Afrodite","Salsicha"],["Escova de cabelo","Luz no fim do túnel","Entrar com tudo"]],
    [ ["Poço","Dia dos Namorados","Abelha"], ["Post-it","Robin Hood","2001: Uma Odisseia no Espaço"],["Dar bolo em alguém","Cana","Patinar na lama"]],
    [ ["Branca de Neve e os Sete Anões","Gênio","Mineração"], ["Asterix e Obelix","Gladiador","Alien, o Oitavo Passageiro"],["Estar uma pilha de nervos","Chapada Diamantina","Volta ao Mundo em 80 Dias"]],
    [ ["Eclipse","Garagem","Sótão"], ["D’Artagnan","Dolinho","Oscar Niemeyer"],["Botar o carro na frente dos bois","Marcelo Adnet","Cavalo Marinho"]],
    [ ["Meteorito","Museu","Geladeira"], ["Lentes de contato","The Sims","Power Rangers"],["Iluminismo","Sudorese","O Homem que Copiava"]],
    [ ["Impressora","Chalé","Tapete"], ["John Lennon","Cidade de Deus","Snowboard"],["Cid Moreira","Big Ben","007 - Operação Skyfall"]],
    [ ["Elefante","Isqueiro","Elfo"], ["Premonição","Bambi","Diabo"],["Eminem","Ter medo de altura","Preparado para o que der e vier"]],
    [ ["Vaso","Dragão","Natação"], ["Plataforma de petróleo","Palito de dentes","Tartarugas Ninjas"],["Quanto mais melhor","Democracia","Orgulho e Preconceito"]],
    [ ["Aladdin","Pipa","Maçã"], ["Fazendeiro","Padeiro","Farol"],["Você está me dando nos nervos","Gaguejar","Perder a calma"]],
    [ ["Carros","Yoda","Submarino"], ["Caixa de correspondência","Woody Allen","Nelson Rodrigues"],["Bronzeamento artificial","Ladrão","É tudo farinha do mesmo saco"]],
    [ ["Cinema","Cobra","Gaguinho"], ["Os Trapalhões","Santo Graal","Garota de Ipanema"],["Estar claro como água","Arrancar os cabelos","Os Muppets"]],
    [ ["Banco Imobiliário","Salada","Escola"], ["Os Pássaros","Rocky","Cazuza"],["O Cavaleiro das Trevas","Forçar a barra","Dormir como um bebê"]],
    [ ["Pá","Cortina","Disfarce"], ["Muhammad Ali","Quadribol","Sandy"],["Enfiar o pé na jaca","Meter o dedo na ferida","Jackie Tequila"]],
    [ ["Água-viva","Ogro","Video game"], ["LEGO","MacGyver","Cinderela"],["A Ponte dos Suspiros","Kleber Bam-Bam","Círculo vicioso"]],
    [ ["Tênis","Aeroporto","Chapéu"], ["Pode vir quente que eu estou fervendo","Princesa Diana","Hebe Camargo"],["Mauricio de Sousa","Dez Indiozinhos","Feridas de guerra"]],
    [ ["Boxeador","Trigo","Cantil"], ["Camarão 7 Barbas","Atlântida","Bob Marley"],["Dar um branco","Dar água na boca","Baioneta"]],
    [ ["Ranho","Aspirina","Macaco"], ["Cinquenta Tons de Cinza","Alf, o Eteimoso","Javali"],["Queda livre","Ali Babá","Cair no golpe"]],
    [ ["Óculos escuros","Regador","Fada"], ["Mogli","Albus Dumbledore","Fertilizante"],["A Turma da Mônica","Al Capone","Ser surdo como uma porta"]],
    [ ["Lobo","Free Willy","Homem de Ferro"], ["Linguagem de sinais","Batom","Judas"],["A pedra de Rosetta","São Pedro","Jogar a toalha"]],
    [ ["Policial","Banana","Ninho"], ["O Bicho-Papão","Arco-Íris","José Padilha"],["Em terra de cego, quem tem um olho é rei","Bater as botas","Três reis-magos"]],
    [ ["Cavalo","Cartão de crédito","Disco voador"], ["Camaleão","Bomba Atômica","Fita adesiva"],["Conversa pra boi dormir","Construir um império","Vestida para matar"]],
    [ ["Chá","Pokémon","Mestre-cuca"], ["Caneta","Patinação no gelo","Navio Fantasma"],["O Show de Truman: O Show da Vida","Portunhol","Homem do saco"]],
    [ ["Autorama","A Múmia","Castelo"], ["Facas Ginsu","O Exorcista","Areia movediça"],["Mover montanhas","Curtindo a Vida Adoidado","Calvin e Haroldo"]],
    [ ["Cubo de gelo","Avestruz","Casamento"], ["Guilherme Tell","Diretório","A Esfinge de Gizé"],["Marshmallow","Pisar fundo","Histórias da Carochinha"]],
    [ ["Restaurante","Estilo","Toupeira"], ["Prótese","O Tempo e o Vento","Tais Araújo"],["Resident Evil","Guerra dos Tronos","Estátua da Liberdade"]],
    [ ["Microscópio","Guarda","Porta-aviões"], ["O Casamento do meu Melhor Amigo","Lima Duarte","Piratas do Caribe"],["500 Milhas de Indianápolis","Magali","Ficar vermelho como pimenta"]],
    [ ["Orquestra","Igreja","Luzes de Natal"], ["Motor a vapor","Pasta de dente","Heliporto"],["O que os olhos não veem, o coração não sente","E.T. - O Extraterrestre","Laranja podre"]],
    [ ["No Limite","Urso de pelúcia","Pardal"], ["Zíper","Maquiagem","Mata-mosca"],["Furar fila","Museu da Língua Portuguesa","Mergulhar de cabeça"]],
    [ ["Abacaxi","Ovo","Carteiro"], ["Poodle","McDonald’s","Empire State"],["Conversa fiada","Lewis Caroll","Rápido como um raio"]],
    [ ["Churrasco","Assassino","Vespa"], ["Pierrô","Amy Winehouse","Gaita"],["Calças curtas","Jogar lenha na fogueira","Onde é o incêndio?"]],
    [ ["Estrela cadente","Bolo","Champagne"], ["Edward Mãos de Tesoura","Os Caça-Fantasmas","Bridget Jones"],["Trepadeira","Chiclete","Voz do Brasil"]],
    [ ["Mineiro","Prisão","Moinho"], ["Porta dos Fundos","Poseidon","O Alquimista"],["Luar","Fazer um brinde","Com uma mão nas costas"]],
    [ ["Morango","Fogos de artifício","Bombeiro"], ["Bill Clinton","Moedor de pimenta","Foca"],["Fidel Castro","Arregaçar as mangas","Duro de Matar"]],
    [ ["Polishop","Mangueira","Papa-léguas"], ["Esqueleto","Trampolim","À Espera de Um Milagre"],["Dar chance para o azar","Tribunal","Memórias Póstumas de Brás Cubas"]],
    [ ["Air bag","Raposa","Binóculos"], ["Dirigível","Princesa","Jumanji"],["Faca de dois gumes","Rapunzel","Jim Carrey"]],
    [ ["Palhaço","GPS","Brinco"], ["Gasparzinho","Guitarra","Frevo"],["Ser um pé no saco","Azar no jogo, sorte no amor","Ter um bom olho"]],
    [ ["Boate","Sapo","Caçador"], ["Transformers","Luz estroboscópica","Escova de dente"],["Matar tempo","Jogos Vorazes","Prender a respiração"]],
    [ ["Tigre","Peixe","Guarda-sol"], ["Sudoku","Massa de modelar","Michael Jordan"],["Príncipe Valente","Falar pelas costas","Martin Luther King"]],
    [ ["Metrô","Assistir","Lobisomem"], ["O Último Samurai","Bonecas Russas","Lara Croft"],["Calcanhar de Aquiles","Cavaleiros do Zodíaco","Enterrar a cabeça no chão"]],
    [ ["Computador","Moinho de vento","Papel-alumínio"], ["Esqueceram de Mim","Diablo","Maionese"],["Loteria","Heitor Villa-Lobos","Pular amarelinha"]],
    [ ["Robô","Estrela-do-mar","Futebol"], ["Ferrovia","Braille","Ferradura"],["Rio de Janeiro","Branco como a neve","Estar com a bola toda"]],
    [ ["Carteira","Lata","Diamante"], ["Praia","Advogado","Biscoito"],["O que é isso, Companheiro?","Sentir cheiro de trapaça","Viagem ao Centro da Terra"]],
    [ ["Protetor solar","Estátua","Casinha do cachorro"], ["Descarga","Shrek","Libélula"],["Gato escaldado tem medo de água fria","Ficar a ver navios","Caverna do Dragão"]],
    [ ["Pinguim","Biblioteca","Doutor"], ["Tio Patinhas","Adoçante","Croissant"],["Fernando Collor","Com os nervos à flor da pele","Botar pra quebrar"]],
    [ ["Abóbora","Sutiã","Pantera"], ["Cartão inteligente","Garçonete","Mary Poppins"],["Perguntar não ofende","Dar uma boa olhada","Marco Polo"]],
    [ ["Concorde","O Homem Invisível","Radar"], ["Mulher-gato","Coala","Pólvora"],["Círculo de amigos","Dinheiro não dá em árvore","Nem que a vaca tussa"]],
    [ ["Cadeira elétrica","Limpador de para-brisa","Titanic"], ["Boliche","Alvejante","Salto agulha"],["Justin Bieber","Burro como uma porta","Desmaiar"]],
    [ ["Papagaio","Canudo","Torre Eiffel"], ["Palavras cruzadas","Marilyn Manson","Dexter"],["Meu precioso","Vestir o paletó de madeira","Ilha de Páscoa"]],
    [ ["Dr. House","Toy Story","Cereja"], ["Cupido","O Artista","Bússola"],["Renunciar","Fazer rodeios","Ben-Hur"]],
    [ ["Planador","Suco de frutas","Leme"], ["Meia-calça","Jurassic Park","Guilhotina"],["Interromper alguém","Jogar uma moeda","Hermione Granger"]],
    [ ["Leite","Rinoceronte","Unicórnio"], ["Capitães de Areia","Propaganda","Lance Armstrong"],["Água mole em pedra dura tanto bate até que fura","De Volta para o Futuro","Boca fechada não entra mosca"]],
    [ ["A Pantera Cor-de-Rosa","Dado","Os Simpsons"], ["A Gaiola das Loucas","Chave","Vênus de Milo"],["De boas intenções o inferno está cheio","Coliseu","Guerra do Vietnã"]],
    [ ["Faixa de pedestres","Papai Noel","Vinicultor"], ["Miss Brasil","Revolução Francesa","Mala"],["Baixar a bola","A Cidade Proibida","Perder a cabeça"]],
    [ ["Bota","Equipamento de mergulho","Ferrari"], ["Empréstimo","A cigarra e a formiga","Escada rolante"],["Abrir o coração","Sazonal","Deixar tinindo"]],
    [ ["Ambulância","Seringa","Pijama"], ["Imã","Sabre de luz","Lata de lixo"],["Tudo vale a pena quando a alma não é pequena","Dar um tiro no pé","Carandiru"]],
    [ ["Tênis de mesa","Luva","Tesoura"], ["Édipo","Estação","Cesariana"],["Muito cansado para pensar direito","Fumar como uma chaminé","Capela Sistina"]],
    [ ["Celular","Telescópio infravermelho","Girafa"], ["Hannibal Lecter","O Nome da Rosa","Torradeira"],["Sexto Sentido","Língua de cobra","Carola"]],
    [ ["Águia","Girassol","Cozinha"], ["Globo Rural","O Exterminador do Futuro","Circo"],["Ficar sem ar","Top Gun - Ases Indomáveis","Clonagem"]],
    [ ["Banco","Quarto","Flauta"], ["Arquimedes","Borat","Velozes e Furiosos"],["Fazer o que bem entender","Billy Jean","Eureca!"]],
    [ ["Triciclo","Bife","Egito"], ["Mudança de Hábito","Assobio","Laços de Família"],["Morder a língua","Sigmund Freud","Antônio Fagundes"]],
    [ ["Ventilador","Café","Chocalho"], ["Crepúsculo","Batman","Sílvio Santos"],["Uma imagem vale mais que mil palavras","Engolir sapo","Jean-Claude Van Damme"]],
    [ ["Dinossauro","Motosserra","Os Smurfs"], ["Crocodilo Dundee","Trem fantasma","Toddynho"],["Pedir a mão de alguém","Tráfico de drogas","A Guerra dos Cem Anos"]],
    [ ["Espinafre","Balsa","Herança"], ["Dr. Jekyll","Moisés","Jack Bauer"],["Millennium: Os Homens que Não Amavam as Mulheres","Esmeralda","Luke, eu sou seu pai"]],
    [ ["Harry Potter","Lago","Coca-Cola"], ["No Rancho Fundo","Trem das Onze","Cassarola"],["Pôr a mão no fogo","Ficar de fora","Pesadelo"]],
    [ ["Sonic","Salto com vara","Trompete"], ["Sauna","Romeu e Julieta","Torre de Pisa"],["Acordar com o pé esquerdo","Abrir os trabalhos","Dois pesos e duas medidas"]],
    [ ["Urso-polar","Bruxa","Boneco de neve"], ["Palácio do Planalto","Sabonete","Baguete"],["Lua de mel","Seguro morreu de velho","Sentir um peso no coração"]],
    [ ["Pena","Coco","Porto"], ["Paraquedas","Catapulta","Prendedor de roupa"],["Carrinho de supermercado","Censura","Pedra que rola não cria limo"]],
    [ ["Ioiô","101 Dálmatas","Borboleta"], ["Wolverine","A Vida é Bela","MIB: Homens de Preto"],["Um raio nunca cai duas vezes no mesmo lugar","Viver a vida no limite","Panela velha é que faz comida boa"]],
    [ ["Lenhador","Mosquito","Micro-ondas"], ["Dercy Gonçalves","Os Infiltrados","Espátula"],["Ter os dois pés no chão","Ligações Perigosas","Morrer de fome"]],
    [ ["Era do Gelo","Golfinho","Caixa d’água"], ["Fantasia","Teclado","Bruce Lee"],["Gremlins","Ficar sem palavras","Entrar pelo cano"]],
    [ ["Bob Esponja","Tempero","Tarzan"], ["E o Vento Levou","Onze Homens e um Segredo","Colheita"],["Se Beber, não Case","Dormir com um olho aberto","Snoopy"]],
  ];
}

?>
